### ISSUE TITLE
Spikes for TTFB when testing on 3g profile for emulated Chrome

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#1000]
Hi Pat,
when we run on emulate mobile Chrome on a 3g profile our TTFB has some spikes, usually adds a extra 100 ms and sometimes more (it happens on all pages we test): 

<img width="1234" alt="screen shot 2017-11-27 at 12 32 49 pm" src="https://user-images.githubusercontent.com/540757/33264727-1e0cff7c-d36f-11e7-8934-644445dde3fd.png">

https://grafana.wikimedia.org/dashboard/db/webpagetest-drilldown?panelId=9&fullscreen&orgId=1&from=now-30d&to=now&var-wiki=enwiki-mobile&var-users=anonymous&var-page=Sweden&var-location=us-east-1&var-browser=Google_Chrome-emulateMobile&var-view=firstView

I cannot see the same on Navigation Timing metrics but I haven't digged into any of the results from WebPageTest yet.

Best
Peter

**Comment by jirawat050** [comment]
Google chrome in mobile not support to use and type mobile ?I don't sure

**Comment by pmeenan** [comment]
Any chance this resolved itself with the Linux fixes for traffic-shaping?

**Comment by soulgalore** [comment]
No we still have it, it's about 100 ms. This graph is from when the traffic shaping was updated (and the Linux agent):
<img width="1381" alt="screen shot 2018-03-07 at 20 24 03" src="https://user-images.githubusercontent.com/540757/37113418-9e168d1c-2245-11e8-8bb3-5427983d6f4f.png">

**Comment by pmeenan** [comment]
ok, thanks.  I'll see if I can reproduce it with any reliability and try to dig in.

**Comment by soulgalore** [comment]
Hi Patrick, I've been looking into this again but from a different angle. I've been looking at stdev for our tests, focusing on TTFB. For all our tests where we run Chrome in "emulated mobile" mode we have spikes of higher TTFB.  Using emulated Chrome stdev is always higher than normal Chrome. 

First I guessed it was because we test in different connectivities but we also have other tests that we run against WebPageReplay where we use same connectivity and I can see the same pattern there. 

I know you are not a member of the Chrome team anymore but maybe it's ring a bell what could cause it? I'll add some more tests running on the same connectivity Chrome vs emulated Chrome to see if there are the same difference there.

Best
Peter

**Comment by pmeenan** [comment]
Maybe try disabling CPU throttling for the mobile tests?
