### ISSUE TITLE
Create video of certain step or run

### ISSUE THREAD

**Issue by tylergraf** [WPO-Foundation/webpagetest#1002]
I'd like to create a comparison video, but my test was run with steps. I can enter the `-s:2-r:5` to get to the run and step I want in the filmstrip, but the create video button just uses the first step and median run.

Is there a way to do this?

Here's my filmstrip url: https://www.webpagetest.org/video/compare.php?tests=171120_HC_41baf2d8dd3b5949514e1d1078d27c07-s:2-r:5,170526_J4_8bec496ff64ea70f588ac0a80b189b61-s:3

**Comment by pmeenan** [comment]
Looks like the update worked: https://www.webpagetest.org/video/view.php?id=171120_5e9bdd5b7ebbbca98eb458b32163b9a70524c55a

**Comment by tylergraf** [comment]
Thank you thank you!
