### ISSUE TITLE
Test in queue position when using api

### ISSUE THREAD

**Issue by code2prog** [WPO-Foundation/webpagetest#1018]
How to enable queue position in check status response when job was added by api request?
Thanks for help

**Comment by pmeenan** [comment]
Which API entry point are you using to check position?  getStatus.php and jsonResult.php should both include position by default (xmlResult does not include position).

**Comment by code2prog** [comment]
testStatus.php?f=json&test=test_id

**Comment by pmeenan** [comment]
Is this a private instance or the public instance?  The [current testStatus.php code](https://github.com/WPO-Foundation/webpagetest/blob/master/www/testStatus.php#L11) is hard-coded to always include position data.  If it is a private instance that has an older version of the code you should be able to pass pos=1 to get the position.

**Comment by code2prog** [comment]
private instance.
Thanks

**Comment by code2prog** [comment]
i check testStatus.php on my server and i have new version of code with position enabled by default  but it does not work correctly. When i add multiple tests to queue test added by last one show status "Waiting at the front of the queue..." until test started. Then show "Test Started x seconds ago"

**Comment by pmeenan** [comment]
As best as I can tell the position should always be returned unless you explicitly pass noposition=1 as an option.  The one exception is if you are using beanstalkd for queues in which case a position isn't available.
