### ISSUE TITLE
Request a file

### ISSUE THREAD

**Issue by Mickey248** [WPO-Foundation/webpagetest#1036]
please Request a file because i add a recaptcha to security and i don't have a file to edit recaptcha
1.https://www.webpagetest.org/forums/member.php?action=lostpw
2.https://www.webpagetest.org/forums/report.php?pid=30124
i can make a recaptcha do you need?

**Comment by jirawat050** [comment]
No have file on github

**Comment by teerapat1739** [comment]
this file is secure of project

**Comment by pmeenan** [comment]
Are the 3 of you working together on something?  You have all been submitting a bunch of PR's and comments on issues but so far mostly either wrong or superficial url changes from http to https.

If there is something you are trying to do, do you have a larger plan?  If not I'm likely to ban you from the project to keep the noise down.

**Comment by jirawat050** [comment]
Sorry for a disturb.I have a plan to do project
