### ISSUE TITLE
chromeUserTiming are missing

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#1046]
I notice that tests results on Chrome don't contains all metrics in the chromeUserTiming.
For instance : http://www.webpagetest.org/result/171212_RG_f70de6a9e839f1f5e6397396051acb29/ or http://www.webpagetest.org/result/171212_BC_9479410477c5efed21d887d6a62992d2/.       
```json
          "chromeUserTiming.responseEnd": 0,
          "chromeUserTiming.domLoading": 0,
          "chromeUserTiming.domInteractive": 1,
          "chromeUserTiming.domContentLoadedEventStart": 1,
          "chromeUserTiming.domContentLoadedEventEnd": 1,
          "chromeUserTiming.domComplete": 1,
          "chromeUserTiming.loadEventStart": 1,
          "chromeUserTiming.loadEventEnd": 1,
```
I tried this configuration that enable the timeline and also when it's emulating a mobile. Data are 0 or 1.

<img width="673" alt="capture d ecran 2017-12-12 a 10 35 37" src="https://user-images.githubusercontent.com/928701/33877294-3b82ced2-df28-11e7-8849-401847932a8e.png">

Before, I was able to get this kind of data : 

```json 
"chromeUserTiming.responseEnd": 2804,
          "chromeUserTiming.domLoading": 2726,
          "chromeUserTiming.domInteractive": 4394,
          "chromeUserTiming.domContentLoadedEventStart": 4400,
          "chromeUserTiming.domContentLoadedEventEnd": 4414,
          "chromeUserTiming.domComplete": 22691,
          "chromeUserTiming.firstLayout": 4379,
          "chromeUserTiming.fetchStart": 125,
          "chromeUserTiming.unloadEventStart": 2725,
          "chromeUserTiming.unloadEventEnd": 2725,
          "chromeUserTiming.firstPaint": 4399,
          "chromeUserTiming.firstContentfulPaint": 4399,
          "chromeUserTiming.firstImagePaint": 4399,
          "chromeUserTiming.firstMeaningfulPaintCandidate": 5755,
          "chromeUserTiming.firstTextPaint": 5602,
          "chromeUserTiming.firstMeaningfulPaint": 5755,
          "chromeUserTiming.loadEventStart": 22691,
          "chromeUserTiming.loadEventEnd": 22737,
```

Chrome is in version 63. I can reproduce the problem on multiple location (Paris, Strasburg)

**Comment by abarre** [comment]
Thank you for this quick fix.
Is there a chance to release a new version soon ?

**Comment by pmeenan** [comment]
I'll cut a new release later this week (wanted to do them quarterly anyway).

**Comment by pmeenan** [comment]
FWIW, I keep the public instance running on the tip of the master branch directly from github so it is also expected to be stable (but I fully understand not wanting to be on the bleeding edge).
