### ISSUE TITLE
REST parameter uastring unreliable

### ISSUE THREAD

**Issue by fsobanski** [WPO-Foundation/webpagetest#1049]
Hi,

when I submit the following test `http://www.webpagetest.org/runtest.php?url=www.otto.de&uastring=TestTestTest&location=Dulles:firefox&k=SECRET` and then take a look at the user agent string of the requests shown in the waterfall, the user agent string is only set to `TestTestTest` in some requests but not all. My first impression is that the user agent string is not overwritten in the requests to https://www.otto.de. The same is true if `uastring` is replaced with `appendua`.

When I submit the same test via the GUI at `http://www.webpagetest.org/` with the user agent string overwritten in the advanced settings menu then all the requests have the overwritten user agent string set. 

On a related note, is there a reason that there is no equivalent to `appendua` in the GUI under `Advanced Settings`?

Best
Fabian

**Comment by pmeenan** [comment]
Was the same test location and browser  used in the UI and API?  The newer cross-platform agent should be much better about making sure the UA string is replaced correctly for Firefox but it has not been deployed everywhere yet.  The UI uses the API so they should behave identically.

As far as appendua goes, there are a few features that aren't used enough to justify adding more to the UI and that was one of them.  If it would be helpful it is easy enough to add - just trying to keep the UI from getting even more crowded.

**Comment by fsobanski** [comment]
In the api, I used `location=Dulles:firefox`. In the UI, I selected `Dulles, VA - Linux (Chrome,Firefox,Opera)` and `Firefox` as the browser.

**Comment by fsobanski** [comment]
You were right. I just tried it out with the new platform agent at one of our private locations and everything worked as expected.
