### ISSUE TITLE
Type of Search error

### ISSUE THREAD

**Issue by fooksupachai** [WPO-Foundation/webpagetest#1063]
**If User may hit the button space bar while input  . The result must be error.**

![search1](https://user-images.githubusercontent.com/26427911/33954793-10d23ff2-e06c-11e7-9e9c-5f3369670089.PNG)

![search2](https://user-images.githubusercontent.com/26427911/33954875-43c4f8c8-e06c-11e7-96cc-f955f76d7313.jpg)

![search3](https://user-images.githubusercontent.com/26427911/33954691-97f0899a-e06b-11e7-9f8d-68be48cc3575.PNG)
![search4](https://user-images.githubusercontent.com/26427911/33954692-98733b60-e06b-11e7-9e40-e5dfda61be45.PNG)

**Comment by pmeenan** [comment]
That is the mybb forum software used for the public forums and doesn't have anything to do with the WebPageTest code itself.

**Comment by fooksupachai** [comment]
Thank you very much.
