### ISSUE TITLE
Tag release in Docker

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#1069]
Hi Pat,
it would be super if the Docker containers could be automatically tagged with the release (you can just set it up in the Docker hub). 

Right now it's mostly using the **latest** tag and I think it is rebuilt on every push to Github?
For example: our documentation for getting WPT up and running locally on Docker is broken since something changed between releases and in the instructions we download the latest tag (since there is no other).

Best
Peter

**Comment by soulgalore** [comment]
And same for https://github.com/WPO-Foundation/wptagent that would be awesome!

**Comment by pmeenan** [comment]
I changed the "latest" tag to pull the release branch which will be more stable.  Is there a way to do a one-time build of each release tag if you want to have tagged docker builds specific to each release?

**Comment by soulgalore** [comment]
not one time build (you can always push a new one) but if you have autobuild turned on, you can let it build a docker tag per git tag:

<img width="1138" alt="screen shot 2018-01-08 at 9 30 03 pm" src="https://user-images.githubusercontent.com/540757/34693498-175606b2-f4c4-11e7-9697-aa4a405bb491.png">

**Comment by timothyclarke** [comment]
If the trigger button does not appear (per some of mine) you need to create a Token in "Build Triggers" and then add it as a webhook in this repo (on a "Create" event).

Dockerhub side
![docker trigger url](https://user-images.githubusercontent.com/9347979/34714274-e3d14c22-f520-11e7-8505-bcf4375482d8.png)

**Comment by mattfarina** [comment]
To add a little context, for repeatibility of deploys we want versioned releases. latest could changes between dev, testing, and deploys to production introducing unforeseen situations. Versioned releases give us a little more control.

**Comment by pmeenan** [comment]
ok, I set up builds with the wildcard tag settings so all new tagged releases should automatically get a build (if it works as expected).

I also manually triggered a build for both the server and agent for the WebPageTest-17.08 release tag.

The "latest" tag will track master and a "release" tag will track the release branch which will usually be a little behind master but ahead of the last stamped release.

**Comment by pmeenan** [comment]
There are now:
* latest - tracks the trunk
* release - tracks the release branch (expect updates roughly monthly)
* release-specific tagged versions - For each WEbPageTest release (quarterly) there will be a tagged docker container automatically created
