### ISSUE TITLE
Lighthouse not Working

### ISSUE THREAD

**Issue by Yamikamisama** [WPO-Foundation/webpagetest#1072]
Hey there so I am running this code:

```javascript
const WebPageTest = require('webpagetest');
const wpt = new WebPageTest('www.webpagetest.org', API_KEY);

let opts = {
  url: 'https://google.com/',
  apiKey,
  strategy: 'mobile'
};

exports.helloWorld = function helloWorld(req, res) {
  wpt.runTest(opts.url, {pollResults: 5, timeout: 5000, lighthouse: true}, (err, data) => {
    res.status(200).send(data);
  });
};
```

And it is returning data, however it does not return Lighthouse Data, which is what I primarily need.
![screen shot 2017-12-19 at 2 10 15 pm](https://user-images.githubusercontent.com/8148176/34178137-2208a38a-e4d4-11e7-9cb8-9eed4aa34e2a.png)

Any clue what Im doing wrong?

**Comment by Yamikamisama** [comment]
When I click on the Lighthouse PWA Score it takes me to this page

![screen shot 2017-12-19 at 4 41 42 pm](https://user-images.githubusercontent.com/8148176/34180185-c91163a4-e4db-11e7-8da0-fe8e1525fdc0.png)

**Comment by pmeenan** [comment]
Sorry, I should have caught it on the initial post.  The default location (Dulles) does not support Lighthouse.  You need to specify one of the EC2 locations or the physical devices (Dulles_MotoG4 for example) - and also make sure to specify the Chrome browser.

In a few months all of the agents will be migrated to the new code which supports Lighthouse but we're not there yet.

**Comment by pmeenan** [comment]
The main Dulles agents have been migrated over to the new (Lighthouse-capable) architecture now.  Please re-open if you still see an issue.
