### ISSUE TITLE
Missing API Key when I trying to get report by using Restful API.

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [WPO-Foundation/webpagetest#1082]
Whan I am trying to get performance report of my webpage using Restful API, I got this below error.

>  An error occurred processing your request (missing API key).  If you do not have an API key assigned you can request one at
> http://www.webpagetest.org/getkey.php

Then, I register properly but still, I didn't get any API key

Please Give me solution for automating this process using API.
Thanks in advance!

**Comment by pmeenan** [comment]
Email me (pmeenan@webpagetest.org) with the email account you used to register the key and I can manually send the activation link.  The verification emails sometimes get lost in the tubes.
