### ISSUE TITLE
Missing documentation for archive_api

### ISSUE THREAD

**Issue by mkreidenweis** [WPO-Foundation/webpagetest#1094]
After trying to find out why test triggered via the API are not archived, we noticed that there is a configuration option `archive_api` which has to be set in order for those tests to be archived. 

Unfortunately this is mentioned neither in the private instance documentation nor in the WebPagetest book nor in the example settings file.

**Comment by pmeenan** [comment]
Are they not archived at all or just not immediately on access?  THat setting should only trigger an immediate archive when jsonResult.php is accessed but otherwise it should archive normally like all other tests.

**Comment by mkreidenweis** [comment]
Ah, you're probably right and they would have been archived after two days. Haven't had the archiving running long enough to notice. 
With the setting it does immediately archive in any case, which is what we wanted. Thanks.

**Comment by githubdev2018** [comment]
@mkreidenweis , would you please share the S3 archiving settings? We have setup a private instance but unable to get the archiving working after the tests are complete using both UI and API.

**Comment by githubdev2018** [comment]
Finally made it working by adding below to the settings.ini since we are protecting our instance inbound traffic:
local_server=http://127.0.0.1
