### ISSUE TITLE
Expand guidance in performance_optimization.php

### ISSUE THREAD

**Issue by addyosmani** [WPO-Foundation/webpagetest#1099]
The current performance_optimization report includes analysis around:

- First Byte Time
- Using gzip compression for transferring compressable responses
- Compressing images
- Using Progressive JPEGs

and a few other ideas. It would be great if we could maybe make these items more actionable. We could maybe link from these different sections to guidance on [Web Fundamentals](https://developers.google.com/web/fundamentals/performance).

A few related docs:

* [Compressing text resources using gzip/brotli](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer)
* Compressing images: 
  * https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization
  * https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/
* [Progressive JPEGs](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/#the-advantages-of-progressive-jpegs)
* [HTTP Caching](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching)

@pmeenan would you be open to a PR adding some links to this guidance?

**Comment by pmeenan** [comment]
Sure, PR's are always welcome.
