### ISSUE TITLE
Sometimes the Chrome trace log doesn't have correct values

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#1100]
Hi Pat,
we graph the CPU metrics for Chrome and it seems like sometimes the timings are not correct, it looks like this (where we almost only have idle time and nothing else):

![grafana webpagetest](https://user-images.githubusercontent.com/540757/35607892-e536d824-0656-11e8-90ee-cadf2468f733.png)

And here is a run with that produces that:
http://wpt.wmftest.org/breakdownTimeline.php?test=180130_YW_Z&run=4

I guess it's a bug in Chrome?

Best
Peter

**Comment by andydavies** [comment]
I see this from time-to-time but can't pin it down - thought it was more prevalent on the Windows (wptdriver) agents but not 100% sure see https://github.com/WPO-Foundation/webpagetest/issues/1078

If you look at the timelines for the run, you'll notice often their either empty or just contain the browser extension traffic

Are you using wptdriver or wptagent?

**Comment by soulgalore** [comment]
Hi @andydavies we are using wptdriver but I've seen this on Linux with Browsertime too.

**Comment by pmeenan** [comment]
Does Browsertime also use trace_parser.py?  It's possible that Chrome changes in 63 that moved the navigation out of process broke the parsing as it used to use the initial resource request to identify the main thread.

That said, the raw trace for that run didn't have a lot of events and script only showed up as a few milliseconds so there's a good chance the data just wasn't captured by devtools.  It might be time to move to the v8 call stats sampling for the JS breakdowns.

**Comment by soulgalore** [comment]
Yep now we use the trace_parser.py (thanks it is great!) but I tried with https://github.com/paulirish/devtools-timeline-model before and we got the same thing there. Also I'm pretty sure we have had this for a long time on our Windows agent (long before 63) but I can verify that tomorrow (we should have data one year back in time), it's just that we haven't paid so much attention to it until now.

**Comment by soulgalore** [comment]
I checked and I could see it that we at least had it since September last year (that was the time we started to collect the metrics). And @andydavies maybe remember if it is always been there?

**Comment by soulgalore** [comment]
I think I could be wrong about the problems on Linux, I've seen we have another problem with Chromedriver that causes the faulty traces (on our side).

**Comment by pmeenan** [comment]
The [trace viewer](http://wpt.wmftest.org/chrome/trace.php?test=180130_YW_Z&run=4) is showing a 600ms layout with dev tools events as well as a few EvaluateScript and other events (from the same trace that the timeline is pulled from):

![image](https://user-images.githubusercontent.com/444165/35681826-a46cd808-072c-11e8-8dfb-5f8a066ee046.png)

It's possible the trace_parser.py in the wptdriver instance had an issue parsing it (or even the current version) but there should have been a lot more activity in the timeline view.
