### ISSUE TITLE
wptdriver AWS Install - I think Chrome64 related - now has 0 RTT value

### ISSUE THREAD

**Issue by padibona** [WPO-Foundation/webpagetest#1102]
Hello,

As of 01/24 some time between 02:32 PM CDT and 03:32 PM CDT  It looks like our AWS Chrome wptdriver windows agents are not recording and/or calculating the Base Page Server RTT anymore. The values are missing from JSON Results and the Raw Page Data.csv. 

Chrome 63 version csv:

![image](https://user-images.githubusercontent.com/2515197/35881541-c204b6b0-0b46-11e8-89b8-c646428b2f9b.png)

Chrome 64 version csv:

![image](https://user-images.githubusercontent.com/2515197/35881581-dff3231e-0b46-11e8-8fd1-f9b89adc9202.png)

This seems to be for both http:// and https:// requests.

Was there some Chrome changes that breaks this functionality?

Can anyone verify if the new wptagent has the same issue?

Any help would be appreciated.

Thanks,

Pete

**Comment by pmeenan** [comment]
Chrome 64 rollong out likely broke wptdriver as it can no longer hook the raw ssl streams.

wptagent doesn't yet pull out the base page RTT as a metric but it's on my list of things to add when I get back into the office next week.

**Comment by padibona** [comment]
Closing this particular issue as it is WPTDriver related. We've moved to the Linux wptagent.
