### ISSUE TITLE
Redesign of the Website

### ISSUE THREAD

**Issue by YoKoGFX** [WPO-Foundation/webpagetest#1105]
I love this tool but the UI is just, so ugly. This UI can be implemented in some minutes, it has a SVG Logo and more modern Colors. I wanted to keep most of the original Design because many people know how to use it. So it just new Logo and Colors.

Feedback is appreciated :)

<img width="1283" alt="bildschirmfoto 2018-02-20 um 20 01 21" src="https://user-images.githubusercontent.com/18743976/36443391-e1e0c888-1678-11e8-915b-683bc1a6f833.png">

**Comment by andydavies** [comment]
I preferred this one - https://www.webpagetest.org/forums/showthread.php?tid=14732&highlight=design

But key thing to do is read the comment Pat left in that thread about how he'd like any PRs to be submitted
