### ISSUE TITLE
HotJar server not listed as using CDN

### ISSUE THREAD

**Issue by Psycic101** [WPO-Foundation/webpagetest#1107]
Resources from https://insights.hotjar.com/ are served by MaxCDN but result in FAILED in test results.
https://help.hotjar.com/hc/en-us/articles/115009335727-Will-Hotjar-Slow-Down-My-Site-
![hotjar-webpagetest-cdn](https://user-images.githubusercontent.com/983667/36471193-44bf22ce-16f6-11e8-8129-15c550add9a3.png)

**Comment by pmeenan** [comment]
Doesn't look like it is set up to serve through MaxCDN.  All of the IP addresses in DNS resolve to EC2 instances in the eu-west-1 region.  The documentation looks to be incorrect or maybe they moved to use a DNS-based localization service to point to EC2 regions but it doesn't appear to be using a CDN.

```
>nslookup insights.hotjar.com
Server:  UnKnown
Address:  192.168.0.1

Non-authoritative answer:
Name:    insights.hotjar.com
Addresses:  34.241.102.249
          52.209.227.123
          34.250.172.204
          52.19.105.22
          52.209.205.49
          52.208.235.157
          52.17.197.111
          52.214.207.35
```

```
>nslookup 34.241.102.249
Server:  UnKnown
Address:  192.168.0.1

Name:    ec2-34-241-102-249.eu-west-1.compute.amazonaws.com
Address:  34.241.102.249
```

**Comment by pmeenan** [comment]
Doing the same DNS lookup from Australia also resolves back to the same EC2 region so it is also not using a DNS-based localization.  The documentation is just wrong and it is not geo-distributed.
