### ISSUE TITLE
Better EC2 agent elasticity defined on runs number rather than tests number

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#1108]
We move to EC2 automatic scaling capability with the following settings : 

```ini
EC2.ScaleFactor=5
EC2.IdleTerminateMinutes=10
EC2.paris.min=0
EC2.paris.max=20
```
We notice a few issues : 
- the maximum instances number has not been taken into account. We had 60 running instances in parallel. I didn't trace the code to see where was the bug.

- ScaleFactor is applied on tests but don't take the number of runs by tests.  At Fasterize, we always perform 10 runs by test and take the median run. In this case, we are waiting too much for getting the median result.
Ideally, we would like to change this behavior to be able to quickly start three or four instances when a test of 10 runs is performed.
So, we think that the ScaleFactor should be defined on **cumulated runs number** rather that tests number.
- We don't have the number of EC2 instances in /getTesters.php?f=html. It's difficult to find the actual size of the pool.

**Comment by abarre** [comment]
Actually, the number of instances reported by **/install** is wrong but the real number of instances follow the constraint of the maximum number of instances.

**Comment by avastu** [comment]
We would also love to see auto scaling based on cumulated runs. We run up to 100 iterations in a particular test, so even if one testing is waiting in the queue, it would be helpful to scale up more than 1 agent. Is there any reason to _not_ add this?
