### ISSUE TITLE
EC2 instances terminated while test is running

### ISSUE THREAD

**Issue by mkreidenweis** [WPO-Foundation/webpagetest#1114]
Hi Pat, 

you already mentioned this issue at SmashingConf in London, but I couldn't find a Github issue for it, so I'm opening one here: 

We're running the provided AMI which automatically launches test agents. However, regularly test agents are being terminated while a test is still running on there. For example look at this `test.log`:
```
2018/02/27 06:17:10 - Test Created
2018/02/27 06:35:25 - Starting test (initiated by tester i-01cf3db507534ac23)
2018/02/27 06:36:20 - Test Run Complete. Run: 1, Cached: 0, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:36:20 - Extracting 799545 byte uploaded file '/tmp/php6blpLh' to './results/18/02/27/8V/8Q'
2018/02/27 06:36:20 - Done Processing. Run: 1, Cached: 0, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:37:08 - Test Run Complete. Run: 1, Cached: 1, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:37:08 - Extracting 1064700 byte uploaded file '/tmp/phpWbqCOs' to './results/18/02/27/8V/8Q'
2018/02/27 06:37:08 - Done Processing. Run: 1, Cached: 1, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:38:03 - Test Run Complete. Run: 2, Cached: 0, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:38:03 - Extracting 859846 byte uploaded file '/tmp/phpuDxVrn' to './results/18/02/27/8V/8Q'
2018/02/27 06:38:04 - Done Processing. Run: 2, Cached: 0, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:38:48 - Test Run Complete. Run: 2, Cached: 1, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:38:48 - Extracting 750702 byte uploaded file '/tmp/phpchoP8X' to './results/18/02/27/8V/8Q'
2018/02/27 06:38:49 - Done Processing. Run: 2, Cached: 1, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:39:40 - Test Run Complete. Run: 3, Cached: 0, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:39:40 - Extracting 819225 byte uploaded file '/tmp/phpcCCDEF' to './results/18/02/27/8V/8Q'
2018/02/27 06:39:40 - Done Processing. Run: 3, Cached: 0, Done: , Tester: i-01cf3db507534ac23
2018/02/27 06:51:42 - Test has been running for 16 minutes and it has been 12.033333333333 since the last update, forcing the full test to finish.
```

The last repeat run never returns. In `ec2.log.20180227` I can find the following entries referencing this tester instance: 
```
06:20:15 - Instance i-01cf3db507534ac23 started: m3.medium ami ami-87f2ebeb in eu-central-1 for eu-central-1,eu-central-1_IE11 with user data: wpt_server=[censored] wpt_loc=eu-central-1,eu-central-1_IE11 wpt_key=[censored]
06:40:13 - Terminated instance i-01cf3db507534ac23 in eu-central-1
```

This config in `settings.ini` might be relevant: 
```
    EC2.ScaleFactor=2
    EC2.max=8
    max_run_minutes=12
    maxtime=480
```
We did *not* set `EC2.IdleTerminateMinutes`, thinking a 15 minute default should be fine.

The most annoying side effect of this behavior actually is that `jsonResult.php` returns an error 500 when checking for the test status. See this excerpt from the nginx access log:
```
35.189.195.204 - - [27/Feb/2018:06:50:41 +0000] "GET /jsonResult.php?test=180227_8V_8Q HTTP/1.1" 200 486 "-" "-"
35.189.195.204 - - [27/Feb/2018:06:50:51 +0000] "GET /jsonResult.php?test=180227_8V_8Q HTTP/1.1" 200 485 "-" "-"
35.189.195.204 - - [27/Feb/2018:06:51:01 +0000] "GET /jsonResult.php?test=180227_8V_8Q HTTP/1.1" 200 483 "-" "-"
35.189.195.204 - - [27/Feb/2018:06:51:11 +0000] "GET /jsonResult.php?test=180227_8V_8Q HTTP/1.1" 200 487 "-" "-"
35.189.195.204 - - [27/Feb/2018:06:51:22 +0000] "GET /jsonResult.php?test=180227_8V_8Q HTTP/1.1" 200 482 "-" "-"
35.189.195.204 - - [27/Feb/2018:06:51:32 +0000] "GET /jsonResult.php?test=180227_8V_8Q HTTP/1.1" 200 485 "-" "-"
35.189.195.204 - - [27/Feb/2018:06:51:42 +0000] "GET /jsonResult.php?test=180227_8V_8Q HTTP/1.1" 500 5 "-" "-"
```
This causes the sitespeed.io job to crash (`ERROR: Error creating WebPageTest result {"name":"WPTAPIError","code":500,"message":"Internal Server Error"}`).
Maybe it's because the test is never seen "done" in `workdone.php` and thus `postprocess.php` is never called there and then some ad-hoc post-processing happens which leads to an error. 
Any subsequent requests to the same `/jsonResult.php?test=180227_8V_8Q` URL actually succeed though. So I cannot really reproduce this error unfortunately. It doesn't show up in any nginx or php error log either. 

Is there any way we can help getting this fixed?

Best regards, 
Martin

**Comment by pmeenan** [comment]
If you pass debug=1 with your jsonResult.php calls it should bypass the the code that disables the logging of errors and hopefully that will at least identify what is causing the 500 errors.  Something in the code path is pretty broken to generate a 500 and I assume it is somewhere in the [logic where it times out tests](https://github.com/WPO-Foundation/webpagetest/blob/master/www/testStatus.inc#L95).

If you sync to the latest from github (release or master branch) I fixed one edge case that I could identify in the idle detection and also added logging for how long the code thought the agent was idle for to the ec2 log which should at least help a bit.

**Comment by abarre** [comment]
@mkreidenweis, the timing is surprising.
I'm spending my two last day on similar issues : a lot of 'Test missing data', error 500 in jsonResult.php.
I will apply the patch and see if I can help.

In our case, `EC2.IdleTerminateMinutes` is set to 10 minutes.

**Comment by padibona** [comment]
Just an FYI on windows ec2 ami agents we also get several 'test data
missing' test per day which can block testing for up to 45 minutes. I
haven't had a chance to look into the why, and don't expect to be able to
any time soon. Just wanted to chime in as I saw 'test data missing'!

Thanks,

Pete

**Comment by dax** [comment]
Here is what we get in the log with `EC2.IdleTerminateMinutes=30` :
```
14:25:12 - Launching c5.large ami ami-4370c63e in eu-west-3 ...
14:25:13 - Instance i-0c9fc7dee99af3c00 started: c5.large ami ami-4370c63e in eu-west-3 ...
15:00:12 - Launching c5.large ami ami-4370c63e in eu-west-3 ...
15:00:13 - Instance i-00f99452986629c2c started: c5.large ami ami-4370c63e in eu-west-3 ...
15:00:13 - Launching c5.large ami ami-4370c63e in eu-west-3 ...
15:00:14 - Instance i-005ade4d74c3fd796 started: c5.large ami ami-4370c63e in eu-west-3 ...
15:05:11 - Terminatingstance  in  - lastWork = 99999, lastCheck = 99999
15:05:11 - Terminated instance i-0c9fc7dee99af3c00 in eu-west-3
15:05:11 - Launching c5.large ami ami-4370c63e in eu-west-3 ...
15:05:12 - Instance i-08a7233696499e1c4 started: c5.large ami ami-4370c63e in eu-west-3 ...
```

Here we can see that:
- instance `i-0c9fc7dee99af3c00` is terminated 30 minutes after it has been started whereas there was tests to run in the meantime (other instances were started as the queue was filling up)
- `lastWork = 99999` and `lastCheck = 99999` seems to be buggy values
- an new instance is started the second after `i-0c9fc7dee99af3c00` is terminated

Hope this helps

**Comment by pmeenan** [comment]
99999 are placeholders I added for when there was no reported times.  Clearly I also had an error in the log message since it didn't list the region and instance ID but it would have been i-0c9fc7dee99af3c00 in eu-west-3.

I think one of the issues may be that the Windows instances may take longer than 15 minutes to start and it is getting terminated before it can start.  The sub-hourly killing was really only meant to be used with the Linux AMI's but I don't think the logic differentiates (or even knows).

I took another stab at cleaning up the logic so that it ignores any instances that were started in the last hour if they haven't checked in yet.  It also looks like the logic change I had made before to track the last time the agents connected was wrong and not helpful - I cleaned that up as well.  I also tweaked the "last job" logic to update any time it gets partial results back so large multi-run tests on a single agent will not look like they were started too long before.

Finally, I just added logic to never terminate an instance if the server thinks it is working on a test. (same thing that marks it as busy in the gettesters.php UI)  Presumably this will take care of any remaining edge cases.

**Comment by abarre** [comment]
In the log above, the ami `ami-4370c63e` is a linux AMI.
I will trace the content of the $instances hash to see if I find inconsistant data for $tester['last'] and $tester['elapsed'];

**Comment by abarre** [comment]
Here is a dump of `EC2_GetRunningInstances()` and `EC2_GetTesters()` for the method `EC2_TerminateIdleInstances`.

```
14:10:11 - instances ->
14:10:11 - Array
(
    [0] => Array
        (
            [region] => eu-west-3
            [id] => i-056abd1eb85e7a9ff
            [ami] => ami-317acc4c
            [state] => 16
            [launchTime] => 2018-03-01T13:59:35.000Z
            [launched] => 1519912775
            [runningTime] => 626
            [locations] => Array
                (
                    [0] => frz_eu_paris_wptdriver
                )

            [running] => 1
        )

    [1] => Array
        (
            [region] => eu-west-3
            [id] => i-055ba57d3f2ccc2c1
            [ami] => ami-317acc4c
            [state] => 16
            [launchTime] => 2018-03-01T14:04:35.000Z
            [launched] => 1519913075
            [runningTime] => 326
            [locations] => Array
                (
                    [0] => frz_eu_paris_wptdriver
                )

            [running] => 1
        )

    [2] => Array
        (
            [region] => eu-west-3
            [id] => i-08df301f2a09c16bc
            [ami] => ami-317acc4c
            [state] => 16
            [launchTime] => 2018-03-01T14:04:38.000Z
            [launched] => 1519913078
            [runningTime] => 323
            [locations] => Array
                (
                    [0] => frz_eu_paris_wptdriver
                )

            [running] => 1
        )

    [3] => Array
        (
            [region] => eu-west-3
            [id] => i-073e7225cf488181b
            [ami] => ami-317acc4c
            [state] => 16
            [launchTime] => 2018-03-01T14:04:37.000Z
            [launched] => 1519913077
            [runningTime] => 324
            [locations] => Array
                (
                    [0] => frz_eu_paris_wptdriver
                )

            [running] => 1
        )

)

14:10:11 - locations
14:10:11 - Array
(
    [Paris_hard_location] => Array
        (
            [testers] => Array
                (
                    [0] => Array
                        (
                            [id] => KIMSUFI-91.121.181.199
                            [pc] => KIMSUFI
                            [ec2] =>
                            [ip] => 91.121.181.199
                            [version] => 17.12.0.403
                            [freedisk] => 1847.933
                            [upminutes] =>
                            [ie] =>
                            [winver] => 6.3
                            [isWinServer] => 1
                            [isWin64] => 1
                            [dns] => 8.8.8.8,8.8.4.4
                            [GPU] => 1
                            [offline] =>
                            [screenwidth] => 1600
                            [screenheight] => 1200
                            [test] =>
                            [rebooted] =>
                            [cpu] => 15
                            [errors] => 3
                            [elapsed] => 0
                            [last] => 180
                            [busy] => 0
                        )

                )

            [elapsed] => 0
            [status] => OK
        )

)
```
We keep getting 99999 values for `$lastCheck` and `$lastWork`.
I suspect that `EC2_GetTesters()` is buggy and don't list locations from ec2_locations.ini since `frz_eu_paris_wptdriver` is not listed in the locations object.

**Comment by abarre** [comment]
I think that I found the bug.
EC2_GetTesters has a loop `while` that will stop if there is the location list is not a **contiguous** sequence started at 1. In our case, we commented several location in ec2_locations.ini. The first uncommented location  `frz_eu_paris_wptdriver ` had the index 16 rather than 1.

**Comment by pmeenan** [comment]
Oh, that will break a lot of things.  The API will probably still work but the UI uses the same parsing logic (which admittedly is a pain to manage).

**Comment by pmeenan** [comment]
And by break, I mean the code assumes the locations are numbered incrementally.  I'd happily accept a PR that changes it though and extracts all of the ID's regardless of the key in front of it.  The current logic was just easier because of how php loads ini files.

**Comment by abarre** [comment]
Thanks for the details @pmeenan.
@mkreidenweis, did you have the same issue as mine about the ini file ?

**Comment by mkreidenweis** [comment]
@abarre Actually we didn't change anything about `ec2_locations.ini` IIRC. The `[locations]` section contains all numbers between 1 and 30 for us. 

Regular 500 errors are gone for us. Last one of them happened on `28/Feb/2018:16:57:49 +0000`. (Not sure how often the autoupdate for WPT runs.)
So I'd consider this bug fixed and am closing this issue now, okay?

Thank you @pmeenan for addressing this so quickly. :-)
