### ISSUE TITLE
Initiator missing for resources injected via scripts(?)

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1115]
Some requests in this test have initiators, but they are missing for others http://www.webpagetest.org/result/180303_5H_4a55b77a68f10ce82f7c4d47092daaf4/1/details/ 

Testing same page (https://www.mountainwarehouse.com/mens/clearance/) in Chrome 64.0.3282.186 shows requests with missing initiators appear to have been script injected e.g by GTM etc

Many of the requests from about 50 on are examples of this.

Issue currently breaks @simonhearne's RequestMap (http://requestmap.herokuapp.com/)

**Comment by pmeenan** [comment]
Just [fixed it](https://github.com/WPO-Foundation/wptagent/commit/dfc905c908ddacbca24b7f7e6aba33b3882c620e) in the agent and it is rolling out now (will take up to an hour to be live across all instances).

**Comment by pmeenan** [comment]
Fix should be rolled out now: http://www.webpagetest.org/result/180305_1C_01c0bdda292c01eb0c62d291309fbe04/1/details/#waterfall_view_step1

**Comment by andydavies** [comment]
Fabulous, thank you
