### ISSUE TITLE
What does "Page Load Timeout" mean?

### ISSUE THREAD

**Issue by trap0959** [WPO-Foundation/webpagetest#1118]
I am using webpagetest_17.12 privateinstance.
IE11 and EDGE execution result "First View (Test Error: Page load timeout") error occurs.

What does "Page Load Timeout" mean?
What is the solution?

**Comment by pmeenan** [comment]
It means the 2 minute timeout for the test hit before the onload event fired (or at least was detected). There have been quite a few improvements to the Edge/IE support in wptagent since the last release that should help.  I'll cut a new official release later today with the updates or you can grab the wptagent updates from [github](https://github.com/WPO-Foundation/wptagent/tree/release).

**Comment by SSam009** [comment]
I  have set up the wptagent  on windows server 2012R2 using latest code   (https://github.com/WPO-Foundation/wptagent/tree/release).  When I run the test with IE11, test ran successfully, But always getting   "First View (Test Error: Page load timeout)"  error.  How can we fix it ?

**Comment by SSam009** [comment]
@pmeenan , I was not able to reproduce it on public instance ,  I have attached the  screenshot and  verbose log from my windows agent
![wpt_pageloadtimeout](https://user-images.githubusercontent.com/38958600/44429929-1b1e8680-a567-11e8-949c-d7382772d322.PNG)
 
[debug9.txt](https://github.com/WPO-Foundation/webpagetest/files/2308106/debug9.txt)

**Comment by dimension85** [comment]
I too have the problem of 'Test Run Error: "Page Load Timeout"'.  This only appears in the log, so looking at the report or JSON output it is assumed you have a full successful run without any issues. 

Is it possible to have this error in the JSON report as well, next to the StatusText would be ideal.?

I found that I was missing test runs on my private instance and this is the cause as I look for the successful run flags, which in this case show as 0, but in fact there is considerable value still in the report.

Phil
