### ISSUE TITLE
AWS Linux wptagent: Test Error: Unhandled exception in test run: 'load_ms' - Public and Private

### ISSUE THREAD

**Issue by padibona** [WPO-Foundation/webpagetest#1124]
Hello.

I just noticed this error popping up on our recent private install of the EC2 linux wptagents and have verified I see it on a public Tokyo EC2 Linux agent as well:

http://www.webpagetest.org/result/180330_WV_6c8c60224478c6849e7abee802e50a81/ 

Unfortunately, I haven't been able to connect to our Autoscaled Linux machine to attempt to debug things, is there a trick to connecting to those?

I do not see this on all pages we test, FYI.

Here are other pages that seem to have the same error. 

http://www.webpagetest.org/result/180330_6M_36db359a03ca5361cbacde5c11bf5257/
http://www.webpagetest.org/result/180330_09_9c6b41ed2ae162fa0eeeed3118317303/
http://www.webpagetest.org/result/180330_BG_f5ac66facd695edfc7cc8b75f99b9f60/
http://www.webpagetest.org/result/180330_XA_ecf2d6d6a9a4d3260445a3e336d1b4a2/
http://www.webpagetest.org/result/180330_4A_93508f5ddd8922a995f59bf705ff4678/
http://www.webpagetest.org/result/180330_DB_efe17f0d1022b2c4642a2544bfbd4e86/
http://www.webpagetest.org/result/180330_SS_562662c4afba45c161feed16d5935d59/

Possibly unrelated, but also saw this: This was on Virgina EC2 Linux wptagent:

https://www.webpagetest.org/results.php?test=180330_TH_ff86f33bdebf6fc9386d6d590f8f380e

Script for test linked directly above, which was kicked off via API, is as follows:

setEventName	01_Home
navigate	http://shop.techsmith.com/store/techsm/DisplayHomePage
setEventName	02_Product_Details
navigate	http://shop.techsmith.com/store/techsm/en_US/pd/productID.289200200
setEventName	03_Add_to_Mini_cart
navigate	http://shop.techsmith.com/store/?Action=AddItemToRequisition&SiteID=techsm&Locale=en_US&Form=&CallingPageID=ProductDetailsPage&CSRFAuthKey=&productID-289200200-0=Download&productID-289200200-1=English&productID=291109100&quantity=1
setEventName	04_Show_Cart
navigate	http://shop.techsmith.com/store/techsm/en_US/DisplayShoppingCartPage
setEventName	05_Checkout
navigate	https://shop.techsmith.com/store/techsm/en_US/DisplayThreePgCheckoutAddressPaymentInfoPage/ThemeID.36513100

Actual request sent to server:

http://yourWebPageTestServer/runtest.php?script=setEventName%0901_Home%0A+navigate%09http%3A%2F%2Fshop.techsmith.com%2Fstore%2Ftechsm%2FDisplayHomePage%0A+setEventName%0902_Product_Details%0A+navigate%09http%3A%2F%2Fshop.techsmith.com%2Fstore%2Ftechsm%2Fen_US%2Fpd%2FproductID.289200200%0A+setEventName%0903_Add_to_Mini_cart%0A+navigate%09http%3A%2F%2Fshop.techsmith.com%2Fstore%2F%3FAction%3DAddItemToRequisition%26SiteID%3Dtechsm%26Locale%3Den_US%26Form%3D%26CallingPageID%3DProductDetailsPage%26CSRFAuthKey%3D%26productID-289200200-0%3DDownload%26productID-289200200-1%3DEnglish%26productID%3D291109100%26quantity%3D1%0A+setEventName%0904_Show_Cart%0A+navigate%09http%3A%2F%2Fshop.techsmith.com%2Fstore%2Ftechsm%2Fen_US%2FDisplayShoppingCartPage%0A+setEventName%0905_Checkout%0A+navigate%09https%3A%2F%2Fshop.techsmith.com%2Fstore%2Ftechsm%2Fen_US%2FDisplayThreePgCheckoutAddressPaymentInfoPage%2FThemeID.36513100&k=yourapiKey&location=us-east-1-linux&runs=1&fvonly=1&connections=0&web10=0&video=1&timeline=0&f=json&tcpdump=0&noopt=0&noimages=1&noheaders=0&pngss=0&noscript=0&iq=100&htmlbody=0&ignoreSSL=1

Now the code I use to drive these API tests polls the status page every 2 seconds until it sees that the test is complete, then pretty much instantly hits the JSON Results URL shown in the initial runtest API call response, if that makes sense.

Is it possible that me hitting the JSON results too quickly is causing a race condition or causing some other issue? EC2 Server Machine is a t2.medium. ami-fcfd6194

When I do the scripted test manually it seems to work fine. 

Also worked fine on wptdriver windows machine previously.

If there is anything you would like me to look at on our server I'd be happy to. 

Thanks for all of the work on the new agents, nice looking Python.

Thanks,

Pete

**Comment by pmeenan** [comment]
Pretty sure I know what's going on. Will have a fix in a minute.

________________________________

**Comment by pmeenan** [comment]
[Fix just landed](https://github.com/WPO-Foundation/wptagent/commit/962a6f703204787ea394ddd13c35dac094a9c13f) and the agents should pick it up within the hour.  It's related to a [fix earlier today](https://github.com/WPO-Foundation/wptagent/issues/94) for calculating fullyLoaded times but could throw an exception for any requests that start but never got a response.

**Comment by padibona** [comment]
Looks good. No more errors.

Thanks!
