### ISSUE TITLE
Some timelines not loading in the inspector

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#1125]
We're seeing a number of Chrome timelines that fail to load in the current inspector (20170320) which is a year old now. Would an update of the inspector help?

Failing to load: https://wpt1.speedcurve.com/chrome/inspector-20170320/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?timeline=t:180322_1N_44c86853c01af4f6a0db8784acc2cd1f,r:2,c:0,s:1

Interestingly an even older version of the inspect seems to load the same timeline fine: https://wpt1.speedcurve.com/chrome/inspector-20160510/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?timeline=t:180322_1N_44c86853c01af4f6a0db8784acc2cd1f,r:2,c:0,s:1

**Comment by pmeenan** [comment]
If you download the timeline does it load in chrome's built-in viewer? That will be a good indicator if updating will work or if it also needs more trace categories.

________________________________

**Comment by zeman** [comment]
Nope doesn't work if I load it into Chrome 65.

**Comment by andydavies** [comment]
I’m seeing this but also seeing Chrome 65 failing to generate usable
timelines locally quite often.

Haven’t had a chance to dig into it in more detail / file bugs etc yet
