### ISSUE TITLE
Firefox - packet capture produces an empty file

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1128]
See http://www.webpagetest.org/result/180416_HS_736c9c26e984a9c7d94a57726ee2f444/

The keylog appears to be generated OK, but the packet capture is only 24 bytes!

Same page tested with Chrome produces a valid pcap, and key log.

(will see if I can spot any obvious issues later in the week)

**Comment by pmeenan** [comment]
Looks [OK on Linux](https://www.webpagetest.org/result/180416_Y0_dae6c675e2050a1967ac718988af9bbb/) - May be a Windows thing that I need to look into (though it would be bizarre to be different for Chrome).

**Comment by pmeenan** [comment]
Looks like it is [broken for Chrome as well](https://www.webpagetest.org/result/180416_DC_636b6b3df1a972a9e3148a74ad87fc8f/) (at least on the Thinkpads).  I'll check and make sure they have the npcap driver installed.

**Comment by pmeenan** [comment]
Should be [Fixed now](https://www.webpagetest.org/result/180416_JK_62bfb4b94e2d541bc00a7765d9eda304/).  All except for one of the thinkpads had the unused WiFi adapter enabled and packet capture on Windows isn't good at picking the right interface when there are multiple available.

**Comment by andydavies** [comment]
Fab, thanks
