### ISSUE TITLE
AMI Private Instance error: Sorry, that test location already has too many tests pending. Pleasy try again later.

### ISSUE THREAD

**Issue by AndreyNikiforov** [WPO-Foundation/webpagetest#1130]
Running private instance (AMI) with autoupdates and auto starting agents; and suddenly started to receive error on all API-base test requests: "Sorry, that test location already has too many tests pending. Pleasy try again later."

/checkURLs.php shows empty list

What is the best way to troubleshoot?

**Comment by pmeenan** [comment]
I'm pretty sure the error message is wrong and it's actually an error with writing the test job to the queue directory (maybe a permissions problem).  Does /install show everything as green?

**Comment by pmeenan** [comment]
Does it work through the UI and just fail through the API?  IF so then there is something wrong with how the API tests are submitted because the UI uses the API itself.

**Comment by AndreyNikiforov** [comment]
My Install returns:

WebPagetest 18.02 Installation Check
PHP
PHP version at least 5.3: 5.5.9-1ubuntu4.4
GD Module Installed: yes
FreeType enabled for GD (required for video rendering): yes
zip Module Installed: yes
zlib Module Installed: yes
mbstring available: yes
curl Module Installed: yes
php.ini allow_url_fopen enabled: yes
APC Installed: yes
SQLite Installed (for editable test labels): yes
Open SSL Module Installed (for "Login with Google"): yes
xml Module Installed (for rss feeds): yes
pcre Module Installed (for rss feeds): yes
xmlreader Module Installed (for rss feeds): yes
php.ini upload_max_filesize > 10MB: 100M
php.ini post_max_size > 10MB: 100M
php.ini memory_limit > 256MB or -1 (disabled): -1
System Utilities
ffmpeg Installed with --enable-libx264 (required for video): yes
ffmpeg Installed with scale and decimate filters(required for mobile video): 1.2.3,scale,decimate
imagemagick compare Installed (required for mobile video): yes
jpegtran Installed (required for JPEG Analysis): yes
exiftool Installed (required for JPEG Analysis): yes
beanstalkd responding on 127.0.0.1 (configured in settings.ini): NO
Misc
python 2.7 with modules (faster mobile video processing): Missing python modules: Pillow,SSIM (optional)
Filesystem
{docroot}/tmp writable: yes
{docroot}/dat writable: yes
{docroot}/results writable: yes
{docroot}/work/jobs writable: yes
{docroot}/logs writable: yes
{docroot}/tmp on tmpfs: yes
Test Locations
us-east-1-group : US East (N. Virginia)
us-east-1 : US East (N. Virginia) - No Agents Connected
us-east-1_IE11 : US East (N. Virginia) - No Agents Connected
us-east-1_IE10 : US East (N. Virginia) - No Agents Connected
us-east-1_IE9 : US East (N. Virginia) - No Agents Connected
us-east-1-linux-group : US East - Linux (N. Virginia)
us-east-1-linux : US East - Linux (N. Virginia) - No Agents Connected
us-east-2-group : US East 2 (Ohio)
us-east-2 : US East 2 (Ohio) - No Agents Connected
us-east-2_IE11 : US East 2 (Ohio) - No Agents Connected
us-east-2_IE10 : US East 2 (Ohio) - No Agents Connected
us-east-2_IE9 : US East 2 (Ohio) - No Agents Connected
us-east-2-linux-group : US East 2 - Linux (Ohio)
us-east-2-linux : US East 2 - Linux (Ohio) - No Agents Connected
us-west-1-group : US West (N. California)
us-west-1 : US West (N. California) - No Agents Connected
us-west-1_IE11 : US West (N. California) - No Agents Connected
us-west-1_IE10 : US West (N. California) - No Agents Connected
us-west-1_IE9 : US West (N. California) - No Agents Connected
us-west-1-linux-group : US West - Linux (N. California)
us-west-1-linux : US West - Linux (N. California) - No Agents Connected
us-west-2-group : US West (Oregon)
us-west-2 : US West (Oregon) - No Agents Connected
us-west-2_IE11 : US West (Oregon) - No Agents Connected
us-west-2_IE10 : US West (Oregon) - No Agents Connected
us-west-2_IE9 : US West (Oregon) - No Agents Connected
us-west-2-linux-group : US West 2 - Linux (Oregon)
us-west-2-linux : US West 2 - Linux (Oregon) - No Agents Connected
ca-central-1-group : Canada Central (Montreal)
ca-central-1 : Canada Central (Montreal) - No Agents Connected
ca-central-1_IE11 : Canada Central (Montreal) - No Agents Connected
ca-central-1_IE10 : Canada Central (Montreal) - No Agents Connected
ca-central-1_IE9 : Canada Central (Montreal) - No Agents Connected
ca-central-1-linux-group : Canada Central - Linux (Montreal)
ca-central-1-linux : Canada Central - Linux (Montreal) - No Agents Connected
eu-west-1-group : Europe (Ireland)
eu-west-1 : Europe (Ireland) - No Agents Connected
eu-west-1_IE11 : Europe (Ireland) - No Agents Connected
eu-west-1_IE10 : Europe (Ireland) - No Agents Connected
eu-west-1_IE9 : Europe (Ireland) - No Agents Connected
eu-west-1-linux-group : Europe - Linux (Ireland)
eu-west-1-linux : Europe - Linux (Ireland) - No Agents Connected
eu-west-2-group : EU (London)
eu-west-2 : Europe (London) - No Agents Connected
eu-west-2_IE11 : Europe (London) - No Agents Connected
eu-west-2_IE10 : Europe (London) - No Agents Connected
eu-west-2_IE9 : Europe (London) - No Agents Connected
eu-west-2-linux-group : Europe - Linux (London)
eu-west-2-linux : Europe - Linux (London) - No Agents Connected
eu-west-3-group : EU (Paris)
eu-west-3 : Europe (Paris) - No Agents Connected
eu-west-3_IE11 : Europe (Paris) - No Agents Connected
eu-west-3_IE10 : Europe (Paris) - No Agents Connected
eu-west-3_IE9 : Europe (Paris) - No Agents Connected
eu-west-3-linux-group : Europe - Linux (Paris)
eu-west-3-linux : Europe - Linux (Paris) - No Agents Connected
eu-central-1-group : Europe (Frankfurt)
eu-central-1 : Europe (Frankfurt) - No Agents Connected
eu-central-1_IE11 : Europe (Frankfurt) - No Agents Connected
eu-central-1_IE10 : Europe (Frankfurt) - No Agents Connected
eu-central-1_IE9 : Europe (Frankfurt) - No Agents Connected
eu-central-1-linux-group : Europe - Linux (Frankfurt)
eu-central-1-linux : Europe - Linux (Frankfurt) - No Agents Connected
ap-northeast-1-group : Asia Pacific (Tokyo)
ap-northeast-1 : Asia Pacific (Tokyo) - No Agents Connected
ap-northeast-1_IE11 : Asia Pacific (Tokyo) - No Agents Connected
ap-northeast-1_IE10 : Asia Pacific (Tokyo) - No Agents Connected
ap-northeast-1_IE9 : Asia Pacific (Tokyo) - No Agents Connected
ap-northeast-1-linux-group : Asia Pacific - Linux (Tokyo)
ap-northeast-1-linux : Asia Pacific - Linux (Tokyo) - No Agents Connected
ap-northeast-2-group : Asia Pacific (Seoul)
ap-northeast-2 : Asia Pacific (Seoul) - No Agents Connected
ap-northeast-2_IE11 : Asia Pacific (Seoul) - No Agents Connected
ap-northeast-2_IE10 : Asia Pacific (Seoul) - No Agents Connected
ap-northeast-2_IE9 : Asia Pacific (Seoul) - No Agents Connected
ap-northeast-2-linux-group : Asia Pacific - Linux (Seoul)
ap-northeast-2-linux : Asia Pacific - Linux (Seoul) - No Agents Connected
ap-southeast-1-group : Asia Pacific (Singapore)
ap-southeast-1 : Asia Pacific (Singapore) - No Agents Connected
ap-southeast-1_IE11 : Asia Pacific (Singapore) - No Agents Connected
ap-southeast-1_IE10 : Asia Pacific (Singapore) - No Agents Connected
ap-southeast-1_IE9 : Asia Pacific (Singapore) - No Agents Connected
ap-southeast-1-linux-group : Asia Pacific - Linux (Singapore)
ap-southeast-1-linux : Asia Pacific - Linux (Singapore) - No Agents Connected
ap-south-1-group : India (Mumbai)
ap-south-1 : India (Mumbai) - No Agents Connected
ap-south-1_IE11 : India (Mumbai) - No Agents Connected
ap-south-1_IE10 : India (Mumbai) - No Agents Connected
ap-south-1_IE9 : India (Mumbai) - No Agents Connected
ap-south-1-linux-group : India - Linux (Mumbai)
ap-south-1-linux : India - Linux (Mumbai) - No Agents Connected
ap-southeast-2-group : Asia Pacific (Sydney)
ap-southeast-2 : Asia Pacific (Sydney) - No Agents Connected
ap-southeast-2_IE11 : Asia Pacific (Sydney) - No Agents Connected
ap-southeast-2_IE10 : Asia Pacific (Sydney) - No Agents Connected
ap-southeast-2_IE9 : Asia Pacific (Sydney) - No Agents Connected
ap-southeast-2-linux-group : Asia Pacific - Linux (Sydney)
ap-southeast-2-linux : Asia Pacific - Linux (Sydney) - No Agents Connected
sa-east-1-group : South America (Sao Paulo)
sa-east-1 : South America (Sao Paulo) - No Agents Connected
sa-east-1_IE11 : South America (Sao Paulo) - No Agents Connected
sa-east-1_IE10 : South America (Sao Paulo) - No Agents Connected
sa-east-1_IE9 : South America (Sao Paulo) - No Agents Connected
sa-east-1-linux-group : South America - Linux (Sao Paulo)
sa-east-1-linux : South America - Linux (Sao Paulo) - No Agents Connected


Since I am auto starting agents, I assume that not connected agents are okay. When I have agent started, then it shows green as expected.

I had error for UI based tests initially, then I restarted master and I can submit test through UI now, but not through API.

**Comment by pmeenan** [comment]
Can you log the full URL you are using for runtest.php from the API and send it to me (or post here with the server info removed)?  It's possible the location ID doesn't match or that something in the request isn't correctly url-encoded.  If the UI works the API should also work and it's just a matter of figuring out which parameter is messing it up.

**Comment by AndreyNikiforov** [comment]
here is final url from my code:

`
http://ServerRemoved//runtest.php?runs=1&lighthouse=1&timeline=1&pageSpeed=0&label=Home&k=KeyRemoved&fvOnly=1&location=us-west-2-linux%3AChrome.3G&mobile=1&mobileDevice=Nexus%205X&f=json&url=https%3A%2F%2Fwww.trulia.com
`

**Comment by AndreyNikiforov** [comment]
same code against public wpt ran fine. here is final url:

`
https://www.webpagetest.org/runtest.php?runs=1&lighthouse=1&timeline=1&pageSpeed=0&label=Home&k=KeyRemoved&fvOnly=1&location=Dulles_IE11%3AChrome.3G&mobile=1&mobileDevice=Nexus%205X&f=json&url=https%3A%2F%2Fwww.trulia.com
`

**Comment by pmeenan** [comment]
Yeah, looking at the request URL, it looks fine.  When you submit through the UI did you also submit the the linux agent for the same location and with the same mobile device emulation?  Just trying to narrow down the failure.

If you add a &debug=1 to the query params runtest.php should re-enable error logging and it's possible something will show up in the error log on the server that would help identify the issue.

**Comment by AndreyNikiforov** [comment]
Ran with debug=1, still got error from API. Where should I check logs?

Checked /var/www/webpagetest/www/logs and /var/www/webpagetest/www/log and nothing is there.

**Comment by pmeenan** [comment]
/var/log/nginx/error.log

**Comment by AndreyNikiforov** [comment]
`tail /var/log/nginx/error.log` (all IPs redacted)

```
2018/04/22 11:03:06 [error] 1207#0: *62015 open() "/var/www/webpagetest/www/user/register" failed (2: No such file or directory), client: 201.XXX.XXX.XXX, server: , request: "POST /user/register?element_parents=account/mail/%23value&ajax_form=1&_wrapper_format=drupal_ajax HTTP/1.1", host: "34.XXX.XXX.XXX"
2018/04/22 11:03:07 [error] 1207#0: *62020 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 201.XXX.XXX.XXX, server: , request: "GET /rss.php?mode=recent HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
2018/04/22 11:17:51 [error] 1207#0: *62118 open() "/var/www/webpagetest/www/wls-wsat/CoordinatorPortType" failed (2: No such file or directory), client: 91.XXX.XXX.XXX, server: , request: "POST /wls-wsat/CoordinatorPortType HTTP/1.1", host: "34.XXX.XXX.XXX:80"
2018/04/22 11:17:51 [error] 1207#0: *62119 open() "/var/www/webpagetest/www/user/register" failed (2: No such file or directory), client: 91.XXX.XXX.XXX, server: , request: "POST /user/register?element_parents=account/mail/%23value&ajax_form=1&_wrapper_format=drupal_ajax HTTP/1.1", host: "34.XXX.XXX.XXX"
2018/04/22 11:17:52 [error] 1207#0: *62124 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 91.XXX.XXX.XXX, server: , request: "GET /rss.php?mode=recent HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
2018/04/22 11:17:53 [error] 1207#0: *62126 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 91.XXX.XXX.XXX, server: , request: "GET /wp-login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
2018/04/22 12:09:33 [error] 1207#0: *62649 open() "/var/www/webpagetest/www/wls-wsat/CoordinatorPortType" failed (2: No such file or directory), client: 191.XXX.XXX.XXX, server: , request: "POST /wls-wsat/CoordinatorPortType HTTP/1.1", host: "34.XXX.XXX.XXX:80"
2018/04/22 12:09:33 [error] 1207#0: *62650 open() "/var/www/webpagetest/www/user/register" failed (2: No such file or directory), client: 191.XXX.XXX.XXX, server: , request: "POST /user/register?element_parents=account/mail/%23value&ajax_form=1&_wrapper_format=drupal_ajax HTTP/1.1", host: "34.XXX.XXX.XXX"
2018/04/22 12:09:34 [error] 1207#0: *62655 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 191.XXX.XXX.XXX, server: , request: "GET /rss.php?mode=recent HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
2018/04/22 12:09:35 [error] 1207#0: *62657 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 191.XXX.XXX.XXX, server: , request: "GET /wp-login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
```

**Comment by AndreyNikiforov** [comment]
running `tail /var/log/nginx/error.log` right after trying test with `debug=1` param gave a bit more info (all IPs and key redacted):

```
2018/04/22 12:09:33 [error] 1207#0: *62649 open() "/var/www/webpagetest/www/wls-wsat/CoordinatorPortType" failed (2: No such file or directory), client: 191.XXX.XXX.XXX, server: , request: "POST /wls-wsat/CoordinatorPortType HTTP/1.1", host: "34.XXX.XXX.XXX:80"
2018/04/22 12:09:33 [error] 1207#0: *62650 open() "/var/www/webpagetest/www/user/register" failed (2: No such file or directory), client: 191.XXX.XXX.XXX, server: , request: "POST /user/register?element_parents=account/mail/%23value&ajax_form=1&_wrapper_format=drupal_ajax HTTP/1.1", host: "34.XXX.XXX.XXX"
2018/04/22 12:09:34 [error] 1207#0: *62655 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 191.XXX.XXX.XXX, server: , request: "GET /rss.php?mode=recent HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
2018/04/22 12:09:35 [error] 1207#0: *62657 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 191.XXX.XXX.XXX, server: , request: "GET /wp-login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
2018/04/22 13:37:18 [error] 1207#0: *63297 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: req_bwDown in /var/www/webpagetest/www/runtest.php on line 169
PHP message: PHP Warning:  file(./settings/blockip.txt): failed to open stream: No such file or directory in /var/www/webpagetest/www/runtest.php on line 1855
PHP message: PHP Notice:  Undefined variable: req_r in /var/www/webpagetest/www/runtest.php on line 973" while reading response header from upstream, client: 8.XXX.XXX.XXX, server: , request: "GET //runtest.php?runs=1&lighthouse=1&timeline=1&pageSpeed=0&label=Home&k=REMOVED&fvOnly=1&location=us-west-2-linux%3AChrome.3G&mobile=1&mobileDevice=Nexus%205X&f=json&debug=1&url=https%3A%2F%2Fwww.trulia.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
2018/04/22 13:37:18 [error] 1207#0: *63296 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: req_bwDown in /var/www/webpagetest/www/runtest.php on line 169
PHP message: PHP Warning:  file(./settings/blockip.txt): failed to open stream: No such file or directory in /var/www/webpagetest/www/runtest.php on line 1855
PHP message: PHP Notice:  Undefined variable: req_r in /var/www/webpagetest/www/runtest.php on line 973" while reading response header from upstream, client: 8.XXX.XXX.XXX, server: , request: "GET //runtest.php?runs=1&lighthouse=1&timeline=1&pageSpeed=0&label=Home&k=REMOVED&fvOnly=1&location=us-west-2-linux%3AChrome.Cable&mobile=0&mobileDevice=false&f=json&debug=1&url=https%3A%2F%2Fwww.trulia.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "34.XXX.XXX.XXX"
```

**Comment by pmeenan** [comment]
:(  None of those look fatal.  Might have to add logging to runtest.php itself to see where and why it is failing.

**Comment by AndreyNikiforov** [comment]
How can I turn on logging in runtest.php? I looked at AMI doc (https://github.com/WPO-Foundation/webpagetest/blob/master/docs/EC2/Server%20AMI.md), private instance doc (https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/README.md), and sample config (https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample) and they have noting about logging in runtest.php.

Once turned on, where those logs appear?

**Comment by AndreyNikiforov** [comment]
I ran `du` on AMI master instance and `/dev/xvda1` mounted as `/` was 100% full. Then I ran `sudo du -x / | sort -n | tail -40` to get most space consuming folders and it was `/var/www/webpagetest/www/results`. I removed all results and `du` shows 8% for `/dev/xvda1` now. Still getting the same error when trying to submit tests.

**Comment by AndreyNikiforov** [comment]
I reinstalled master (AMI) and everything works now. Although it is a workaround, I am closing the issue.
