### ISSUE TITLE
GetMedianRun potentially incorrect with ascending metric sort

### ISSUE THREAD

**Issue by jchuong** [WPO-Foundation/webpagetest#1135]
I was wondering if the calculation of GetMedianRun could be slightly incorrect.

Given a test with docTime of `[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]`, we expect and do get the 5th run with docTime of 50 as the median run.

However, if we consider that docTime (and all performance metrics) are actually better if they are lower, we should actually have the sorted array of `[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]`, which means the median run is the run with docTime of 60.

Abstracting this further if we added other nth 'percentile' run selections (best, worst, 90th, etc), the current ascending sort with 100th percentile is the last item (which has the worst metric), the 0th percentile (will actually have the best metric).

I was wondering if the ascending sort is intentional (I am implementing my own selection of best run/worst run but wasn't able to match the median with WPT's choice without also using the ascending sort, but logically it seemed like descending sort makes sense for performance metrics).

**Comment by pmeenan** [comment]
With 10 runs the median is undefined which is why I generally recommend doing an odd number of runs.

**Comment by jchuong** [comment]
Well, thinking about it a bit more, maybe we actually want to use 90th percentile as 90% of users will see at worst this run (removing some outlier with users timing out or some other network issues).  

Thanks.
