### ISSUE TITLE
Nginx error log filled with "ob_end_clean()" on postprocess.php

### ISSUE THREAD

**Issue by rposbo** [WPO-Foundation/webpagetest#1139]
I'm getting hundreds of these errors on my AWS c4.large WPT server ami:

```
FastCGI sent in stderr: "PHP message: PHP Notice:  ob_end_clean(): failed to delete buffer. No buffer to delete in /var/www/webpagetest/www/work/postprocess.php on line 14" while reading response header from upstream, client:[redacted], server: , request: "GET /work/postprocess.php?test=[various] HTTP/1.1", upstream:  "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[redacted]"
```

It seems to happen after I've queued ~150 tests (using Marcel's WPT API within a NodeJs AWS Lambda) over a 5 min period, with a pingback (to another AWS Lambda) so I'm not polling/waiting for as result. 

I use a combination of EC2 autoscaling and my own EC2 instances (from the same AMIs) for speedier responses (and since I have a couple in China too).

I'm no PHP guru, but is it possible to check if there is a buffer before deleting, or is this error indicative of something else I've done wrong?

My issue is not just that the logs are full of this message, but that once this starts to happen I can no longer enqueue tests and I receive the following error from the WPT API:
```
Failed to enqueue WPTAPIError: Internal Server Error

{ Error
at Object.<anonymous> (/var/task/enqueueTests/node_modules/webpagetest/lib/helper.js:213:25)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/enqueueTests/node_modules/webpagetest/lib/webpagetest.js:14:15)
at Module._compile (module.js:570:32)
name: 'WPTAPIError',
code: 500,
message: 'Internal Server Error' }
```

Probably related: I have previously had to delete thousands of empty "getwork.php" files in `/var/www/`, as my WPT server was hanging when attempting to queue any tests. There are thousands more in there now, so presumably they are meant to be there and I've broken it by deleting them?

**Comment by pmeenan** [comment]
Have you tried the patch to see if it resolves the underlying problem?  Something seems fundamentally broken with the server configuration for the getwork.php files to be written into /var/www.  It's not something I have ever seen happen.

Some questions on the WPT server:
- Is it using the server AMI or did you roll your own?
- Nginx or Apache?
- php-fpm or how is php deployed?
- What OS?

**Comment by pmeenan** [comment]
Also, does sites-available/* have multiple websites and roots available?  You may need to specify the hostname to use in settings.ini for the loopback requests (which is what postprocess.php is).

**Comment by rposbo** [comment]
## This looks like it was two separate issues, at lease one of which was my poor configuration.

I've applied the patch and have kicked off a few hundred tests, tail-ing `/var/log/nginx/error.log`, and no `ob_end_clean()` issue appeared.

However, the same error was still being returned from WPT API - I believe it was actually due to having a custom agent in the `location.ini` that was being treated as an EC2 agent (an agent in China AWS), since there were errors around being unable to get a lock for EC2 instances in the WPT logs from ec2.inc.php https://github.com/WPO-Foundation/webpagetest/blob/1b7369b8107174d83b173899a49acd815eca6613/www/ec2/ec2.inc.php#L44  

This appeared to be causing errors to be returned from WPT (there were matching HTTP 500s in `/var/log/nginx/access.log`). 

I've since rewritten my `locations.ini` from scratch as it was a mess (duplicating most of `ec2_locations.ini`), and that WPT API/EC2 lock/HTTP 500 error is no longer occurring.

## Regarding the setup info:

I'm using the server AMI (webpagetest-server-2014-11-25) from the AWS Community AMIs in eu-west-1; nginx, Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-36-generic x86_64).

## Regarding `getwork.php`:

Looks like getwork.php is a result of the EC2 implementation, according to this comment & function: https://github.com/WPO-Foundation/webpagetest/blob/70fb0fc3b0ad97921a4eda7f47de26b8107e8372/www/cron/5min.php#L51
