### ISSUE TITLE
Radio button labels not clickable

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#1142]
Labels next to first view and repeat view radio buttons are not clickable (e.g. to switch between those two options).

![2018-05-23_14-57-14](https://user-images.githubusercontent.com/38076/40445262-9e2feac4-5e99-11e8-813a-34ccee7c8002.png)

Would be a simple change of HTML, but labels are styled to be section labels, e.g. to work for checkboxes mostly which is not surprising as these two are the only radio buttons here.

https://github.com/WPO-Foundation/webpagetest/blob/1cd8ffb900819c6d86ba2d3a279cf98a27ba470b/www/index.php#L350-L351

**Comment by sergeychernyshev** [comment]
It looks like it applies to radios for selecting filmstrip options
![2018-05-23_18-04-53](https://user-images.githubusercontent.com/38076/40453625-d1d4c52e-5eb3-11e8-9982-88d045a14124.png)

**Comment by tkadlec** [comment]
Added to the home page, as well as the filmstrip. Some serious a11y gains here. 💪 

**Filmstrip before (tested using Wave)**
![Screenshot from Wave showing 17 accessibility errors, 53 alerts and 13 features](https://user-images.githubusercontent.com/66536/112158520-3e45c280-8bb6-11eb-9260-e2a74decb017.png)

**Filmstrip after (tested using Wave)**
![Screenshot from Wave showing 3 accessibility errors, 45 alerts and 31 features](https://user-images.githubusercontent.com/66536/112158714-6d5c3400-8bb6-11eb-9a88-bdfe0081de44.png)
