### ISSUE TITLE
Rendering begins before CSS downloading

### ISSUE THREAD

**Issue by yannfill** [WPO-Foundation/webpagetest#1151]
In a test on our WPT 17.12 private instance, we saw in the filmstrip view that the rendering begins before CSS files are downloaded.

The bug occurs with chrome 67 and Chromium 66 on Linux.

![capture du 2018-06-15 17-09-32](https://user-images.githubusercontent.com/11028416/41475983-76581d80-70c0-11e8-8567-ee2493bfeb40.png)

The bug doesn't seem to happen when tested on webpagetest.org: https://webpagetest.org/video/compare.php?tests=180615_G8_6e204555279c960fedd93ef73b2d855e-r:1-c:0

Do you have any idea why we have this behaviour on our instance?

Thanks for your help.

**Comment by pmeenan** [comment]
Probably changes in the video capture logic since 17.12 was released.  I'm pretty well overdue for a new release at this point but if you update the wptagent to the latest release branch from github you should have the same as is running on the public agents.

**Comment by yannfill** [comment]
I have updated agents to version 180616.180619 (WPT UI still in 17.12) and the bug is still present.

**Comment by pmeenan** [comment]
Is the css in the waterfall actually used for the document or is it lazy loaded?  Testing it on the public instance right now it looks like it was either moved inline with the document or some time much later: https://webpagetest.org/video/compare.php?tests=180621_70_168bf3a4bbccfd43b0606bf3521f1440-r%3A1-c%3A0&thumbSize=200&ival=100&end=full

**Comment by yannfill** [comment]
No lazy loading. Here is a test where the bug still happens on our instance: http://wpt000.francecentral.cloudapp.azure.com/results.php?test=180622_A08VMuiWPT001iWS_62
The same page on webpagetest.org: https://www.webpagetest.org/result/180622_XS_fcea3791609d574107a4e9bdb8d8f212/

**Comment by yannfill** [comment]
No lazy loading. Here is a test where the bug still happens on our instance (sorry, github don't let me upload the screenshot): https://imgur.com/a/U10bkhu
The same page on webpagetest.org: https://www.webpagetest.org/result/180622_XS_fcea3791609d574107a4e9bdb8d8f212/

**Comment by yannfill** [comment]
Seems like the bug also occurs on webpagetest.org: https://www.webpagetest.org/forums/showthread.php?tid=15412

**Comment by pmeenan** [comment]
Those are later steps in a multi-step script which is quite a different beast (where a start render can just be a visual change on the previous page).

**Comment by yannfill** [comment]
Can you check this test result, please: http://wpt000.francecentral.cloudapp.azure.com/results.php?test=180629_a08vmuiwpt001iW9_22
The bug occurs on runs 1 and 2, but not on run 3. UI and agents are up to date with master branches.

**Comment by yannfill** [comment]
We have found the issue: The FPS rate was too low to accurately analyze the rendering. Using the default 10 FPS solved this.
