### ISSUE TITLE
Scripts do not get executed with Rest API.

### ISSUE THREAD

**Issue by abhagupta** [WPO-Foundation/webpagetest#1152]
I have posted this issue on WPT forums as well.. just needed more visibility hence posting it here as well.

Hi,

I am not able to run scripted test using Rest API on my private instance. Wptdriver Version latest (17) 

Scenario 1: When I run a script manually on the server url, the script works perfectly fine. I see the test.job created as follows (notice the script tag):

Test ID=180621_M7_MD
url=script://180621_M7_MD.pts
fvonly=1
timeline=1
timelineStackDepth=0
Capture Video=1
runs=1
bwIn=5000
bwOut=1000
latency=28
plr=0
browser=Chrome
lighthouseTrace=1
orientation=default
IPAddr=161.69.122.10

[Script]
navigate https://www.walmart.com/
execAndWait document.querySelector('[data-automation-id="header-search-input"]').value='TV'; document.querySelector('[data-automation-id="GlobalHeaderSearchbar-submit"]').click();
execAndWait document.querySelector('.search-result-productimage div a').click();
execAndWait document.querySelector('.prod-product-cta-add-to-cart button').click()
execAndWait document.querySelector('.cart-pos-view-cart button').click()
logData 1

Scenario 2 : When I give the same command using curl command with url encoded :

curl -X POST http://www.webpagetest.org/runtest.php -F 'k=<mykey>' -F 'script=navigate%09https%3A%2F%2Fwww.walmart.com%2F%0D%0AexecAndWait%20document.​querySelector%28%27%5Bdata-automation-id%3D%22header-search-input%22%5D%27%29.value%3D%27TV%27%3B%20document.querySelector%28%27%5Bdata-automation-id%3D%22GlobalHeaderSearchbar-submit%22%5D%27%29.click%28%29%3B%0D%0AexecAndWait%20document.querySelector%28%2​7.search-result-productimage%20div%20a%27%29.click%28%29%3B%0D%0AexecAndWait%09document.querySel​ector%28%27.prod-product-cta-add-to-cart%20button%27%29.click%28%29%0D%0AexecAndWait%20document.querySelector%28%27.​cart-pos-view-cart%20button%27%29.click%28%29%0D%0AlogData%091' -F 'f=json' -F 'location=CentralUS4:Chrome' -F 'url=https://www.walmart.com'

I get:

{"statusCode":400,"statusText":"Invalid Script (make sure there is at least one navigate command and that the commands are tab-delimited). Please contact us if you need help with your test script."}

Scenario 3 when I run passing a script as a file to curl command

curl -X GET http://<myserver>/runtest.php -F 'script=@cart_script.txt' -F 'f=json' -F 'location=CentralUS4:Chrome'

I get:
Invalid URL, please try submitting your test request again.

Scenario 4 when I pass the url in above command, 

curl -X POST http://<myserver>/runtest.php -F 'script=@script.txt' -F 'f=json' -F 'location=CentralUS4:Chrome' -F 'url=https://www.walmart.com'

I get a test running but when i see the test.job in server, I do not see the Script part. The test runs with only first page open.

Here is contents of the test.job file.

Test ID=180621_VX_ME
url=https://www.walmart.com
runs=1
bwIn=5000
bwOut=1000
latency=28
plr=0
browser=Chrome
orientation=default
IPAddr=161.69.122.11

I have also noticed that some small scripts run on WebPagetest.org successfully but they do not run on my private instance with exact same script and parameters. What are some of the troubleshooting tips in these cases?

Thanks

**Comment by pmeenan** [comment]
This is a problem with how you are using curl.  If you url-encode the test options, just add them as query parameters to the URL and make a get request:

```
curl "http://www.webpagetest.org/runtest.php?k=A.88c97beca38c84a7fee4d328c75c63aa&script=navigate%09https%3A%2F%2Fwww.walmart.com%2F%0D%0AexecAndWait%20document.​querySelector%28%27%5Bdata-automation-id%3D%22header-search-input%22%5D%27%29.value%3D%27TV%27%3B%20document.querySelector%28%27%5Bdata-automation-id%3D%22GlobalHeaderSearchbar-submit%22%5D%27%29.click%28%29%3B%0D%0AexecAndWait%20document.querySelector%28%2​7.search-result-productimage%20div%20a%27%29.click%28%29%3B%0D%0AexecAndWait%09document.querySel​ector%28%27.prod-product-cta-add-to-cart%20button%27%29.click%28%29%0D%0AexecAndWait%20document.querySelector%28%27.​cart-pos-view-cart%20button%27%29.click%28%29%0D%0AlogData%091&f=json&location=CentralUS4:Chrome&url=https://www.walmart.com"
```

If you really want to post the fields separately you need to include the script directly (not as an attached file) and the special characters need to be passed however it makes sense for the shell you are using.  i.e. for bash it can be:

```
-F $'script=navigate\thttp://www.walmart.nom\n....'
```

Now that you have published the server url and your private API keys to a public issue you also need to go back and secure the server (make sure it requires keys) and delete the key that you posted, otherwise it will be open for abuse.

**Comment by abhagupta** [comment]
Thanks Patrick.   

Your suggestion does work.. I can see the script in test.job now.. Its not running completely, but I think it just needs to be improvised a bit. I have deleted my post and masked my keys in this github issue, but we are looking into securing the server.
thanks again
