### ISSUE TITLE
Custom Headers in REST API?

### ISSUE THREAD

**Issue by abhagupta** [WPO-Foundation/webpagetest#1155]
Is it possible to send Custom Headers  in the test using REST API?  I see we can add Custom Headers in Webpagetest.org in Advanced tab but I couldn't find how to do this using API.

**Comment by pmeenan** [comment]
Yes.  The UI uses the API itself so anything the UI can do can also be done through the API.  When in doubt, the easiest thing to do is inspect the UI form and see the name of the field for the form element (as I can sometimes be bad about documenting).

In this case it is "customHeaders".  Just make sure to urlencode the data before sending it if you pass it on the URL.

It can also be set using a script with the addHeader command.

**Comment by pmeenan** [comment]
Closing as fixed.  Re-open if you are still having issues.
