### ISSUE TITLE
Lighthouse throttling issues?

### ISSUE THREAD

**Issue by alexgibson** [WPO-Foundation/webpagetest#1156]
Around 30th June we've been seeing a distinct upward jump in our Lighthouse performance scores, across many pages on different sites. I don't think this is related to any changes on our side, and there may have been a change in how WPT is running Lighthouse tests.

I can observe this via jobs run using the [WebPageTest API](https://github.com/marcelduran/webpagetest-api):

https://www.webpagetest.org/results.php?test=180705_M1_8656ec83ed6211b8081dfc2eb33885fc

And also directly via webpagetest.org:

https://www.webpagetest.org/result/180705_C3_d157d894bf34309d9ec1f50ad29e4144/

Both of the above tests are run using `California, USA - EC2 - Chrome - 3G`, yet the Lighthouse performance scores are way higher than I would expect. In fact, they match in scores for this test, which is using `California, USA - EC2 - Chrome - Native`:

https://www.webpagetest.org/results.php?test=180705_ND_b191e69777f5db921fa47307c2d500b2

I may have missed some change in config or documentation maybe, but it seems that WPT is not passing any kind of throttling information to Lighthouse, which is always running at `Native` speed?

This was our typical score before June 30th for `California, USA - EC2 - Chrome - 3G`: https://www.webpagetest.org/lighthouse.php?test=180628_58_3581097979cbe2f96cd66da6110b6886

Any help in understanding this would be appreciated

**Comment by zeman** [comment]
I believe the WPT network and CPU throttling is done at the OS level so there's no need for any of Lighthouse's inbuilt throttling. It's running within a throttled environment.

I suspect the change is score is due to the different versions of Lighhouse. The old test was on 2.9.4 vs 3.0.1. @pmeenan might be able to provide insight into how the scoring changed between versions.

**Comment by alexgibson** [comment]
> I suspect the change is score is due to the different versions of Lighhouse. The old test was on 2.9.4 vs 3.0.1.

I first suspected this also, but I see identical Lighthouse scores when running between `3G` and `Native` network speeds using WPT (as linked above), which is what rose my suspicion that maybe something wasn't right. Would be good to understand this better if in fact the change is as-intended.

**Comment by zeman** [comment]
Here's the background on how the scoring has changed in v3.

https://developers.google.com/web/updates/2018/05/lighthouse3#scoring

**Comment by alexgibson** [comment]
Interesting, thanks for this info 👍

**Comment by pmeenan** [comment]
There is the 3.0 change but I also changed the Lighthouse integration with WPT to always use the same connection profile (3G Fast).  

The lighthouse scores are [calibrated against a 3G connection](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) but the 3G connection it used for calibration of the scores was the WPT "3G Fast".  To make sure the scores are always accurate on WPT I changed it so the test connection speed is ignored for the lighthouse portion of the test and it always uses the correct profile.

**Comment by pmeenan** [comment]
Change is [here](https://github.com/WPO-Foundation/wptagent/commit/0c1b9fe697b295d750ba5459e6709353d265d3f7) by the way.  I'm open to adding a flag to force the connection profile but it will make the scores less useful.

**Comment by alexgibson** [comment]
> The lighthouse scores are calibrated against a 3G connection but the 3G connection it used for calibration of the scores was the WPT "3G Fast". To make sure the scores are always accurate on WPT I changed it so the test connection speed is ignored for the lighthouse portion of the test and it always uses the correct profile.

Ok, so this means that if I want my both my WPT results and my Lighthouse results to use the same benchmark network simulation, I should be using "3G Fast" for my WPT runs? (fine if so, just wanted to understand the change).

**Comment by pmeenan** [comment]
Correct

________________________________

**Comment by alexgibson** [comment]
Ok, thanks all for helping me better understand the change 🌮
