### ISSUE TITLE
Yesterdays commit broke the JSON results

### ISSUE THREAD

**Issue by rdejuana** [WPO-Foundation/webpagetest#1157]
I'm not sure what it is, but something has changed and all my test are breaking.  I'm currently looking into it to get more info

**Comment by pmeenan** [comment]
What do you mean by "broke"?  Is it not parsing as valid JSON, is it not returning JSON at all?  Is it something you can reproduce on the public instance?

**Comment by pmeenan** [comment]
i.e. I just ran [this test](https://www.webpagetest.org/result/180707_5E_9f169b6fff5b4375408f7397743a2c06/) and the [JSON result](https://www.webpagetest.org/jsonResult.php?test=180707_5E_9f169b6fff5b4375408f7397743a2c06) looks fine as best as I can tell.

**Comment by rdejuana** [comment]
looks like gzip_save changed some how.  Does it return null now?

**Comment by rdejuana** [comment]
I have a fix for my code that I'm testing.  My service is written in Python and I'm a Ruby guy, so i will be the first to say that my code might be bad

**Comment by rdejuana** [comment]
my fix seems to have fixed my issues.  Its just a None check on gzip_save
