### ISSUE TITLE
does LastInteractive value represent FirstInteractive in JSON data 

### ISSUE THREAD

**Issue by abhagupta** [WPO-Foundation/webpagetest#1162]
When I fetch the raw  results for a test, the value of `FirstInteractive` on UI matches with `LastInteractive`  and there is no `FirstInteactive` metric in the results.   Are these values same?

**Comment by pmeenan** [comment]
I assume the UI shows ```> xxx```.  If First Interactive isn't available because there wasn't enough idle time at the end of the test to detect it (requires 5 seconds) it falls back to Last Interactive with a >.  That is the earliest it would have been if the main thread had continued to be idle for 5 more seconds.

**Comment by abhagupta** [comment]
Yes it is `> xxx`.  thanks.. makes sense

**Comment by abhagupta** [comment]
so what metric would be safe to capture if we need to get a valid TTI time?   I get something like `interactivePeriods: [ [ 0, 2773 ], [ 11558, 15521 ], [ 15852, 17903 ] ],`  in test results   . For serving the purpose of capturing TTI, which metric should I actually capture when tests are running in automated fashion (when I do not have control  of determining whether I actually got FirstInteractive)?

**Comment by pmeenan** [comment]
If "TimeToInteractive" isn't available (which is the Chrome team's TTI) then falling back to Last Interactive is reasonable.  You can also increase the activity time to 10 seconds or something like that to get the test to run longer and increase the liklihood of capturing it.

**Comment by abhagupta** [comment]
Yep, does not look like I get `TimeToInteractive`, but I do get `TTIMeasurementEnd`  which has slightly different value.

So here are TTI related metrics : 

```
TTIMeasurementEnd: 17903,
LastInteractive: 15852
```
So if I am understanding the concept of TTI correctly, these 2 metrics are last set of `interactivePeriods` .. and the reason we have difference in these values is there could be some in-flight request between 2 metrics. Is that correct understanding?

Also, is there a way to increase the activity time setting programmatically (using REST api)?

**Comment by pmeenan** [comment]
The official definition is [here](https://github.com/WICG/time-to-interactive).  It will always be the start of an "Interactive Period" that is at least 5 seconds long.  Not necessarily the last one but it does require a 5-second period.

Activity time through the API can be set by passing time=10 (or some other timeout in seconds).
