### ISSUE TITLE
Running a manual test not working

### ISSUE THREAD

**Issue by Yamikamisama** [WPO-Foundation/webpagetest#1165]
I am trying to run a manual test as well as a test using the API, both are returning failed tests, but not for any reason I know of

<img width="1552" alt="screen shot 2018-07-13 at 2 20 49 pm" src="https://user-images.githubusercontent.com/8148176/42707458-463c3746-86a8-11e8-91ca-302a6ca00951.png">
<img width="1552" alt="screen shot 2018-07-13 at 2 25 15 pm" src="https://user-images.githubusercontent.com/8148176/42707579-a9bd638a-86a8-11e8-8646-61e746a1e376.png">
<img width="1552" alt="screen shot 2018-07-13 at 2 25 22 pm" src="https://user-images.githubusercontent.com/8148176/42707581-a9d3a424-86a8-11e8-8ab5-734e735dbee7.png">

????

**Comment by pmeenan** [comment]
Should be fixed now.  An update earlier today to allow for location services for sites was crashing Chrome on the Moto G4's.  I've rolled back the change until I can figure out why.
