### ISSUE TITLE
Improve setActivityTimeout to be based on Main Thread Activity

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#1169]
At fasterize, we are trying to get reliable Speed Index for a bunch of websites. 

In #880, we were suggested to experiment around `setActivityTimeout` to avoid issues related to slideshow or animation.

For the moment, we use the `setActivityTimeout` set to a value of 250ms. It works for most websites but for other websites, the capture is stopped too quickly. This kind of issues are hard to detect.

In this [example](https://wpt.fasterize.com/result/180718_SD_R/2/details/), the capture happens too quickly because the browser is busy with JS : 

<img src="https://wpt.fasterize.com/waterfall.php?test=180718_SD_R&run=2&cached=&step=1" />

I suggest to improve the `setActivityTimeout` to be based on `Main Thread Activity`.

**Comment by pmeenan** [comment]
Main thread activity is not available at runtime and is only available during post-processing of the trace.  Might be able to do something based on CPU activity of the system but that will be a lot flakier.

**Comment by abarre** [comment]
I did some search on this point.
Lighthouse will detect the end of the test based on the network activity, the cpu activity and the window onload event. (ref : https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L871)

All of the following conditions have been met:
 - page has no security issues
 - pauseAfterLoadMs milliseconds have passed since the load event.
 - networkQuietThresholdMs milliseconds have passed since the last network request that exceeded
         2 inflight requests (network-2-quiet has been reached).
 - cpuQuietThresholdMs have passed since the last long task after network-2-quiet.
 - maxWaitForLoadedMs milliseconds have passed.
