### ISSUE TITLE
Suggestion: PHP-FPM to use TCP/IP instead of sockets on EC2 server instance

### ISSUE THREAD

**Issue by rposbo** [WPO-Foundation/webpagetest#1174]
When I kick off a couple of hundred tests via @marcelduran 's awesome WPTAPI (with pingbacks set, so I'm not waiting around), my EC2 WPT server instance tends to throw HTTP 502s and log the error:
```
connect() to unix:/var/run/php5-fpm.sock failed (11: Resource temporarily unavailable)
```

I'm using a m4.large instance and the api calls to enqueue a test run have a randomised `wait` between 0-1000ms.

By changing my server to use PHP-FPM over TCP instead of sockets, this seems to be more scalable. I appreciate I may be losing some responsiveness though.

## Suggestion:
Either make it easy to swap the setup to use TCP or add a how-to within the wpt-docs pages to flesh out what is essentially:

## /etc/nginx/sites-available/default
```
# comment out/delete this line:
#fastcgi_pass    unix:/var/run/php5-fpm.sock;

# add this line instead
fastcgi_pass   127.0.0.1:9000;
```

## /etc/php5/fpm/pool.d/www.conf
```
# comment out/delete this line:
#listen = /var/run/php5-fpm.sock

# Add these lines instead:
listen = 127.0.0.1:9000
listen.allowed_clients = 127.0.0.1
```

## Restart php-fpm and nginx
```
sudo service php5-fpm restart
sudo service nginx restart
```

Is there a preference/any opinion on this?

**Comment by pmeenan** [comment]
:-/  That's a little strange because I assume the API calls are serialized and shouldn't have an issue with high concurrency.  Glad to hear switching to tcp/ip resolved it for you but unix sockets should perform at least as well if not better (I have some systems that submit a few hundred thousand tests concurrently across 30 threads in a few minutes that don't run into unix socket issues).

Usually the biggest win for scaling comes from switching to beanstalkd for the work queues.

**Comment by rposbo** [comment]
Yeah, I would have guessed that you run tests of a significantly higher volume than mine! Perhaps it's specifically an EC2 instance issue; I'm sure if I increased the instance size it would manage more.

The API calls are via a mapped array of (nodejs) promises, so aren't serialized; so I believe they're parallel (with a random wait).

**Comment by pmeenan** [comment]
Ahh, gotcha.  If possible you might be better off to see if you can do them in batches with no more than ~20 pending promises (not sure if node has an easy work queue to manage that kind of thing).  You are probably bumping into limits with the number of concurrent fpm clients and the depth of the nginx request queue.
