### ISSUE TITLE
Lighthouse does not work in Desktop agent

### ISSUE THREAD

**Issue by abhagupta** [WPO-Foundation/webpagetest#1175]
Is lighthouse feature not available in desktop agents?  Chrome version 67.

**Comment by pmeenan** [comment]
[Works fine](https://www.webpagetest.org/result/180724_RE_c9f2e8f0466f55d69720f62d2a6d332e/).

If you're seeing issues with it in a private instance I'll need info about the agent and debug log.  i.e. it only works with wptagent (not wptdriver) but should work fine for desktop.

That said, Lighthouse is very mobile-focused for the audits so even with the desktop agent you will probably want to enable mobile emulation.  It WILL run the audits against a desktop site (like I linked above), it just might not produce useful results.

**Comment by abhagupta** [comment]
Thanks Patrick.   I got it working on the wptagent installed agent..   and also made a note of your comment around its applicability around mobile.
