### ISSUE TITLE
Film Strip shows parts before logData 1

### ISSUE THREAD

**Issue by abhagupta** [WPO-Foundation/webpagetest#1177]
I ran the below test
https://www.webpagetest.org/result/180726_Q4_5a8ae57b43d340df06813330f369432c/

and got 2 things:
- The film strip shows some parts of the page before `logData 1` was put in.  is it normal?  How should we interpret the metrics in this case?  Are they inclusive of any network requests that might be in flight before `logData 1` was executed?
- The first byte metric came out to be 0. Can you think of any reason why?

**Comment by pmeenan** [comment]
What do you mean "shows some parts of the page before logData 1 was put in"?  The video starts capturing with the page in the state it is in and then executes the command so (for example), clicking a button will start the video with the page just before the button is clicked and record whatever latency is included in the action of clicking the button.

**Comment by abhagupta** [comment]
Makes sense.. thanks..   Can you let me know what could be reason of  first byte = 0

**Comment by pmeenan** [comment]
Looks like maybe an unload beacon or other analytics fired right at the time of the action and that triggered the early first byte.  If you want to be sure it only catches the activity for the actual action you are doing you will need to block or otherwise disable the other activity.

**Comment by abhagupta** [comment]
Thanks Patrick.
