### ISSUE TITLE
Is the domain blocking step being executed prematurely in scripted tests?

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1205]
@souders technique for testing service workers (https://speedcurve.com/blog/pwa-performance/) no longer seems to work.

adactio.com has a service worker that serves content offline (confirmed with Chrome DevTools in offline mode)

But a test using the script below fails with **First View: Test Error: net::ERR_CONNECTION_REFUSED** see https://www.webpagetest.org/result/181010_E0_f3d2b819a71f49216723c789ed84e6ca/ 

```
logData 0
navigate https://adactio.com/
execAndWait document.body.innerHTML=""
logData 1
blockDomainsExcept unused.zz
navigate https://adactio.com/
```

Script succeeds when the blockDomain step is removed - https://www.webpagetest.org/result/181010_DE_82fe75e9d0097b02eabd6876ba14c4b4/

Reducing the script down to a minimum (through trial and error)

```
navigate	https://adactio.com/
blockDomainsExcept	unused.zz
```

Also results in an First View: Test Error: net::ERR_CONNECTION_REFUSED error -https://www.webpagetest.org/result/181010_R8_8a1ddbd2e0ec770f909a401d77e2e74c/

This seems to suggest the blocking may be applied before the navigate step rather than after it

**Comment by machal** [comment]
I'm getting this error ("**First View: Test Error: net::ERR_CONNECTION_REFUSED**") when testing site without Service Worker too:
https://www.webpagetest.org/result/191114_XR_6ac20fe4d70a9a4dae83b9b41b8dcbb1/

I have tried to test the same site with `blockDomainsExcept`…
https://www.webpagetest.org/result/191114_AR_27bcd735ce2f2ef25ce5263f809f0485/ (getting First View: Test Error: net::ERR_CONNECTION_REFUSED)

…and without it: https://www.webpagetest.org/result/191114_18_8045469a5510064a06536213a1abde3d/

So I think there is issue with `blockDomainsExcept`.
