### ISSUE TITLE
Consider growing the base width of the WPT HTML output from 980px to ~1200px or more

### ISSUE THREAD

**Issue by jakub-g** [WPO-Foundation/webpagetest#1207]
As mentioned in #1204, WPT HTML output is wrapped with a div `.page {width: 980px;}` which is probably a bit legacy those days.

According to http://gs.statcounter.com/screen-resolution-stats/desktop/worldwide the 1024x768 resolution is now used by less than 4% of users _(not considering mobile screens here because I don't think many people use WPT from their smartphones)._

Perhaps this base width should be changed to something around 1200px.

Changing the base width would involve going through many pages and checking if their layout doesn't crash, but by doing this, we could increase the widths of graphs and several tables that are full of data and sometimes overflow (user timings) and/or have some columns data (most notably URLs) shortened server-side using ellipses.

Let me know if this a welcome change, and if so, I might try to work on it.

**Comment by pmeenan** [comment]
There is a [page-wide class](https://github.com/WPO-Foundation/webpagetest/blob/master/www/pagestyle.css#L20) that can be used on any given page that changes it to a min-width of 980 (sample [here](https://github.com/WPO-Foundation/webpagetest/blob/master/www/video/compare.php#L274) in the filmstrip UI).

I haven't moved the main pages over other than the filmstrip view and maybe a couple of others but if you'd like to incrementally tackle pages I'd welcome PR's.
