### ISSUE TITLE
Two servers in conflict in the same zone on EC2

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#1209]
We discovered after a few hours of investigation that two servers configured for using default agents AMI on default `ec2_locations.ini` for the zone `eu-west-3-linux` were in conflict. In fact, we discovered that agents launched for one server were killed by another server.
I suspect that server retrieves all agents on a zone regardless of the attached server rather than retrieving only agents launched by itself. 

The code related to the issue seems to be this method : https://github.com/WPO-Foundation/webpagetest/blob/master/www/ec2/ec2.inc.php#L445

**Comment by pmeenan** [comment]
Yeah, the code is pretty immature and really only expects one server to be controlling all of the instances.  It would be worth adding a server ID of some kind to settings.ini that can be used to tag the instances and only kill tagged instances that match if it is set to support multi-server auto-scaling configs (maybe use the server ID that already exists for test ID's if they are archiving to the same place).
