### ISSUE TITLE
Anyway to display archived test results w/o a WebPageTest server instance?

### ISSUE THREAD

**Issue by iDVB** [WPO-Foundation/webpagetest#1210]
We're using the containerized version of the agent and server to 
1) spin up
2) test
3) archive to S3 
4) tear down
on each test

in the end we have a ton of tests in the s3 bucket and would LOVE to have an HTML way to view them WITHOUT having to fire up a WebPageTest server instance.

Short of recreating our own UI for all the archive data.... is there some way we could display these tests?

**Comment by pmeenan** [comment]
The stored data is just the raw test data - even the waterfalls are generated on the fly from the underlying data.  You'd either need a separate server just for viewing (configured with the same archive bucket) or you'd need to create something that scrapes the result HTML and images from the live servers before they are killed.

**Comment by iDVB** [comment]
Thanks @pmeenan. Was actually hoping more for a export/archive to html+json option. 
or something like this... https://github.com/springernature/webpagetest-mapper

yet to try it though.
