### ISSUE TITLE
script doesn't work in both hosted and private instance

### ISSUE THREAD

**Issue by chrischjh** [WPO-Foundation/webpagetest#1213]
I'm new to WPT, and have mangaged to set up a private instance, however got a hard time to make test scripts work even for below simple ones. However strangely, "setCookie" actually works to me in my test. Appreciate any help, thanks a lot

navigate	google.com
click	name=btnI

**Comment by chrischjh** [comment]
result example here: https://www.webpagetest.org/result/181031_W0_0fc3b1d70445dbefbf608d780a03e83c/

**Comment by pmeenan** [comment]
You need an "andWait" version of a command to start a measurement.  Try replacing "click" with "clickAndWait".

The non-wait versions exist so you can do a bunch of form filling, etc to prepare things before doing the actual action that causes the new page to load.

**Comment by chrischjh** [comment]
Thanks for your reply, it works
