### ISSUE TITLE
Content Breakdown explanation - Uncompressed size is lower than Bytes.

### ISSUE THREAD

**Issue by abhagupta** [WPO-Foundation/webpagetest#1215]
We are trying to investigate how uncompressed size would be lesser than the Bytes, sometimes even 0 in Content Breakdown page. For example, https://www.webpagetest.org/result/181101_WY_c68066534a54d05ad63b5c0bbf81c635/1/breakdown

My thought would be that Uncompressed data would always be higher  than or equal to Bytes data, unless Uncompress only measures what was explicitly compressed by headers.

Can you shed some light on this? Is there any documentation which gives standard definition of these 2 values.

**Comment by fdoumet** [comment]
Any insight on how to address this?
