### ISSUE TITLE
Huge drop on TTI

### ISSUE THREAD

**Issue by soulcorrosion** [WPO-Foundation/webpagetest#1217]
Hello, I noticed a huge drop on TTI starting 3rd of November. So, on the 2nd of November it was around 13 seconds and then dropped to 2.5 seconds. TTI inside chrome seems to have the same values values but WPT results are very different.

Here are a few examples via SpeedCurve:
Before the drop: https://wpt1.speedcurve.com/result/181102_6X_d0832440800cf2d700cc69e71d723403/
After the drop: https://wpt1.speedcurve.com/result/181103_EN_d8ee7ef57c06e8e7577af616627ad1ed/

Thank you.

**Comment by pmeenan** [comment]
Chrome 70 changed the process model a bit and now there are multiple processes all claiming to host the "main frame" for the document, even though one is clearly labeled "Subframe".  WPT became inconsistent about picking the right thread for the main thread which caused the drop.

I just rolled out a fix that ignores the "main frame" processes that are labeled as "Subframe" so you should see the numbers jump back up. It's most clearly visible when looking at the "main thread activity" graph under the waterfall.  When the wrong thread is picked there are very few events.  With the fix in place it looks like it did before: https://www.webpagetest.org/result/181105_QD_1b3efc7a3bcdacc87f9697ae589aa594/
