### ISSUE TITLE
Agent gets tests with http://docompare.php  and http://runtest.php 

### ISSUE THREAD

**Issue by abhagupta** [WPO-Foundation/webpagetest#1220]
We have a weird issue going on in our agents. We run WPT tests every 2 hours in our azure VMs, but there are few times when I see url http://docompare.php and http://runtest.php queued up. These are not working URLs so all other tests queue up behind them.  We thought that our wpt server is hacked, but I see that these files are a part of webpagetest code itself.  Wanted to confirm if this is a bug in the agent or server code before we start thinking about security and key integration.

We updated the agent code on 11/11 so we have latest code.   We have not update `webpagetest` (server) code.. 

We have around 7 agents running and only one of them gets this issue. Any guidelines to troubleshoot might be helpful

**Comment by pmeenan** [comment]
The server can sometimes call itself to re-run a test or to create a comparison video but those calls shouldn't be queued up as tests (and I've never seen it).  There is a setting in settings.ini where you can specify the hostname to use for the loopback requests in case it needs to use a different path from the external interface (like explicitly the private interface or 127.0.0.1).

What do you mean by the other tests getting queued up? Since those are invalid, if they were queued up as a test I'd expect it to fail quickly and move on to the next test.

**Comment by abhagupta** [comment]
What I meant was the test with docompare.php gets stuck on the browser, agent is not able to close it and all the other genuine tests which gets triggered every 2 hour, are sitting in queue, eventually bloating the queue . This is happening mostly at night time for us.

**Comment by abhagupta** [comment]
Hello Pat, back on this again.  I did some investigation, found that these tests are created on IE and have a Priority of 2 (for docompare.php)  and 7 (for runtest.php). I am getting the priority from the test name itself . Example `18113000016F.181130_5B_1FQ.p2`  for `docompare.php` and `18113000016T.181130_PP_1G7.p7` for `runtest.php`.  We are not running tests on IE at all, so I am not sure if this is a result of a malicious activity and if its time to set up security on our server but before I declare that  I still want to get to bottom of this and get your feedback.    I got some sense of priority from this https://www.webpagetest.org/forums/showthread.php?tid=12060 but I am not sure how priority 2 and 7 can be triggered. Can you please let me know. thanks

**Comment by pmeenan** [comment]
Check you access logs. Passing priority=7 or priority=7 with a test request will set those explicitly. I believe the video comparison UI submits tests at priority 2 by default as well.
