### ISSUE TITLE
Is there any virtual appliance available for download?

### ISSUE THREAD

**Issue by JFC-MC** [WPO-Foundation/webpagetest#1222]
Hi!
I've seen AMI images are out there. As well as GCE images.
But is there any image of already configured virtual machine that I can host on my corporate infrastructure(KVM,VHD,VMDK, whatsoever)?

It'd be so convenient to have it.

**Comment by pmeenan** [comment]
Not directly but there are Docker images for the [server](https://hub.docker.com/r/webpagetest/server/) and [agent](https://hub.docker.com/r/webpagetest/agent/) as well as 1-step setup scripts for the [server](https://github.com/WPO-Foundation/wptserver-install) and [agent](https://github.com/WPO-Foundation/wptagent-install).

**Comment by JFC-MC** [comment]
Thank you for rapid answer!
