### ISSUE TITLE
WPTAPIError 503 Service Unavailable

### ISSUE THREAD

**Issue by alexgibson** [WPO-Foundation/webpagetest#1226]
Hi, beginning on Dec 1st 2018 we started seeing frequent WPTAPIError 503 errors being returned via the API in our test scripts:

```
- Failed: https://www.mozilla.org/en-US/firefox/ [ec2-us-west-1:Chrome:Native]
{ Error
    at Object.<anonymous> (/app/node_modules/webpagetest/lib/helper.js:213:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/webpagetest/lib/webpagetest.js:14:15)
    at Module._compile (module.js:653:30)
  name: 'WPTAPIError',
  code: 503,
  message: 'Service Unavailable' }
```

The example above is using the node wrapper library, but I don't believe this is an issue related to that repo itself, as it's just returning the response as expected.

At first I suspected this may have been an issue with our web hosting, but the failures have started happening for multiple web properties that are all hosted independently, and our monitoring doesn't indicate any such errors and I'm out of ideas. The errors are intermittent but frequent. Could this be a WPT infra issue? 

Note: We currently run tests against the public online instance.

**Comment by pmeenan** [comment]
Were you seeing errors for an extended period (and are you still seeing them)? There was a network outage for a few hours with Verizon which likely caused the 503's.

**Comment by alexgibson** [comment]
We’re seeing errors in our daily test run consistently since Dec 1st. Still seems to be an issue that has been ongoing for many days :(

**Comment by alexgibson** [comment]
Whatever the source of the issue here, things seemed to return back to normal for us on Dec 22nd. I'll continue to monitor logs, but things seem stable once again. Closing, thanks.
