### ISSUE TITLE
Race condition between GetTestStatus and GetJob

### ISSUE THREAD

**Issue by nikhilgupta345** [WPO-Foundation/webpagetest#1231]
When we hit jsonResult.php to get the status of a test, there is sometimes an issue where the test is just about to be started. I don't know the exact details, but it seems to be an issue mainly if there's high latency on file writes (we're using EFS to share file-based queues between multiple servers). Here's one of the test logs:

```
2018/12/13 23:24:32 - Test Created
2018/12/13 23:26:00 - The test was not started but the test job could not be found.  Forcing it to end.
2018/12/13 23:26:00 - Starting test (initiated by tester i-0c8ba692b88672da9)
2018/12/13 23:26:00 - Run 1 assigned to i-0c8ba692b88672da9
2018/12/13 23:26:40 - Test Run Complete. Run: 1, Cached: 0, Done: , Tester: i-0c8ba692b88672da9
2018/12/13 23:26:40 - Extracting 150461 byte uploaded file '/tmp/phpEa7WTS' to './results/18/12/13/HA/WTN'
2018/12/13 23:26:41 - Done Processing. Run: 1, Cached: 0, Done: , Tester: i-0c8ba692b88672da9
2018/12/13 23:26:51 - Test Run Complete. Run: 1, Cached: 1, Done: 1, Tester: i-0c8ba692b88672da9
2018/12/13 23:26:51 - Marked shard 1 as complete: {"1":true}
2018/12/13 23:26:51 - All 1 runs are complete
2018/12/13 23:26:51 - Extracting 47961 byte uploaded file '/tmp/phpHA8wm3' to './results/18/12/13/HA/WTN'
2018/12/13 23:26:52 - Done Processing. Run: 1, Cached: 1, Done: 1, Tester: i-0c8ba692b88672da9
2018/12/13 23:26:52 - Test Complete
2018/12/13 23:26:54 - Test post-processing complete
```

**Comment by nikhilgupta345** [comment]
@pmeenan

**Comment by pmeenan** [comment]
You probably need your {wptdir}/tmp directory to be shared as well assuming efs supports flock because lock files for the queues and tests are stored there.

THat said, multiple servers operating off of a single queue isn't officially supported or even tested so you're likely to bump into a bunch of issues.

**Comment by nikhilgupta345** [comment]
We have the tmp directory shared, along with:
```
    "log"
    "results"
    "tmp"
    "work/jobs"
    "work/video"
    "dat"
    "logs"
    "settings"
    "tests/data"
    "ec2"
```

This isn't an issue that occurs frequently but only every 20 tests or so. I understand it's not officially supported but we would really appreciate any thoughts you may have! Thanks in advance

**Comment by nikhilgupta345** [comment]
Also, do you think using an external beanstalkd queue that the servers shared would work without issues?

**Comment by pmeenan** [comment]
beanstalkd may help but it looks like a pretty serious problem with efs. The test ID shouldn't be returned before the job file is written but the polling shows the job file not being there yet. It kind of looks like there is some caching or propogation delay in efs.

Maybe you can retry checking for the job file a few times in teststatus with a delay inbetween to let efs catch up but that's somewhat concerning.

**Comment by nikhilgupta345** [comment]
Looks like using the `noposition` flag in jsonResult fixed our issues by not checking the job position at all. Thanks for the help!
