### ISSUE TITLE
ec2_instance_size being ignored on private instance

### ISSUE THREAD

**Issue by sholman** [WPO-Foundation/webpagetest#1242]
I have uncommented the ec2_instance_size setting and changed it to ec2_instance_size=m3.medium while I'm testing but this setting seems to be being ignored.

I have restarted nginx using "sudo service nginx restart" and also rebooted the master instance.

**Comment by thedoc31** [comment]
I'd suggest you check your ec2_locations.ini and do a search/replace in there too. Instance sizes can be overridden in the various settings for browsers and AMIs. 

Example:

https://github.com/WPO-Foundation/webpagetest/blob/fba2d39864e1a299e14af388351aee7783d26bed/www/settings/ec2_locations.ini#L58

**Comment by sholman** [comment]
You are correct, I was just looking in locations.ini, but didn't realise that that was merged with ec2_locations.ini.

**Comment by sholman** [comment]
Can confirm that changing in ec2_locations.ini and restarting nginx worked.
