### ISSUE TITLE
setDNS remove the DNS lookup time in the waterfall

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#1249]
The [documentation](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setDns) states that `setDns` command allows for overriding the IP address to be used for a host name. The original name will still be looked up so that accurate timings will be recorded but the address will be replaced by the one specified.

In my [test using `setDns`](https://wpt.fasterize.com/result/180423_5T_C/5/details/#waterfall_view_step1) on the official linux AMI, the DNS lookup duration is zero.

Either a regression appears on the code or the documentation is outdated.

**Comment by pmeenan** [comment]
Docs have been updated. It's no longer possible to modify the responses directly so it effectively becomes the same as using a hosts file (which wipes out DNS times).
