### ISSUE TITLE
Can we include the full browser_version in parentheses, e.g. (66.0a1) in the web UI?

### ISSUE THREAD

**Issue by stephendonner** [WPO-Foundation/webpagetest#1250]
Hi Pat - 

I'd like to include the PHP equivalent/exposed ```browser_version``` which we're using happily over in https://github.com/mozilla/wpt-api/blob/487607f423b8dd154fdfe52bbb1b5084b2866192/send_to_datadog.py#L51, via Python.

Would you mind helping me with how to cleanly do so in PHP?  I'm looking through https://github.com/WPO-Foundation/webpagetest/blob/79f638047103cf857dae24116c93b11d027e1bab/www/include/Browser.php and elsewhere.

Thanks!

/cc @davehunt

<img width="1918" alt="screen shot 2019-01-28 at 12 39 00 pm" src="https://user-images.githubusercontent.com/387249/51867054-651e4c00-22ff-11e9-9e87-d20e08e9f9ef.png">

**Comment by pmeenan** [comment]
It might be possible to pull it from the median run but right now that string is built by the settings that were requested when the test was run and doesn't use anything from the actual result. The code for it is [here](https://github.com/WPO-Foundation/webpagetest/blob/master/www/header.inc#L219)

**Comment by scottjehl** [comment]
late reply but recent redesigns included this one. fixed! https://www.webpagetest.org/result/220713_BiDcG2_DX8/
