### ISSUE TITLE
total_api - intentionally returning 0 for wrapped API calls, or bug/unintended feature?

### ISSUE THREAD

**Issue by stephendonner** [WPO-Foundation/webpagetest#1251]
Hi Pat -

I take it ```total_api```[0] is 0 in private instances which use Marcel's ```webpagetest-api``` NodeJS wrapper[1], to call it?

Makes sense if so intentionally, just curious, along with @davehunt.

Cheers!

[0] https://github.com/WPO-Foundation/webpagetest/blob/7b8d5d0821ae18b547f475133cae28a3c2b2778a/www/usage.php#L99
[1] https://github.com/mozilla/wpt-api/blob/bbca8375eef200f8d991793cd9077b6dca689201/Jenkinsfile#L21-L28

<img width="2031" alt="screen shot 2019-01-29 at 8 23 52 pm" src="https://user-images.githubusercontent.com/387249/51958248-da734500-2403-11e9-8a1d-8585d447997f.png">

**Comment by pmeenan** [comment]
Are you using API keys or is it wide open? It looks to see what API key was used to run a test to determine "API" tests but if keys aren't being used it won't be able to detect them.

**Comment by stephendonner** [comment]
Pat, sorry for the delayed response, and thank you for your reply.  We're authenticating to the server, but **not** using an API key in our Jenkins setup: https://github.com/mozilla/wpt-api/blob/ad97dd90050117db35cf6715e965cc3281dcd0da/Jenkinsfile#L11

Feel free to close, and again, thanks!
