### ISSUE TITLE
No apparent way to block OCSP check

### ISSUE THREAD

**Issue by mac9416** [WPO-Foundation/webpagetest#1252]
I'm trying to prevent the OCSP check to get apples-to-apples comparisons between EV and non-EV certificate sites.

In #1119 you mentioned maybe trying to block the OCSP domain.

I just ran a test, and blocking the OCSP domain didn't prevent the OCSP check:
http://webpagetest.org/result/190201_VG_033d3b802cb7658f743dc3ea2c0e3791/1/details/

Is there another way to cut out the extra time added by the OCSP check?

**Comment by pmeenan** [comment]
You were close. It looks like it falls back from ocsp to a crl check so you need to block multiple domains.

```
blockDomains	ocsp.godaddy.com crl.godaddy.com
navigate	https://www.crutchfield.com/
```
https://www.webpagetest.org/result/190203_SG_9a2cda5f303bb16cb63853e658fb87a6/

The setDns command needs a domain so if you wanted to use that instead you'd need to do:
```
setDns	ocsp.godaddy.com	127.0.0.1
setDns	crl.godaddy.com	127.0.0.1
navigate	https://www.crutchfield.com/
```

**Comment by mac9416** [comment]
Can't believe I missed that. This is a great solution, it'll make benchmarking much easier. Thanks a lot!
