### ISSUE TITLE
WPT waterfall data and exclusive flag on HTTP2 requests

### ISSUE THREAD

**Issue by r-s-sandbox** [WPO-Foundation/webpagetest#1263]
Hi
I am looking at the waterfall data for a few sites that are either using cloudflare or cloudfront CDNs and serving content over HTTP2. 

https://www.webpagetest.org/result/190326_JZ_4be6bd7bd1fcda9a85e02fd28b365fef/1/details/#waterfall_view_step1
https://www.webpagetest.org/result/190326_81_d4166f39242836feeaca9079b8047d57/1/details/#waterfall_view_step1
https://www.webpagetest.org/result/190326_X2_75d24875a4dcf7661c01d83d1fc31587/1/details/#waterfall_view_step1
https://www.webpagetest.org/result/190326_6W_0fbd7413289d248f8acce9494eec27e4/1/details/#waterfall_view_step1

All HTTP2 requests are showing an exclusive flag and I am trying to understand where is this flag being set - agent, client or server. 

<img width="1090" alt="Screen Shot 2019-03-27 at 10 52 25" src="https://user-images.githubusercontent.com/43778016/55070767-e20b3f00-507e-11e9-84eb-f355159787d9.png">

For our site, we are using cloudfront and are also noticing the exclusive flag in WPT waterfall data without explicitly setting it ourselves.

**Comment by andydavies** [comment]
@r-s-sandbox It's set by Chrome when it makes the initial request, Firefox has a different approach 

@pmeenan's talk from Dec's LDNWebPerf meet up is well worth a watch if you want to understand more - https://www.youtube.com/watch?v=xDhUrdx0bRY

**Comment by r-s-sandbox** [comment]
Thanks for the response and link @andydavies. Was definitely worth the watch.
