### ISSUE TITLE
Start Render question

### ISSUE THREAD

**Issue by soulcorrosion** [WPO-Foundation/webpagetest#1265]
Hi, just a question. In order to track Start Render, WPT checks changes every 100 ms right?
If so, it means that if the first visual change was at 101 ms, we would get a 200 ms Start Render value?

I'm asking this, because we have performance budgets and if I have one budget on Start Render at 200 ms and one test shows a 300 ms Start Render, it would mean exceeding the budget by 50% but  in reality that change might have happen much earlier, like 220ms, like I see with First Paint.

**Comment by pmeenan** [comment]
For desktop, the video capture rate defaults to 10fps (100ms) - for the physical mobile devices it is 60fps.

And yes, a 101ms value would show up as 200ms.
