### ISSUE TITLE
[Question] Why bulk test option is disabled on open version of WebPageTest?

### ISSUE THREAD

**Issue by Danon9111** [WPO-Foundation/webpagetest#1269]
Like in title. Why currently there is no possibility to run bulk test using https://www.webpagetest.org/ ? 

Is this somehow related to test results or to some other tool issue?

Best Regards

**Comment by andydavies** [comment]
It's only available on private instances - it enables people to run hundreds of tests

**Comment by Danon9111** [comment]
@andydavies thank you for clarification. 

Closing as a resolved :)
