### ISSUE TITLE
Incomplete waterfalls generated for custom error pages e.g. 404

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1275]
Sites frequently serve custom error pages e.g. https://www.bluefountainmedia.com/asd but WPT generates an incomplete waterfall for them e.g. http://webpagetest.org/result/190611_76_de3d66d1180ed32a753a1872c869ca31/

The traces contain the network requests, and for some sites the screenshots are more complete than others.

Guessing the HTTP Status code short-circuits the response processing somewhere

**Comment by nilskuhn** [comment]
Congratulation, I never had a customer with the budget to performance optimize an error page ;)
Well, if I think about it again, I had one load testing and scaling it...

**Comment by Nooshu** [comment]
There is now a workaround for this issue, as Pat has [added a fix](https://github.com/WPO-Foundation/wptagent/issues/349) for the 'Minimum test duration' with 404 pages.

![Screenshot 2020-06-01 at 22 42 19](https://user-images.githubusercontent.com/1223960/83459084-94951980-a45b-11ea-8d70-81ea4df6ae18.png)

Results in:
![waterfall](https://user-images.githubusercontent.com/1223960/83459098-9b239100-a45b-11ea-83d7-ce8362d4f5b3.png)
