### ISSUE TITLE
TTI deep dive

### ISSUE THREAD

**Issue by soulcorrosion** [WPO-Foundation/webpagetest#1277]
Hi @pmeenan , I know the specification behind TTI, but I was trying to understand how the exact number is calculated in WPT. What do you recommend for getting there? I was using the trace view. For instance let's consider this simple test: https://www.webpagetest.org/result/190619_6C_75c1f4574dca4ab9fe41059152920499/

TTI = 1.754s

I was looking at the trace trying to figure out how 1.754 is obtained.

![image](https://user-images.githubusercontent.com/7148510/59762034-2416dc00-928e-11e9-989c-ea40735f7e12.png)

I understand we want to get the first interactive window, so that would be exactly after the last tasks taking more than 50ms right? In this case I don't see anything taking longer than 50ms, except the "wall duration" in the "Timer Fire". I can't seem to get the exact 1.754s. Can you explain?

Thank you very much. :)

**Comment by pmeenan** [comment]
The "zero" time in trace viewer will likely not match WabPageTest's zero time so you won't see times line up exactly. WebPageTest looks for the start of the navigation in the trace and uses that as the start time.

As far as the 50ms goes, the main thread is blocked for the duration of the "Timer Fire" event and "wall duration" is exactly what matters to the user and is what is used for TTI.

The actual logic that tracks it is here: https://github.com/WPO-Foundation/wptagent/blob/master/internal/support/trace_parser.py#L471

It's not particularly selective about WHAT that tasks are. Any dev tools timeline event that has a wall clock duration of > 50ms will trigger.
