### ISSUE TITLE
Chrome 75: Missing FMP for some URLs

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#1281]
Unsure if this a WPT or Chrome issue but since Chrome 75 we're finding that First Meaningful Paint is missing for some URLs tested.

Here's an example on public: https://www.webpagetest.org/jsonResult.php?test=190624_6P_acc3c3afa576f19be74058342302125c

There are plenty of "chromeUserTiming" events but "chromeUserTiming.firstMeaningfulPaint" is missing. Does WPT extract the FMP value or does it just pass through all available "chromeUserTiming" events? In another words is this a WPT or Chrome issue?

**Comment by zeman** [comment]
Thanks for taking a look @pmeenan. I reran the test and I'm still not seeing FMP. 

https://www.webpagetest.org/jsonResult.php?test=190626_ER_f14c975dc2f9f3576579ec91344732d4

**Comment by pmeenan** [comment]
Doh. I pushed the code update but didn't update my server. Will update in a
bit and let you know when it is live.

**Comment by pmeenan** [comment]
Server is updated now and here is a re-run: https://www.webpagetest.org/result/190626_GX_c36dd9efe8d09eb500da570df7078958/

```json
"chromeUserTiming":[
    {"name":"firstImagePaint","time":0},
    {"name":"domInteractive","time":242},
    {"name":"domContentLoadedEventStart","time":242},
    {"name":"domContentLoadedEventEnd","time":273},
    {"name":"firstMeaningfulPaint","time":491},
    {"name":"firstMeaningfulPaint","time":491},
    {"name":"firstMeaningfulPaintCandidate","time":491},
    {"name":"domComplete","time":6138},
    {"name":"loadEventStart","time":6138},
    {"name":"loadEventEnd","time":6152}
],
"chromeUserTiming.firstImagePaint":0,
"chromeUserTiming.domInteractive":242,
"chromeUserTiming.domContentLoadedEventStart":242,
"chromeUserTiming.domContentLoadedEventEnd":273,
"chromeUserTiming.firstMeaningfulPaint":491,
"chromeUserTiming.firstMeaningfulPaintCandidate":491,
"chromeUserTiming.domComplete":6138,
"chromeUserTiming.loadEventStart":6138,
"chromeUserTiming.loadEventEnd":6152,
```

That said, the waterfall for that test looks bizarre so there are probably other issues that need to be sorted out with parsing Chrome 75 results still.
