### ISSUE TITLE
(Test Error: net::ERR_ABORTED) - with two or more navigates in scripted test

### ISSUE THREAD

**Issue by JamesHDa** [WPO-Foundation/webpagetest#1284]
If you try running a script with two or more navigates you get Test Error: net::ERR_ABORTED on the second navigate.  For example [test result error](https://www.webpagetest.org/result/190708_V8_596e508c208edea469fd26b5289e3e13/  ) with the following script:
```
navigate	www.google.com
navigate	www.yahoo.com
navigate	www.aol.com

```
Which should be possible as of [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-combineSteps)

**Comment by nilskuhn** [comment]
It works for me with the given three url's if you don't use `combineSteps`:
https://www.webpagetest.org/result/190708_MH_daf7eade4902e9554f84651620a6cae4/
In this case you will get one result with timings for every step in your script. 
 
If you want to open multiple pages of the same site in a customer journey and doesn't want to measure each page separately (for which I don't see a very good reason) it works for other URL's using `combineSteps`, too:
https://www.webpagetest.org/result/190708_JD_d9f3f4f90a23ae89f29373d3c5afc9f9/

Maybe the 307 redirects for yahoo.com and aol.com make your test crash?

**Comment by JamesHDa** [comment]
Sorry, I suspect that you maybe right about the redirects in this case. 
I found out what the exact issue was with the website i was actually testing, it was to do with a request of type `text/event-stream` I got around it by just blocking the request url.  

Thanks.
