### ISSUE TITLE
Test History page has false negatives

### ISSUE THREAD

**Issue by votemike** [WPO-Foundation/webpagetest#1285]
The test history page seems to get confused by the HTTPS protocol.

After running [a test with the string https://www.bbc.co.uk/sounds](http://webpagetest.org/result/190716_SW_87723d8f59bcb98a381284e0634c1b8e/) the Test History page [shows a result for www.bbc.co.uk](http://webpagetest.org/testlog.php?days=30&filter=www.bbc.co.uk) but [not https://www.bbc.co.uk](http://webpagetest.org/testlog.php?days=30&filter=https%3A%2F%2Fwww.bbc.co.uk)

**Comment by andydavies** [comment]
@votemike Does this still occur for you - I just tried in and it seem to work correctly for me

**Comment by pmeenan** [comment]
I fixed it back on January 4th and added : and / to the allowed characters.  Otherwise they were being filtered out (to protect against abuse) and the search string was changed.

**Comment by votemike** [comment]
Cheers. Both.
