### ISSUE TITLE
FR: Chrome extension - hover to see load time of any element

### ISSUE THREAD

**Issue by daxliniere** [WPO-Foundation/webpagetest#1292]
Hey team,
Thanks for continuing the development of this tool. I just discovered it and it's extremely useful to a novice webcoder like me.

I had an idea for a very useful Chrome extension: When you hover your mouse over any element on a page there is a continuous popup displaying the load time.

Thanks for listening to my idea,
Dax.

**Comment by nilskuhn** [comment]
[This chrome extension](https://chrome.google.com/webstore/detail/ncc-image-checker/fphiheficgnpphmjdliclanppccfgifl?hl=en-GB) shows download times for every image on a page. Even though the main purpose of the tool is actually to visualize too large images.

**Comment by daxliniere** [comment]
Awesome! Thanks so much, Nils!
