### ISSUE TITLE
Missing response bodies

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#1296]
Hi Patrick,
we've been debugging an internal issue and found that it looks like we sometimes do not get the response body for Chrome.

Here's an example:
http://wpt.wmftest.org/result/190906_F6_B/

The first and the last run, miss out on the response body of the HTML:
<img width="610" alt="Screen Shot 2019-09-06 at 11 15 28 AM" src="https://user-images.githubusercontent.com/540757/64416570-ad70ca00-d097-11e9-8953-290818238302.png">

But the other runs gets the body:
<img width="941" alt="Screen Shot 2019-09-06 at 11 17 51 AM" src="https://user-images.githubusercontent.com/540757/64416717-02acdb80-d098-11e9-8231-04701e7510f1.png">

Best
Peter

**Comment by edwincoronado** [comment]
@soulgalore did you check the "Save reponse bodies" checkbox in the "Advanced" tab of WPT? If you're executing this through `runTest.php` then you need to pass the `bodies=on` parameter.

**Comment by pmeenan** [comment]
Can you capture a test with debug=1 to save the debug log and dev tools
messages? Bodies require a request ID from dev tools so if a request isn't
captured in the dev tools messages and is only available because of the
netlog then the body won't be available.
