### ISSUE TITLE
Incorrect run being marked as median

### ISSUE THREAD

**Issue by edwincoronado** [WPO-Foundation/webpagetest#1298]
I have attached an example JSON files of results. These are the values for First View.

| Run | Document Complete | Visually Complete |
|-----|-------------------|-------------------|
| 1   | 562               | 9100              |
| 2   | 570               | 10200             |
| 3   | 537               | 10000             |
| 4   | 544               | 9000              |
| 5   | 578               | 11800             |

But if you notice in the JSON path `data►median►firstView►run`, it is marked as 1. Where it should be marked as 3.

This issue happened on release 19.04. We have an integration running that is dependent on median values and this is a pretty significant issue for us and I'm sure many other people. Any help would be appreciated.

**Comment by edwincoronado** [comment]
[median-error.log](https://github.com/WPO-Foundation/webpagetest/files/3649330/median-error.log)

Attached file as `.log` instead of `.json` because github wasn't allowing.

**Comment by pmeenan** [comment]
Do you have the SpeedIndex times? By default (unless you pass medianMetric=xxx) it will use SpeedIndex to pick the median run.

**Comment by edwincoronado** [comment]
| Run | Speed Index |
|-----|-------------------|
| 1   | 7506 |
| 2   | 8591 |
| 3   | 5112 |
| 4   | 6532 |
| 5   | 9190 |

This would make run 1 median, which is what we're seeing. I see in the RESTful APIs documentation that `loadTime` is the default for `medianMetric`. What value could I pass to make WPT use timings instead of SpeedIndex? Also, would it look at the document complete or the visually complete? 

Thanks a lot for your prompt help.

**Comment by pmeenan** [comment]
Whatever the JSON key is that you want to use should work as a target for pulling the median.

medianMetric= docTime
medianMetric=fullyLoaded
medianMetric=visualComplete

Any of those will work as a query param (as well as any of the other metrics in the JSON)

**Comment by edwincoronado** [comment]
Thanks for your answer. I tried this on `results/######/?f=json&medianMetric=visualComplete` and it worked. I also saw that I can do this on `runTest.php`. I would like to contribute by updating documentation on this. I feel that people could run into the same question. If you could point me to how to do this I would appreciate it.
