### ISSUE TITLE
Why 4G network's RTT is more than Fast 3G

### ISSUE THREAD

**Issue by kkdev163** [WPO-Foundation/webpagetest#1300]
Hi, I am confused with this config, why 4G network's RTT is more than 3G-Fast ? 
![image](https://p1.music.126.net/Ymf_8YtrKXgZl-S8flQeHQ==/109951164389801022.png)

**Comment by pmeenan** [comment]
Because mobile has a WIDE range of performance and the different technologies overlap. "$G" is faster than "3G" on latency but "LTE" is the fast version of 4G tech. The numbers were pulled from real field performance data when the clients were connected to each of the different technologies.
