### ISSUE TITLE
WebPageTest.org doesn't use HTTPS

### ISSUE THREAD

**Issue by tomayac** [WPO-Foundation/webpagetest#1302]
In [theory](https://twitter.com/patmeenan/status/1178631967534915584) there should be a an HTST header according to @pmeenan, but in [practice](https://t.co/abGIDyH6gM) there isn't.

**Comment by tomayac** [comment]
Actually, HSTS headers delivered over HTTP are to be [ignored](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#Description) (yellow note).
(via https://twitter.com/bkhowson/status/1178654880652759041)

**Comment by pmeenan** [comment]
I deployed a reasonable compromise.
* The HSTS header is (actually) there now so if a user's browser ever visits a page on webpagetest.org over https then the browser will auto upgrade all navigations to any page.
* The landing pages for running tests (webpagetest.org/ and webpagetest.org/easy) 301 redirect to https versions
