### ISSUE TITLE
Improve getTesters.php page by showing offline agents

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#1306]
I am always confused by the page `/getTesters.php?f=html` on our private instance connected to EC2 agents.
In fact, most active agents in EC2 are missing in `/getTesters.php` list. After digging into this bug, I discovered that the reason was the fact that most active agents were marked as 'offline' and getTesters.php doesn't show offline agents.

I understand that **offline** means that "the agent is an excess instance that will eventually go idle and terminate".

Could we change this page to see offline agents and add a column mentioning if the agent will be terminated ?

**Comment by abarre** [comment]
Also, the 'k' option doesn't work on this page, I suspect that the `parse_ini_file` is wrong.

**Comment by pmeenan** [comment]
I don't think "k" support was ever added to the testers page, just the locations page.

**Comment by abarre** [comment]
I was mentioning this part of the code : https://github.com/WPO-Foundation/webpagetest/blob/master/www/getTesters.php#L6.
