### ISSUE TITLE
Blink features not up to date

### ISSUE THREAD

**Issue by chlily1** [WPO-Foundation/webpagetest#1308]
https://github.com/WPO-Foundation/webpagetest/blob/3dfde91dd0b51e989e7a307ff8df904f9d5ca460/www/lib/trace/trace_parser.py#L1064-L2790

Hi, I'm not quite sure if I'm looking at the most up-to-date version of this code, but it seems from the global defined here that more recent Blink WebFeatures past 2065 are not being tracked. In [web_feature.mojom](https://cs.chromium.org/chromium/src/third_party/blink/public/mojom/web_feature/web_feature.mojom) in the Chromium source code, the features go up to 3073.

I was looking at this because I was trying to find data for my features, 2916 and 2917, which were added a few months ago but never showed up in the HTTP Archive data.

**Comment by bkardell** [comment]
+1 / @pmeenan 

We have no data for this https://chromestatus.com/metrics/feature/timeline/popularity/2998
relevant to this intent https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/7X2CKPGeEa0/7Rau54VwDQAJ said data would be very helpful

**Comment by pmeenan** [comment]
I'm away from my computer right now so I can't tag him directly but ping
Rick Viscomi. Wpt is up to date with the features and collects the data.
It's the chrome status dashboard that needs updating.

That's assuming the feature made it to stable which is what the http
archive uses for testing.

**Comment by rviscomi** [comment]
I checked the September 2019 HTTP Archive dataset and the highest feature number it contains is 2936 (LazyLoadImageMissingDimensionsForLazy). Here's a truncated version of the query:

```sql
#standardSQL
CREATE TEMP FUNCTION getFeatureNumber(feature_name STRING)
RETURNS NUMERIC LANGUAGE js AS '''
var features = {"PageDestruction":"0"}; // truncated
return feature_name in features ? parseInt(features[feature_name], 10) : -1;
''';

SELECT
  MAX(getFeatureNumber(feature)) AS max_feature_number
FROM
  `httparchive.blink_features.features`
WHERE
  yyyymmdd = '20190901'
```

See the query with the full feature mapping: https://bigquery.cloud.google.com/savedquery/226352634162:cc6b6a06db4d40e09fb8cf71f4f0f04f

Given that, I think @pmeenan is correct that WPT and HTTP Archive have the latest features. Still not sure why some newer features would be counted and not others...

**Comment by chlily1** [comment]
Oh, ok. Thank you both for checking!

Still seems odd to me that my features, [2916](https://chromestatus.com/metrics/feature/timeline/popularity/2916) and [2917](https://chromestatus.com/metrics/feature/timeline/popularity/2917), aren't showing up at all, even using the query above that directly pulls from httparchive.blink_features.features. I'm sure they should be showing up on at least 1 page out of all the pages that HTTP Archive indexes, as they appear on over 60% of pages overall. I've verified that they're in the [UKM feature list](https://cs.chromium.org/chromium/src/components/page_load_metrics/browser/observers/use_counter/ukm_features.cc?q=kCookieNoSameSite+-file%3Aout&ss=chromium%2Fchromium%2Fsrc&l=107), if that's relevant. I've even gone to e.g. cnn.com and verified via logging from my local Chrome build that they are occurring.

Hypothesis: These are logged browser-side; maybe only renderer-side events are being recorded correctly? (Would you happen to have a reference to where in the code these events are being emitted? I think it's [here](https://cs.chromium.org/chromium/src/components/page_load_metrics/browser/observers/use_counter_page_load_metrics_observer.cc?l=132&bpv=1&bpt=1) but I'm not sure.)

(A bit out of scope for the original issue (feel free to close), but any help or pointers would be appreciated. The data that is missing would be very useful to my team.)

**Comment by morlovich** [comment]
Oh, hold on, you're talking about the second chart (which just managed to be below the fold for me) --- that is indeed missing for SandboxBackForwardStaysWithinSubtree

**Comment by chlily1** [comment]
Thanks @pmeenan! That trace is emitted from here: https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/frame/use_counter_helper.cc?bpv=1&bpt=1&l=93

Looks like there's nothing on the browser side that refers to the blink.feature_usage trace. :-(

That must be the issue then. I'll file a crbug.

Thanks @morlovich for investigating!

**Comment by morlovich** [comment]
Probably worth highlighting that it means that data collected for metrics reported on both ends is likely questionable.  I think in current Chrome only kDownloadInAdFrameWithoutUserGesture & family fit the bill... looks like they're owned by a colleague on a sister team, which makes this easier.

**Comment by chlily1** [comment]
Filed https://crbug.com/1019823

**Comment by chlily1** [comment]
Oh hm, @bkardell your feature is recorded in Blink, not the browser, so there's definitely something else going on... You may want to file a separate bug.

Closing this since it's not WPT's fault.

**Comment by yoavweiss** [comment]
@bkardell - I bugged @pmeenan into investigating 2998 and 2999 and it seems it's a simple matter of versions: They landed in August 15, on the M78 branch, which reached stable on October 22nd.
