### ISSUE TITLE
Changes on search?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#1313]
Hi Patrick,
the search on our private instance has stopped working. I'm not sure when because I haven't used that functionality in a while and I wonder if it could be related to some change in the project because we haven't touched our server in a while?

When I do a search in http://wpt.wmftest.org/testlog.php?days=7&filter=&all=on I don't get any results. But when I check the search log I can see that we have log files from today and it looks as before:
```
2019-11-25 3:56:51	IP	0	0	191125_5T_f21af3710db98d5c77e1e48e9f6068a7	https://www.wikipedia.beta.wmflabs.org/ ....
```

I can see that our tests is running and we get the data but I can't see it in the search. Do you have any pointers where I should look?

Best
Peter

**Comment by soulgalore** [comment]
When I test going back 30 days, I get a forbidden response. I think we had the same issue a couple of years back, I'll see if I can find what caused it that time.

**Comment by pmeenan** [comment]
Fwiw, does the search work without the https: in the search term? I think
the colon may be breaking it.

**Comment by soulgalore** [comment]
No it doesn't show anything event without any search term. Let me look into it.

Search older than seven days: We (or I) have accidentally removed our local hack for the 7 day limit as in https://github.com/WPO-Foundation/webpagetest/commit/98263d8a9730885fd701954195edd7f4e66867b4#diff-8fff559d9da9f63232a9c86ab3dfe1ac

**Comment by soulgalore** [comment]
I could see that it stopped working the 11/12/19 and I could not see any commits correlating to that so the change must be on our side, let me close this.
