### ISSUE TITLE
[Metrics] LargestContentfulPaint (LCP) support

### ISSUE THREAD

**Issue by gfx** [WPO-Foundation/webpagetest#1315]
This is a new metric to represent user experience, introduced recently to Chrome:

https://web.dev/lcp/

> Largest Contentful Paint (LCP) is an important, user-centric metric for measuring perceived load speed because it marks the point in the page load timeline when the page's main content has likely loaded—a fast LCP helps reassure the user that the page is useful.

**Comment by pmeenan** [comment]
When reported by Chrome it will be in the JSON result data (not exposed in the UI).

Most recent work is [here](https://github.com/WPO-Foundation/wptagent/commit/3cf43d9234bb29ff4231fe01a5f3d86eabf4aa42) with some fixes [here](https://github.com/WPO-Foundation/webpagetest/commit/6002b343c3912bb33434c0c40e675fe65215230b). That said, the actual trace messages for emitting LCP are still a bit hit or miss.

It will be added to the UI at some point when the metric is stable and has proven to be useful.

**Comment by gfx** [comment]
@pmeenan Thank you. As you said, there is LCP in the result JSON, so I'll use it for now.

**Comment by sys-2020** [comment]
I run in web and LCP is not there... 
:(
