### ISSUE TITLE
False 404 Reported in Waterfall

### ISSUE THREAD

**Issue by mikeytag** [WPO-Foundation/webpagetest#1321]
We've been using WPT for some time now and I've come across an interesting issue. If you take a look at the following test, you'll notice a few assets (jquery.min.js) and such are reporting 404 errors.

https://webpagetest.org/result/200107_BH_d5af7df91838d08f12c634b1f084ad82/1/details/

However, in Chrome or any browser there aren't any 404 errors reported. Some of the time, WPT is malforming a script src like this:

https://www.domain.com//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js

This is obviously incorrect and errors out, but I'm having a hard time deciphering why this happens in the waterfall report. FWIW, here's a URL of ours that is always showing this issue, but the 404 errors that are reported never show up in Chrome Developer Tools or any other native browser test I do.

https://www.taxreliefcenter.org/Tax-Relief/Installment-Agreement.html

![Screen Shot 2020-01-06 at 6 11 35 PM](https://user-images.githubusercontent.com/219403/71862868-038a6400-30b0-11ea-9db3-886bdf8845f7.png)

**Comment by andydavies** [comment]
It's an upstream problem as those resources are being pushed by the server.

Unfortunately DevTools doesn't show failed pushes but here's a extract from a (locally) produced NetLog

```
t=117989 [st= 262]  HTTP2_SESSION_RECV_PUSH_PROMISE
                    --> :method: GET
                        :path: //ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js
                        :scheme: https
                        :authority: www.taxreliefcenter.org
                        accept-encoding: gzip, deflate, br
                        accept-language: en-GB,en-US;q=0.9,en;q=0.8
                        user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
                    --> id = 5
                    --> promised_stream_id = 2
t=117989 [st= 262]  HTTP2_SESSION_SEND_RST_STREAM
                    --> description = "Invalid pushed request headers."
                    --> error_code = "7 (REFUSED_STREAM)"
                    --> stream_id = 2
t=117989 [st= 262]  HTTP2_SESSION_RECV_PUSH_PROMISE
                    --> :method: GET
                        :path: //api.trustedform.com/trustedform.js
                        :scheme: https
                        :authority: www.taxreliefcenter.org
                        accept-encoding: gzip, deflate, br
                        accept-language: en-GB,en-US;q=0.9,en;q=0.8
                        user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
                    --> id = 5
                    --> promised_stream_id = 4
t=117989 [st= 262]  HTTP2_SESSION_SEND_RST_STREAM
                    --> description = "Invalid pushed request headers."
                    --> error_code = "7 (REFUSED_STREAM)"
                    --> stream_id = 4
```

**Comment by pmeenan** [comment]
Looks like the [request to](https://webpagetest.org/result/200107_BH_d5af7df91838d08f12c634b1f084ad82/1/details/#step1_request13) ```https://www.taxreliefcenter.org/track/assist.php?form_id=156&site_id=41&form_track=d1abdc189083b079436f15335aae03a9``` has link preload headers with relative URLs which is causing Cloudflare to push the 404's.

```
link: <//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js>; rel=preload; as=script
link: <//api.trustedform.com/trustedform.js>; rel=preload; as=script
```

You probably need to file a bug with Cloudflare to have them fix the push support for protocol-relative URLs (or better yet, disable the automatic conversion from preload to push).

**Comment by pmeenan** [comment]
FWIW, I did verify that the link header is supposed to support [protocol-relative URLs](https://tools.ietf.org/html/rfc3986#section-5) so it's a Cloudflare bug with the push integration.

**Comment by mikeytag** [comment]
Interesting. Thanks for the run down. I'll work on getting that remedied from my side. I had a feeling it was related to HTTP/2 push headers.
