### ISSUE TITLE
Question - Check location status 

### ISSUE THREAD

**Issue by rusikf** [WPO-Foundation/webpagetest#1329]
It it possible through REST API to check specific location status?
I mean through one endpoint, not by parsing result of /getLocations.php (https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-restful-apis)

**Comment by pmeenan** [comment]
No (at least no currently). getLocations.php takes a f-json query param so you can get the full location data as json but there's no way to pull just a single location.  Even in a single location case it would require parsing json at a minimum.
