### ISSUE TITLE
Result calculating incorrect median for SpeedIndex

### ISSUE THREAD

**Issue by edwincoronado** [WPO-Foundation/webpagetest#1330]
We have a private instance running 19.04 and we noticed that one of the results which we are passing the `medianMetric=speedindex` parameter we get run #4 as the median run for repeat view. However, when inspecting the data as JSON (`medianMetric=speedindex&f=json`) and manually checking the runs we get these values:

| Run | Speed Index |
|-----|-------------|
| 1   | 2805        |
| 2   | 2375        |
| 3   | 2717        |
| 4   | 2673        |
| 5   | 2924        |

Which when sorted, result in this:

| Run | Speed Index |
|-----|-------------|
| 2   | 2375        |
| 4   | 2673        |
| 3   | 2717        |
| 1   | 2805        |
| 5   | 2924        |

Which makes run #3 the median. Not #4. I found the function `getMedianRunNumber` in [TestResult.php](https://github.com/WPO-Foundation/webpagetest/blob/3de67b54c58127faa66038cccc07ed3883845727/www/include/TestResults.php) that calculates this. I copied some of the code and tested it with my values and I do in fact get `2` which is correct when counting on a 0-based index. So I don't see how when going to the HTML results page the median run is incorrect. Perhaps somewhere in the pipeline an extra 1 is being added?

```php
$values = array(2805, 2375, 2717, 2673, 2924);
$numValues = count($values);
asort($values);
$runNumbers = array_keys($values);
$medianIndex = (int)floor((float)($numValues - 1.0) / 2.0);
echo $runNumbers[$medianIndex];

<img width="932" alt="Screen Shot 2020-01-29 at 2 13 03 PM" src="https://user-images.githubusercontent.com/7434954/73393570-85317400-42a1-11ea-909f-aee0122b9086.png">

**Comment by pmeenan** [comment]
The metric is case-sensitive and needs to match the JSON key.  In this case it is "SpeedIndex". Try with medianMetric=SpeedIndex

**Comment by edwincoronado** [comment]
Thanks @pmeenan . After doing this, I am getting run number 3 as the median. One question though, I thought if you didn't pass the `medianMetric` parameter it would default to Speed Index as median metric. However, if I don't pass the `medianMetric=&medianMetric=SpeedIndex`, I see run #4 as median instead of #3.

**Comment by pmeenan** [comment]
Not by default  There is a setting in settings.ini where you can change the default metric to use for the median: https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample#L99
