### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by neilstuartcraig** [WPO-Foundation/webpagetest#1345]
Hello
First off, thanks so much for working on WPT, I love it!
Whilst running some tests tonight, I found a security issue with WPT (the public service) which I'd like to report. It's reasonably serious but also should be readily fixable.
Can you please tell me how best to provide you with the details privately so as to avoid leaking information to nefarious types?
Cheers

**Comment by pmeenan** [comment]
Email me at pmeenan@webpagetest.org. Thanks.

**Comment by neilstuartcraig** [comment]
Thanks Pat, I'll put the info together and email it over now.
