### ISSUE TITLE
Old WPT Test scores CLS 0 while there are 2 layout shifts

### ISSUE THREAD

**Issue by gilbertococchi** [WPO-Foundation/webpagetest#1353]
Hi all, I am not sure if this is an attribution issue or a Chromium issue but I've noticed that on old WPT tests CLS may score 0 like in this case https://webpagetest.org/result/190524_N3_64dafbc84530c6b753bcdf4dd2f4cc14/ while the Layout definitively shifts.
<img width="586" alt="chloe_cls" src="https://user-images.githubusercontent.com/329023/82800334-d03c4c00-9e7b-11ea-9757-a9c26bf27f06.png">

Could it be that WPT is assigning the metric even before it started to exist?
https://webpagetest.org/jsonResult.php?test=190524_N3_64dafbc84530c6b753bcdf4dd2f4cc14&pretty=1

`"chromeUserTiming.CumulativeLayoutShift": 0,`

**Comment by pmeenan** [comment]
Good catch, thanks. CLS only reports events when layout actually shifts and no baseline to say "I support reporting CLS" so it was defaulted to 0. I just updated it to only report for versions of Chrome that support it.

**Comment by gilbertococchi** [comment]
Thank you patrick!
