### ISSUE TITLE
Enable FMP field on Metrics tab in https://www.webpagetest.org/lighthouse.php?test=xxxxxxxx&run=1

### ISSUE THREAD

**Issue by KarthikP1306** [WPO-Foundation/webpagetest#1354]
Hi 

As recently lighthouse got updated to 6.0, FMP has been removed from report.html, as currently we are using the FMP value in our project. We need to enable FMP so that it can appear on the report.html. Can you please let me know how to enable FMP field?

![image](https://user-images.githubusercontent.com/24503435/82909012-5775e680-9f86-11ea-9f96-95b2f42d6c0d.png)

**Comment by pmeenan** [comment]
You'd need to file a request with the [lighthouse project](https://github.com/GoogleChrome/lighthouse) since that's their report. That said, it's unlikely to happen since [Lighthouse 6 no longer uses FMP and it is now deprecated](https://web.dev/lighthouse-whats-new-6.0/).

**Comment by KarthikP1306** [comment]
Thanks @pmeenan  .
But in this project, can you please let me know how lighthouse's default-config.js has been used,?
