### ISSUE TITLE
How lighthouse's default-config.js used in this project

### ISSUE THREAD

**Issue by KarthikP1306** [WPO-Foundation/webpagetest#1355]
Hi 

Can you please let me know the place in this project where lighthouse default-config.js
 has been used ?
as i found that path only in the audits_worker_module.js and audits2_worker_module.js files.
#1354

**Comment by pmeenan** [comment]
The lighthouse tests are run from devtools_browser.py. I don't think we explicitly specify a config though and use the defaults from Lighthouse (and will continue to).
