### ISSUE TITLE
Web page test Start render is not giving correct time

### ISSUE THREAD

**Issue by FernandoSolano20** [WPO-Foundation/webpagetest#1361]
Hi!

After some analysis with the team, we notice that start render increase a lot during last days.
Check the following test to see the increment https://webpagetest.org/result/200607_KC_04b558d1e3d7113dfde305a0a6f7d8a9/1/details/#waterfall_view_step1

Speedcurve tools notify that we don't have any blocking resource on our site, and also we check that start render is trigger after DOM Content loaded and LCP metrics. 

So could you help me with this issue?

Thanks

**Comment by pmeenan** [comment]
Start render is correct.  [here](https://www.webpagetest.org/getfile.php?test=200608_5Y_0aa8a6f5c91ba1b13efba9d9e3dbfefe&file=1_video.mp4) is a raw video capture from the phone. The navigation starts when the orange goes away and you can see the page is blank until around the 6 second mark.

My guess is Chrome is reporting invalid times for FCP and LCP, possibly around the time the address bar color is set.

[here](https://www.webpagetest.org/result/200608_5Y_0aa8a6f5c91ba1b13efba9d9e3dbfefe/) is the full test result if you want to compare.

**Comment by pmeenan** [comment]
Don't know if it will help, but filed a Chrome issue for them to fix FCP and LCP reporting: https://bugs.chromium.org/p/chromium/issues/detail?id=1092473

**Comment by FernandoSolano20** [comment]
Thanks for the fast answer.
When I create the issue I don't notice that we are loading https://support.google.com/optimize/answer/7100284, I believe that the issues with the start render is caused by this.

Thanks.

**Comment by pmeenan** [comment]
It's possible (likely?) that that is the cause of the late rendering but Chrome's metrics are still incorrect which is a larger problem for all of the tooling that depends on those (including Lighthouse and Google search).

**Comment by tkadlec** [comment]
I commented on the Chrome ticket as well, but I'm not sure that it is a bug. That snippet puts an opacity of 0 on the page, so technically, a paint event occurs, it's just that we're painting something that you can't see. I could be wrong of course...but that makes sense in my head at least.

@FernandoSolano20 I'd recommend testing how often you're hitting the Optimize timeout period, which fires if Optimize hasn't had a chance to run yet. The default is 3 seconds. You can check to see if the timeout fires (basically, if Optimize was loaded too late for the experiment to run in time) with the following snippet.

```
if ( window.dataLayer.hide ) { 
    return window.dataLayer.hide["GTM-xxxxxxx"]; 
}
```

Then you can track that in SpeedCurve using `lux.addData` and see how frequently, and how significantly, Optimize is hurting your render times.

**Comment by pmeenan** [comment]
@tkadlec My main concern on the Chrome side is if people are tracking FCP and LCP, particularly from RUM to set goals, measure user experience, etc - they won't see the impact of something like this. It will look like the optimize script had no impact on the user experience when in fact it could be huge.

Same goes for Chrome itself optimizing towards FCP/LCP metrics (depending on how common the pattern is).

**Comment by andydavies** [comment]
I’ve seen it happen with Adobe Launch in the wild - took me a while to
understand why the hero image was loaded really early but nothing rendered
for three seconds!

**Comment by tkadlec** [comment]
@pmeenan Yeah, that is a very valid concern. In fact I've worked with a few folks where that exact situation was happening. Just not sure if that's a bug of the paint timings or a limitation of them. :/
