### ISSUE TITLE
Web Vitals on the compare view?

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1364]
Would it be possible to add a graph on the compare view to allow a comparison of the metrics coming back from the Web Vitals scores?

Example test run comparison can be [seen here](https://www.webpagetest.org/video/compare.php?tests=200616_G6_62122e52cc92dbba018f0cf585dbcf10,200616_SJ_ea6078c9cfc67fd566434ccfe699ca8d):

- GOV.UK with cookie banner
- GOV.UK without cookie banner (cookie already set)

CLS changes from 0.007 to 0.316, but can only be seen when clicking into the individual test results.

**Comment by pmeenan** [comment]
Yeah, I mostly didn't add CLS with the other vitals because the scale is so far off that it requires it's own graph.  I'll take a look.
