### ISSUE TITLE
LCP (Largest Contentful Paint) metric of a fresh create-react-app website from WPT testing looks a bit poor.

### ISSUE THREAD

**Issue by anton-karlovskiy** [WPO-Foundation/webpagetest#1365]
I have tried to improve LCP in my project (create-react-app based web app) using various approaches but I did not manage to make improvements to LCP in spite of those approaches.
I used [WPT](https://webpagetest.org/) to see if there was a difference in LCP between approaches in the process.

I tried [PSI](https://developers.google.com/speed/pagespeed/insights/) in order to double check if there wouldn't be difference in LCP between approaches but there was a definite difference (approx. `0.5s`) between 2 approaches while there wasn't in WPT.

I thought of trying a very fresh create-react-app website to see how LCP looked there. The test results were as the following.
1st time:
https://webpagetest.org/result/200612_6M_f3e917c07088b2d12b3039a8e4b55019/

2nd time:
https://webpagetest.org/result/200612_5K_3d3622881dc4c69138e5b45a1504ecd7/

3nd time:
https://webpagetest.org/result/200612_JW_7047b4bdf0e23fdd00e0f7553efe8a94/

In all cases, the LCP of a fresh create-react-app website is `3.5s` on average that I think is relatively much greater than the LCP threshold `2.5s` according to https://web.dev/vitals/.

So I wonder if the LCP calculation logic in WPT might be different than we expect.

Thank you.

**Comment by pmeenan** [comment]
WPT doesn't actively calculate LCP, it reports the timing of when Chrome reports the event.  That said, it also draws a red border around the frame in the filmstrip that corresponds with the LCP time and in the tests you linked it was accurately reporting when the hero image rendered.

You might be better off using "3G Fast" for the connection speed which is what lighthouse uses but if the concern is how long it takes React to reach LCP in a trivial app, it's probably an issue for the react project to investigate.

**Comment by anton-karlovskiy** [comment]
@pmeenan Thank you for your advice. I will close this issue then.
