### ISSUE TITLE
Visualize layout instability (CLS) on comparison page

### ISSUE THREAD

**Issue by rviscomi** [WPO-Foundation/webpagetest#1366]
Related to #1364 

Similar to the visual progress visualizations, I'd like to propose a couple of layout instability visualizations.

The first is the chart of visual progress over time:

![image](https://user-images.githubusercontent.com/1120896/85053127-11b4d400-b168-11ea-9d14-d025fd4095b4.png)

We could have a chart showing the accumulation of layout shift scores over time.

The second is the treatment in the filmstrip:

![image](https://user-images.githubusercontent.com/1120896/85053312-49238080-b168-11ea-8c6b-805a6ca4b3f4.png)

Visual progress is represented two ways: a yellow border when the film cell includes a change in visual progress, and a caption with the current percent of visual progress (corresponding to the graph above).

We could similarly add a border (purple for layout?) when the film cell includes a change in layout instability, and a caption with the current CLS.

I walk through a manual process of aligning CLS custom metric with the WPT filmstrip to visually identify sources of layout instability in [this post](https://dev.to/chromiumdev/fixing-layout-instability-176c). I think it would be helpful to add native annotations to the comparison page to facilitate this kind of debugging process.

**Comment by rviscomi** [comment]
Here's a prototype of the filmstrip proposal:

![image](https://user-images.githubusercontent.com/1120896/85055362-6f96eb00-b16b-11ea-8592-32d76af58a21.png)

_Enhance..._
![image](https://user-images.githubusercontent.com/1120896/85056275-f39da280-b16c-11ea-80c6-e1b74b345d94.png)

The yellow border is added with the `thumbChanged` class on the image element. The prototype adds a `clsChanged` class to the image at 3.1s. Here's the affected CSS:

```css
.thumbChanged {
    box-shadow: 0 0 0 3px #FFC233;
    margin: 3px;
}
.clsChanged {
    box-shadow: 0 0 0 3px #9A7DE7;
    margin: 3px;
}
.thumbChanged.clsChanged {
    outline: dotted 3px #9A7DE7;
    box-shadow: 0 0 0 3px #FFC233;
    margin: 3px;
}
```

There are 3 cases:

- I'm pretty sure every CLS change would also result in a visual change, so the effect would be a striped yellow/purple border.
- But there may be visual changes that are not also CLS changes, so the effect would only be a solid yellow border (current behavior).
- The `.clsChanged` style rule might be overkill if it's impossible to have CLS with no visual change (by definition), but in case there are some edge cases, it would appear as a solid purple border.

The prototype is based on this [filmstrip](https://webpagetest.org/video/compare.php?tests=190918_6E_ef3c166b4a34033171d47e389cf82939-r%3A5-c%3A0&thumbSize=200&ival=100&end=visual) and [this custom metric](https://webpagetest.org/custom_metrics.php?test=190918_6E_ef3c166b4a34033171d47e389cf82939&run=5&cached=0). Here's the JSON data with layout shift entries:

```json
[
  {
    "name": "",
    "entryType": "layout-shift",
    "startTime": 3087.2349999990547,
    "duration": 0,
    "value": 0.3422101449275362,
    "hadRecentInput": false,
    "lastInputTime": 0
  }
]
```

**Comment by pmeenan** [comment]
We already have the raw layout shift events in the traces so no need for a custom metric.  Just added it to the json:

```json
                "LayoutShifts": [
                    {
                        "time": 607,
                        "cumulative_score": 0.087409632299999998,
                        "score": 0.087409632299999998
                    },
                    {
                        "time": 744,
                        "cumulative_score": 0.31337593559999999,
                        "score": 0.2259663033
                    },
                    {
                        "time": 799,
                        "cumulative_score": 0.31407303380000001,
                        "score": 0.00069709820000000001
                    },
                    {
                        "time": 869,
                        "cumulative_score": 0.31554508329999997,
                        "score": 0.0014720495
                    }
                ]
```

That should make it relatively easy to add to the comparison view.  As far as the filmstrip treatment, I'm thinking I might just change the color of the bottom or top border because there are also red frames for LCP and that way it's a little easier to manage the classes.

**Comment by pmeenan** [comment]
Still just on the dev server but the graph is working now.
![Screen Shot 2020-06-18 at 3 12 23 PM](https://user-images.githubusercontent.com/444165/85062340-56e00280-b176-11ea-82c9-5e60421eaa30.png)

**Comment by rviscomi** [comment]
That looks great, thanks for whipping it up so quickly! My only nitpick is that CLS is technically unitless, in reference to "(Viewports)".

**Comment by pmeenan** [comment]
Are you sure about that? I remember hearing at some point that a score of 1 was equivalent to shifting an entire viewport.  I'm happy to remove the legend but if it's accurate it helps understand the scale of the shifts.

**Comment by pmeenan** [comment]
I went with a dotted border of the existing color for layout shifts.  It was hard to see any other colors.

I'm wondering if we want a minimum threshold before flagging though (or maybe it's worth keeping since any shift is bad).  In this case, the last frames shift by 0.00001 or something tiny like that.

![Screen Shot 2020-06-18 at 3 36 10 PM](https://user-images.githubusercontent.com/444165/85064628-d0c5bb00-b179-11ea-93cf-5a94c4d20d92.png)

Sample test: https://www.webpagetest.org/video/compare.php?tests=200616_G6_62122e52cc92dbba018f0cf585dbcf10,200616_SJ_ea6078c9cfc67fd566434ccfe699ca8d

**Comment by pmeenan** [comment]
@rviscomi 
```
The value of a layout shift is the percent of the viewport that moved. So in this example perhaps 10% of the viewport shifted. If another shift of 2% happens later, the page's CLS would be 12%.
```
From your post [here](https://dev.to/chromiumdev/measuring-cumulative-layout-shift-cls-in-webpagetest-5cle).  That means a value of 1 would be a movement of 100% of a viewport moved (or 1 viewport), wouldn't it?

I have it with no units for right now but I think people will understand the scale a lot better if it isn't an opaque score.

**Comment by rviscomi** [comment]
That was my understanding at the time - and it's a helpful way to explain it - but the [canonical docs](https://web.dev/cls/) intentionally omit units. IIRC the point of contention was how multiplying two fractions don't actually equal a percent of the viewport. Not sure if this usage of fractional viewports is any different from % of viewport. I'll check.

Anyway, I love the improvement!

Did you decide not to show the CLS progress caption under the filmstrip? SGTM if so. One compromise to keep the information density low while conveying the data may be to include it in the `title` attribute of the image. For example, `title="$label: $x% visually complete, $y CLS"`.

> I'm wondering if we want a minimum threshold before flagging though (or maybe it's worth keeping since any shift is bad). In this case, the last frames shift by 0.00001 or something tiny like that.

+1. How about >= 0.0001?

**Comment by tkadlec** [comment]
@rviscomi Closing this one since it's been sitting so long and a lot has changed. If there's still something you're hoping to see here, please open a new issue and we can tackle it. :)
