### ISSUE TITLE
iOS "openURL.ipa" is incorrectly signed

### ISSUE THREAD

**Issue by zwri** [WPO-Foundation/webpagetest#137]
The agent's [openURL.ipa](https://github.com/WPO-Foundation/webpagetest/blob/master/lib/ios/openURL/openURL_20130326.ipa) is incorrectly signed with our lab-internal provisioning profile, which means it can't be installed on third-party iOS devices.  It should be re-signed with the public key.

**Comment by pmeenan** [comment]
wont fix.  The old blaze agent is deprecated and iOS testing uses the node.JS agent now.
