### ISSUE TITLE
Earth experience metrics

### ISSUE THREAD

**Issue by gerrymcgovernireland** [WPO-Foundation/webpagetest#1370]
Measuring the energy consumption of a page or element. How much pollution is a particular page causing? Identify energy hog elements that create the most pollution. Identify unnecessary waste, particularly where it has a high energy component. 

Everything digital requires energy and digital is consuming more and more energy. It would be great if we could create a digital that has the lightest possible carbon footprint.

**Comment by pmeenan** [comment]
I don't see how that could be usefully measured on the client side or actionable. It's probably a worthwhile Phd thesis to study the power consumption of the full stack but I'd wager that the data center power consumption for a single request far outweighs the client-side impacts.
