### ISSUE TITLE
Accessing richer TLS information

### ISSUE THREAD

**Issue by lirantal** [WPO-Foundation/webpagetest#1372]
I'm wondering how can we populate the data collected for TLS with richer information.
One item I'm interested in is `tls_cipher_suite`, which is found in the JSON test result file:
![image](https://user-images.githubusercontent.com/316371/87247024-d4d3b880-c459-11ea-9947-aa6cdcde076d.png)

But `4867` is a representation of the cipher suite  using the numeric ENUM instead of the actual full name for it, and using the enum representation isn't as useful as the full name: `TLS_CHACHA20_POLY1305_SHA256`.

Is it possible to pull that information as well?
I can see it pulled in the devtools_parser (https://github.com/WPO-Foundation/wptagent/blob/e590d266d6453cc3c92df122abb46b9cc55d1837/internal/support/devtools_parser.py) but not sure what other variables are available.

P.S.
MS has a reference [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.tlsciphersuite?view=netcore-3.1) but it's not an easy to consume one and

**Comment by pmeenan** [comment]
The securityDetails are a passthrough of what Chrome makes available. I'm hesitant to maintain a separate mapping in the agent until there is enough demand for it and evidence that a separate mapping during analysis won't be just as effective (or that it shouldn't be a feature request of Chrome to have dev tools emit the friendly names). I went down this rabbit hole with the chrome feature flags and now have to maintain a lookup table which needs monthly updating.

**Comment by lirantal** [comment]
@pmeenan I'm specifically referring to whether there is more information from Chrome that we can draw.
Currently I see that the parser uses [these](https://github.com/WPO-Foundation/wptagent/blob/e590d266d6453cc3c92df122abb46b9cc55d1837/internal/support/devtools_parser.py):

![image](https://user-images.githubusercontent.com/316371/87279193-69d4c100-c4ef-11ea-93e6-a6b5122063ba.png)

but I'm wondering if there's maybe `tls_cipher_suite_name` etc that would include that extra information.
I couldn't find a reference to where Chrome makes all of this information available. If you know I'm happy to follow-up on that list and see if there's something useful there for us to use.

**Comment by pmeenan** [comment]
looks like it is already in the securityDetails.cipher (just not at the top-level of the json):

```json
{
securityDetails: {
    certificateId: 0,
    protocol: "TLS 1.2",
    keyExchange: "ECDHE_RSA",
    validTo: 1598465453,
    certificateTransparencyCompliance: "compliant",
    sanList: [
        "agent.webpagetest.org",
        "api.webpagetest.org",
        "cdn.webpagetest.org",
        "dev.webpagetest.org",
        "grafana.webpagetest.org",
        "origin.webpagetest.org",
        "staging.webpagetest.org",
        "static.webpagetest.org",
        "webpagetest.org",
        "www.webpagetest.org"
    ],
    subjectName: "webpagetest.org",
    keyExchangeGroup: "X25519",
    validFrom: 1590689453,
    signedCertificateTimestampList: [
        {
            status: "Verified",
            origin: "Embedded in certificate",
            logDescription: "Let's Encrypt 'Oak2020' log",
            signatureData: "3046022100A623DD0675C47A7BFB2069E7F92ED374EAAA52E5D5001F753C110B49049AA595022100E96B0804CBEB66FF38AD9B6DC14496CA39519FDCFBA386EBD76F0BC86AC4C57B",
            timestamp: 1590693053738,
            hashAlgorithm: "SHA-256",
            logId: "E712F2B0377E1A62FB8EC90C6184F1EA7B37CB561D11265BF3E0F34BF241546E",
            signatureAlgorithm: "ECDSA"
        },
        {
            status: "Verified",
            origin: "Embedded in certificate",
            logDescription: "Google 'Xenon2020' log",
            signatureData: "30460221008764F75FB9FC18A83A8CEACEB46DA76CAF92277234498CF9DD523B2B0C78B1E6022100DEF60276CBFB36BD4C794FF56B59DE94357D30F2461BE41D6D1F372C367F75DC",
            timestamp: 1590693053779,
            hashAlgorithm: "SHA-256",
            logId: "07B75C1BE57D68FFF1B0C61D2315C7BAE6577C5794B76AEEBC613A1A69D3A21C",
            signatureAlgorithm: "ECDSA"
        }
    ],
    cipher: "CHACHA20_POLY1305",
    issuer: "Let's Encrypt Authority X3"
}
}

**Comment by lirantal** [comment]
Have seen that but it's not the full cipher_suite. I'd like to build something that could rate the certificate configuration the way Mozilla's Observatory tool does and they have [this JSON as a guideline](https://ssl-config.mozilla.org/guidelines/5.3.json) for Modern/Intermediate/Old score levels.

The cipher suite there is the more complete notation:
```
            "ciphersuites": [
                "TLS_AES_128_GCM_SHA256",
                "TLS_AES_256_GCM_SHA384",
                "TLS_CHACHA20_POLY1305_SHA256"
            ],
```

Basically, the top level `tls_cipher_suite` corresponds with that long name representation `TLS_CHACHA20_POLY1305_SHA256` but I need a mapping to match it and I was hoping that long name representation is already made available from Chrome somewhere.

**Comment by pmeenan** [comment]
Nope.  What you see in the JSON is everything that Chrome exposes.  Here are the actual docs for the [network events](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-SecurityDetails) and [security events](https://chromedevtools.github.io/devtools-protocol/tot/Security/#type-CertificateSecurityState)

**Comment by lirantal** [comment]
Gotcha. What I can do then is refer to an official list of all the ciphers, which provide a map: https://www.iana.org/assignments/tls-parameters/tls-parameters.xml and map the `tls_cipher_name` hex code into one of the ciphers from that list to find out the full cipher suite name.

Once I have that, I can color the certificate the same way as Mozilla's Observatory does it: 
![image](https://user-images.githubusercontent.com/316371/87728184-2e761300-c7cb-11ea-8ea1-943dab472bdd.png)

And we can note that in the WPT UI as part of the waterfall that shows the yellow lock, maybe we replace it with a different color of a lock to indicate that the certificate details can be improved?
![image](https://user-images.githubusercontent.com/316371/87728415-b52af000-c7cb-11ea-9099-e5d31f434413.png)

How would users know what to fix? Maybe we can add a security tab where the 2nd arrow is and note all the security details we already have about the page? the security headers/JS vulns for this URL and the addition of the certificate information.

WDYT?
