### ISSUE TITLE
Visually Complete reaching 100% twice

### ISSUE THREAD

**Issue by edwincoronado** [WPO-Foundation/webpagetest#1375]
Hello Patrick,

We are hosting internal instances of WPT running 20.01 for both server and agents. We are noticing an issue where Visually Complete reaches 100% then drops back down to something less than 100% then reaches 100% again. This is causing the system to report the wrong number because it uses the first time 100% is reached but the filmstrip will show the 2nd one as well (which is the right one). See the image below for reference:

<img width="310" alt="image002" src="https://user-images.githubusercontent.com/7434954/88688269-c1ae2300-d0be-11ea-939d-07c8a542215b.png">

**Comment by pmeenan** [comment]
It is intentional that it reports the first 100% as visually complete (it always has). Have you looked into what is causing it to drop below and go back up?

**Comment by veerareddyganta** [comment]
is it possible to force it to report last 100% as visually complete?

**Comment by pmeenan** [comment]
Anything is possible with a code change but it doesn't support doing that
currently.
