### ISSUE TITLE
Why TotalBlockingTime/TimeToInteractive/maxFID are missing from the results

### ISSUE THREAD

**Issue by kszarlej** [WPO-Foundation/webpagetest#1376]
Hey!

I am having a bit of trouble understanding the circumstances required to calculate on my private WPT instance following metrics:

* TotalBlockingTIme
* TimeToInteractive
* maxFID

I ran dozens of tests and sometimes those metrics are calculated, sometimes not. Few times TTI and maxFID were in the results and only TBT was missing. I've been playing with minimal test duration but I couldn't make it reliable so that all those three metrics are always in the test result.

I would assume that those metrics must be heavily dependent on page that is being tested but for the exactly same URL sometimes I am getting those metrics and sometimes not. As an example - test of webpagetest.org that is missing all those three metrics https://webpagetest.org/result/200730_DC_ca0057125327ff427a23937aac5eb7a3/

On my private instance the tester is Chrome on Linux (AWS) with Chrome Dev Timeline enabled. Using newest wpt (from master branch)

**Comment by kszarlej** [comment]
The results table

![Zrzut ekranu 2020-07-30 o 16 18 47](https://user-images.githubusercontent.com/16528258/88934030-6c217400-d280-11ea-9a5d-bea3b50a5580.png)

Sometimes like that:

![Zrzut ekranu 2020-07-30 o 16 18 57](https://user-images.githubusercontent.com/16528258/88934050-72afeb80-d280-11ea-9c96-0b0b92a2affc.png)

Notice the additional TBT column in Web Vitals

**Comment by pmeenan** [comment]
Timeline capture needs to be enabled (timeline=1 if you are using the API).

**Comment by pmeenan** [comment]
Nevermind, see you have that enabled already.  Do you see any main thread activity in the waterfall when they aren't reported?

**Comment by kszarlej** [comment]
Hey @pmeenan  thanks for quick answer :) 

Here is a comparison of two tests. Both tests are

* Scheduled from the API using exactly the same command
* Scheduled for the exact same URL
* The second test was made 15 minutes after first test was done.

Results are as follows:

**Test with all the metrics (TimeToInteractive,TotalBlockingTime,maxFID)**
![good1](https://user-images.githubusercontent.com/16528258/89039723-dac70600-d342-11ea-9a69-7dbdf6d1a1a6.png)
![good2](https://user-images.githubusercontent.com/16528258/89039730-ddc1f680-d342-11ea-9c13-a2897563689a.png)

**Test with maxFID and TotalBlockingTime missing**
![bad1](https://user-images.githubusercontent.com/16528258/89040007-51fc9a00-d343-11ea-85e8-43b55f627aca.png)
![bad2](https://user-images.githubusercontent.com/16528258/89040011-54f78a80-d343-11ea-9bbd-266a552e1692.png)

The main thread activity seems very similar, the interactivity as well. I am starting to think that this might be working as designed? If any of the Main Thread Blocked periods(if there are any) are shorter than 50ms then the TotalBlockingTime is not calculated? And thus the FirstInputDelay is also so small that it can be assumed it is close to 0? So lack of those metrics might be a good sign? Is that correct?

**Comment by kszarlej** [comment]
@pmeenan If possible, could you provide some feedback here? :)

**Comment by pmeenan** [comment]
It will take an hour for the agent-side of the change to roll out but after that it should be fixed.  The UI will now correctly show TBT when it is zero (for new tests).  The agent update is needed so it correctly won't show TBT when timeline capture isn't enabled (otherwise it will incorrectly report it as zero)
