### ISSUE TITLE
look up for category type of each domain/Host names? (e.g Advertising, Analytics, CDNs, Social, Developer Utilities)

### ISSUE THREAD

**Issue by AfrouzHojati** [WPO-Foundation/webpagetest#1378]
Host names or Domains are categorized in different categories including _Advertising_, _Analytics,_ _CDNs,_ _Social,_ _Developer Utilities_, _Tag Management_, _Unknown._ Where in code the categories are defined?  and How can I access them?

More, "Company" and "Product" attributes are defined as well for each domain and I need a list or a dataset in which I can look up for a domain name and get the **"Company"**, **"Category"** and **"Product"** values for the domain. How can I access such data?

a list of _CDN_ names can be extracted in:
 https://github.com/WPO-Foundation/wptagent/blob/master/internal/optimization_checks.py#L48 ,
 but what about other types of categories?

**Comment by pmeenan** [comment]
WebPageTest does not define categories for domains.  If you are seeing them you are seeing it in Lighthouse or Request Map (both of which are separate projects).
