### ISSUE TITLE
TimeToInteractive sometimes not recording

### ISSUE THREAD

**Issue by murdrae** [WPO-Foundation/webpagetest#1379]
I'm having an issue where sometimes TimeToInteractive is not showing up in the results.  
Was wondering what could be causing this?

Output example: https://gist.githubusercontent.com/jasonhouzz/10085e399b7cb56ad2254e93cdfe510d/raw/365b1f5dee1e18b5705fb46d2e6bf1aa64ddf112/TimeToInteractive_missing.json

`enable_agent_processing=1` is enabled in settings.ini

**Comment by pmeenan** [comment]
If there isn't 5 seconds of main-thread idle at the end of the test then TTI is likely not possible to calculate from the captured data.  The UI falls back to use "LastInteractive" instead and changes it to "> xxx" to say that it was at least xxx but may be even later.
