### ISSUE TITLE
Add ability to force other Lighthouse audits to run

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1385]
In the JSON results I can see that only the performance audit is being run. This makes perfect sense to me as the site is performance focused after all!

![Screenshot 2020-09-02 at 09 41 21](https://user-images.githubusercontent.com/1223960/91960245-8fb55f80-ed01-11ea-8579-510dc3efebed.png)

I was wondering if there could be some hidden functionality to force other audits to be run as well? I guess this will add time to the tests, hence the addition of it being hidden by default. I was thinking maybe along the lines of a URL parameter (like the bulk testing setting).

## Usecase
I have 260+ service domains I'd like to run an Lighthouse accessibility audit over via [Andy Davies WPT Bulk Tester script](https://github.com/andydavies/WPT-Bulk-Tester).

**Comment by Nooshu** [comment]
Updating ticket for others to reference. A full Lighthouse test is already being run and can be seen in the JSON results under `data.median.firstView.lighthouse.` where `lighthouse.` is the prefix for the results.

**Comment by pmeenan** [comment]
The scores for each audit should be rolled up (in median, etc). data.lighthouse should have the full, raw lighthouse result with all of the audits as well though.  If you just want the scores though it's probably easiest to pull it out of the median section though.
