### ISSUE TITLE
Details skips index.html sometimes (maybe cached)

### ISSUE THREAD

**Issue by jashsayani** [WPO-Foundation/webpagetest#1386]
I ran WebPageTest on google image search and saw this ([test run](https://www.webpagetest.org/result/200902_CP_627ea38bf088e4c404f322bdaa5e8e15/1/details/#waterfall_view_step1)):
![Screen Shot 2020-09-02 at 8 03 53 PM](https://user-images.githubusercontent.com/18684/92066863-c027e880-ed57-11ea-8054-f9769725c5e7.png)

When I re-ran it a few times, I saw assets being loaded but no `index.html` ([test run](https://www.webpagetest.org/result/200903_H7_27d6f67d39bf9ee1b491805a04baa6c5/1/details/#waterfall_view_step1)):
![Screen Shot 2020-09-02 at 8 06 49 PM](https://user-images.githubusercontent.com/18684/92067010-20b72580-ed58-11ea-9c22-3e016941a296.png)

Screenshots look right in both cases, so its loading the site properly, just `index.html` not shown in some traces.

**Comment by pmeenan** [comment]
It's a known problem with iOS 13 that is (hopefully) fixed in iOS 14.  The remote dev tools interface in iOS 13 is racy and doesn't provide a way to attach fast enough to get the beginning of the navigation.

**Comment by jashsayani** [comment]
Has this been fixed with iOS 14?

**Comment by pmeenan** [comment]
Should have been.  Do you still see the issue on any of the devices?
