### ISSUE TITLE
AVIF images colour coded as 'other' rather than an image

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1387]
New format that was only enabled in Chrome 85. It is currently colour coded under the 'other' key in the waterfall rather than as an image. 

![waterfall](https://user-images.githubusercontent.com/1223960/92182565-e7f47a80-ee43-11ea-912a-f521ca7c20f0.png)

Example test can be [found here](https://www.webpagetest.org/result/200903_5H_95f15961c0c2683d967a943ef086f718/1/details/#waterfall_view_step1).

**Comment by pmeenan** [comment]
I'll see if I can sniff the content type but those are being sent with application/octet-stream instead of image/avif.  If you send them with image/avif then it should color correctly (image/* I believe)

**Comment by Nooshu** [comment]
Thanks Pat 👍 

Pages hosted on GH pages so sounds like I need to raise an issue with GitHub to serve AVIF images with the correct MIME type, as I don't believe I have any control over that (annoyingly).

**Comment by pmeenan** [comment]
In the meantime I added .avif to the file extensions for images so if you hard-refresh it should color code correctly

**Comment by Nooshu** [comment]
Yes I see it. Incredibly efficient work as per usual Pat! Thanks! 😄

**Comment by pmeenan** [comment]
It's minor but I also just added agent support for sniffing the avif type from the file header and including them in the image optimization check.

**Comment by Nooshu** [comment]
Do any of the changes push the AVIF files to be classified as images rather than other in the comparison view?
![Screenshot 2020-09-04 at 01 04 10](https://user-images.githubusercontent.com/1223960/92185038-addaa700-ee4a-11ea-94ed-f32685c93267.png)

![Screenshot 2020-09-04 at 01 04 21](https://user-images.githubusercontent.com/1223960/92185022-a0252180-ee4a-11ea-8cd5-858f3c5f6027.png)

Or is that only possible via use of the correct MIME type? Example images taken [from here](https://www.webpagetest.org/video/compare.php?tests=200903_33_04ee0401127bde962711fd99fce7f042-l%3APNG+Images%2C200903_XF_07fe5d22fc13edf3c9bd6baf58aa571b-l%3AWebP+Images%2C200903_5H_95f15961c0c2683d967a943ef086f718-l%3AAVIF+Images&thumbSize=200&ival=500&end=full)

**Comment by pmeenan** [comment]
I think the content sniffing change I just made does: https://www.webpagetest.org/video/compare.php?tests=200903_TxWW_b44e3de2313c64a23962ab064205c30a-r:1-c:0

It'll take an hour to roll out to the agents and only apply to new tests though.

**Comment by Nooshu** [comment]
Good to know, thanks Pat! 👍

**Comment by zeman** [comment]
@Nooshu FYI I just added AVIF to the SpeedCurve content types as well. Ours actually work independently from the WPT content types.

**Comment by Nooshu** [comment]
Excellent, thanks for letting me know @zeman!
