### ISSUE TITLE
Change security headers check from feature policy to permissions policy

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#1389]
To match security headers: https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/

FYI @lirantal

**Comment by lirantal** [comment]
@pmeenan today we don't score for or against a Feature-Policy so we're neutral on it and there's no change to the score on WPT. I definitely think we can update the scores to be more aligned with securityheaders.com but note that Scott hasn't published a formal and up to date scoring table so we'd be doing a guesstimate to figure out scoring there.

I'll hopefully take a stab at this one soon enough.
