### ISSUE TITLE
Archiving failed

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#1395]
Hi Pat,
a couple of days ago our WebPageTest instances stopped to work and I think the reason is that we run out of disk space for the tests. In our setup we should upload all the files to S3 and not keep any tests on our instance (only the log file), but I think something is wrong there. Checking the archive log (/var/www/webpagetest/www/cli/archive.log) I see that we got many errors that looks like:

```
Video 190117_6N_NK.3.0: Failed to archive
Video 190614_7F_6A.3.0: Failed to archive
Video 190710_YP_99.1.0: Failed to archive
Video 190914_3S_cd27ebc6f97415a521c64cbdd0bf1052.1.0: Failed to archive
Video 190914_3S_cd27ebc6f97415a521c64cbdd0bf1052.2.0: Failed to archive
```

I've seen that you did some fixes on the video archiving functionality some days ago but I'm not 100% sure we run the latest code (we do now though). And my guess is that we have had the problem for some time but I missed to see it.

If I try to hit  http://wpt.wmftest.org/cli/archive.php the output looks like this:

```
...
Arc:0, Del:0, Kept:0, Video:150928_65_3A.10.1                            
Arc:0, Del:0, Kept:0, Video:150928_65_3A.2.1                             
Arc:0, Del:0, Kept:0, Video:150928_65_3A.5.0                             
Arc:0, Del:0, Kept:0, Video:150928_65_3A.7.0                             
Arc:0, Del:0, Kept:0, Video:150928_65_3A.9.0                             
Arc:0, Del:0, Kept:0, Video:150928_V5_36.2.0                             
Arc:0, Del:0, Kept:0, Video:150928_V5_36.4.1 
...
```

What's the safest way for me to move forward? I wanna archive the current data we have to S3 and make sure our test can run again.

**Comment by pmeenan** [comment]
Until recently the videos were not archived at all (which is why you have videos from 2015 there).  I added some video archive support which is why it is in the logs now but it wasn't hooked up for s3 yet (and shouldn't be trying - I can take a look and fix that).

I added a new archiving method to post/get to a simple server for both tests and video. I don't think I broke test archiving when I added it but if disk usage went up significantly that might be why (will take a look).

If it ran out because of videos and it has just been building up over 5+ years of videos then it's just unfortunate timing to coincide with the other archiving changes.  Possible but seems unlikely.

**Comment by pmeenan** [comment]
I added support for s3 archiving of videos.  Can you ssh into the system and run a 'df -h' to see overall available disk space and 'df -sh *' from the /var/www/webpagetest/www/results folder to see how much of the disk space is being used by various types of results?

**Comment by soulgalore** [comment]
So the dir structure is by year I guess then? It looks like this:

```
du -hsx -- * | sort -rh | head -10
27G	20
1.1G	video
1.5M	18
332K	16
300K	15
224K	17
52K	01
24K	19
8.0K	zxMlFtU1
8.0K	mx2wdHSG
```

**Comment by soulgalore** [comment]
Ping @dpifke you have better insights what's been changed on our side and maybe can see if there's something on our side or if something changed in WPT?

**Comment by pmeenan** [comment]
Yep, by year with all of the videos separate in the video directory.  Did you verify that the server is out of space with df -h?  30GB of test data shouldn't be enough to knock out a server but I don't know how the instance was allocated.

**Comment by soulgalore** [comment]
Yep it's a 30 GB, its an extra disk just to keep the logs that I setup originally five years ago but there was some problem lately and @dpifke fixed it. I'll look into more tomorrow.

**Comment by pmeenan** [comment]
Ah, in that case it looks like the regular archiving failed.  I'll look closer to make sure it's not something I broke.

**Comment by soulgalore** [comment]
I can see that it stopped working the 10 or 11 of September but I couldn't see a change in WPT that could have caused it at that moment, so my guess its something on our side, let me have a look.

**Comment by soulgalore** [comment]
@pmeenan it correlations pretty good to some changes we did on the server, sorry for not seeing that in the beginning. I'll close the issue for now.
