### ISSUE TITLE
LCP red mark missing on the filmstrip view image export

### ISSUE THREAD

**Issue by jpvincent** [WPO-Foundation/webpagetest#1398]
Hi !
It looks like the red border around the frame that fired the Largest Contentful Paint is missing from the exported filmstrip.
See this comparison : 
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/427625/95975666-bdb8b400-0e16-11eb-945d-9716de4c59cb.png">

At frame 2.0 the UI filmstrip has a red border (Largest Contentful Paint), but on the exported image above, the border stays yellow.

Here is the detail of the test : https://www.webpagetest.org/video/compare.php?tests=201009_DiKJ_d3d03cc2a9635c5e19cde1ec29b64a6b-r%3A1-c%3A0&thumbSize=200&ival=100&end=visual

Not a big deal, but it would help :)

thanks in advance

**Comment by jpvincent** [comment]
In case it helps, here is the full exported image that has been genrated
![filmstrip-94](https://user-images.githubusercontent.com/427625/95976093-57806100-0e17-11eb-9f28-465d27d0b47d.png)

**Comment by pmeenan** [comment]
The red LCP frame should be there new.  The dotted borders for layout shift aren't there and may be quite a bit harder to pull off so I probably won't attempt those.

![Screen Shot 2020-10-14 at 2 08 56 PM](https://user-images.githubusercontent.com/444165/96028183-fb253d80-0e26-11eb-916f-bcdacee7bd3f.png)
