### ISSUE TITLE
Samsung Browser Devtools Connection Error

### ISSUE THREAD

**Issue by kimsangsoo** [WPO-Foundation/webpagetest#1402]
Samsung Browser Version : 12.4

Devtools Connection Error

There is no information in response.

15:57:39.297 - Dev Tools tabs: []
15:57:39.831 - http://localhost:9222 "GET /json HTTP/1.1" 200 5

**Comment by pmeenan** [comment]
What device, Android version and version of Samsung Internet? It appears to be [sort of working](https://www.webpagetest.org/result/201029_DiQ1_7325cfa2edfbcbb4dff7256c2bf882af/) on the Moto G4's on the public instance (though looks like it needs the eula to be manually cleared)

**Comment by kimsangsoo** [comment]
I am using wptagent locally and my device is a Samsung Galaxy Note9. Android version is 9.
