### ISSUE TITLE
Azure CDN not recognized properly

### ISSUE THREAD

**Issue by vladonemo** [WPO-Foundation/webpagetest#1405]
Webpagetest doesn't recognize Azure CDN properly.

For example:
https://fleet.siemens-healthineers.com/favicon.ico

I think that there could be another response headers taken into account, e.g. presence of **x-azure-ref** or **x-azure-ref-originshield** or **x-cache**

**Comment by pmeenan** [comment]
Are you sure that's on a CDN and not just Azure load balancing or serving?  It's somewhere north of 100ms from Washington DC which is unusually high for a CDN.

**Comment by vladonemo** [comment]
disabled CDN for that URI literally just a few seconds ago. Before that, yes, pretty sure it was on CDN.

**Comment by pmeenan** [comment]
If you have any other URLs that are currently active on the CDN that aren't being detected I can take a look.

**Comment by tkadlec** [comment]
This should be taken care of courtesy of https://github.com/WPO-Foundation/wptagent/commit/0014d5ffe4aa8a94869774a8100db3c0e44e36bd
