### ISSUE TITLE
favicon.ico is ugly in dark mode browsers

### ISSUE THREAD

**Issue by jakub-g** [WPO-Foundation/webpagetest#1406]
This is definitely the least urgent issue in the world, but favicon.ico being transparent and without any shadow around the perf indicator makes it look unreadable in dark mode.

![image](https://user-images.githubusercontent.com/1437027/100880342-e2431b00-34ac-11eb-9fc2-d7d48045cb66.png)

I could try to fix it by adding a few non-transparent pixels around the black outline, but I'm wondering if there are some plans to update favicon following the Catchpoint acquisition? Don't want to do useless work.

**Comment by pmeenan** [comment]
I'm sure there will be an actual update at some point but for now I made it non-transparent so it's at least a little better.
