### ISSUE TITLE
Custom UA string broken in some browsers (Advanced -> User Agent String)

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1413]
Testing this setting with a very simple string 'my-custom-ua-string'. I'm getting mixed results:

**Pass**
- iPhone 8 - Pass, UA string changed with PTST still appended - [test](https://www.webpagetest.org/result/201226_DiPE_d9b9593eaaabdc4990fad404af1fd31d/)
- Firefox Stable - Pass, UA string changed with PTST still appended - [test](https://www.webpagetest.org/result/201226_DiYH_b1140daed4e1f4264b21b1be795f100b/)

**Fail**
- Chrome Stable - Fail, UA string untouched - [test](https://www.webpagetest.org/result/201226_DiMB_c29a59126b1c75daa9736b53d873e312/)
- Chrome Beta - Fail, UA string untouched - [test](https://www.webpagetest.org/result/201226_DiE9_56ad3582d0aa6f4ff75a452325de71ac/)
- Chrome Canary - Fail, UA string untouched - [test](https://www.webpagetest.org/result/201226_DiM0_dc5605e02cdd0ddbcf8be67988f9fe21/)
- Edge Stable - Fail, UA string untouched - [test](https://www.webpagetest.org/result/201226_DiMA_130b4ef1d5bc4791bf2c3267c5d2f24f/)
- IE11 - Fail, UA string untouched - [test](https://www.webpagetest.org/result/201226_DiFT_99f08b3fe0998ec1c3304e88b4e7f013/)
- Moto G4 - Fail, UA string untouched - [test](https://www.webpagetest.org/result/201226_Di51_6d3655101793d90926eaac911a8ad50b/)

**Comment by pmeenan** [comment]
Fix for Chrome (and Android) should be rolling out over the next hour.  Edge and IE don't support it though so those won't be able to be fixed.

It's a bit confusing, but if you also check the "Preserve original user agent string" checkbox it will use your custom UA string and not add PTST to the end of it.
