### ISSUE TITLE
'Script includes sensitive data' leaves the `cookie` header in the request headers

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1415]
When this checkbox is check the script can no longer be seen in the results as expected, but sensitive data can still be seen in the request headers as the `cookie` header.

Example test [here](https://www.webpagetest.org/result/201228_DiMY_0dbdb986ed57e6099dd5a7ec318dfda0/1/details/#waterfall_view_step1)

`cookie: sensitive_data=true` can be seen.

Original script:

```
setCookie	https://www.gov.uk/	sensitive_data=true
navigate	https://www.gov.uk/
```

For reference, a test without the checkbox checked can be [seen here](https://www.webpagetest.org/result/201228_DiDS_885728a99fc5d85067c341b1ae2b4a62/)

I believe [this is the function](https://github.com/WPO-Foundation/webpagetest/blob/dd989044201a8d01f6fc3e19a9ece90a63b7f3f0/www/work/workdone.php#L340) that should be removing this header?

**Comment by pmeenan** [comment]
Fix landed and is rolling out over the next hour.
