### ISSUE TITLE
' Discard all HTTP headers' functionality currently missing

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1416]
When checking 'Discard all HTTP headers' there's no difference in the resulting tests (from what I can see).

- [Enabled test](https://www.webpagetest.org/result/201228_DiBF_2ad05ac99cd6899a74a8caede356f0ab/)
- [Disabled test](https://www.webpagetest.org/result/201228_DiZA_1863bd203ee91ce943a4e5325a012cf2/)

**Comment by pmeenan** [comment]
Fix landed and is rolling out over the next hour.
