### ISSUE TITLE
Add '3G Fast' option to the 'Simple Testing' & 'Visual Comparison' tabs

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1418]
Both these tabs have the option dropdown where you can choose a Test Configuration. These include `3G Slow`, `3G Regular`, and `4G`. But `3G Fast` is missing where it is available under the 'Advanced' tab. Had a brief discussion with @pmeenan who mentioned he should add it. Raising a ticket for it to be tracked.

**Comment by pmeenan** [comment]
Looks like there is a config file with the profiles so it was an easy add. I made it the default since it is what Lighthouse and PageSpeed Insights uses (though I expect I'll hear from Alex Russel about it).
