### ISSUE TITLE
Invalid Location over some public instances

### ISSUE THREAD

**Issue by NeverBehave** [WPO-Foundation/webpagetest#1422]
When using location listed in https://www.webpagetest.org/getLocations.php, some of them will return `Invalid Location, please try submitting your test request again.`

## Sample GET request 

`https://www.webpagetest.org/runtest.php?url=example.com&location=Dulles_MotoG4&fvonly=1&private=1&f=json&k={TOKEN}`

## Locations so far known won't work 

- Sydney (Sydney2..4)
- Beijing2

## Note

I have checked the documentation https://github.com/WPO-Foundation/webpagetest-docs/blob/master/dev/api.md but can't really find any stated limitations or restrictions over instances.

**Comment by pmeenan** [comment]
Assuming you are using an API key, they have a restricted set of locations available (locations with more than just one instance so they can handle the additional load of API testing): https://www.webpagetest.org/getLocations.php?k=A&f=html

**Comment by NeverBehave** [comment]
Cool, thanks for the information. Using the link above, I actually find some related thread https://www.webpagetest.org/forums/showthread.php?tid=15722&pid=31640 , should have looked deeper next time :)

Still, I think it would be great if it is listed in the documentation.
