### ISSUE TITLE
test results page responding 500 after changes in TestInfo.php in commit f4cae282f8a3e2ef33698deede3ef5510c2d191d

### ISSUE THREAD

**Issue by chandanpasunoori** [WPO-Foundation/webpagetest#1423]
commit  
Recover multi-step when it isn't reported correctly
f4cae282f8a3e2ef33698deede3ef5510c2d191d
https://github.com/WPO-Foundation/webpagetest/commit/f4cae282f8a3e2ef33698deede3ef5510c2d191d

after this commit results page resulting in 
HTTP/1.1 500 Internal Server Error

specifically at 
```php 
if (preg_match('/^(\d+)_(\d+)_/', basename($file), $matches)) {
```
 in `www/include/TestInfo.php` at 262 line

I removed changes in constructor and its working as expected.
```php 
// Manually build the test run info if it isn't present
    $runs = null;
    if (!isset($testInfo['testinfo']['test_runs'][1]['steps'])) {
      $this->ScanTestSteps($rootDirectory, $runs);
      if (isset($runs)) {
        $testInfo['testinfo']['test_runs'] = $runs;
      }
    }

    if (!isset($testInfo['testinfo']['steps']) || !$testInfo['testinfo']['steps']) {
      if (!isset($runs)) {
        ScanTestSteps($rootDirectory, $runs);
      }
      if (isset($runs)) {
        $testInfo['testinfo']['steps'] = 0;
        foreach($runs as $run) {
          if ($run['steps'] > $testInfo['testinfo']['steps']) {
            $testInfo['testinfo']['steps'] = $run['steps'];
          }
        }
      }
    }```

**Comment by chandanpasunoori** [comment]
@pmeenan  file names in result directory is not matching with regex '/^(\d+)_(\d+)_/'

**Comment by pmeenan** [comment]
Problem was calling ScanTestSteps without $this-> in front of it for the second case.  Fixed in https://github.com/WPO-Foundation/webpagetest/commit/c38709b29cf79e7ca79d31dc19669d792004a833

Sorry about that.

**Comment by chandanpasunoori** [comment]
@pmeenan I have one more question, we deployed server and agent in GCP with scripts provided few months back, when this issue occurred I realised that php files are updated but I don't know how? do we have any auto upgrade configured?

I verified cronjobs but found only this 
```bash
*/5 * * * * curl --silent http://127.0.0.1/work/getwork.php
```

**Comment by pmeenan** [comment]
The GCP scripts set up a server (and agents) that automatically update from the github release branch hourly. Since the agents tend to be ephemeral they always need to pull the latest code when they start up (and install OS/browser updates).

Here is the server update: https://github.com/WPO-Foundation/webpagetest/blob/master/www/cron/hourly.php#L45

If you put a setting in settings.ini "gitupdate=0" then it will turn off the automatic updates (but then you will need to manage updating).

**Comment by chandanpasunoori** [comment]
@pmeenan thanks for info.
