### ISSUE TITLE
Add a view of LCP candidate events

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#1424]
Create a view of the paint events from the json with the raw details of each event (including node information) and a thumbnail of the page at the time of the event.

**Comment by tkadlec** [comment]
Not sure yet how I feel about this, but dropping it here so I don't forget (and maybe to get the creative juices going).

It makes sense (I think) to have the debug info handy in the filmstrip, so I was thinking about some ability to toggle display of the raw details. Ignore the horrible design decisions, but something like this:

![Screen Shot 2021-01-21 at 10 03 18 AM](https://user-images.githubusercontent.com/66536/105378053-0bd91280-5bd1-11eb-9de7-676707f6a4d2.png)

And then, when clicked:

![Screen Shot 2021-01-21 at 10 09 48 AM](https://user-images.githubusercontent.com/66536/105378092-12678a00-5bd1-11eb-8521-b66d17002cad.png)

**Comment by andydavies** [comment]
@tkadlec Are you thinking of adding the nodeInfo etc. when it's present in the results?

**Comment by tkadlec** [comment]
@andydavies Yup! There's typically a lot more information available than that and we'd plan on showing the raw, unfiltered details.
