### ISSUE TITLE
Allow WebP and AVIF image types to be disabled in tests

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1431]
Chrome 88 has just added the setting to disable WebP and AVIF images [via the DevTools](https://developers.google.com/web/updates/2020/11/devtools?utm_source=devtools#emulate-image). Would it be possible to include this as a setting under the 'Chromium' Tab?

**Comment by pmeenan** [comment]
Should be able to get to it later today.  [Here](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDisabledImageTypes) is the dev tools protocol command (for my reference).
