### ISSUE TITLE
google translate in filmstrip

### ISSUE THREAD

**Issue by staabm** [WPO-Foundation/webpagetest#1437]
I am wondering, why I can see a google translate toolbar on the filmstrip images, even though the website we are measuring does not at all contain google translate.

website https://www.kunzmann.de/

example film-strip
https://webpagetest.org/video/compare.php?tests=210216_DiHF_26b975a18b91f5854e9fe6d64ae869e8-r%3A1-c%3A0&thumbSize=600&ival=500&end=visual

example image
https://webpagetest.org/thumbnail.php?test=210216_DiHF_26b975a18b91f5854e9fe6d64ae869e8&fit=400&file=video_1/ms_011162.jpg

![grafik](https://user-images.githubusercontent.com/120441/108063305-4b254280-705b-11eb-8b9f-67e3023b0c2c.png)

**Comment by pmeenan** [comment]
I swear the Chrome team does this just to screw with anyone automating it.

Looks like they [changed the command-line flag](https://bugs.chromium.org/p/chromium/issues/detail?id=770776#c13) to disable the built-in translate feature (again).

I just pushed out an update which should roll out over the next hour.  I'll verify the fix before closing.

**Comment by pmeenan** [comment]
Looks like [that fixed it](https://webpagetest.org/video/compare.php?tests=210216_Di1Q_f4ff90d9354858d2b8dd77e4db5aed93-l%3AAfter%2C210216_DiK1_25764ba1e03b6ec90a0274c20163ad1e-l%3ABefore&thumbSize=200&ival=500&end=visual).  Thanks for the report.
