### ISSUE TITLE
WPT Results Not Showing Uncompressed Size of H2 Server Pushed Assets

### ISSUE THREAD

**Issue by gregorywolf** [WPO-Foundation/webpagetest#1439]
It appears that for assets that are H2 Server Pushed, the uncompressed size of the object is not being tracked. I have run across this now in multiple tests. For assets that are not pushed, you can see the uncompressed size in the Details tab when drilling into the item on the waterfall. This number is then carried over to the Uncompressed column of the Content Breakdown screen. 

The following are three different examples showing this behavior:

Single CSS, server pushed
https://www.webpagetest.org/result/210303_AiAY_c0c9f45809cc698be0f3eb40a9af1f4b/

Single CSS, server pushed
https://webpagetest.org/result/210204_Di8F_8e274acc33db69df97421b73554ef618/

5 CSS assets (only first 3 server pushed)
https://webpagetest.org/result/210303_Ai6P_331fe165551465ed74b9a07e8c0088cd/

**Comment by pmeenan** [comment]
Whew. Think I finally got it sorted: https://dev.webpagetest.org/result/210303_ZiAc3A_b065d83a950823de40b403f4b209c96f/1/breakdown/

Fix should be rolling out over the next hour.

**Comment by Nooshu** [comment]
Can now [see the fix on live](https://www.webpagetest.org/result/210303_Ai6D_bb5fcaa9a501dffe4bb007263200a139/1/breakdown/).

**Comment by gregorywolf** [comment]
Looks great! I just confirmed it is working on my site. Thanks for the quick response!!
