### ISSUE TITLE
WebPageTest doesn't recognize Fastly CDN

### ISSUE THREAD

**Issue by PavelZhuravlev** [WPO-Foundation/webpagetest#1444]
Hello!
Im using Cloudinary service to serve images for my website.

Cloudinary uses **Fastly CDN**  under the hood.
![Снимок экрана 2021-03-09 в 20 41 56](https://user-images.githubusercontent.com/14184094/110521034-ee77ed80-8117-11eb-8299-7528445b1e1b.png)
![Снимок экрана 2021-03-09 в 20 14 46](https://user-images.githubusercontent.com/14184094/110520755-9345fb00-8117-11eb-8ad1-2dafb9fcb7f7.png)

When im trying to test my website using WebPageTest,
results say that my images don't use CDN at all:
![Снимок экрана 2021-03-09 в 20 23 15](https://user-images.githubusercontent.com/14184094/110520739-8c1eed00-8117-11eb-8ffe-a054be71d1fb.png)

**Comment by pmeenan** [comment]
Do you have a link to a test result?  Feel free to send it to me directly (pmeenan@webpagetest.org) if you don't want the URL public.

**Comment by PavelZhuravlev** [comment]
@pmeenan , thanks for reply
Im sending to your email

**Comment by pmeenan** [comment]
Fix should be rolling out over the next hour.

**Comment by PavelZhuravlev** [comment]
@pmeenan , Thank you so much!

**Comment by pmeenan** [comment]
Just verified the fix.  Let me know if it shows up again.

**Comment by ilyazub** [comment]
@pmeenan It still doesn't detect Fastly CDN.

WebPageTest link: https://www.webpagetest.org/performance_optimization.php?test=210323_XiCS_bc9c0b0ff99922d6c66eaa3c11c95fe0&run=2#use_of_cdn

![image](https://user-images.githubusercontent.com/282605/112170410-b7b3d400-8bfb-11eb-9c57-30d9f0f8cae9.png)

Cache headers exist in the response.

```bash
$ curl -I  https://cdn.shopify.com/s/files/1/0257/2733/6499/files/favicon_32x32.png?v=1581424421
HTTP/2 200 
content-type: image/png
cache-control: public, max-age=31557600
expires: Thu, 10 Mar 2022 19:58:11 GMT
last-modified: Wed, 10 Mar 2021 19:58:11 GMT
edge-cache-tag: mime-image/png,source-ShopAssetsBackend,segment2-5,segment4-1470,revision-983402c20a1f0b5ce82cdc3066c35aff33ec041d,cdn-shopify-com-s-files-1-0257-2733-6499-files-favicon-png,shop-25727336499
x-image: generated
access-control-allow-origin: *
timing-allow-origin: *
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
link: <https://cdn.shopify.com/s/files/1/0257/2733/6499/files/favicon_32x32.png>; rel="canonical"
x-request-id: eff0f513f13059a0c58bd449ae9b3816610bcfeca54feffca2e5557aaa8e23e9
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-dc: gcp-us-east1
accept-ranges: bytes
date: Tue, 23 Mar 2021 15:20:55 GMT
server: cache-vie21644-VIE
nel: {"report_to":"network-errors","max_age":600,"failure_fraction":1.0,"success_fraction":0.0}
report-to: {"group":"network-errors","max_age":2592000,"endpoints":[{"url":"https://monorail-edge.shopifycloud.com/v1/reports/nel/20190325/imagery"}]}
x-cdn: Fastly, http2
x-served-by: cache-lga13625-LGA, cache-vie21644-VIE
x-cache: HIT, MISS
x-cache-hits: 1, 0
x-timer: S1616512856.695679,VS0,VE95
vary: Accept
content-length: 284
```

`dig` shows that cdn.shopify.com uses Fastly.

```bash
$ dig +short cdn.shopify.com
cdn.tm.shopifysvc.com.
tls13.shopify.map.fastly.net.
199.232.17.12
```

**Comment by ilyazub** [comment]
A few minutes later `dig` shows that `cdn.shopify.com` uses Akamai and `x-cache` headers are missing in the response :confused: 

```bash
dig +short cdn.shopify.com
cdn.tm.shopifysvc.com.
cdn.shopify.com-v3.edgekey.net.
e11787.dscb.akamaiedge.net.
23.47.208.158
```

```bash
curl -s -I https://cdn.shopify.com/s/files/1/0257/2733/6499/files/favicon_32x32.png?v=1581424421 
HTTP/2 200 
content-type: image/png
content-length: 284
cache-control: public, max-age=31557600
expires: Thu, 10 Mar 2022 19:59:17 GMT
last-modified: Wed, 10 Mar 2021 19:59:17 GMT
accept-ranges: bytes
surrogate-key: mime-image/png source-ShopAssetsBackend segment2-5 segment4-1470 revision-983402c20a1f0b5ce82cdc3066c35aff33ec041d cdn-shopify-com-s-files-1-0257-2733-6499-files-favicon-png shop-25727336499
x-image: generated
access-control-allow-origin: *
timing-allow-origin: *
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
link: <https://cdn.shopify.com/s/files/1/0257/2733/6499/files/favicon_32x32.png>; rel="canonical"
x-request-id: b3d8a0f
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-dc: gcp-us-east1
date: Tue, 23 Mar 2021 15:36:22 GMT
report-to: {"group":"network-errors","max_age":2592000,"endpoints":[{"url":"https://monorail-edge.shopifycloud.com/v1/reports/nel/20190325/imagery"}]}
nel: {"report_to":"network-errors","max_age":600,"failure_fraction":1.0,"success_fraction":0.0}
```

**Comment by pmeenan** [comment]
I'm sure they're using a multi-cdn setup.  If you have tests where it fails to detect any CDN, send them my way and I can look at the headers and IP address of the edge to see what holes there are in the detection (and if there are any reliable headers or CNAME's exposed).

In some cases it is possible to turn off all of the CDN-specific headers and use dedicated IP's and those aren't likely to be able to be detected but these look like they should.
