### ISSUE TITLE
Link on the home page is broken

### ISSUE THREAD

**Issue by justin808** [WPO-Foundation/webpagetest#1445]
The private instance release link is broken.
> If you are looking to install your own instance, I recommend grabbing the latest **private instance release**.

**Comment by pmeenan** [comment]
Where on the home page are you seeing the link (which URL)?

**Comment by yzaki** [comment]
The link https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/README.md
I also can't access the private instance location

**Comment by pmeenan** [comment]
The private instances doc moved to here: https://docs.webpagetest.org/private-instances/

What I'm asking is where you see the broken link because I can't see anything in the current site code that points to the old location.

**Comment by yzaki** [comment]
![Screenshot_20210314_074253](https://user-images.githubusercontent.com/9818043/111056545-2923b200-8499-11eb-979c-284eb67359d6.jpg)

**Comment by yzaki** [comment]
It's under this https://github.com/WPO-Foundation/webpagetest

**Comment by pmeenan** [comment]
Wow, thanks.  I was looking on the actual www.webpagetest.org site.  The project readme looks like it was WAY out of date and still referenced the legacy agents too.
