### ISSUE TITLE
Text is really big on the request pop up in the new UI

### ISSUE THREAD

**Issue by bazzadp** [WPO-Foundation/webpagetest#1456]
![Really large font sizes on Request pop up](https://user-images.githubusercontent.com/10931297/112134913-21fd5200-8bc5-11eb-892d-41af5038bf4e.png)

Means you need a lot of needless scrolling when looking at Request or Response tabs if more than a screenfull.

Looks like it's 16px, which I normally wouldn't have thought was too big but looks really big here (maybe just in comparison to the other, smaller, font sizes behind the pop up?).

**Comment by tkadlec** [comment]
Probably a couple things going on here. First, yeah....the waterfall uses a comparatively smaller font. But we also have a different font stack in place elsewhere on the site (typically Helvetica or Arial) versus here (Verdana). Given Verdana's higher x-height, I suspect that's exaggerating the issue. 

Here's the box as is:

![Screen Shot 2021-03-23 at 9 21 53 AM](https://user-images.githubusercontent.com/66536/112162364-faed5300-8bb9-11eb-9ed0-bb550e4dafcc.png)

And here it is with the font stack updated to match the rest of the site:

![Screen Shot 2021-03-23 at 9 24 30 AM](https://user-images.githubusercontent.com/66536/112162435-0c365f80-8bba-11eb-9989-1ada95f89144.png)

Does that look a bit tighter, @bazzadp? Ideally, we'd avoid going too small here (in fact, we should probably look into bumping the font size ever so slightly on the waterfalls at some point).

**Comment by bazzadp** [comment]
Difficult to tell to be honest, as even my original screenshot doesn't look that bad! You probably think I'm whinging over nothing... 😀

Your suggestion is definitely an improvement as it squeezes two more lines into the same space with no loss in readability IMHO.

I was trying to remember what the old UI looked like (two days ago was such a long time ago! 😁) and dug up this screenshot from @Nooshu 's [guide](https://nooshu.github.io/blog/2019/10/02/how-to-read-a-wpt-waterfall-chart/#horizontal-timings):

![Old pop up](https://user-images.githubusercontent.com/10931297/112163557-102ba700-8be5-11eb-894a-43d26a763b21.png)

So looks like we have the following:

  | Waterfall lines it spans | Content lines it allows in pop up
-- | -- | --
Old site | 23 | 20 or even 21 as blank line at the end?
Old site | 23 | 16 (but lose two due to wrapping, so basically 14)
Suggested | 23 | 16 (and nothing wraps)

So definitely an improvement as get the two extra lines back and so can see more content, but still 4-5 lines short of what we used to have. Not that older is always better, but I wonder would 14px be enough, given the rest of the UI uses 11px or 12px so a jump to 16px does seem quite a jump? Any ideas if that was what it was on the old site?

And we'll leave the em/rem font-size discussion for another day! 😁

**Comment by pmeenan** [comment]
Whoops, @tkadlec and I both looking at the same issue at the same time :).

I shrunk the font a bit, expanded the dialog a bit and also cleaned up the preformatted json "raw details" tab a bit.  Should be able to see most of the details in one view again.

**Comment by pmeenan** [comment]
I now spans ~30 waterfall lines and shows ~23 content lines.

**Comment by bazzadp** [comment]
Good stuff @pmeenan - looks much better!
