### ISSUE TITLE
Start test button at the bottom as well?

### ISSUE THREAD

**Issue by tunetheweb** [WPO-Foundation/webpagetest#1457]
Minor one this, but with the new UI and the Start Test button where it is, next to the URL I find I'm scrolling up and down more than I used to.

So flow is:
1. Enter URL
2. Click on Chrome tab
3. Fill in some options
4. Scroll back up to URL field
5. Click Start Test

I'd almost expect the Start Test button to be at the bottom, after you've changed the options. Maybe for Easy it's better to be near the URL, but for Advanced it makes less sense.

I think the old UI, I was able to reach most of my commonly used options, but with the more spaced out options of the new design it leads to more scrolling.

Any chance of a Start Test button at the bottom as well as next to the URL?

**Comment by kgrz** [comment]
Or perhaps a fixed position summary, containing the URL, connection throttling, and the start button?
