### ISSUE TITLE
All waterfall requests are highlighted in blue

### ISSUE THREAD

**Issue by pablomercadolibre** [WPO-Foundation/webpagetest#1458]
Some tests have all the waterfall requests highlighted in blue(like the image below)

<img width="296" alt="Captura de Pantalla 2021-03-23 a la(s) 18 11 51" src="https://user-images.githubusercontent.com/33631943/112253197-02097500-8c3d-11eb-88f7-289c3c749f2a.png">

Here the test related to the image https://www.webpagetest.org/result/210322_XiWM_33f6da2bcfb4e85915c4a82d0a1e0096/1/details/cached/#step1_request
For this one we don't have a service worker and while the page is not a pure SPA we do listen for history and update the url in some scenarios, e.g a modal for the product description opens or close

And here another example provided in the webperformance slack channel by another user using webpagetest.org itself https://www.webpagetest.org/result/210323_Xi0X_17471b2adbddc0893fbc1dc71e7e4230/1/details/

Let me know if more information is needed,

Thanks!

**Comment by pmeenan** [comment]
Should be fixed now (you may need to shift-reload to refresh an old waterfall in cache if looking at an existing test).
