### ISSUE TITLE
Add ability to hide tests on the "Test History" page.

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1459]
Certain tests I run by mistake when the settings aren't correct. It would be good to be able to hide these tests so they don't add to the noise. I'm also thinking potentially a new checkbox at the top of the page which allows you to show hidden tests?

**Comment by andydavies** [comment]
I'd like the ability to delete the tests "I got wrong" e.g. forgot to configure mobile, chose the wrong location etc. but this would work for me too

**Comment by Nooshu** [comment]
I agree with Andy. Deleting would be be ideal, and also save a tonne of server resources (I guess?). But if that's too complex then a hide feature would work well.

**Comment by tkadlec** [comment]
I want this too for all the same reasons. Let me chat with the team.

**Comment by tkadlec** [comment]
@rik, @Nooshu and @andydavies Could you have a look at the history page? The team added a "hide test" button that should help out here.

![Screen Shot 2021-07-21 at 1 39 02 PM](https://user-images.githubusercontent.com/66536/126542082-85c3a9a8-69d2-49d9-b6b6-34dfd1865763.png)

**Comment by rik** [comment]
Works great!

May I suggest to use a different icon though? The trash icon might let people think the test has been deleted. The slashed eye icon maybe?
