### ISSUE TITLE
'Dirty mark' at the start of the URL field on MacOS Safari

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1460]
There's are small black pixels at the start of the URL field in MacOS Safari - Version 14.0.3 (15610.4.3.1.6, 15610)

Suspect it's the hidden label leaking through but haven't debugged it, doesn't happen on Chrome, or iPad Safari

![Screenshot 2021-03-26 at 12 06 25](https://user-images.githubusercontent.com/427052/112631101-5fb0e380-8e2e-11eb-8c3e-4301fc994486.png)

**Comment by tkadlec** [comment]
Having a hard time reproducing this right now in 14.0.3 (16610.4.3.1.4) :/

![safari-url bar](https://user-images.githubusercontent.com/66536/113929097-3f314380-97b5-11eb-9387-8f4938cdd81d.png)

**Comment by andydavies** [comment]
I can't reproduce any longer

I think the mark is actually the hidden label for the URL field showing through so perhaps some other changes have resolved it?
