### ISSUE TITLE
Issues with either missing or always-zero TBT / TotalBlockingTime / Total Blocking Time

### ISSUE THREAD

**Issue by d19dotca** [WPO-Foundation/webpagetest#1462]
I have noticed that when running tests to any websites via the Los Angeles, CA- M1 Mac Mini location, the Total Blocking Time column under the Core Web Vitals section is consistently a value of 0. It seems to be location-based, with the issue found in the Los Angeles, CA- M1 Mac Mini location, as the reported behaviour is not seen when using California, USA - EC2, for example.

Other times I have seen the column completely missing though, presenting the behaviour reported earlier by others in https://github.com/WPO-Foundation/webpagetest/issues/1376. It seems intermittent in nature, it either shows no column at all for TBT or if it does it's always a value of 0 (zero). However one thing I can confirm is when testing across about 4 different locations, this behaviour only occurs when using the Los Angeles, CA- M1 Mac Mini location.

When it works fine using the California, USA - EC2 location: https://www.webpagetest.org/result/210327_XiFA_125357b042ac8438510982422ba96ea3/
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/8153796/112729933-df50b800-8eeb-11eb-99b7-757d8bcf3ab1.png">

When it shows but a value of (always) 0 when using the Los Angeles, CA- M1 Mac Mini location: https://www.webpagetest.org/result/210327_XiRT_d91e0121d56268474035030801874032/
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/8153796/112729953-f2fc1e80-8eeb-11eb-9137-3e2069242918.png">

When it shows but a value of (always) 0 even using a lower speed where there should certainly be TBT calculated when using the Los Angeles, CA- M1 Mac Mini location: https://www.webpagetest.org/result/210327_Xi02_d791422a81dfc282a49abec8d0c8e784/
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/8153796/112730127-107db800-8eed-11eb-8007-3dd283ccb51c.png">

**Comment by pmeenan** [comment]
The M1 Mac Mini's are significantly faster machines/CPU's than virtually anything else available on WebPageTest.  TBT depends on the CPU performance of the machine it is running on (it is wall clock of the Javascript blocking the main thread).

The vast majority of the WebPageTest locations run slower systems on purpose to target the middle/lower end of the market and expose potential issues.

In Dulles, The Thinkpads are slightly faster than most of the other locations but the M1 Mac Minis in both Dulles and LA are MUCH faster than everything else.

Running it in Safari (in the iOS emulator) would be even faster.  Chrome does not yet have optimizations for the javascript floating point instructions that Apple added to their CPU's a year or two ago and it can make JS performance as much as 40% faster, even compared to their already-screaming-fast performance.

**Comment by d19dotca** [comment]
That makes sense. Thanks for the detailed explanation. 😀
