### ISSUE TITLE
Arrow that displays / hides the test script is malformed

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1466]
Summary and Details tabs in test results have a script section that can be expanded to show the script, or contracted to hide it.

Before the redesign there was an arrow to the right of the Script heading as a affordance but this seems to have become malformed - see attached

<img width="1061" alt="Screenshot 2021-03-29 at 22 11 11" src="https://user-images.githubusercontent.com/427052/112901446-b04d6880-90dc-11eb-92d0-e7b4a52a3a36.png">
<img width="1061" alt="Screenshot 2021-03-29 at 22 11 04" src="https://user-images.githubusercontent.com/427052/112901449-b2172c00-90dc-11eb-984f-0aa141cf0b7d.png">

**Comment by tkadlec** [comment]
Should be much better now.
