### ISSUE TITLE
Move agent's traffic shaping to shell script

### ISSUE THREAD

**Issue by zwri** [WPO-Foundation/webpagetest#147]
The agent's [traffic_shaper.js](
https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/traffic_shaper.js) is currently hard-coded to use ipfw.  Instead, the ipfw-specific details should be factored out into a user-modifiable script.

Current impl:
  1. Agent started with `deviceAddr=1.2.3.4`, gets job with `"bwIn":5000,"bwOut":1000,"latency":28,"plr":0`
  1. [scheduleStart()](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/traffic_shaper.js#L171):
    1. call below "scheduleStop()"
    1. allocate unique pipeIds, e.g. "42" (via socket bind)
    1. `ipfw add 42 pipe 42 ip from any to 1.2.3.4 in`
    1. `ipfw pipe 42 config bw 5000Kbit/s delay 14ms`, ...
  1. Run job iteration
  1. [scheduleStop()](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/traffic_shaper.js#L243):
    1. `ipfw list` then `ifw deiete` any rules/pipes that match our deviceAddr
    1. release pipeIds (via socket close)

The proposed solution is similar to our existing [video_hdmi.js](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/video_hdmi.js) + "capture" script, but with more flexibility to support custom start/stop values:
  1. Add new `--trafficShaper PATH` arg with default value "lib/traffic_shaper/ipfw.sh"
  1. Alias current `--deviceAddr 1.2.3.4` to optional `--trafficShaperArg 1.2.3.4`, where the value must match `"^[^-\s]\S*$"`.
  1. Modify [scheduleStart()](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/traffic_shaper.js#L171) to check if the script file exists, execute the shaper with args `-s myDeviceId start 1.2.3.4 --bwIn 5000 --bwOut 1000 --latency 28 --plr 0`, read and skip lines except an option line matching `"^stop=([^-\s]\S*)$"` (e.g. `stop=foo_1.2.3.4`), and return when it reads a line matching `"^(.*\s)?started\."` (or EOF or timeout after 10 seconds).
  1. Modify [scheduleStop()](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/traffic_shaper.js#L243) to execute the shaper with args `-s myDeviceId stop foo_1.2.3.4`, return when it reads a line matching `"^(.*\s)?stopped\."` (or EOF or timeout after 10 seconds).

One awkward issue is recreating the dynamic, unique pipeId assignment in Bash.  At worst we can loop on `r=$RANDOM; nc -l -k $r`.  I'll have to think about this a bit...

**Comment by pmeenan** [comment]
Done
