### ISSUE TITLE
Validation prevents scripted or bulk tests being submitted unless something is in the URL field

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1471]
It's impossible to submit either a bulk test or a scripted test e.g.

```
navigate https://www.example.com
```

Unless there's a value in the URL field

**Comment by tkadlec** [comment]
Well that's not good! Where are you seeing this? Tested in Safari, Chrome, Firefox and Edge and it seemed to work alright.

![Screen Shot 2021-04-07 at 3 19 14 PM](https://user-images.githubusercontent.com/66536/113928575-9edb1f00-97b4-11eb-8b08-d330832c474b.png)

**Comment by andydavies** [comment]
Safari Version 14.0.3 (15610.4.3.1.6, 15610)

**Using navigate https://www.johnlewis.com**

<img width="1393" alt="Screenshot 2021-04-07 at 22 24 25" src="https://user-images.githubusercontent.com/427052/113937135-9e607980-97f0-11eb-88af-570872f58d00.png">


**Using the bulk tab, and script with navigate %URL%**

<img width="1393" alt="Screenshot 2021-04-07 at 22 23 51" src="https://user-images.githubusercontent.com/427052/113937235-bcc67500-97f0-11eb-81f7-22e62523feef.png">

<img width="1393" alt="Screenshot 2021-04-07 at 22 23 42" src="https://user-images.githubusercontent.com/427052/113937271-c8b23700-97f0-11eb-9aeb-d5d683dc6279.png">

**Comment by andydavies** [comment]
Oddly, I can't find "Fill out this field" in the page or the WPT codebase so perhaps there's something weird going on here!

**Comment by andydavies** [comment]
URL field has a `required` attribute on it which I'm guessing is triggering the message from Safari - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

<img width="1393" alt="Screenshot 2021-04-07 at 22 43 36" src="https://user-images.githubusercontent.com/427052/113938741-ea142280-97f2-11eb-828c-5cec1a453be1.png">

**Comment by tkadlec** [comment]
Yeah, makes sense. Just super confused why I'm able to submit it anyway in all browsers I'm testing. :/

Anyway, we'll fix that.

**Comment by Nooshu** [comment]
Adding a note here that this also prevents submission in FF 87.
