### ISSUE TITLE
Test history is no longer most recent test first

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1472]
Order of the test history page has changed so that the most recent test is a the bottom rather than the top of the list

It can be sorted so most recent is at top but, run date is hidden by default on a 13" MBP, and even when a sort order is chosen it's not remembered

**Comment by pmeenan** [comment]
Thanks.  I noticed the same thing this morning - they're on it!

**Comment by tkadlec** [comment]
@pmeenan @andydavies Has this one been fixed? I'm not seeing it myself anymore

**Comment by andydavies** [comment]
AFAICT it looks fixed to me
