### ISSUE TITLE
Feature Request: Chrome Stable-1 version

### ISSUE THREAD

**Issue by bazzadp** [WPO-Foundation/webpagetest#1476]
It would be nice to have a Chrome -1 version as an option.

For example Chrome is currently v89 but Page Speed Insights are v88 and seeing differences in CLS between the two. I know there were some fixes in Chrome 89 for invisible CLS but would be nice to confirm it's definitely due to that.

There are also more [upcoming changes in CLS](https://web.dev/evolving-cls/) so again being able to directly compre these would be good.

Don't think this needs to be a widespread option but maybe having one location with this available would be good?

**Comment by pmeenan** [comment]
FWIW, there is Stable + 1 and Stable + 2 if you want to compare the upcoming changes to the current CLS.

Maintaining stable - 1 is extremely difficult with Chrome since it auto-updates fairly aggressively and it is also opening the agents up to running with known security vulnerabilities.

**Comment by bazzadp** [comment]
By Stable +1, you mean Beta? And Stable +2 is Canary?

Fair point about -1, finding it particularly annoying with PSI showing different CLS numbers at the moment and very difficult to repeat them (in part because Chrome does update so aggressively as you say!)

**Comment by pmeenan** [comment]
Yes, sorry. Beta and Canary.

In PSI are you seeing the different numbers from the field data or from the lighthouse test?  The CrUX data for PSI has a 28-day rolling window so it's going to lag a bit anyway.

**Comment by bazzadp** [comment]
Nah, was lab. Can't find an example now of course.

Anyway will close this as seems like Chrome-1 will be more effort than it's worth.
