### ISSUE TITLE
Favicons are different between app.webpagest.org and www.webpagetest.org

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1477]
- app.webpagetest.org has the Catchpoint logo as it's favicon
- www.webpagetest.org has the WPT logo as it's favicon
- www.webpagetest.org/chrome/timeline.php?test=... appears to have the old WPT favicon

**Comment by tkadlec** [comment]
Updated on app.webpagetest.org. Will verify on next deploy that timeline view is also good to go, then close.

**Comment by tkadlec** [comment]
All set here so gonna close this.
