### ISSUE TITLE
Add agent video post-processing script

### ISSUE THREAD

**Issue by zwri** [WPO-Foundation/webpagetest#148]
Port the WPT Server's [ProcessAVIVideo PHP code](https://github.com/WPO-Foundation/webpagetest/blob/master/www/video/avi2frames.inc.php) to an optional NodeJS-Agent script.  The script can be in Bash / Python / whatever, maybe even [command-line PHP](http://www.ibm.com/developerworks/library/os-php-command/) (?) :/

If enabled, the agent will upload the post-processed PNG frames instead of the raw AVI (or, optionally, both).

This will have several benefits:
   1. Reduces server-side load and upload size
   1. Allows agent to error-check the frame extraction
   1. Allows user to customize both the capture + processing scripts

The agent currently waits for all the results to upload before starting the next run/job, but this post-processing script could take a while to finish, so instead, the agent should do these post-process/upload actions _in parallel_ with the next run.  As a throttle, when the agent finishes run `i`, it shouldn't start run `i+1` until prior run `i-1`'s results have been fully uploaded (can generalize to `i-k` w/ default `k=1`).

This parallelism will improve the agent job throughput.

**Comment by pmeenan** [comment]
Done.  Agent now runs the stand-alone visualmetrics.py script and does all of the processing on the edge.
