### ISSUE TITLE
Allow multiple tables of data for `graph_page_data.php` when > 1 test ID

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1484]
## Feature Request Summary
When you click 'Plot full results' link you are presented with x number of metrics in a graph, each have an associated table:

![Screenshot 2021-04-16 at 22 41 15](https://user-images.githubusercontent.com/1223960/115087308-d27d1e00-9f05-11eb-8af3-11db389487fc.png)

Unfortunately this table disappears when you pass in multiple test ID's. I can see the point where it is [hard-coded here](https://github.com/WPO-Foundation/webpagetest/blob/c0ce0cfc65a5dfbf26102164a216a7f82830ae81/www/graph_page_data.php#L355). It would be great to have a table for each of the test ID's passed in so you can compare the stats data from each of the test runs against each other. (p25, p75, StdDiv, CV etc)

It may be possible to use the empty cell in the top left of the table to hold the test label / ID so each can be identified.

### What's the motivation or use case for the change/feature?
At the moment I can generate these tables individually my only passing in a single ID, and then comparing them against each other. But it would be useful to have them all listed in a single place. This data give you some great information on the spread of the data from all the runs in each test for every metric.

**Comment by tkadlec** [comment]
Wanna take a peek @Nooshu ?

**Comment by Nooshu** [comment]
Hey @tkadlec,

Yes this looks excellent! Just tested with 5 sets of data as seen in the image below and it works well. Comparing packet loss settings across tests. Thanks!

<img width="956" alt="Screenshot 2021-05-03 at 15 57 48" src="https://user-images.githubusercontent.com/1223960/116893129-84b42580-ac28-11eb-86a3-413534fdb614.png">

**Comment by tkadlec** [comment]
Yay!

**Comment by Nooshu** [comment]
Only thing I've noticed @tkadlec is we've lost the CSS for the statistical analysis tables that are shown below when selected. I modified the CSS in the [PR seen here](https://github.com/WPO-Foundation/webpagetest/pull/1482).

Test URL [here](https://www.webpagetest.org/graph_page_data.php?tests=210329_XiBZ_82b5bf1bae2119591621a677202ecfda-l%3A3PL%2C210329_Xi4A_0679d30b2dc8de471d1cade9f793183c-l%3A2.5PL%2C210329_XiKN_d329ef9e13a07bcd4bbca866777375fb-l%3A1.5PL%2C210329_Xi4C_ad8e2d4857cb143b85748b8e0ec6a8d2-l%3A1PL%2C210329_Xi3T_3e9b78ff5114579915f521df5d10045e-l%3A0PL&medianMetric=LoadTime&fv=1&zero_start=true&control=4)

<img width="439" alt="Screenshot 2021-05-03 at 16 15 10" src="https://user-images.githubusercontent.com/1223960/116895244-e4133500-ac2a-11eb-94bd-641cdb34b65b.png">

<img width="951" alt="Screenshot 2021-05-03 at 16 15 19" src="https://user-images.githubusercontent.com/1223960/116895248-e5dcf880-ac2a-11eb-9758-a4c4c2c72075.png">

**Comment by tkadlec** [comment]
Huh. Indeed we did.

Just pushed the fix for that. Thanks!

**Comment by Nooshu** [comment]
Great, yes I see it now! Thanks @tkadlec 

<img width="958" alt="image" src="https://user-images.githubusercontent.com/1223960/116897402-1e7dd180-ac2d-11eb-892f-73d64a665fff.png">
