### ISSUE TITLE
Force some graphs to start at 0 in the y-axis on the `graph_page_data.php` page

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1485]
## Feature Request Summary
For some of the graphs for the metrics the y-axis looks to autoscale and pick's y-axis values to fit the data. Is it possible to add a setting to force the charts to start from 0, despite what this will do for the scaling.

![Screenshot 2021-04-16 at 23 03 36](https://user-images.githubusercontent.com/1223960/115088545-4ddfcf00-9f08-11eb-8667-20204e037dc8.png)

For example: in the graph above, force it to start from 0.

### What's the motivation or use case for the change/feature?
The autoscaling of the y-axis can sometimes make results look better or worse than they actually are in practice. This setting would allow a better perspective when comparing tests.

**Comment by tkadlec** [comment]
Should be good to go! @Nooshu Can you have a look just to verify?

**Comment by Nooshu** [comment]
Just checked this.

## CLS by default

<img width="703" alt="Screenshot 2021-05-03 at 16 08 53" src="https://user-images.githubusercontent.com/1223960/116894505-0b1d3700-ac2a-11eb-8871-e3b7fa3483ef.png">

## CLS with y-axis zeroed

<img width="678" alt="Screenshot 2021-05-03 at 16 09 13" src="https://user-images.githubusercontent.com/1223960/116894583-2425e800-ac2a-11eb-9696-c9fba2a1dccf.png">

Nice work, thanks @tkadlec!
