### ISSUE TITLE
Send header only to same-origin hosts or allow to specify path

### ISSUE THREAD

**Issue by dhs3000** [WPO-Foundation/webpagetest#1492]
## Feature Request Summary
It would be great to be able to set a header for authentication when using `navigate` in a script.

This might be possible to achieve if I could either specify
* to only sent the header to the same-origin hosts
* a path, similar to `setCookie`

### What's the motivation or use case for the change/feature?
Currently, when using  `setHeader`, this will be sent to all outgoing requests even to those not being the same origin.

* This is not good as it sends "secret" information to other websites
* This breaks when using CORS and one of the hosts uses things like `access-control-expose-headers` / `access-control-allow-origin`

This might be related to issue https://github.com/WPO-Foundation/webpagetest/issues/69 .

**Comment by rik** [comment]
I think this is supported by [`setHeader`](https://docs.webpagetest.org/scripting/#setheader):
```
setHeader Foo: Bar %HOST_REGEX%
```

**Comment by dhs3000** [comment]
Thanks @rik It reads like it could help. Will try it out.

**Comment by josebolos** [comment]
Hi @tkadlec! Thanks for following up on this.

I've been working with @dhs3000 trying to debug this issue. If I'm not mistaken, using any of the following two scripts on webpagetest.org will show the header being applied to all the requests regardless of the filter being specified for `setHeader`:

```
setHeader	X-foo:abc123	%HOST_REGEX%
navigate	https://webpagetest.org/
```

```
setHeader	X-foo:abc123	webpagetest\.org
navigate	https://webpagetest.org/
```

For example, [this test was run with the 1st script](https://webpagetest.org/result/210614_AiDcDV_2be5cbe2bd53e24b58e8cdb5e9304c4b/1/details/#waterfall_view_step1). You can see the `x-foo` header being applied to, for example, request #9 to www.google.com:

![image](https://user-images.githubusercontent.com/1792637/121874821-a4e30400-ccff-11eb-952b-0a5632412f89.png)

I'm not sure if I'm doing something wrong or there's something that I have missed, I would expect the header to be applied only to `webpagetest.org/*` URLs.

**Comment by tkadlec** [comment]
Saw another discussion on this so came back to it. 

Filtering, as it turns out, never got implemented (I'm removing it from the docs). The underlying Chrome Dev Tools protocol applies headers to all requests. To selectively apply them, we would need to do something like request interception, which is going to have an impact on the performance of the page and reduce test accuracy. See https://github.com/WPO-Foundation/wptagent/issues/155

**Comment by tkadlec** [comment]
I'm going to close this one off until something happens in CDT that makes this possible without messing with the integrity of test results. 

Here's the relevant Chrome bug to follow https://bugs.chromium.org/p/chromium/issues/detail?id=1229598
