### ISSUE TITLE
Page alignment weighted to the left

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1493]
This may be intentional, but am flagging as I use WPT on a screen that is ~2,500px wide. The main page layout seems to be heavily weighted to the left hand side.

![Screenshot 2021-05-09 at 00 30 36](https://user-images.githubusercontent.com/1223960/117556252-cdbc0d80-b05e-11eb-8c27-63616151742b.png)

**Comment by pmeenan** [comment]
Looks like @tkadlec fixed it and I just pushed the release.  Should align correctly again.
