### ISSUE TITLE
Highlight render-blocking JS and CSS resources in the waterfall

### ISSUE THREAD

**Issue by fabkrum** [WPO-Foundation/webpagetest#1497]
## Feature Request Summary
In the SpeedCurve waterfall, I like that you can see at one glance which JavaScript and CSS resources are render-blocking (stripe pattern).

![image](https://user-images.githubusercontent.com/21277749/118542006-b19d2800-b752-11eb-8162-20970fb01acc.png)

### What's the motivation or use case for the change/feature?
To be able to optimize the page speed it is important to understand which resources are render-blocking.
Seeing synchronously loaded resources at one glance in the waterfall would save me time as I don't have to check the code.

Seeing this info in the waterfall would also help to explain to my clients where we start optimizing and why.

**Comment by pmeenan** [comment]
We're working with the Chrome team to tag resources that are actually render blocking first before figuring out how best to represent it in the UI.  Right now I'm pretty sure SpeedCurve is using some heuristics about the resources that happened to load before render, wether they are actually blocking or not.

**Comment by tkadlec** [comment]
Chrome's first stab at this had a few issues where it would flag some things as blocking that weren't. They've shipped a fix for that, so I'll have another look and see if it's a bit more accurate now.

**Comment by tkadlec** [comment]
So I took the latest changes in the way Chrome flags render blocking resources for a spin, and it's much more reliable now. (It was misreporting on dynamically injected scripts before.)

The [changes land in v92](https://bugs.chromium.org/p/chromium/issues/detail?id=1198294). Given the misreporting issue, I think we'll hold off on doing anything prominent with the status until closer to that time.

**Comment by tkadlec** [comment]
@fabkrum We're now showing an icon next to all render blocking resources. :) Think this helps a ton.

![render-blocking-icon-waterfall](https://user-images.githubusercontent.com/66536/126372359-689a3268-44ba-4c7b-9013-5df963dbbf54.png)
