### ISSUE TITLE
Track socket errors

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#15]
Add support for tracking socket-level connection errors to wptdriver.  Right now only requests that make it far enough to send the http request out are being tracked.

https://code.google.com/p/webpagetest/issues/detail?id=19

**Comment by orzage** [comment]
+1

It would also be invaluable to see in the connection view all of the sockets that were opened and domain names that were resolved, but not needed/used, especially when using rel=dns-prefetch and rel=preconnect very heavily. Right now, this requires review of the packet capture.
