### ISSUE TITLE
Setting the background and text colours on compare.php no longer works effectively

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1503]
## Description

It used to be possible to use the `bg` and `text` query parameters to set the colours in the comparison page.

But now this no longer works, and produces odd results

### Steps to reproduce

Create a comparison between two tests, and then add `&bg=ffffff&text=000000` to the URL

e.g. https://www.webpagetest.org/video/compare.php?tests=210611_AiDcEX_61d484e7cb56bc323b01956f96a918e5,210611_AiDcWD_93bf82e46066db9346e58b78aa8d76e7&bg=ffffff&text=000000

### Expected result

Background and text colours should change to match the specified parameters

### Actual result

Background doesn't change, but some text does e.g. labels to the left of the filmstrips, link to download and image etc.

**Comment by tkadlec** [comment]
Fixed with c94e6f98
