### ISSUE TITLE
Add up/down ability to waterfall details screen

### ISSUE THREAD

**Issue by tunetheweb** [WPO-Foundation/webpagetest#1505]
## Feature Request Summary
It would be nice to be able to click on a waterfall line, and then press up or down to cycle through the other lines.

i.e. clicking on request 8 would show the details, and press down arrow on keyboard would highlight request 9 with the open details screen updated (on the same tab as was already selected).

### What's the motivation or use case for the change/feature?
Would allow easier comparison of requests (protocol, priority, headers, size...etc.).

**Comment by tkadlec** [comment]
I like this a lot. :) Let me look into it.
