### ISSUE TITLE
Exclude update (and related OCSP) requests from the Firefox waterfall

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/webpagetest#1509]
Examining an unusual font loading issue in Chrome, @andydavies ran the same test in Firefox. Requests 19-21 of this test on Firefox for a 2G connection show the browser trying to update. This pushes the page load time past the 22 second mark, where it looks to be around 13 seconds. 

Test case [here](https://www.webpagetest.org/result/210710_AiDcSV_2e1f24112906f49e8aa27d879701f5cd/1/details/#waterfall_view_step1)

![waterfall](https://user-images.githubusercontent.com/1223960/125275902-7dd02000-e307-11eb-8849-208c6a114494.png)

Is there a way to filter out these update requests from the FF waterfall?

**Comment by pmeenan** [comment]
Updates SHOULD have been blocked and the update URL was also set to "" but Firefox is pretty bad about changing prefs and adding new updates/connections.  I just added to domain to the blocklist (backup to the prefs) so hopefully that will solve it (in an hour after the agents update).

**Comment by pmeenan** [comment]
Looks like it worked: https://www.webpagetest.org/result/210712_AiDcQ6_7a01e3f665eb5470302d82a2e97522ec/

**Comment by Nooshu** [comment]
Awesome, Thanks @pmeenan!
