### ISSUE TITLE
JS error : SelectRequest is not defined

### ISSUE THREAD

**Issue by jpvincent** [WPO-Foundation/webpagetest#1510]
## Description
When clicking on the details of a request in the waterfall, nothing opens. I got the following JS error : `SelectRequest is not defined`

```Uncaught ReferenceError: SelectRequest is not defined
    at HTMLDivElement.onclick (compare.php?tests=21…65a9a38-r:8-c:0:588)
```

### Steps to reproduce
On this test, on Firefox or Chrome : https://www.webpagetest.org/video/compare.php?tests=210715_BiDcS5_275c2f974f60d7401469abf4165a9a38-r:8-c:0
Click on any request in the waterfall, the Details popin does not open and the JS error is throwned.

What is strange is that by looking at the HTML source, I see that the `SelectRequest` is correctly defined underneath. There might be a more global bug preventing the HTML parser to read the inline JS ?

Cheers

**Comment by tkadlec** [comment]
Should be all set now @jpvincent! It was funky, for sure. :) In one of the JSON objects, there was a `script` element referenced and the browser was somehow parsing that oddly, causing it to skip that entire `script` block.

We now base64 encode the object data on the back end, and then decode in JS to avoid this (and potentially other issues).
