### ISSUE TITLE
Redirection of blocking resources should be marked as blocking

### ISSUE THREAD

**Issue by rik** [WPO-Foundation/webpagetest#1511]
https://www.webpagetest.org/result/210720_BiDc46_80bf429713ae69c821edc4dbdd4f7317/1/details/#waterfall_view_step1

![Truncated waterfall](https://user-images.githubusercontent.com/3653/126494081-71250d2b-1732-44c9-84d5-45995e1c750d.png)

## Description
In the linked WPT run, the 302 redirect of request 9 goes to request 20. Therefore request 20 should also be marked as blocking.

**Comment by pmeenan** [comment]
Going to take an hour to roll out to prod but should be fixed:

![Screen Shot 2021-07-21 at 10 54 14 AM](https://user-images.githubusercontent.com/444165/126510241-0745ec5f-af9a-41d0-825f-356acb51fd7f.png)
