### ISSUE TITLE
Ellipses where items are filtered from custom waterfalls are marked with exclamation mark!

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1513]
## Description
When creating a customer waterfall the ellipses that signal omitted requests are marked with an exclamation mark to signify they're not HTTPS

### Steps to reproduce
1. Open https://www.webpagetest.org/customWaterfall.php?test=210726_AiDcNA_6a20411b5e2d8c4fbd2248e6f6a39a5b&run=1&width=930
2. Filter to requests 2 & 3

### Expected result
No markers against the ellipses

### Actual result
Markers against the ellipses signalling they're not HTTPS

### Related issues?
None

![waterfall-26](https://user-images.githubusercontent.com/427052/127147367-22a85517-108f-4d83-8661-d29391d0446b.png)

**Comment by tkadlec** [comment]
Ick. :) Thanks @andydavies! Will get that fixed in a jiffy.

**Comment by tkadlec** [comment]
Much better. :)

![image](https://user-images.githubusercontent.com/66536/127219935-acddfbb3-9c5b-47e9-8125-4c390fd2850b.png)

**Comment by andydavies** [comment]
👍
