### ISSUE TITLE
Traces and timelines of Lighthouse runs cannot be viewed

### ISSUE THREAD

**Issue by patrickhulce** [WPO-Foundation/webpagetest#1515]
## Description
The "View" trace and "View" timeline links at the bottom of Lighthouse reports appear to lead to broken pages.

Stacktrace of timeline failure is

```
Uncaught (in promise) TypeError: Cannot set property length of #<Storage> which has only a getter
    at be.setPreference [as _setCallback] (host.js:1)
    at be.set (common.js:1)
    at Ae._migrateSettingsFromLocalStorage (common.js:1)
    at Ae._updateVersionFrom11To12 (common.js:1)
    at Ae.updateVersion (common.js:1)
    at se._createSettings (main.js:1)
    at se._loaded (main.js:1)
```

Stacktrace of trace failures is
```
Uncaught ReferenceError: tr is not defined
    at trace.php?test=210806_BiDcJF_8a38b078065f00e30f827d6c5a513d56&run=lighthouse:3701
trace.php?test=210806_BiDcJF_8a38b078065f00e30f827d6c5a513d56&run=lighthouse:10513 

Uncaught ReferenceError: Polymer is not defined
    at HTMLDocument.<anonymous> (trace.php?test=210806_BiDcJF_8a38b078065f00e30f827d6c5a513d56&run=lighthouse:10513)
```

### Steps to reproduce

1. Run any URL with Lighthouse.
2. Open the Lighthouse report by clicking on the score.
3. Click "Timeline - View" at the very bottom of the report.

See example https://webpagetest.org/chrome/timeline.php?test=210806_BiDcJF_8a38b078065f00e30f827d6c5a513d56&run=lighthouse

### Expected result
The DevTools timeline of the trace is opened as it can be once downloaded and opened with DevTools

### Actual result
Nothing loads

### Related issues?
#1489 is similar but this isn't CSP issue and I believe "Timeline" should be using the devtools-frontend, not perfetto. It's been awhile since I've opened the trace link, so not sure if it's perfetto yet :)
possibly #1125 ?

**Comment by pmeenan** [comment]
Trace viewer should now open perfetto and appears to work: https://www.webpagetest.org/lighthouse.php?test=210807_BiDc7V_64b632a91c3eb2b279679945ac99880e&run=1

I'm having trouble reproducing the timeline issue though.

**Comment by patrickhulce** [comment]
Aha thanks so much for looking into it! 

The trace link does indeed open for me now. I'm greeted with this bug report ask, but nothing seems broken 👍 

![image](https://user-images.githubusercontent.com/2301202/128899226-e8302b9d-4696-44ff-bfb7-f03473bb3fb8.png)

As for the timeline, it appears to be environment specific. I opened the link in an incognito window and it works just fine 🤔 

Digging in deeper to the stack trace of the exception, it looks like it's failing to migrate my DevTools settings from a previous version in localStorage! Clearing it out did the trick. Perhaps clearing previous settings on load might be a reasonable workaround? I doubt folks configure *too* much about the timeline viewer on WPT 🤷 

![image](https://user-images.githubusercontent.com/2301202/128900257-fca6463a-335b-4467-ad4d-77092dfde001.png)
