### ISSUE TITLE
Could Webpagetest letter grades be made available in JSON output?

### ISSUE THREAD

**Issue by briancoogan** [WPO-Foundation/webpagetest#1517]
## Feature Request Summary
Could Webpagetest letter grades be made available in JSON output?

Currently the user-visible letter grades are not exposed via the JSON return data, and the only way to collect them is to visit the user-readable results page and scrape them from the HTML.  The letter grades are a key part of the webpagetest result and are incredibly useful to the end user, so it makes sense for me as a third party to go to that level of effort to retrieve them for display.

As an aside, one exception to this is the security grade, which is available in the current JSON as:
`                    "securityHeadersGrade": "A+",
(taken from jsonResult.php (see below for URL example) - not sure where that line is in the JSON object hierarchy, sorry)
I can't find the other grades anywhere, though it's entirely possible they've evaded my regex search for "[A-H]+*", and they may be returned as numeric percentages somewhere.  Being an Australian pain in the a**, I prefer not to map percentages to letters because I'm lazy and easily confused and can't work out whether A is 80 or 90, plus the grading system may change over time.

It would be great to have a set of values providing the letter grades, and for them to be re returned somewhere in the JSON output, eg very loosely, something like:
```
grades->firstByteTime = "F"
grades->keepAliveEnabled = "A"
grades->compressTransfer = "A"
grades->compressImages = "A"
grades->cacheStaticContent = "A"
grades->effectiveCDN = "X"  or "Y"  (I guess, to map the current X and check-mark)
```
Grades are currently scraped from results.php page (example URL below) 

**Normal user-friendly results.php results:** https://www.webpagetest.org/results.php?test=210803_AiDcR3_d27b6018f4fa47d63c55a9e6ea384059
**Matching JSON results here:** https://www.webpagetest.org/jsonResult.php?test=210803_AiDcR3_d27b6018f4fa47d63c55a9e6ea384059&pretty=1

### What's the motivation or use case for the change/feature?

Third party software eg WordPress Performance Timeline plugin currently in final stages of development

I'd like to be able to display the letter grades to the user to provide a sense of the webagetest results.  Currently I achieve this by scraping the grades out of the HTML for the user-visible results page (eg: from the results.php output).  Obviously HTML scraping is easily broken over time through minor upgrades to the HTML over time, and I'd love not to have to go there as neither beer, icecream or coffee is involved.

This image provides an idea of how this might be useful that will probably make more sense than a late-night wall of words:

![perftime-example](https://user-images.githubusercontent.com/16713078/128880691-5729e0cd-514c-4f11-ac57-c3908d3099df.jpg)

Tim Kadlec may be able to provide additional perspective on this feature request.

**Comment by pmeenan** [comment]
The scores that support the grades are already in the JSON:

![Screen Shot 2021-08-10 at 10 06 31 AM](https://user-images.githubusercontent.com/444165/128881562-186b6555-7be7-49fa-88a6-a448dd891018.png)

The letter grades are a straight mapping:
90+ = A
80+ = B
70+ = C
60+ = D
< 60 = F

**Comment by pmeenan** [comment]
-1 is N/A (or an old check that is no longer done)

**Comment by tkadlec** [comment]
@briancoogan For the CDN score, anything above an 80 results in an 'X'. Anything above is considered ok. https://github.com/WPO-Foundation/webpagetest/blob/4eed66053db2bdae8caf04904268ed8eb12347a9/www/optimization_detail.inc.php#L129

**Comment by tkadlec** [comment]
Are we all set here @briancoogan ?
