### ISSUE TITLE
Comparison page: Wasted vertical space in sticky mode

### ISSUE THREAD

**Issue by rik** [WPO-Foundation/webpagetest#1518]
## Description
On viewports narrower than 1600px (which is most of them), there is a lot of empty space between "Waterfall opacity" and the slider. This leaves only a tiny space for the waterfall.

I've narrowed the issue down to the use of `float: right` for `#layout`. I've tried a few tiny changes but none of them worked well (one of them prevented clicking on Create Video). I don't feel confident enough to rewrite the CSS to use grid, that would require too much fiddling with all the cases handled by the inline PHP.

### Steps to reproduce
1. Go to any comparison page ([example](https://www.webpagetest.org/video/compare.php?tests=210705_AiDc9N_2374ac4f3cbabf4d9220187c6af3fcd8%2C210705_BiDcWB_ffa6c9d9af5a67a0a4c09b9b4775512d&sticky=1&thumbSize=200&ival=500&end=visual))
2. Enable "Make filmstrip sticky"
3. Make sure your viewport is smaller than 1600px
4. Scroll until the sliders are sticky

### Actual result
![Actual](https://user-images.githubusercontent.com/3653/129447022-6575e39b-c406-4572-b03d-04ba27f35057.png)

### Expected result
![Expected](https://user-images.githubusercontent.com/3653/129447024-8be12cd7-28a1-428f-8294-4398f42fc21a.png)

**Comment by tkadlec** [comment]
Should be a lot better now, @rik. Can you have a look and let me know?

**Comment by rik** [comment]
Oh thanks, it is much better. I tried doing just `clear:both` and discarded it as there was a lot of empty space in the non-sticky case. But if you're ok with it, it's perfect for me :)

**Comment by tkadlec** [comment]
I didn't like all the space, so I did cut a bunch of that out in another commit. :)
