### ISSUE TITLE
Agent results.zip corrupt in ~2% of runs

### ISSUE THREAD

**Issue by zwri** [WPO-Foundation/webpagetest#153]
The NodeJS Agent's [createZip()](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/wpt_client.js#L434) function creates a corrupt zip for about 2% of all runs.

Ideally will be fixed by upgrading our [agent/js/node_modules/node-zip/](https://github.com/WPO-Foundation/webpagetest/tree/master/agent/js/node_modules/node-zip)

Example:

    $ unzip 1_results.zip
    Archive:  1_results.zip
      inflating: 1_devtools.json         
      error:  invalid compressed data to inflate

    $ unzip -v 1_results.zip
    Archive:  1_results.zip
     Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
    --------  ------  ------- ---- ---------- ----- --------  ----
     3263459  Defl:N   219274  93% 2013-11-07 16:06 00d9da80  1_devtools.json
    --------          -------  ---                            -------
     3263459           219274  93%                            1 file

    $ unzip -tq 1_results.zip
      error:  invalid compressed data to inflate 1_devtools.json
    At least one error was detected in FILE.

**Comment by pmeenan** [comment]
Haven't seen this happen in a long time (and a lot has changed with the agent).  Closing.  Re-open if it shows up again.
