### ISSUE TITLE
Include render blocking counts in the test JSON

### ISSUE THREAD

**Issue by tkadlec** [WPO-Foundation/webpagetest#1531]
## Feature Request Summary
Now that we have a reliable render blocking status, we should move a count to a top-level metric in the test JSON.

### What's the motivation or use case for the change/feature?
We visually signal render blocking resources, but for folks consuming results via the API, having an easier to access top-level metric makes a lot of sense.

**Comment by rik** [comment]
Does count mean number of render blocking resources? It would also be interesting to report the cumulative weight of the render blocking resources.

**Comment by tkadlec** [comment]
I was going for number of, yeah. 

What would you use the cumulative weight for?

**Comment by rik** [comment]
I'd use it in conjunction with the count: 1MB over one blocking resource probably has a bigger impact than 100KB over ten resources.

**Comment by tkadlec** [comment]
I'm going to move the weight discussion to another issue so we can ship and close the counts quickly in https://github.com/WPO-Foundation/wptagent/issues/438

**Comment by rik** [comment]
Fair enough. You've closed both issues though. The new one is linked to the count PR. Maybe you meant to rename this one for weights?
