### ISSUE TITLE
Add 'pingback' URL to API

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#154]
Current process for testing via the API follows a pattern of:
1. Submit test
2. Poll for test completion
3. Get results (if test successful)

An alternative might be to allow a pingback URL to be submitted as one of the API parameters and when the test completes the URL gets called with the ID of the test.

Not sure whether this should only apply to privates instances but I can see it speeding up some CI tests.

Will probably take a look at this myself.

**Comment by jayakrishna531** [comment]
hi , do we have any working URL format for pingback?
