### ISSUE TITLE
Provide a DIFF of the HTML source

### ISSUE THREAD

**Issue by tkadlec** [WPO-Foundation/webpagetest#1553]
## Feature Request Summary
It might be nice to see WebPageTest provide a diff of the original HTML source and the modified source (after JS has run).

### What's the motivation or use case for the change/feature?
Sometimes JS does _bad_ things (shocking, I know) or renders a very different DOM or lazy-loads an image...stuff like that. A diff would be a nice way to compare contrast what happens with and without JavaScript, particularly since it's getting harder (maybe not possible at all??) do to much in WebPageTest if we disable javascript (see: #1495 )

[AB#140845](https://dev.azure.com/catchpointsystems/3530e88b-329c-4a68-a776-27327b83ff68/_workitems/edit/140845)

**Comment by scottjehl** [comment]
I love this idea!

**Comment by scottjehl** [comment]
Hey we should've closed this! It's live :)
