### ISSUE TITLE
Lighthouse emulation for desktop sites is currently broken

### ISSUE THREAD

**Issue by rposbo** [WPO-Foundation/webpagetest#1554]
## Description
When choosing to get lighthouse results for desktop runs, WPT passes in `--emulated-form-factor` which is no longer suported in LH version 7; I think this needs to be `formFactor`, according to the "Changes made in v7" LH notes: https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md#changes-made-in-v7

### Steps to reproduce
Choose to run a test for a desktop configuration, tab to "Chromium" and select the lighthouse option.

https://webpagetest.org/result/210927_AiDcEH_0d8a0d38162131dc12a83a9d27971593/

### Expected result
WPT test to complete with a link to a LH test for the same configuration (but with emulated mobile connectivity, I believe)

### Actual result
The WPT "lighthouse score" box is a question mark, clicking this shows an error page:

```
Sorry, Lighthouse had some issues gathering your report on WebPageTest. Please try again or try using Lighthouse through another way

Lighthouse test log:

lighthouse "https://news.bbc.co.uk" --channel wpt --enable-error-reporting --max-wait-for-load 80000 --port 9246 --output html --output json --output-path "/home/ubuntu/wptagent/work/wpt_euw3_instance-10.10.1.205/210927_AiDcEH_0d8a0d38162131dc12a83a9d27971593.1.0/lighthouse.json" --throttling-method provided --save-assets --skip-audits screenshot-thumbnails,final-screenshot --emulated-form-factor desktop --chrome-flags="--user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/94.0.4606.61 Safari/537.36 PTST/210914.204639'"
Runtime error encountered: Invalid emulation flag. Emulation configuration changed in LH 7.0. See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md
Error: Invalid emulation flag. Emulation configuration changed in LH 7.0. See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md
    at assertValidFlags (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config.js:147:11)
    at new Config (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config.js:193:7)
    at generateConfig (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:65:10)
    at lighthouse (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:43:18)
    at runLighthouse (file:///usr/lib/node_modules/lighthouse/lighthouse-cli/run.js:244:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## Related Issues
https://github.com/GoogleChrome/lighthouse/issues/10910

**Comment by tkadlec** [comment]
Thanks @rposbo for a super helpfully detailed issue! :)

Lighthouse's version check, which we used to determine which params to send, is acting funky post v 8.5.0 (https://github.com/GoogleChrome/lighthouse/issues/13129) which was causing us to fallback to the older params.

I removed the version check altogether in https://github.com/WPO-Foundation/wptagent/pull/434 to just use the updated params (Seems fair given that v7 came out last year :) ). Once the test agents update, we should be good to go again.
