### ISSUE TITLE
Allow moving waterfalls in a comparison

### ISSUE THREAD

**Issue by nhoizey** [WPO-Foundation/webpagetest#1592]
I would like to be able to move one or more waterfall(s) in a comparison, to be able to compare them after a similar event happening at a different time.

For example, if I get different TTFB over several runs, I would like to align TTFB of multiple runs to easily compare (with opacity) what happens after this event.

For example on [this comparison](https://webpagetest.org/video/compare.php?tests=211022_AiDc54_6209ba24c13340bf60eea435041f235e-l:Canary-r:2,211022_AiDcRJ_6fa65669b6a6b9a7432fcc99b2fc01f2-l:Stable-r:2&medianMetric=SpeedIndex&bg=000000&text=ffffff), TTFB are 0.687s and 0.849s so I would like to move the longest 162ms left to really compare what happens after that.

[AB#141307](https://dev.azure.com/catchpointsystems/3530e88b-329c-4a68-a776-27327b83ff68/_workitems/edit/141307)

**Comment by scottjehl** [comment]
@nhoizey Thank you! Thinking I'll close as duplicate of #1435. Sound okay?

**Comment by nhoizey** [comment]
@scottjehl yes, it's okay, I close it! 👍
