### ISSUE TITLE
Add IPV6 suport

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#16]
Add support for IPV6 sockets/addresses

https://code.google.com/p/webpagetest/issues/detail?id=21

**Comment by JakeDEvans** [comment]
May I suggest if/when this is added, that the tests are run ipv4 and ipv6 indepentantly, as to show 3rd party services that may not be ipv6 compatible.

**Comment by szepeviktor** [comment]
Are there plans to add an IPv6 checkbox?

**Comment by pmeenan** [comment]
It's not quite that easy:

1 - The agents themselves have to support IPv6
2 - The test location will need to be on an IPv6 network with an IPv6 address (I don't believe any of the current public agents are)
3 - You probably don't want an explicit flag.  A location will be designated as supporting IPv6 but it will be dual-homed.  For those agents (when they exist) it might be possible to dynamically disable IPv4 or 6 for a given test

#1 is mostly what this issue covers and is mostly just a matter of fixing the few locations in the code (particularly around DNS lookups and socket connections) where it only processes IPv4 addresses.

#3 isn't something I have any intention on building myself (at least any time soon).  It could be very risky and if the agent can't successfully re-enable IPv4 it could effectively cut itself off from the server.

**Comment by JakeDEvans** [comment]
I would not want the agent to be dual-stacked, only the central server sending requests to the agents needs to run both protocols.  Many sites are partially IPv6 which the test should show dependent or 3rd party objects.

**Comment by pmeenan** [comment]
It will certainly be possible for private instances.  It will probably be a while before the public instance has any IPv6 locations, at a minimum because Verizon Fios doesn't have IPv6 yet which is what the main server and location use for connectivity.

**Comment by JakeDEvans** [comment]
tunnelbroker.net is free and is what I use on my fios connection.

**Comment by szepeviktor** [comment]
I rent a small (1 core, 1 GB) IPv6-enabled VPS for $3 and use SSH as a SOCKS proxy.
*It is actually faster than my connection directly because of latency reduction.*

**Comment by paulbeachum** [comment]
Any plan to support IPv6 soon? My team runs a private instance and would like to be evaluate speed of sites on IPv6 (dual stack) vs IPv4. Ideally we could opt into IPv6 or IPv4 in the client via a test run parameter; startup parameter used in separate clients would also work. Thanks!

**Comment by pmeenan** [comment]
IPv6 should work with the existing agent as long as the system it is installed on has a working IPv6 stack and the browser also supports it.  I'm not sure how runtime toggling between v4 and v6 would work though - odds are you'd need separate agent instances for v4 and v6 testing.

**Comment by szepeviktor** [comment]
Do you know any of the public instances supporting IPv6?

**Comment by pmeenan** [comment]
No, none of the public instance agents have IPv6 connectivity.

**Comment by paulbeachum** [comment]
Great thank you, will give it a try!
