### ISSUE TITLE
Support Ctrl/Cmd+Enter to submit form in new window

### ISSUE THREAD

**Issue by kevinfarrugia** [WPO-Foundation/webpagetest#1607]
This is a feature request for the front-end (https://webpagetest.org/). Sorry if this is the incorrect repo.

## Feature Request Summary
I would like to ask if it is possible to support Ctrl/Cmd + Enter to submit the form and open the results page in a new window, similarly to how an HTML `form` works natively. Using the mouse (Ctrl/Cmd + click) opens the results page in a new window as expected, while pressing Enter (without Cmd/Ctrl) opens in the current window.

### What's the motivation or use case for the change/feature?
I regularly need to run tests against a few URLs and want to open the results in separate tabs instead of navigating back and forth.

**Comment by tigt** [comment]
I’m having a hard time reproducing this on Mac even with JS disabled, and it might actually be an inconsistency from browsers:

- On MacOS Chrome, <kbd>Shift</kbd>+<kbd>Enter</kbd> can submit the form into a new _window_, but nothing for a new tab. [This seems to be a known Chrome bug](https://superuser.com/questions/693689/chrome-submit-form-in-new-tab-with-keyboard)

- [Firefox has a 23-year-old bug about submitting into new tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=17754), with a prioritization of `firefox-doesn't-want`

Additionally, the relevant JS attached to the form’s `submit` event doesn’t monkey with the usual form submission flow at all, only returning `true` or `false` depending on if the inputs are valid:

<details><summary><code>function ValidateInput(form)</code></summary>

```js
function ValidateInput(form)
{
    if( (form.url.value == "" || form.url.value == "Enter a Website URL") &&
        form.script.value == "" &&
        (form['bulkurls'] == undefined || form.bulkurls.value == "") &&
        (form['bulkfile'] == undefined || form.bulkfile.value == "") )
    {
        alert( "Please enter an URL to test." );
        form.url.focus();
        return false
    }

    if( form.url.value == "Enter a Website URL" )
        form.url.value = "";

    if (form['runs']) {
      var runs = form.runs.value;
      if( runs < 1 || runs > maxRuns )
      {
          alert( "Please select a number of runs between 1 and " + maxRuns + "." );
          form.runs.focus();
          return false
      }
    }

    var date = new Date();
    date.setTime(date.getTime()+(730*24*60*60*1000));
    var expires = "; expires="+date.toGMTString();
    var options = 0;
    if (form['private']) {
      if( form.private.checked )
          options = 1;
    }
    if( form['viewFirst'] && form.viewFirst.checked )
        options = options | 2;
    document.cookie = 'testOptions=' + options + expires + '; path=/';
    if (form['runs']) {
      document.cookie = 'runs=' + runs + expires + '; path=/';
    }

    // save out the selected location and connection information
    try {
      document.cookie = 'cfg=' + $('#connection').val() + expires +  '; path=/';
      document.cookie = 'u=' + $('#bwUp').val() + expires +  '; path=/';
      document.cookie = 'd=' + $('#bwDown').val() + expires +  '; path=/';
      document.cookie = 'l=' + $('#latency').val() + expires +  '; path=/';
      document.cookie = 'p=' + $('#plr').val() + expires +  '; path=/';
    } catch(error) {
    }

    SaveSettings();

    return true;
}
```

</details>

**Comment by kevinfarrugia** [comment]
Yes, you are correct. `Shift` + `Enter` works well for me. Thank you
