### ISSUE TITLE
"experimentSettings" overlay getting overlapped by other elements

### ISSUE THREAD

**Issue by screenspan** [WPO-Foundation/webpagetest#1609]
## Description
In the waterfall chart of a test result, the "experimentSettings" overlay gets overlapped by other elements on the page (z-index).

### Steps to reproduce
1. Using Brave Browser (Version 1.31.87 Chromium: 95.0.4638.54), open up a test results (e.g. https://www.webpagetest.org/result/211105_AiDc4Z_1c53fc65a17892d571bd516e6c283fbc/1/details/#waterfall_view_step1). 
2. Click on a resource in the waterfall chart, click on the "Experiment" tab, then block the selected resource by URL or Domain.

### Expected result
The "experimentSettings" overlay should appear in front of all other elements on the page.

### Actual result
The "experimentSettings" overlay gets overlapped by other elements on the page, e.g.:

![image](https://user-images.githubusercontent.com/19509110/140508096-3c695e0f-1d25-4a26-b443-6cbf1adf1dfc.png)
![image](https://user-images.githubusercontent.com/19509110/140508168-20142f26-4ff3-4b87-95af-b053be38be28.png)
![image](https://user-images.githubusercontent.com/19509110/140508133-82eb8e65-6164-4b52-ac30-dbb5f67944dd.png)

### Related issues?
Any related issues filed already?

**Comment by tkadlec** [comment]
Woof.

Definitely agree the table shouldn't cover it, and that's an easy fix. Question is the request dialog box—I'd lean towards that having the higher z-index, personally. What do you think @screenspan?

**Comment by screenspan** [comment]
Yes @tkadlec, I'd also go for having a higher z-index on the dialog box.

You might wanna define some rules for z-index on the page. I noticed the following z-index values are in use on the page:
200000, 1000, 10001, 10, 3000, 999.

**Comment by tkadlec** [comment]
Should no longer be an issue with the latest updates. Will still need some love for the small-screen view of the experiment settings box, but we'll track that as a separate thing.
