### ISSUE TITLE
Add support for waiting for arbitrary state

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#1657]
Add script commands:

* waitFor xxx
* waitInterval yyy

Every yyy seconds (defaults to 5 seconds to minimize polling overhead), wptagent would run the script provided in xxx and only when it returns true would the step complete. The waitFor state would persist until reset with an empty xxx string.

This will allow for people to implement arbitrary logic for SPA testing to determine when a step is complete (or for pages with dynamic content or videos that may otherwise terminate too early).

**Comment by tkadlec** [comment]
We can close this now, right @pmeenan ?
