### ISSUE TITLE
Unable to parse WordPress version using Wappalyzer detection

### ISSUE THREAD

**Issue by rviscomi** [WPO-Foundation/webpagetest#1667]
Noticed this while querying HTTP Archive. 64% of WordPress pages don't have a version in the Wappalyzer output. However, about half of those pages do have the meta generator containing the WordPress version.

Here's an example test: https://webpagetest.org/result/220121_AiDc6A_099d202c8e0bd1f0e7281fbfb66ffdd8/

In the JSON output, notice that the detected WordPress version is empty:

```js
har.data.runs[1].firstView.detected_apps.WordPress; // ""
```

I also ran this test with a custom metric to emulate Wappalyzer's version detection for WordPress:

```js
[wp_version]
var versionPattern = /^WordPress ([\d\.]+)/;
return document.querySelector('meta[name=generator][content^=WordPress]').getAttribute('content').match(versionPattern)[1];
```

Here's the corresponding markup on the page:

```html
<meta name="generator" content="WordPress 5.8.3">
```

And when I extract the result of that custom metric, I successfully get the WordPress version:

```js
har.data.runs[1].firstView.wp_version; // "5.8.3"
```

Testing the website (https://www.ottawafoodbank.ca/) directly with the Wappalyzer extension for Chrome enabled, it's also correctly detecting the version as "5.8.3".

![image](https://user-images.githubusercontent.com/1120896/150611770-fc757dda-9564-4fd8-aadf-712153673501.png)

So I think there might be something wrong with WebPageTest's implementation of Wappalyzer's version detection.

cc @pmeenan

**Comment by pmeenan** [comment]
Verified the fix: https://webpagetest.org/jsonResult.php?test=220129_BiDcWV_4717722cb429ffc497fe9dc75f41148a&pretty=1

```json
"detected": {
	  "CMS": "WordPress 5.8.3",
	  "Blogs": "WordPress 5.8.3",
	  "Page builders": "Elementor 3.5.4",
	  "Databases": "MySQL",
	  "Programming languages": "PHP",
	  "Video players": "YouTube",
	  "JavaScript frameworks": "GSAP 2.1.3",
	  "WordPress themes": "Hello Elementor 2.4.1",
	  "SEO": "Yoast SEO 17.9",
	  "WordPress plugins": "Yoast SEO 17.9,WP Rocket,Google Tag Manager for WordPress 1.14.2,Gravity Forms 2.5.16",
	  "Caching": "WP Rocket",
	  "Analytics": "Pinterest Conversion Tag,Twitter Analytics,Google Analytics,Google Ads Conversion Tracking,Facebook Pixel 2.9.51",
	  "JavaScript libraries": "jQuery UI 1.12.1,core-js 3.11.0,jQuery Migrate 3.3.2,jQuery 3.6.0",
	  "Advertising": "Twitter Ads,Microsoft Advertising",
	  "Widgets": "Twitter,Facebook",
	  "Security": "reCAPTCHA",
	  "PaaS": "Kinsta",
	  "Hosting": "Kinsta",
	  "Tag managers": "Google Tag Manager",
	  "Font scripts": "Google Font API,Font Awesome",
	  "CDN": "cdnjs,Cloudflare",
	  "Miscellaneous": "Gravity Forms 2.5.16,Swiper Slider"
	},
```
