### ISSUE TITLE
WPT new design breaks bookmarklets for quick access

### ISSUE THREAD

**Issue by deltaview** [WPO-Foundation/webpagetest#1682]
## Description
Apparantly, the new WPT design breaks simple bookmarklets, and extensions like [this ](https://chrome.google.com/webstore/detail/webpagetest/jhbepelanbbipbinkkjcadbjjinjmiec) and [this](https://chrome.google.com/webstore/detail/sitetools/hkpidmfcndknemmdpdeafbbnmenlpdna), which enable users to quickly open WPT test page for the current tab URL. This was working smoothly earlier.

### Steps to reproduce
Open this URL <https://www.webpagetest.org/?url=https%3A%2F%2Fnews.ycombinator.com%2F>, which should pre-populate the URL input box with the provided `url` parameter on the WPT site, but it fails.

#### Why this is useful
This feature along with option for more parameters for settings like CWV etc., would help users to quickly open WPT site using any booklmarklet or browser extensions.

**Comment by scottjehl** [comment]
Thank you for filing. We'll give this a look! I'm sure we'll be able to fix it up.
