### ISSUE TITLE
Cannot quickly see connection speed on results page in new design

### ISSUE THREAD

**Issue by DamonHD** [WPO-Foundation/webpagetest#1687]
## Description
Especially if I'm trying different locations or connection speeds, one of the first things that I used to check top left was the speed of the current run, now I'm not seeing it.  Maybe I'm just being silly!

### Steps to reproduce
Here is an example run.
https://www.webpagetest.org/result/220127_AiDcR7_ef656996f186f30d6747d3bcf7138e97/1/details/#waterfall_view_step1
I see on closer inspection an LTE marker.  Maybe make that hoverable or clickable for connection characteristics (latency, speed).

### Expected result
Those numeric connection metrics to be easily visible.

### Actual result
A non-obvious (to me!) label.  I had to go back to the home page to look up the parameters when I was confused by 'Native' not in fact being as fast as I expected (eg not as fast as LTE).

### Related issues?
Otherwise, good design tweak, thank you.  And thank you for WPT in general!

**Comment by scottjehl** [comment]
Hi there! Nice test run. Thanks for the feedback.

As you mentioned, in the new design that there's a consistent header on every result page (and across all views of that result as well, such as the filmstrip). On any of these pages, the information about the test conditions can be found at the top:
![image](https://user-images.githubusercontent.com/214783/151448275-6d3bce14-b585-44e8-8baf-4501dbdfc9a6.png)

I think your point is good that we can and should surface more info here. We'll likely aim to place it in the MORE menu or even on hover as you mentioned as well. Thanks

**Comment by scottjehl** [comment]
You should find more information in that strip as of the last few days. And browser version is in there now as well.
![image](https://user-images.githubusercontent.com/214783/152597151-942214c8-cc97-4a2d-ad9e-c1b252a63daa.png)

**Comment by DamonHD** [comment]
Thank you: I'll go and take a look!

Rgds

Damon
