### ISSUE TITLE
Add support to specify & install browser app

### ISSUE THREAD

**Issue by zwri** [WPO-Foundation/webpagetest#170]
Allow job to specify which browser to use ("chrome_dev 32.1").  This will improve device reuse between location pools, e.g. instead of separate locations for:
  * My_Nexus4_Chrome32
  * My_Nexus4_Chrome33
we'd simply have "My_Nexus4".

Will require both server-side and agent-side mods:

**WPT Server**
Add job field to select app (APK for Android, IPA for iOS), e.g.:
  *  Chrome_43.21.apk
  *  Chrome_dev_32.1.apk
  *  ...

Initial impl can list these in the locations.ini, provide UI drop-down, and assume we've manually copied the matching files to a served path, e.g. http://www.webpagetest.org/app/

Advanced impl can allow user upload of APKs, optionally shared between locations or on a per-job basis -- all TBD, esp given security concerns.

Some HDMI-enabled devices (e.g. Droid Razrs) require a modified APK to set the screen rotation from landscape-mode to portrait-mode.  Arguably this is either the user's responsibility (i.e. the APK should be pre-modified) or the WPT server/agent's responsibility; for the initial impl, let's assume the APK is pre-modified.

**NodeJS Agent**
Download app file from WPT server.  The agent can (& should) keep a cache, assuming it verifies the MD5 sum match (either specified as "job.app_md5" field or via HTTP HEAD for "Content-MD5:" header)

Install app on device -- this is already partially supported in [browser_android_chrome](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/browser_android_chrome.js#L208).
Initial impl can always re-install app on first run of job; we can later make this a job option.

**Comment by pmeenan** [comment]
There is also now UI for uploading custom builds.  Closing.
