### ISSUE TITLE
Add other useful social media WPT accounts to site footer

### ISSUE THREAD

**Issue by scottjehl** [WPO-Foundation/webpagetest#1711]
![image](https://user-images.githubusercontent.com/214783/151910107-f4f678da-90f2-4d4d-8d4d-3ce6a7609e9c.png)

**Comment by jeenamerina** [comment]
Hi Scott, we have updated the LinkedIn Page. Could you add the LinkedIn icon and link here: www.linkedin.com/company/webpagetest/
