### ISSUE TITLE
Test label is not shown on details page

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#1730]
## Description
Test label is no longer visible in the header of the details page which mostly makes it impossible to distinguish one test from another.

Label text is in HTML inside of `<details class="heading_details">` which is hidden using CSS:
```
.heading_details {
    font-size: 0.875em;
    display: none;
    /* TODO TODO */
}
```
Please do the TODO ;)

### Steps to reproduce
Run a test with a label (bottom of the first panel of advanced settings), observe details page, fail to find the label text on the page

### Expected result
Label is visible next to the rest of the identifying information.

### Actual result
Label is not visible
<img width="1024" alt="2022-02-03_23-29-38" src="https://user-images.githubusercontent.com/38076/152472679-3cebea32-de09-4a01-b00c-473d5692c85b.png">

**Comment by scottjehl** [comment]
Thanks! Looks like we'd missed this one near the end. I think we could swap out the mobile/desktop labels when there's a custom one, but we'll try some things to get it in all results headers.
