### ISSUE TITLE
CSV files are missing from the Export Menu

### ISSUE THREAD

**Issue by paulcalvano** [WPO-Foundation/webpagetest#1739]
In the Export Menu there are currently options for downloading JSON, Test Logs and HAR files. In the past there was also the ability to download CSV files.  While those links are not present in the current UI, the csv.php script still exists and works.

![image](https://user-images.githubusercontent.com/7459458/152615902-1531b408-afad-4566-a886-b178c7749e05.png)

For example, if I wanted the CSV files for the test: https://webpagetest.org/result/220203_AiDcNG_ffcdea171c3bb84320fdb02c95bb226c/

Then I can download 
https://webpagetest.org/csv.php?test=220203_AiDcNG_ffcdea171c3bb84320fdb02c95bb226c for the page summary
amd https://webpagetest.org/csv.php?test=220203_AiDcNG_ffcdea171c3bb84320fdb02c95bb226c&requests=1 for the request summary.

**Comment by scottjehl** [comment]
Thanks Paul! Good find. Interesting, I didn't think we touched that menu HTML. We'll get a fix up.
