### ISSUE TITLE
Display "Total Connection Time" in Request Details Modal

### ISSUE THREAD

**Issue by screenspan** [WPO-Foundation/webpagetest#1755]
## Feature Request Summary
I'd like to see the "Total Connection Time" (DNS Lookup + Initial Connection + SSL Negotiation) in the Request Details Modal to more quickly figure out what might be saved by moving a resource to an open connection.

<img width="470" alt="Screen Shot 2022-02-16 at 20 19 15" src="https://user-images.githubusercontent.com/19509110/154340686-394ce643-cd6b-440a-b2ec-40f3d6e1bdeb.png">
<img width="503" alt="Screen Shot 2022-02-16 at 20 21 58" src="https://user-images.githubusercontent.com/19509110/154340705-f038b806-ca90-4cf0-84b0-55a6fef09f96.png">

### What's the motivation or use case for the change/feature?
I often come across (very often 3P) requests that incur extra connection costs. It would be helpful to quickly see just how long the connection took to establish.

**Comment by tkadlec** [comment]
File this one under "things that have annoyed Tim and yet it never crossed his mind to just fix it".

Good idea. :) We can do this.

**Comment by screenspan** [comment]
Awesome! Thanks a lot!

**Comment by tkadlec** [comment]
Thanks for filling! :)
