### ISSUE TITLE
Resources with defer attribute shown as render blocking in waterfall view

### ISSUE THREAD

**Issue by 25prathamesh** [WPO-Foundation/webpagetest#1807]
HI 

I am facing this issue for some tests.  I have javascript resources link tags in my initial HTML, all JS resources have defer attribute. but webpagetest shows them as render-blocking resources (orange cross icon ). The site is developed in NextJs 11 (SSR) framework

Site URL   - https://www.healthkart.com/  , platform - Desktop  

Test run date - DATE: 11/04/2022, 13:35:38 IST 
Webpage test URL - https://webpagetest.org/video/compare.php?tests=220411_AiDcMM_5NZ-r:1-c:0
Request numbers 7 -12 & 25-37 have defer attribute still shown as blocking 
Same JS is still on-site you can check the view source of the site 

It's not happening always today I did similar tests but the same resources are not render-blocking which is correct behavior 
Test run date - 22/04/2022, 19:17:49
 Webpage test URL - https://www.webpagetest.org/result/220422_AiDcY6_ASK/1/details/#waterfall_view_step1

**Comment by 25prathamesh** [comment]
Webpagetest Twitter handles informed this is chrome issue
https://twitter.com/RealWebPageTest/status/1517505734296100865

**Comment by tkadlec** [comment]
Looks like it's fixed in Chrome now (https://chromium-review.googlesource.com/c/chromium/src/+/3596328) and will roll out in version 103. Will keep this open until that happens so we can confirm.
