### ISSUE TITLE
Paid account for quicker tests

### ISSUE THREAD

**Issue by ebizindia** [WPO-Foundation/webpagetest#1822]
## Feature Request Summary
Our company offers **Page Speed Optimisation as a service**. While working on client sites, I need to run tests several times to see the impact of changes that we are making. At times, the tests take a long time to run as there is a queue in some data centres.

Is it possible to have a **paid account (like the API service)** so that we can get our tests run sooner instead of waiting in a queue?

### What's the motivation or use case for the change/feature?
This service addition will add to your revenue as well as allow us to run tests quicker rather than waste time waiting in a queue.

Thanks for your consideration.

**Comment by tkadlec** [comment]
@ebizindia Thanks for suggesting this. Definitely stay tuned. :)

In the meantime, are these tests you could run via the API to help with the queuing? Or is the UI the better fit for you?

**Comment by ebizindia** [comment]
I am more comfortable with the UI :)

I can sign-up for the API if that helps my tests launched through the UI.

**Comment by ebizindia** [comment]
Thanks for a great update. Struggling with a tech problem in upgrading the account. However, this should be sorted out soon.

**Comment by ebizindia** [comment]
Cheers!
