### ISSUE TITLE
Provide a "Upgrade" button in My Account

### ISSUE THREAD

**Issue by ebizindia** [WPO-Foundation/webpagetest#1942]
## Feature Request Summary
A large number of FREE account users will like to upgrade their accounts. It will be helpful to have an Upgrade button as a CTA in the "My Account" section.

### What's the motivation or use case for the change/feature?
When one wants to upgrade the account from FREE to paid, it is very difficult to find the option which will enable one to do so. An easily visible option should increase the conversion rate.

**Comment by jefflembeck** [comment]
Noting: This is a bug.

We're working out the logic for why this doesn't exist for some users. Expecting a fix by early next week.

**Comment by ebizindia** [comment]
Thanks. I have been able to upgrade my account to Pro mode.
