### ISSUE TITLE
Fonts are loaded from externally-requested CSS when preloaded

### ISSUE THREAD

**Issue by kevinfarrugia** [WPO-Foundation/webpagetest#1946]
## Description
> 2 fonts are loaded from externally-requested CSS
> When font-face definitions are in external CSS files, there are two steps involved in loading them: fetching the css, then fetching the fonts. Moving font-face rules into HTML can help fonts be discovered and downloaded faster.

WPT is reporting the above when there is a 301 redirect. I do not think this is correct as the fonts are preloaded following the 301 redirect.

### Steps to reproduce
Reported (w/ redirect): https://www.webpagetest.org/result/220602_AiDc9J_9EZ/2/experiments
Not reported (w/o redirect): https://www.webpagetest.org/result/220602_BiDcJ7_9HF/

### Expected result
- If they are already preloaded, then it should not recommend anything.
- It could also recommend to preload if the fonts are not preloaded.

### Actual result
Recommends that font-face rules are inlined into HTML.

_Sorry for the many tickets, I'm enjoying this feature._

**Comment by tkadlec** [comment]
Thanks for the detailed info @kevinfarrugia—the redirect was indeed tripping it up. Fixed that now!

And don't apologize for the tickets—we _love_ getting good, detailed, helpful tickets and I'm glad to hear you're enjoying the feature!
