### ISSUE TITLE
Lazy-loaded images being incorrectly reported as in viewport

### ISSUE THREAD

**Issue by tunetheweb** [WPO-Foundation/webpagetest#1947]
## Description
Images loaded at the bottom of the page with `loading=lazy` are incorrectly flagged as being in viewport and an incorrect suggestion is given suggesting removing the `loading=lazy` attribute.

### Steps to reproduce
Run a webpage test on mobile on https://almanac.httparchive.org/en/2021/third-parties

Example test:
https://www.webpagetest.org/result/220602_BiDcSX_9K1/1/experiments/#Quick

### Expected result
Web mention avatars loaded at bottom of the page are recognised as not in the viewport so correct to lazy load them so not opportunity flagged.

### Actual result
Web mention avatars are incorrectly flagged as in view port:

![511E0065-834D-48AF-979F-D287A424DE0B](https://user-images.githubusercontent.com/10931297/171619659-50600a3c-fb9f-44d6-965f-3f8be1911f8f.jpeg)

### Related issues?
Couldn’t see any.

**Comment by ebizindia** [comment]
I have also received a similar error. A footer logo that is way down got an error "Do not lazyload an image in the viewport".

**Comment by erunyon** [comment]
I get the same on this run: https://www.webpagetest.org/result/220602_BiDcQN_AFK/1/experiments/

The two images being reported are more than half-way down the page, one in the footer.

**Comment by ozcoder** [comment]
Me too.
**Images within the initial viewport are being lazy-loaded.**
https://www.webpagetest.org/result/220602_AiDc2S_AKG/1/experiments/

The images mentioned are not seen, even with the layout shift problem we have with the LCP banners.

**Comment by tkadlec** [comment]
Thanks @ozcoder, @tunetheweb and @erunyon. Should be fixed now!

All three tests now drop to zero critical images being lazily loaded. 
https://www.webpagetest.org/result/220602_AiDcR3_D0P/3/experiments/#Quick & https://www.webpagetest.org/result/220602_AiDc34_D0F/1/experiments/#Quick
https://www.webpagetest.org/result/220602_BiDcMZ_CXE/2/experiments/#Quick
