### ISSUE TITLE
Once my test has run instead of giving me the results, it brings me to a blank page

### ISSUE THREAD

**Issue by apalysPSC** [WPO-Foundation/webpagetest#1950]
## Description
I am trying to test my sites core web vitals. I change the test selection to 'Core Web Vitals', I enter my sites URL, press test. Wait for the other tests to finish, runs through the test as normal. Once the test is finished, instead of bringing me to the common screen of the results, it is a blank screen with only the WPT header. I have used this site for a long time and this has never happened, but it seems to be happening anytime I change the URL to something different as well. I even cleared my browser history- nothing.

### Steps to reproduce
change the test selection to 'Core Web Vitals', I enter my sites URL, press test

### Expected result
should give the results to my web test (as it has every other time)

image of what the screen looks like:
![image](https://user-images.githubusercontent.com/81984132/171630279-7bdba5a7-e84b-4f41-af62-853915fbd6e4.png)

**Comment by apalysPSC** [comment]
Not sure where exactly to find the test ID... here's the URL though https://www.webpagetest.org/result/220602_AiDcHY_AZW/?view=webvitals

**Comment by tkadlec** [comment]
Thanks @apalysPSC! Super helpful context! It was indeed something amiss with that particular section. Got it fixed now!
