### ISSUE TITLE
Lazyloads images inside the viewport when requesting for those outside

### ISSUE THREAD

**Issue by ebizindia** [WPO-Foundation/webpagetest#1952]
## Description
I asked to lazyload images outside the viewport but it lazyloaded the images inside it.

### Steps to reproduce
1. Run a test on a site with lots of images.
2. In experiments, ask to lazyload images outside the viewport.
3. it lazyloads the ones inside. Says that on the description too.
4. 
### Expected result
The images outside the viewports should have been lazyloaded.

### Actual result
Those inside the viewport got loazyloaded.
See this: https://www.webpagetest.org/result/220602_BiDcBS_B6G/0/experiments/

### Related issues?
No.
![lazyloading viewport images](https://user-images.githubusercontent.com/964146/171651110-d2406d81-7cf4-4972-bc38-e20f189b814c.jpg)

**Comment by tkadlec** [comment]
@ebizindia I appreciate your patience (and the super well-written issue!)

Can you have another look? Think we're good to go here.

**Comment by ebizindia** [comment]
Looks fine to me. I will create another issue if I find a problem. 

Thanks!
