### ISSUE TITLE
Remove Jun 1 notice at the top as the event has happened

### ISSUE THREAD

**Issue by ebizindia** [WPO-Foundation/webpagetest#1970]
## Description
"Jun 1 Save the date" notice can now be removed.

### Steps to reproduce
I am seeing this stale notice every time I load webpagetest.org

### Expected result
The notice should be taken off or at least hidden.

### Actual result
What actually happens?

### Related issues?
Any related issues filed already?

**Comment by scottjehl** [comment]
Thanks! A link to Tim's post on the new features may be best here.

**Comment by deathbearbrown** [comment]
removed for now.  Thank you so much @ebizindia ! You write great issues. We really appreciate them.

**Comment by ebizindia** [comment]
Thanks for your kind words.
