### ISSUE TITLE
Password reset doesn't work

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#1974]
I was trying to log into WebPageTest.org, but it denied my access so I assume all I need to do is to reset my password, but when I do so, it sends me a password reset email for Catchpoint.

I assumed it is OK as WebPageTest is now part of Catchpoint, but it is resetting my password for a Catchpoint account and doesn't let me log in with that into WebPageTest.

Not sure when it started, but I assume with the new release earlier this month.

My corporate email is `schernyshev@` at my employer, if that helps with debugging

**Comment by deathbearbrown** [comment]
Hello! We are aware of the bug and are currently trying to get a patch out to fix it. I'll let you know when it's ready to test.

**Comment by deathbearbrown** [comment]
Hello again! The patch has been released and you should be able to reset your password. Let us know if anything else comes up
