### ISSUE TITLE
Mobile testing shows successful on un-reachable page

### ISSUE THREAD

**Issue by songlibo** [WPO-Foundation/webpagetest#198]
Mobile testing shows successful on un-reachable page, http://www.webpagetest.org/result/140228_0G_PJD/

while the desktop testing shows error of the test: http://www.webpagetest.org/result/140228_C8_PJG/

**Comment by pmeenan** [comment]
Fixed: http://www.webpagetest.org/result/160205_52_38cbbabcd1b184d2e302cf5014cb6a55/
