### ISSUE TITLE
Make ‘Waterfall View’ and ‘Connection View’ charts [images] the same width

### ISSUE THREAD

**Issue by csswizardry** [WPO-Foundation/webpagetest#2290]
I’m pretty sure these two graphs used to line up, so flagging as a bug/regression. Attributing activity in the _Connection View_ to responses in the _Waterfall View_ would be much easier if they were aligned.

![image](https://user-images.githubusercontent.com/751944/186453648-c74c145c-589c-4b1f-96a8-6c07900558d4.png)

Thank you!

**Comment by tkadlec** [comment]
Closed with #2297
