### ISSUE TITLE
webpagetest.org/webvitals loads site.js twice in Firefox

### ISSUE THREAD

**Issue by stoyan** [WPO-Foundation/webpagetest#2307]
title says it all

**Comment by tkadlec** [comment]
Hmmm...I don't see it happening. Can you make sure that "Disable cache" isn't set in Chrome Dev Tools?

**Comment by stoyan** [comment]
Tried again, seems Firefox only

<img width="568" alt="Screen Shot 2022-08-30 at 1 39 26 PM" src="https://user-images.githubusercontent.com/51308/187506169-af095224-216d-49df-a6fd-1562ce8ea4af.png">

**Comment by stoyan** [comment]
JS indeed loads 2x only in FF, but it does execute 2x in all browsers
