### ISSUE TITLE
Preserve custom waterfall configuration in the URL

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#2337]
## Feature Request Summary
When I customize waterfall on a page like https://www.webpagetest.org/customWaterfall.php?test=220908_AiDcP9_FAP&run=1&width=930

and change max duration or a subset of requests to be displayed, my settings are not preserved in the URL parameters and I can not share it with my business stakeholders to motivate them to optimize the pages I am analyzing.

Please preserve all the changes to custom waterfall in the URL so I can share it.

(discovered and discussed at NY Web Performance meetup: https://www.meetup.com/web-performance-ny/events/mtxcwsydcmblb/)

**Comment by stoyan** [comment]
This is live, check it out now and share any feedback
