### ISSUE TITLE
Traceroute always runs from Virginia

### ISSUE THREAD

**Issue by tkadlec** [WPO-Foundation/webpagetest#2349]
## Description
No matter the location chosen for a traceroute test, the location that the test is run from ends up being Virginia.

### Steps to reproduce
1. Go to https://www.webpagetest.org/traceroute
2. Choose a location other than Virginia and run the test
3. Notice that the results show the test ran from Virginia

### Expected result
The test should run from the selected location.

### Actual result
The test runs from Virginia.

### Note
[Tweet reporting issue](https://twitter.com/Sarkies_Proxy/status/1569804953924915200)

**Comment by tkadlec** [comment]
Ok....this one looks like a JS issue. I see an error in the console that I think is causing the location to not properly update when changed.

**Comment by stoyan** [comment]
This is in lighthouse tests (when you pick a location), maybe similar issue?
<img width="587" alt="Screen Shot 2022-09-15 at 12 59 06 PM" src="https://user-images.githubusercontent.com/51308/190464161-784aa7f2-2220-4449-90ea-025ddb7719e8.png">

**Comment by stoyan** [comment]
in `test.js`...
before:
```js
  if (has_chrome && mobileDevices) {
```
after:
```js
  if (has_chrome && 'mobileDevices' in window && mobileDevices) {
```

This certainly mutes the error but in my setup I can't test if this is the right fix
