### ISSUE TITLE
Request details wrong on multistep scripted test

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#237]
The following test loads a page, and then clicks on a link:

http://www.webpagetest.org/result/140528_C9_b63496a77a8bc5661ca7964baca30a1c/1/details/

The resource labels in the waterfall are correct but looking at the actual request details there's a mismatch of information e.g. 

request 32 has a URL of http://malconfiguratorprod.blob.core.windows.net/mal-config-spider650s/en-gb/data/options.json?sr=c&si=public&sig=kaPYf9N8UXZrofghvxvspRdzWEIQgEYxccRCbn3mVJE%3D&bv=1.4.5261.16775

but the headers section shows:

GET /mal-config-spider650s/shared/images/swatches/ec0004e-40.jpg?sr=c&si=public&sig=kaPYf9N8UXZrofghvxvspRdzWEIQgEYxccRCbn3mVJE%3D&bv=1.4.5261.16775 HTTP/1.1

**Comment by pmeenan** [comment]
Should be fixed now.  Moved to using explicit request ID's for matching up the requests, headers and response bodies.
