### ISSUE TITLE
CLS high - can't understand reason

### ISSUE THREAD

**Issue by ebizindia** [WPO-Foundation/webpagetest#2380]
## Description
The WPT test is reporting a high CLS but it does not look like that in the video or filmstrip.
https://www.webpagetest.org/vitals.php?test=220927_BiDc22_B11&run=1&cached=0#cls

Am I missing something? Sorry, this may not be a bug. However, please help me understand the reason for the high figure. The 1st paint should not be considered under CLS, I assume.

### Steps to reproduce
Clear steps to reproduce the issue. If it's relevant and you're able, please provide a link to a WebPageTest run—it makes it _much_ easier for us to dig in.

### Expected result
I expected a much lower CLS in the range of < 100 ms. 

### Actual result
CLS is reported at 0.836ms.

### Related issues?
Any related issues filed already?

**Comment by scottjehl** [comment]
Hey @ebizindia 

In the section you linked above, it shows the layout shift windows visually. Scrolling through them, it looks like the cookie popup is responsible for the layout shifts that are detected. Hope that helps!
