### ISSUE TITLE
Chrome + HTTPS not setting image_total or objectSize in requests file

### ISSUE THREAD

**Issue by jklein** [WPO-Foundation/webpagetest#243]
In this result all images show as zero bytes:

http://www.webpagetest.org/pageimages.php?test=140607_5A_H68&run=1&cached=0

I pulled a test result into my private instance and confirmed that the issue goes all the way to the requests file (1_IEWTR.txt.gz in my case).  The values we care about are just zero in that file.  

This result over HTTP to another site has the correct values:

http://www.webpagetest.org/pageimages.php?test=140607_B5_H6N&run=1&cached=0

This implies to me that it could be a TLS related issue.  I've seen the same problem on other sites over HTTPS, not just Etsy.

**Comment by pmeenan** [comment]
This was fixed a while ago.  Also just finished implementing TLS decode for Chrome so it has access to the raw requests.
