### ISSUE TITLE
Scrollable tables rendering hiccups

### ISSUE THREAD

**Issue by stoyan** [WPO-Foundation/webpagetest#2452]
Several big scrollable tables in the results have hiccups rendering and only show up on scrolling.

Example: https://www.webpagetest.org/result/221007_AiDc8P_FYA/1/details/

https://user-images.githubusercontent.com/51308/199577550-9083c0db-c524-4abd-b749-f05f5537b134.mov

Edit: URL and video to show `mx-blend-mode` on/off

**Comment by stoyan** [comment]
Viewport size happen to be 2002x1146 (w x h)

**Comment by hecktarzuli** [comment]
I'm also seeing some funky tables.  Macbook Pro 16" 2019, Chrome 105.  1920x1080.

https://youtu.be/3-E2raj55yk

**Comment by stoyan** [comment]
Appears to happen only in Chrome (including Canary 109.0.5396.0) and Brave. It's fine in Safari and Firefox.

**Comment by yoavweiss** [comment]
@stoyan - Could y'all file an issue on https://crbug.com with a reproducible test case?
