### ISSUE TITLE
LCP background image is not found when set via inline style

### ISSUE THREAD

**Issue by scottjehl** [WPO-Foundation/webpagetest#2455]
Here's an example.

https://www.webpagetest.org/result/221008_BiDcAF_935/2/experiments/#Quick 

We can likely parse it out of the outerHTML if it's a bg image, and the url isn't defined.

**Comment by scottjehl** [comment]
Update: we won't be able to parse it ourselves because we can't know which url is active just by looking at a style attribute in the outerHTML. For example this google flights html has two background urls in it 

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/214783/195167625-cfee2e0b-795d-43a8-8b4a-0357ff68752e.png">

**Comment by pmeenan** [comment]
Interestingly, that doesn't end up as a background-image, it ends up as "content".

I can plumb it though using the "url" property that comes in with the element and I can also include the "content" attribute.  Not sure I want to backfill "content" into "background-url" though.
