### ISSUE TITLE
Experiment: Remove JS

### ISSUE THREAD

**Issue by jefflembeck** [WPO-Foundation/webpagetest#2497]
Suggestion from @csswizardry : Replace script type with “foo”, it’ll stop the browser from executing or fetching but maintains payload

**Comment by scottjehl** [comment]
I think we might be covered on this with our disable scripts experiment! The current disable scripts experiment changes script tags to ‘scrapped’ tags, keeping inline payloads the same but preventing parse/exec.

**Comment by jefflembeck** [comment]
@scottjehl awesome. Harry also mentioned

As well as:

/s/<script/<script type=foo

…we’ll probably also want:

/s/noscript/nocript

…to fully emulate the *disabled* JS experience (rather than simply removing JS).
