### ISSUE TITLE
Waterfall image stuck, won't scroll.

### ISSUE THREAD

**Issue by ClarkMitchell** [WPO-Foundation/webpagetest#2519]
## Description
Waterfall image appears stuck (as if it had position: fixed), request popup and request line highlighting will scroll separately from waterfall image and no longer correspond.

### Steps to reproduce
In Chrome Canary, with a network waterfall of >250 requests, with a browser width small enough to trigger X axis overflow scrolling, click on a request item to trigger the popup. Now scroll. Popup and highlight line should scroll away, but the waterfall image stays in place.

Disabling `mix-blend-mode: multiply;` on `id=waterfall_step1`
seems to stop the bug.

The bug does not seem to occur in Safari or Firefox.

### Expected result
Waterfall Image scrolls and stays in sync with the request popup.

### Actual result
Popup and highlight line should scroll away, but the waterfall image stays stuck.

This test was used for this video demonstration: https://www.webpagetest.org/result/221104_BiDcJR_ABX/1/details/#waterfall_view_step1

https://user-images.githubusercontent.com/7844500/200014772-dd90ab8f-95b8-4255-ab80-969a66ea14c5.mp4

**Comment by rik** [comment]
Is this also happening on stable Chrome? Also, I see an Update button in the top right corner, which Chrome Canary are you using?

I can't reproduce on my Chrome Canary (109.0.5400.0 arm64 macOS 13.0) nor my Chrome stable (107.0.5304.87 arm64 macOS 13.0).

**Comment by scottjehl** [comment]
Following up. I think Chrome must have fixed this issue in 107 or 108...

I'll reopen if necessary but currently I'm not seeing the bug anymore. Thanks!
