### ISSUE TITLE
London test centre is always super busy

### ISSUE THREAD

**Issue by ebizindia** [WPO-Foundation/webpagetest#2546]
## Description
Whenever I try to schedule a test, the London test centre is super busy with about 100-300 tests in the queue. The capacity might need to be increased here.

![London test centre busy](https://user-images.githubusercontent.com/964146/203722122-74797efc-4850-46c7-b86e-034e5be8820c.jpg)

**Comment by tkadlec** [comment]
Yeah, this one has gotten popular. We're jumping capacity. Will post back here when it's done!

**Comment by tkadlec** [comment]
We ramped up the autoscaling on this instance and I've been watching it for a bit and things look good. Closing this one!
