### ISSUE TITLE
Add explanation to section that compares WPT results to CrUX data

### ISSUE THREAD

**Issue by scottjehl** [WPO-Foundation/webpagetest#2583]
This section's so handy. I think it could use a sentence or two explaining how to read the charts so that it's even clearer what we're looking at.
 
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/214783/207170418-90c815f5-8976-4b59-86f6-87a835f52227.png">

**Comment by tkadlec** [comment]
Duplicate of #1721?

**Comment by scottjehl** [comment]
Oooh, yes thanks @tkadlec
