### ISSUE TITLE
Only display differing lines in HTML diff

### ISSUE THREAD

**Issue by rik** [WPO-Foundation/webpagetest#2608]
## Feature Request Summary
Add an option to only show lines that differ. Maybe with a few more lines for context (just like the `diff` tool).

### What's the motivation or use case for the change/feature?
Running the diff on very large HTML payloads slows scrolling (at least in Safari) but more importantly, it makes it hard to focus on the differences with so many lines not differing.

See on [this run](https://www.webpagetest.org/result/221222_AiDcRW_DQ0/1/htmldiff/) with "Prettify HTML before the diff" checked.

**Comment by stoyan** [comment]
thanks, and this is an excellent example!

**Comment by stoyan** [comment]
This is live now, example: https://www.webpagetest.org/result/221222_AiDcRW_DQ0/1/htmldiff/#removed_1_pretty
