### ISSUE TITLE
Remove "capture video" checkbox

### ISSUE THREAD

**Issue by stoyan** [WPO-Foundation/webpagetest#2620]
## Feature Request Summary
Looks like it's being ignored and video is captured anyway. Also we need video for some metrics (Start Render, Speed Index) and features (filmstrip?)

### What's the motivation or use case for the change/feature?
Cleaner UI and codebase

Tagging @pmeenan for thoughts

**Comment by pmeenan** [comment]
Not sure if it's linked to that checkbox specifically (and it won't really hurt to remove it) but the agents support capturing video for calculating the metrics but not uploading it so you can still get the visual metrics without the storage requirements of having to keep filmstrips.
