### ISSUE TITLE
Chrome doesn't save response bodies for sites accessed via HTTPS

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#272]
When a HTTPS site is tested using Chrome, reponse bodies aren't saved even when the option is checked, Firefox works OK

**Chrome:**
http://www.webpagetest.org/result/140709_82_a7e21dfc0f7a1751150c7f659b094f67/1/details/

**Firefox:**
http://www.webpagetest.org/result/140709_7S_d8c606b134c7baa8937ad61d688e2a3d/

**Comment by yoavweiss** [comment]
I've also hit this issue just now :/

**Comment by pmeenan** [comment]
Finally got TLS decode for Chrome implemented so bodies, optimization checks and HTTP/2 push should all work well now.
