### ISSUE TITLE
Create self-scaling EC2 AMI WPT Instance

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#310]
The initial use case is to support the [grunt-perfbudget](https://github.com/tkadlec/grunt-perfbudget/issues/13) project but this could be really useful for getting people started with private instances.

#Some rough thoughts:
* Instance would be fetch latest stable UI code and config on startup
* Config would include definitions for all available AMI locations
* On startup, read user data config information and populate settings
* When a test is submitted for a location, if no agents are available it will automatically spin up an instance for the given location (limit to 1 instance for now)
* Hourly check for idle agents and terminate them automatically (just under an hour since it bills hourly)
* Auto-update UI and agent code code (git pull on cron?)
* Optionally archive test results to S3 so they can persist beyond the server's lifetime (optionally provide a TTL on the archived items)
* Allow for the UI instance to self-terminate if it hasn't been used for an extended period.

#Config items that would need to be passed through user data
* EC2 key and secret
* S3 bucket name for archiving tests (optional)
* S3 archive TTL (optional, defaults to never expiring)
* Idle time before terminating web UI instance (optional - defaults to 24 hours?)
* Idle time before terminating test agents (optional - defaults to 10 minutes, checked hourly)
* Headless flag (prevents tests from being submitted through the UI) (optional - defaults to false?)
* Instance size for test agents (optional - defaults to C3.medium)
* Instance type (optional - defaults to spot)
* Max spot price (optional - defaults to $0.30?)

I'm sure I'm missing a bunch but those are the basics and shouldn't be too hard to pull off.

**Comment by adamwintle** [comment]
Is there a master AMI of this in the Singapore region, or only us-east-1 for now?

**Comment by pmeenan** [comment]
Just in us-east-1 but it should be trivial to copy.  If you can't make a
copy of the us-east one let me know and I can copy it directly to different
regions.

**Comment by adamwintle** [comment]
ok got it. Anyone else wondering, you can right-click any AMI and copy to another region :)

**Comment by pmeenan** [comment]
Closing this as done. The AMI is now available is all regions and any enhancements can be treated as regular WPT issues.
