### ISSUE TITLE
Edit test labels after the test completes

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#32]
Test labels are very useful, but it's very common that you either forget to set them when submitting a test or only realize you want one after the fact. 

It'll be great to allow users to edit the labels of tests submitted by them after the test is done, even multiple times.

https://code.google.com/p/webpagetest/issues/detail?id=74

**Comment by adamwintle** [comment]
So how do we actually edit the labels? Do we need to pass a parameter via the URL?

**Comment by jklein** [comment]
@adamwintle there's a button in the test history:

![image](https://cloud.githubusercontent.com/assets/629982/5892116/48ef0b0a-a482-11e4-9fb0-f86a135d3e65.png)

**Comment by adamwintle** [comment]
@jklein Is that on the private instances too?

**Comment by jklein** [comment]
It should be if you have the latest version ([2.16](https://sites.google.com/a/webpagetest.org/docs/private-instances) currently)

**Comment by pmeenan** [comment]
Also requires sqlite to be installed for it to show up.
