### ISSUE TITLE
Speed Index measurement dropped after upgrading from WPT 2.14 to 2.15

### ISSUE THREAD

**Issue by JelleZijlstra** [WPO-Foundation/webpagetest#320]
We continually run tests on a few pages on our site and record the speed index. After we upgraded WPT from version 2.14 to 2.15, our speed index measurements dropped by about 50% despite no changes on our side. Is this an expected upgrade result?

**Comment by pmeenan** [comment]
Closing. Hasn't been reported elsewhere and the agents are heavily used.  Re-open if you can setill reproduce it with 2.18
