### ISSUE TITLE
Wrong url in details of request in waterfall view - repeated domain.

### ISSUE THREAD

**Issue by artursudnik** [WPO-Foundation/webpagetest#334]
For requests that have domain other than main URL of the test, protocol and domain is repeated.

Example:
URL: http://www07.mydomain.comhttp://www07.mydomain.com/cdn/img/sprite_toolbar.png?1413795523

It happens probably because in test result file for other domains requests in url column full url is stored and then concatenated to host column in LoadRequests function.

I use latest version of WPTServer and wptdriver 2.15.0.190

**Comment by pmeenan** [comment]
Should be fixed now.
