### ISSUE TITLE
Highlight visual differences on filmstrip

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#343]
Filmstrip is very powerful tool, but sometimes it's hard to see what has changed on those orange-bordered screenshots, it'd be a great help if visual differences were highlighted - best way is probably just showing the changed pixels in red on mouse-over over particular image.

Just computing a diff of pixels is already done (and duplicates are dropped) so creating a visual diff of consequent images might be just a matter of using ImageMagick's "compare".

**Comment by staabm** [comment]
I just stumbled over this exact problem. I get a filmstrip with a lot of screenshots (e.g. every 0.5 sec) - but it would be more interessting to see only those images which actually have changed (no matter when, but in correct order of course).

that way one would not need to try to identify where things might have changed..

**Comment by pmeenan** [comment]
@staabm The frame border will tell you which frames changed.  If there is no border then there wasn't any change.  Yellow, red, dotted all have different additional meanings (layout shifts, LCP, etc) but there will only ever be a border around the filmstrip frame if the frame changed from the previous one.

As far as WHAT changed, that's more what Sergey is asking for and to be able to do a diff.  Right now the easiest way is to just open the two frames of interest into separate browser tabs and go back and forth between them.
