### ISSUE TITLE
where is the "mobile" folder in 2.16

### ISSUE THREAD

**Issue by jhdxr** [WPO-Foundation/webpagetest#367]
I'm using the mobile agents with webpagetest. and the introduction here (https://code.google.com/p/mobitest-agent/source/browse/trunk/mobitest-agent/Android/BZAgent/README) says 
> if you installed webpagetest from one of the bundled packages in a private instance, you'll need to also check out the "mobile" folder (http://webpagetest.googlecode.com/svn/trunk/www/webpagetest/mobile/).

but in the version 2.16, I cannot find the folder "mobile" or something similar. Is it removed or moved to somewhere else?

**Comment by pmeenan** [comment]
Node agent now supports iOS as well (lightning connector required for video).  Closing as the mobitest agents are deprecated.
