### ISSUE TITLE
How to communicate via wifi between nodejs agent and real android mobile

### ISSUE THREAD

**Issue by luisxiaomai** [WPO-Foundation/webpagetest#370]
Hi,

I want to know if it's possible to connect real android mobile and nodejs agent by wifi? 

For example, in the nodejs agent server I use adb to connect my real android mobile like "adb connect 10.77.xx.xx:5555". But when start to launch the nodejs agent via the ip, it's not supported. It seems currently only support USB connect and then use the serial number.

@pmeenan , can you give me some insights? Thanks.

B.R.
Luis

**Comment by pmeenan** [comment]
The agent only supports connecting over usb.  It may be as simple as changing the device ID validation regex to allow for the IP address style device ID's: https://github.com/WPO-Foundation/webpagetest/blob/master/agent/js/src/agent_main.js#L75

Specifically change:

```
if (!/^[a-z0-9]*$/i.test(runTempSuffix)) {
```

To be something more like:

```
if (!/^[a-z0-9\.\:]*$/i.test(runTempSuffix)) {
```

**Comment by luisxiaomai** [comment]
@pmeenan , thanks for you apply. 
The command I used it :wptdriver.bat -m debug --browser android:10.xx.xxx.xxx:5555 --serverUrl 10.xx.xx.xxx:8081 --location XXX. But it stills says:"& was unexpected at this time"
