### ISSUE TITLE
Server AMI - mutiple copies of getwork.php.nnn left in /var/www

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#377]
I've fired up a the server AMI and I've notice multiple copies of getwork.php.nnn is being left in /var/www

They're all zero bytes and appear to be generated once a minute.

**Comment by pmeenan** [comment]
Hmm.  There should be a cron job running wget against work.php but it's supposed to throw away the result.  Kind of sounds like it is writing it out instead.  I'll take a look and if necessary update the AMI but it probably makes sense to have getwork.php clean up those files as well so anyone using the existing ami won't have issues.

**Comment by pmeenan** [comment]
which AMI?  I'm not seeing the files show up when using ami-fcfd6194 (the newer one).

**Comment by pmeenan** [comment]
Nevermind, was looking in the wrong place - I see them now

**Comment by pmeenan** [comment]
Not exactly fixed (would need to update the AMI) but the 5min cron script now cleans these up automatically so no more than 5-6 of them should accumulate
