### ISSUE TITLE
Confused additional requests about proxy and ssl.gstatic.com

### ISSUE THREAD

**Issue by luisxiaomai** [WPO-Foundation/webpagetest#378]
Hi, 

I used webpagetest to test one internal web page everyday, but I found sometimes the result was totally blocked by some additional requests about proxy and ssl.gstatic.com like attachment. 

![proxy](https://cloud.githubusercontent.com/assets/6835229/5698725/a998960c-9a4f-11e4-8684-6d5efad07d37.png)

My test agent use the automatic proxy script, and the tested webpage is https. I want to know why sometimes it requested above mentioned requests, but most times didn't. 

@pmeenan , can you continuous give me some helps and tell me how to solve this problem.

**Comment by pmeenan** [comment]
What does the pac script look like?  It might also help to capture a netlog or tcpdump to see if it is trying to connect directly to gstatic.com or if the problem is going through the proxy.

**Comment by luisxiaomai** [comment]
Hi Patrick, 


Thanks a lot for your continuous support, I attached tcpdump and netlog for failed case and succeed case which tested in my internal private webpagetest instance.
It run in chrome with specified proxy, not a pac script. Can you find something from that, thanks a lot.


B.R.
Luis




在 2015-01-12 23:52:48，"Patrick Meenan" <notifications@github.com> 写道：


What does the pac script look like? It might also help to capture a netlog or tcpdump to see if it is trying to connect directly to gstatic.com or if the problem is going through the proxy.

—
Reply to this email directly or view it on GitHub.

从网易126邮箱发来的云附件
amazonFailed.cap (11.03M, 2015年1月30日 14:30 到期)
下载
amazonFailed.txt (4.24M, 2015年1月30日 14:32 到期)
在线预览 | 下载
amazonRight.cap (6.98M, 2015年1月30日 14:26 到期)
下载
amazonRight.txt (5.33M, 2015年1月30日 14:34 到期)
在线预览 | 下载
