### ISSUE TITLE
EC2 private instance: Updating user data has no affect on a re-started instance

### ISSUE THREAD

**Issue by kevindixon** [WPO-Foundation/webpagetest#379]
When stopping and EC2 server instance, updating the user data and the re-starting the instance the new settings are not picked up. It is necessary to manually update /var/www/webpagetest/www/settings/settings.ini in order to get settings to update.

See http://www.webpagetest.org/forums/showthread.php?tid=13451.

**Comment by pherris** [comment]
FYI, the documentation was updated to reflect this behavior: https://github.com/WPO-Foundation/webpagetest/blob/master/docs/EC2/Server%20AMI.md

**Comment by pmeenan** [comment]
As pherris mentioned, this is working as intended and was largely a documentation gap that he fixed.  The user data is just the seed for the initial configuration.  Any further configuration for the settings (or API keys) needs to be done directly on the server.

**Comment by kevindixon** [comment]
OK, I understand.
One last question if I may - I presume the auto-update from Git on the AMIs keeps the settings.ini should I change it (i.e. it won't get over-written)?

**Comment by pmeenan** [comment]
Correct.  Git only has settings.ini.sample and usually people will rename that and use it as a starting point.  Nothing in the core repository to overwrite the local settings.
