### ISSUE TITLE
Somtimes visually complete metric is so long

### ISSUE THREAD

**Issue by luisxiaomai** [WPO-Foundation/webpagetest#380]
Hi,

I just found the same page tested in webpagetest, sometimes the performance result is right, but sometimes the"visually complete" metric is so long. The video is also too long.

@pmeenan , can you help me and give some commets for this.Thanks.

Wrong pic:
![error](https://cloud.githubusercontent.com/assets/6835229/5736133/06ec4b50-9c0d-11e4-9425-f8c64b399191.png)

Normal pic:
![right](https://cloud.githubusercontent.com/assets/6835229/5736161/6a2e9056-9c0d-11e4-91fe-ec45ce6ee05d.png)

**Comment by pmeenan** [comment]
Do you have links to the actual tests or the videos? Those screen shots
don't really show anything about why it was different, just that it was.

If it is a private instance, what version? The mobile video processing has
had a lot of work on it over the last 6 months.
