### ISSUE TITLE
We really ought to be using IAM Instance Profiles in place of aws keys.

### ISSUE THREAD

**Issue by flyinprogrammer** [WPO-Foundation/webpagetest#385]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UsingIAM.html

So - I'm going to propose that instead of recommending putting ec2 and s3 keys into user-data/hardcoded configuration, that we support and encourage the use of IAM Instance Profiles instead. This is much more secure as the keys that will be used by the service will be temporary, and never hard coded into configurations. However; due to automatic updates we will need to provide backwards compatibility for getting the keys out of stored configuration. I'm going to also propose that we allow for the reuse of ec2_key and ec2_secret for s3 as well, and that we take care of this logic in what has become known as a default aws credentials provider chain. This chain would use the following logic to resolve credentials:

When asking for ec2_key/ec2_secret:
If set as configuration settings; return them
Else use the metadata service to fetch temporary keys

When asking for s3 credentials:
If set as configuration settings; return them
Else if ec2_key/ec2_secret are provided; return them
Else use the metadata service to fetch temporary keys

To do this correctly though, typically a cache is used to store the temporary keys, and logic is also therefore required to quickly and quietly fetch new keys when they are eventually expired.

I'm comfortable writing the necessary code to accomplish these tasks, however; it brings about a fundamental question. Logic already exists in the latest aws php sdk to handle the caching and re-fetching of the keys. Additionally it already has some set opinions about where, and in what order to fetch default credentials - sadly our current setting names do not match their cross sdk standards. Regardless, would it make sense for us to upgrade the sdk we use for amazon api calls - or would you prefer that I write my own minimalist approach? I'm also curious, should you prefer I roll my own versions of these ideas, where in the code base you would desire me to logically put them. It seems wrong to pollute the www/ec2 child directories with my code; but I am sadly not sure where else it would belong.

I'm hoping that by answering some of these questions I can quickly close this issue and submit a pull request.

**Comment by pmeenan** [comment]
The latest [AWS SDK](https://github.com/WPO-Foundation/webpagetest/tree/master/www/lib/aws) should already be being used for the scaling logic (it is under the lib directory now).

We can't automatically use the ec2_key setting for s3 because there may be people who don't want to archive to S3 and both key settings are tied to enabling the respective features.  We could clean it up going forward with new settings that don't carry the same baggage but the existing ones will need to continue working the way they currently do.

**Comment by flyinprogrammer** [comment]
>The latest AWS SDK should already be being used for the scaling logic (it is under the lib directory now).

Oh I see! Would we want to deprecate www/ec2 then and re-write www/ec2/ec2.inc.php to use the new sdk?

>We can't automatically use the ec2_key setting for s3 because there may be people who don't want to archive to S3 and both key settings are tied to enabling the respective features. We could clean it up going forward with new settings that don't carry the same baggage but the existing ones will need to continue working the way they currently do.

Why not verify if a bucket name (archive_s3_bucket) is set? ec2 but no archive_s3_bucket = do ec2 things, but don't archive.

**Comment by pmeenan** [comment]
ec2.inc.php already uses the new SDK.  The main thing I'm aware of that
still uses the old SDK is the archiving code in archive.inc (should be easy
enough to migrate - I just haven't).

Good point on the bucket - sounds good to me.  The cleanest way would
probably be to prefer the s3 key if it is there but fall back to the ec2
key if not (when the bucket is specified).

**Comment by flyinprogrammer** [comment]
forgive me for being a php n00b. I'm going to set aside some time this week to do a more thorough code read so that I don't continue to waste your time!

**Comment by okor** [comment]
Any updates on this? IAM Instance Profiles would be great.

**Comment by carlnordenfelt** [comment]
+1 on this issue.
Having credentials laying about is never a good thing so this is in fact a security concern.

I'm also assuming that some of the permissions do not need Resource: '*'?
For example, TerminateInstances & StopInstances should only apply to instances with a specific tag and not to all instances? It' be great to see some documentation on this.

**Comment by pmeenan** [comment]
Pull requests welcome :-)

Seriously, the EC2 code is all self-contained [here](https://github.com/WPO-Foundation/webpagetest/blob/master/www/ec2/ec2.inc.php) and isn't all that complicated.  There is just a lot of other stuff WAY ahead of it on the priority list for me.

**Comment by carlnordenfelt** [comment]
@pmeenan Apart from the fact that I don't really know how to test it (which just might come down to me not looking properly) I've done some patching to the file you linked that _should_ work :)
Should I just submit a PR or is there anyway to actually confirm that it works before I do that?

**Comment by pmeenan** [comment]
The S3 part does both AWS S3 and Internet Archive's S3-like interface.  That one may be best to split code paths depending on if the s3 server is non-aws or not and only use roles when it isn't.  Generally the code needs to be able to fall-back to using keys anyway for those who already have working deployments.

Only way I know of to actually test it is to deploy a server on EC2 and test there :(

**Comment by carlnordenfelt** [comment]
I've submitted a PR, if you can take a look and review it quickly I'll see what I can do about testing it. I don't think my changes will impact existing configurations.

https://github.com/WPO-Foundation/webpagetest/pull/749
