### ISSUE TITLE
Add details to AWS instance name

### ISSUE THREAD

**Issue by adamwintle** [WPO-Foundation/webpagetest#386]
When running multiple tests in different browsers on EC2 there can be many instances running and in various stages at any one time. 

Often the Status Checks fail when a new instance is starting and this will stall the testing process. These instances then block further tests in the same region/browser. These instances also won't auto terminate after one hour. 

In this example its difficult to see which browser tests have stalled or become stuck initialising
![screenshot 2015-01-21 21 49 39](https://cloud.githubusercontent.com/assets/167075/5838201/3a15ebac-a1b8-11e4-9b60-149741fcfc19.png)

It would be useful if the browser name and some other info could be added to the instance name.

**Comment by pmeenan** [comment]
There is a "WPTLocations" tag that you can show in the console that has a list of the location IDs that each instance is connected to.  Of you click the gear in the console you should see a checkbox on the left column (tags) for enabling display of the WPTLocations tag
