### ISSUE TITLE
UI/UX Revamp

### ISSUE THREAD

**Issue by adamwintle** [WPO-Foundation/webpagetest#387]
I noticed there a minified version of the [Bootstrap](getbootstrap.com) CSS [located in the project](https://github.com/WPO-Foundation/webpagetest/blob/master/www/css/vendor/bootstrap-3.1.1.min.css), but none of the main pages seem to be utilising the framework.

In my opinion a visual revamp would be welcome; to bring the app inline with other testing tools such as Pingdom and Google Page Speed, which both have nice UI/UX.

I think an initial improvement would be converting the various existing headings, tables and other UI components to Bootstrap (since this framework is already in the project). This would also make the online test reports responsive for mobile. 

I could have a crack at this since my strongest skill-set is in front-end development, but a lot of the header and footer code is mixed with PHP, so I may need a PHP expert to help out. 

Is @pmeenan or anyone else opposed to this?

I know the Bootstrap UI is sometimes criticised for making web apps all look the same; so if someone has seen a great open-source admin theme we could use then maybe we could try it?

**Comment by pmeenan** [comment]
The bootstrap code is only used in the [status pages](http://www.webpagetest.org/getLocations.php?f=html) right now.  I wouldn't be opposed to using it for a more site-wide revamp of the UI though I'd want to also tackle a responsive UI that worked well on mobile at the same time.

**Comment by giovanisp** [comment]
+1 for a responsive layout with at least 3 breakpoints (smartphones, tablets, desktop). Flat design is also trending for quite some time and seems to be consolidating (from Google to Apple). There are many open iconsets that can be used and sources of inspiration as well:
* https://github.com/google/material-design-icons
* http://uxporn.uxpin.com/flat-design/
* http://flatuicolors.com/

Redesigning the UI could also be done first using wireframes, if there are changes in placement of page elements. Are there any design guidelines already in use ?

**Comment by pmeenan** [comment]
Guidelines....ha, you crack me up :-)

Back in late 2010 a designer took a crack at modernizing the developer UI that I had in place but it was mostly about making it look less like a developer designed it (and I should really never be allowed anywhere near user-facing UI).

Here is what it looked like before the redesign: https://web.archive.org/web/20100313073338/http://www.webpagetest.org/test

**Comment by sgaurav** [comment]
A site-wide UI/UX revamp is a great idea indeed. Currently, I personally have written a lot of CSS to make private instance pages look better for management users.

I have a background in php and can chip in couple of hours per day on this task.

**Comment by giovanisp** [comment]
@sgaurav cool! can you share some of those so we can try to come with some kind of joint proposal together with @adamwintle? I can't share the reports I created for the customers I worked for because of my contract, but I can come with "ideas" :)

**Comment by sgaurav** [comment]
@giovanisp sorry, was out of town. Sadly my work is under NDA and can not be shared. I am open to collaborate on this with everyone interested and we can come up with something useful. Given both of us have previous stint with creating reports, we can share inputs and move this proposal forward.

**Comment by jonathan-fielding** [comment]
Hey, has any progress been made on the UI redesign?

**Comment by soulgalore** [comment]
Would be cool if @zeman and the rest of the Speedcurve crew could contribute back the frontend to support OSS :)

**Comment by pmeenan** [comment]
I think right now the code is a bit of a mess with logic intermingled with presentation.  It might be a good idea to move to something more MVCish and separate things out first to make freshening up the UI easier.

I don't think I want to go full-on SPA (maybe I'm just crotchety and old) but I like keeping it as plain html/css as possible (not sure where something like bootstrap fits on that spectrum but I'm a bit allergic to frameworks).

Maybe I'll try to carve out a page at a time over the next month or two to separate out all of the current UI from the logic which should make changing UI a lot easier.

**Comment by jonathan-fielding** [comment]
I agree its better that the tool has rendered HTML but I also think it would be good to use a server side presentation framework to enable the view to be easily seperated from the logic. Happy to help with the new UI though. Perhaps its worth creating a new UI in a different repo which can later be intergrated to web page test.

**Comment by sburnicki** [comment]
I recently changed the design for our private instance. I just wrote a custom.css and replaced a few images, the markup is untouched. It's simply using consistent colors, font sizes and margins.

So some new standard CSS would also allow a better UI in my opinion and is quite easy to implement.

![wpt_design1](https://cloud.githubusercontent.com/assets/5701519/18171634/efc5aa44-7062-11e6-8b1a-ed2c21d0a557.png)

![wpt_design2](https://cloud.githubusercontent.com/assets/5701519/18171639/f431c342-7062-11e6-99a1-9dae4367711c.png)

![wpt_design3](https://cloud.githubusercontent.com/assets/5701519/18171645/f757d5f2-7062-11e6-8b17-4492f01ac87c.png)
