### ISSUE TITLE
videoFrames URLs in repeatView are invalid

### ISSUE THREAD

**Issue by kevindixon** [WPO-Foundation/webpagetest#388]
We have a private instance, and it looks like the /xmlResult is returning invalid URLs for the repeatView video frames.
For instance:
```
<firstView>
    <videoFrames>
        <frame>
            <time>0</time>
            <image>
http://mydomain.com/getfile.php?test=150126_RP_2G&video=video_1&file=frame_0000.jpg
            </image>
            <VisuallyComplete>0</VisuallyComplete>
        </frame>
        ....
    </videoFrames>
</firstView>
<repeatView>
    <videoFrames>
        <frame>
            <time>0</time>
            <image>
http://mydomain.com/results/15/01/26/RP/2G/getfile.php?test=150126_RP_2G&video=video_1_cached&file=frame_0000.jpg
            </image>
            <VisuallyComplete>0</VisuallyComplete>
        </frame>
        ....
    </videoFrames>
</repeatView>

```
The first image URL works just fine (firstView). The second image URL is not found (repeatView). The repeatView image does existing, and can be accessed from http://www.mydomain.com/getfile.php?test=150126_RP_2G&video=video_1_cached&file=frame_0000.jpg

**Comment by kevindixon** [comment]
Checked www.webpagetest.org and it has the same problem, so no a private instance issue. 
Example: http://www.webpagetest.org/xmlResult/150126_9Y_FG5/

**Comment by pmeenan** [comment]
Thanks.  Should be fixed now.  If your private instance is running on the EC2 server AMI it should pull down the fix in the next hour or so.
