### ISSUE TITLE
Visually complete happens after fully loaded?

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#389]
No sure if this is a WPT bug as it only seems to happen for Chrome but for fast sites sometimes the visually complete time can come after fully loaded.

I would of expected fully loaded to always be the very last metric? Or could visually complete be delayed by the browser paint time even though all network activity has stopped? If this is the case then I would expect fully loaded to include the additional browser paint time.

Here's an example where it effects the rendering of the filmstrip. Toggle between "fully loaded" and "visually complete" to see the last frame dropped.

http://donut.speedcurve.com/video/compare.php?tests=150125_W2_BEH&thumbSize=200&ival=100&end=full

Looking at the times, fully loaded = 2350 and visually complete = 2700 which is why the last frame get's dropped.

**Comment by pmeenan** [comment]
This isn't necessarily unexpected.  The fully loaded time metric is purely network and the visual metrics may not even have any relation to network activity.  In extreme cases there may be animation, pop-ups, or random other behaviors (in addition to possible browser delays in getting content to the screen).

I wouldn't want to tie them together in the default metrics but I wouldn't be opposed to exposing a new metric that is the greater of either.

**Comment by zeman** [comment]
Thanks Pat. A new "page complete" metric would be quite useful that takes into account both network activity and any on screen changes to indicate when the "page" is fully complete rather than just network activity.

My more immediate need is a filmstrip setting that renders a filmstrip to either "fully loaded" or "visually complete" based on which of these is larger so I can avoid blank filmstrips where "visually complete" happens after "fully loaded".

I can look at putting together a pull request if you think this would be useful.
