### ISSUE TITLE
Create a modular python agent

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#390]
Instead of the current monolithic agents, create a bunch of components that can be assembled as needed (separate modules/processes):
- Chrome dev tools timeline/tracing/remote control
  - Interaction through stdio and timeline/traces logged to files
  - Work with ios dev tools proxy
- IE ETW processing/decoding
- tcpdump module (including decoding where possible)
- Simple test driver
  - Web server for extensions to talk to for navigation
  - Capable of driving Chrome remote dev tools component
- WebDriver wrapper
  - Launch automated webdriver tests while measuring in parallel
- Browser process launcher
  - Chrome Desktop
  - Firefox
  - IE
  - Chrome Android
  - iOS?
  - Phantom
- Browser-specific extensions
  - As few as possible since they are only available on desktop
- Video processing script (already available)
- Video capture module
- WebPageTest server interaction module (polling server, running tests, etc)

The current Node agent is a bear to develop (and run) and the desktop agents are Windows-only.  This would allow for cross-platform agents and a MUCH simpler codebase.

**Comment by klepikov** [comment]
Awesome idea! Ideally reusable even outside of WPT agents, just like the video script.

**Comment by andydavies** [comment]
+1
