### ISSUE TITLE
AWS private instances intermittently fail to terminate agents when idle

### ISSUE THREAD

**Issue by kevindixon** [WPO-Foundation/webpagetest#397]
Intermittently, EC2 test agents are failing to be be stopped - its not unusual on my private instance to have 4 or 5 instances that have not been stopped over the period of a week. These instances have been idle for long period of time (8 hours+).
When this happens, the instances are not visible in /getTesters.php and the error log includes this kind of line:
```
20:00:02 - EC2:Launching EC2 instance. Region: eu-west-1, AMI: ami-d0c76fa7, error: 
The instance ID 'i-XXXXXXXX' does not exist
```
So far, I have observed this in agents running on us-east-1 and eu-west-1.
Perhaps the re-try mechanism for terminating agents isn't quite working as expected?

Full history of this issue is here: http://www.webpagetest.org/forums/showthread.php?tid=13465.

**Comment by pmeenan** [comment]
I think I know what may be going on.  The running instance detection code relies on the tags that identify the instances as WPT instances and which locations they are tied to.  If the instances start but fail tagging for some reason it would be possible for them to become orphaned (though they really should still be connecting in unless they are completely dead).

I'll change the logic to also include any known AMI ID's and backfill the location information automatically which should catch all running instances even if they fail to get tagged.

Should have something ready later this afternoon.

**Comment by pmeenan** [comment]
Fingers crossed this change will fix the issue: https://github.com/WPO-Foundation/webpagetest/commit/111ea78dbe1582319966ab32efc2f7dceeae86ea

If you're running the server AMI it should pick up the change within the next hour.

**Comment by kevindixon** [comment]
IIRC the orphaned agents did indeed have a blank tagging field in the EC2 console, so I'm hopeful this will fix it!

**Comment by kevindixon** [comment]
Closing this now - I've been monitoring EC2 agent instances since this fix was made, and even with 100s of tests overnight for the past month or so, I haven't seen any orphaned instances (where before there were at least a couple a week).
