### ISSUE TITLE
Inaccurate timing reports

### ISSUE THREAD

**Issue by yoavweiss** [WPO-Foundation/webpagetest#398]
I semi-rare cases, I see inaccurate timing report when comparing the reported times with the joined tcpdump captures.

A few examples:
* http://www.webpagetest.org/result/150203_3J_716e2fd842f9981a0f3053d7a892242d/4/details/
Requests 10-12, 14-16 and 18 report odd times, which are suspiciously aligned. The TCP dump shows an entire different story, where the actual timing for these requests seems shorter.
* http://www.webpagetest.org/result/150205_35_X6X/1/details/ at least for requests 19 & 22 the DNS time reporting is skewed and messed up the results.

After the initial case, it didn't take me a long time to find another one, so I'm guessing this happens quite often. I'm not sure if it skews the overall time reporting though.

**Comment by pmeenan** [comment]
WebPageTest reports the timings based on the browser interacting with the sockets and not necessarily when the packets arrive (when the browser does the reads themselves).  You will tend to see more skew like that when the CPU is pegged like it was on that test.

At some point it would be useful to combine both views and use the tcpdump to fix up the timings to reflect the network view but also include the delays the browser itself introduced.

**Comment by yoavweiss** [comment]
Yeah, that explains everything! :)
It could be interesting to measure these delays and expose them to the user as idle time due to CPU stress or something. But that's a totally separate issue. Closing this one.
