### ISSUE TITLE
support for private ec2 instance autoscaling elastic ip addresses

### ISSUE THREAD

**Issue by nheath** [WPO-Foundation/webpagetest#400]
We are using this project to auto scale agents in ec2. However, some of the sites we would like to test are behind protected security groups. In order to allow the webpage test agents to access these protected sites, we need a way to guarantee the IP address of the agent that will be created. Using subnets is an option, but cross region support then becomes an issue. 

This issue is to request a feature addition to support assignment of elastic ip addresses to the launched instance, so that security groups can allow traffic from these addresses. 

Alternately, if you can offer suggestions as to how auto-scaled test agents in multiple regions, can be used for a site with restricted access, I would love to hear them. Thanks!

**Comment by giovanisp** [comment]
+1 for this!

**Comment by pmeenan** [comment]
Do you want to provide a list of IPs to use explicitly or is it good enough to have it walk the list of unused elastic IP's you have allocated in the region and just pick one?

**Comment by nheath** [comment]
I had envisioned this as a region specific list of elastic ips in config, which I think for my use case is a necessity. We have various staff using the same AWS account for different use cases, and this avoids making assumptions about the purpose of unassigned elastic ips. For my use case, its critical that the IPs be in the correct security groups, and being explicit in settings guarantees this.

**Comment by anandbagmar** [comment]
Hi, Is there any update on this issue? Is there a way I can tell the WPT agent in EC2 to use an elastic IP on startup?

**Comment by chchrist** [comment]
Any update? We are trying to use the EC2 instance for private network and we have to use one of our elastic ips too. We will try to give it a go ourselves and if successful make a pull request.

**Comment by joychester** [comment]
+1

**Comment by joychester** [comment]
any update on this feature?

**Comment by chchrist** [comment]
Any update on this?

**Comment by bhattdeepak90** [comment]
Any update on this feature??

**Comment by jpgrace** [comment]
bump. This is a blocker for me too.
