### ISSUE TITLE
Resources where TCP connection fails missing from waterfall

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#406]
This test contains a resource that's mistakenly referenced from an invalid host (10.64.30.186) and so the TCP connection never succeeds.

http://www.webpagetest.org/result/150218_9M_cb0e791ede0877450c934a7031a668d1/

Filtering the generated tcpdump will show the attempted connection and it's retries but it's missing from the waterfall.

The missing resources causes confusion as it's unclear why the document complete marker is so late in the waterfall.

Chrome fires a Network.requestWillBeSent for the URL but obviously never gets a response

(this may be related to #11)

**Comment by pmeenan** [comment]
I think the best way to handle this will be to list any DNS lookups and socket connections that failed (or didn't complete) as measured from the winsock layer.  I can see that for all browsers and it won't rely on the dev tools messages (and may not be that hard).

The main issue is that you'll only see the domain and not the full request URL (that can be back-filled with the dev tools data).
