### ISSUE TITLE
Some changes I've made to our private instance

### ISSUE THREAD

**Issue by mjellings** [WPO-Foundation/webpagetest#407]
hi all,

I'm very new to WebPageTest and to github in general.  I'm running a private instance that we use for testing and wanted to let people know of a couple of changes I've made to the source code.

Batch processing via sitemap.xml
I've added a feature when i can specify the sitemap.xml location (specifically the one generated automatically by WordPress), this file is then read, processed and all URLs (based on 'loc' entries in the XML file) are added the list for batch processing.
![sitemap](https://cloud.githubusercontent.com/assets/1764051/6374116/b6d43176-bd06-11e4-9a44-c28b3baccaac.jpg)

Include grades on the batch processing screen
Ive copied over the code which shows the grades at the top right of the screen onto the batch processing results page so that you can see at a glance the grades for each page.
![batch-processing](https://cloud.githubusercontent.com/assets/1764051/6374127/cfb9f9e6-bd06-11e4-91a9-95630ef4264c.jpg)

Apologies for not sharing the code or submitting a pull request, part of the reason is because the code which reads and XML file and converts it to a PHP array isn't mine and I'm not sure if the licence allows me to share it.  The other reason is because I'm not sure if this is something people would want.

If anyone wants example code or anything let me know, otherwise it may be worth considering these features for a future release if others want them as well.

Thanks,

Matt

**Comment by hatzopoulos** [comment]
Nice feature.
