### ISSUE TITLE
Starting from scratch with EC2, no locations in built instance.

### ISSUE THREAD

**Issue by marr** [WPO-Foundation/webpagetest#415]
Hi,
I just built an instance of the AMI by following [this readme](https://github.com/WPO-Foundation/webpagetest/blob/master/docs/EC2/Server%20AMI.md). I understand that is a server and I can connect to it now. I built it with _user data_ containing my `ec2_key` and `ec2_secret` along with and api key. When I connect to the instance via the webpage its location list is empty. I tried a local `webpagetest` call as well using the _-s_ flag to pass my server's IP. The same issue appears, this time in presentable JSON:

```
{
  "statusCode": 400,
  "statusText": "Invalid Location, please try submitting your test request again."
}
```

**Comment by okor** [comment]
So I'd like to share my experience with setting up the WebPageTest AMI.

If you create a "keys to the kingdom" admin level user, generate keys and add to the EC2 instance as extremely minimal documentation says ... all is well and the cluster will be created/scaled, etc.

If you attempt to create a user with less than admin permissions, in my experience ... the results are tragic/frustrating as hell. No test agents will be created. Submitting a test through the UI will result in a blank white page. I have not found any helpful logs. As far as I can tell, there is not even an error log present on the filesystem for webpagetest. I still have not found a solid, sane permission mix to allow instances to be created without risking nuking other production instances.

Right now, I have elected to run the cluster in a sandboxed **account** and just throw an admin key at the config. If you read this bug report here: https://github.com/WPO-Foundation/webpagetest/issues/429 shivers will run down your spine. I really hope that's not a real bug but I don't have any reason to assume that's the case.

Some more robust documentation for setting up the AMI would be very much appreciated. An error log would also be awesome.

**Comment by andydavies** [comment]
I found I needed the following EC2 permissions:

```
ec2:CreateTags
ec2:DescribeRegions
ec2:DescribeVolumes
ec2:DeleteVolume
ec2:DescribeInstances
ec2:RunInstances
ec2:StartInstances
ec2:StopInstances
ec2:TerminateInstances
```

Can't quite workout a limited set of S3 permissions for archiving, I tried the following but think I'm still missing some:

```
s3:GetObject
s3:PutObject
```
