### ISSUE TITLE
webpageTest私例能访问部署在内网的项目地址吗？

### ISSUE THREAD

**Issue by turboTimo** [WPO-Foundation/webpagetest#420]
我的webpageTest部署在本地，本地计算器连接有内网，也能连接外网，有一个项目是部署在内网的，外不对外，本地计算器能访问这个项目，请问能否用webpagetest进行测试监控性能？

**Comment by pmeenan** [comment]
According to Google translate, this roughly translates to:

```
My webpageTest deployed locally, local calculator connected network, it can be connected to external networks, there is a project to deploy internal network and the outside is not foreign, local calculator can access the project, will be able to use the test webpagetest monitor performance?
```

You can run your own private instance entirely within your private network, no external access is required: https://sites.google.com/a/webpagetest.org/docs/private-instances

Or (hopefully) in Chinese:

```
你可以在你的专用网络中完全运行自己的私有实例，没有外部访问是必需的：https://sites.google.com/a/webpagetest.org/docs/private-instances
```

**Comment by klepikov** [comment]
http://25.media.tumblr.com/d57268315d7233f34c4bc0e9a6482856/tumblr_mnf234BXpl1qzk2upo1_500.gif
