### ISSUE TITLE
OpenURL on iOS not working 

### ISSUE THREAD

**Issue by udayramakrishna** [WPO-Foundation/webpagetest#423]
First off thanks to everyone for the great work. We are trying to use the new OpenURL on iOS to try and get it to integrate with the WPT server. We have managed to get the iPhone 4 with 7.1.2 jail broken with Pangu to run Cydia. Having followed all instructions we successful have things to a point where WPT is able to see the device. Once a test url is launched from WPT below are some issues we encountered and appreciate some thoughts on how we could resolve them. 

1) Though there is a ssh key without a passcode the prompt seems to wait for a password. I had to use the password that i used from commandline to connect with cydia openssh. There was no way to blank this password. Not sure if there is anyway to force this to use ssh keys. 
2) The test seem to fail and below are some log  lines from the client 

Apr_03_16:52:49.437 wpt_client.js:440 Client.processJobResponse_ : Got job: {"Test ID":"150403_7Z_D","url":"http:\/\/www.udayslens.com","Capture Video":1,"runs":1,"browser":"iPhone 4","orientation":"default"}
I Apr_03_16:52:49.450 agent_main.js:261 Agent.app_.schedule.addErrback.job.agentError : Starting run 1a/1 of job 150403_7Z_D
E Apr_03_16:52:49.452 agent_main.js:337 Agent.<anonymous> : Unable to start job: Internal error: unclean non-retry first view
I Apr_03_16:52:54.531 agent_main.js:141 Agent.<anonymous> : wd_server child process exit code null signal SIGKILL
root@5805fdd016aa6348681ea322cf7be49eab813184's password: 
E Apr_03_16:53:04.690 wpt_client.js:529 Client.<anonymous> : Agent is offline: ssh -F /dev/null -i /.ssh/id_dsa_ios -o 'ProxyCommand="/wpt/agent/js/lib/ios/usbmux_python_client/sshproxy.py" -u %h' -o 'User=root' 5805fdd016aa6348681ea322cf7be49eab813184 'echo show State:/Network/Interface/en0/IPv4|scutil' timeout after 10 seconds, stderr[162] Connecting to device <MuxDevice: ID 23 ProdID 0x1297 Serial '5805fdd016aa6348681ea322cf7be49eab813184' Location 0x14500000>
Connection established, relaying data
A Apr_03_16:53:04.691 wpt_client.js:554 Client.<anonymous> : Failed run 1a/1 of finished job 150403_7Z_D:  (Internal error: unclean non-retry first view)
root@5805fdd016aa6348681ea322cf7be49eab813184's password: 
W Apr_03_16:53:14.774 wpt_client.js:395 Client.<anonymous> : Agent is not ready: ssh -F /dev/null -i /.ssh/id_dsa_ios -o 'ProxyCommand="/wpt/agent/js/lib/ios/usbmux_python_client/sshproxy.py" -u %h' -o 'User=root' 5805fdd016aa6348681ea322cf7be49eab813184 'echo show State:/Network/Interface/en0/IPv4|scutil' timeout after 10 seconds, stderr[162] Connecting to device <MuxDevice: ID 23 ProdID 0x1297 Serial '5805fdd016aa6348681ea322cf7be49eab813184' Location 0x14500000>
Connection established, relaying data

**Comment by pmeenan** [comment]
The node agent no longer relies on openurl
