### ISSUE TITLE
Agent not timing out when using script

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#424]
By default an agent should fail a test if it takes longer than 60 seconds.

http://www.webpagetest.org/result/150410_V1_40609c1a55b164112fdfbee7129ef887/

This test which has only 1 run and a script that causes the agent to fail took 8 mins to fail the test.

Does the timeout apply to scripted tests?

**Comment by pmeenan** [comment]
At the upper-limit level scripts are given 10x the normal timeout to allow for multiple steps each with a 60s timeout but that logic could be radically improved to actually count the number of measurement/navigation steps.

The overall timeout aside, that test should have still failed individual steps at 60s so something went wrong that caused the backup timeout to be the one that kicked in so there's a bug in there somewhere.

**Comment by zeman** [comment]
Where does the 10x happen in code? Is it in runtest.php or in the agent code itself? We'd like to get rid of it so we can count the number of steps in a script and control the timeout ourselves and pass it in using the timeout parameter.

**Comment by pmeenan** [comment]
Looks like it should only be 2x with some added fluff to allow for post-test processing but it is don in the agent itself: https://github.com/WPO-Foundation/webpagetest/blob/master/agent/wptdriver/wpt_test.cc#L334

I could probably add a setting for a max_test_run_time or something like that that the server can pass down and have wptdriver use that as the hard-stop time (if it doesn't complete and calculate results by then you will get "test completed with no successful results")

**Comment by zeman** [comment]
"max_test_run_time" sounds great as we're finding timeout has little effect over scripted tests that have commands like execAndWait. We might be suffering from this issue thought #531
