### ISSUE TITLE
ec2_prune_volumes removes volumes that were not created by webpagetest

### ISSUE THREAD

**Issue by tdesvenain** [WPO-Foundation/webpagetest#429]
Hi,
webpagetest works into an aws environment where we run many other services (ec2 instances, ebs, etc)
e2_prune_volumes was set to 1
it removed all detached volumes of the environment, even those unrelated with webpagetest

**Comment by okor** [comment]
@tdesvenain I'm curious, what kind of permissions did you give to the user whose keys you used to configure webpagetest? Global admin?
