### ISSUE TITLE
Traffic shaping/ipfw+dummynet not working on Win 8.1 x86 / x64

### ISSUE THREAD

**Issue by Vandrix** [WPO-Foundation/webpagetest#434]
Traffic shaping/ipfw+dummynet is not working correctly on Windows 8.1 Pro x86 and x64 version.

See topic: http://www.webpagetest.org/forums/showthread.php?tid=13649

Upload stream is completely dead when I install and enable IPFW+Dummynet and run a speedtest on speedtest.net. 
WPT Agent is very slow with PHP posts to WPT server (private instance).

Running ipfw.cmd manually (as administrator) gives a lot of errors like this:

C:\webpagetest\dummynet>ipfw queue 1 config pipe 1 queue 100 noerror mask dst-po
rt 0xffff
2 [main] ipfw 2992 find_fast_cwd: WARNING: Couldn't compute FAST_CWD point
er. Please report this problem to the public mailing list cygwin@cygwin.com

**Comment by Vandrix** [comment]
I've installed ipfw+dummynet from: https://github.com/WPO-Foundation/webpagetest/releases/download/WebPageTest-2.16/webpagetest_2.16.zip

**Comment by pmeenan** [comment]
I think the cygwnd messages are a red herring.  I get the same ones on the Windows 8.1 Pro VM I just set up but am not seeing the same upstream performance issues.

![dummynet](https://cloud.githubusercontent.com/assets/444165/7432554/1b5669f2-eff7-11e4-93a2-bc2bc0f19da0.png)

It's possible that there is a conflict with another protocol or filter in the chain through.  One thing I usually do is to uninstall the Windows QOS service, all of the network mapping and responder stuff, the windows clients and also uncheck IPv6 so the only things configured for the NIC are IPv4 and the dummynet service.

If that's not it then there may be something specific with the NIC.  For example, the Xen paravirtual driver that Amazon uses on AWS is known to kave conflict issues with the ipfw driver.

**Comment by Vandrix** [comment]
Hi Pat,

Thnx for your answer.
Every other protocol/filter is already removed.
VPS is using Red Hat VirtIO Ethernet Adapter. (running on KVM)

With dummynet enabled:
![slow_upload](https://cloud.githubusercontent.com/assets/11033723/7434825/481df74c-f03e-11e4-8fa5-85a06fb1dca8.png)

Without Dummynet:

![without_dummynet](https://cloud.githubusercontent.com/assets/11033723/7434836/5b33c17c-f03e-11e4-851e-e3fd2404abb8.png)

Adapter:

![network](https://cloud.githubusercontent.com/assets/11033723/7434840/643725ca-f03e-11e4-825d-76e61a795842.png)

**Comment by pmeenan** [comment]
Are there other options on the KVM version you are running for Ethernet (like, say an e1000 device)?  My guess is that the hooks the paravirtual driver uses for better performance don't play nice with the hooks ipfw uses.

**Comment by Vandrix** [comment]
Unfortunately there are no options for changing ethernet device.. It's not supported :(

**Comment by redfineric** [comment]
I'm experiencing the same problem with brutal packet loss after having installed ipfw+dummynet.  I've seen the problem so far on Windows Server 2008R2 x64 and Windows 7 Pro x32.  Both are using the Redhat VirtIO ethernet adapter (a restriction of my VPS provider).  I would just run EC2 instances using the WPT AMI, but I need more geodiversity for my test agents than AWS can currently provide.
