### ISSUE TITLE
Android : the chrome translate popup seems to block scripts execution

### ISSUE THREAD

**Issue by jpvincent** [WPO-Foundation/webpagetest#438]
Hello there

I needed to test a french page, on mobile, and it looks like the popin kindly asking to the user if he wants the page to be translated blocks any further script
Simply going on google.fr let the popin appear, and the next command ( execAndWait in this case) is not executed.
Here is the tests, containing the script : http://www.webpagetest.org/video/compare.php?tests=150511_YC_F64-r:1-c:0

For now, I'm using the regular chrome desktop, with mobile emulation turned ON, but it's not ideal.

**Comment by pmeenan** [comment]
Multi-step navigation scripts don't work on mobile devices yet which is probably what you are seeing.  You can try using a [webdriver script](https://sites.google.com/a/webpagetest.org/docs/private-instances/node-js-agent/setup#TOC-WebDriver-Scripts) to see if that does what you need.

There are plans to bring the full scripting support to mobile, just hasn't been implemented yet.

**Comment by jpvincent** [comment]
Ok, it would do what I want I guess, it's just I have to learn another scripting language :) 

thanks for your quick answer

**Comment by jpvincent** [comment]
Note that if the translation popup can be disabled, it would be good anyway for the readability of the screenshots :)
