### ISSUE TITLE
Monitoring and alerts

### ISSUE THREAD

**Issue by dandv** [WPO-Foundation/webpagetest#445]
Is there a free service based on WebPageTest that performs periodic monitoring and alerts when load time exceeds a threshold? I've only found GTmetrix so far; here's [the StackExchange question](http://softwarerecs.stackexchange.com/questions/19633/free-website-performance-load-time-monitoring-online-service) for juicy points.

**Comment by darraghgrace** [comment]
Try sitespeed.io, run your tests on web page test and fail on performance budget.

**Comment by nilskuhn** [comment]
https://github.com/IteraSpeed/OpenSpeedMonitor is a free and open source monitoring web application based on webpagetest measurements. It has an interface to send result data to graphite in addition. So an alerting you could/would have to base on graphite data.
