### ISSUE TITLE
window.performance.mark not show for several browsers

### ISSUE THREAD

**Issue by stefanjudis** [WPO-Foundation/webpagetest#446]
I just noticed that `window.performance.mark` and the resulting `user time` metrics are broken for several Browsers.

I'm running wpt against a site I'm tunneling through ngrok.
The site included to marks. One is included in the HTML itself and the other one is included a loaded JavaScript file.

When running from Dulles with `firefox nightly` and `IE 11` everything seems to be fine.

FF nightly: http://www.webpagetest.org/result/150525_HT_AB1/1/details/
IE 11: http://www.webpagetest.org/result/150525_DN_ADE/1/details/

Unfortunately when choosing any other browser then FF nighty or IE 11  "User Timings" are shown in the waterfall legends but not displayed in the actual waterfall. And also the values are not displayed at all.

![screenshot 2015-05-25 08 12 41](https://cloud.githubusercontent.com/assets/962099/7792632/d861a3ec-02b5-11e5-9979-d6ce4ac0fa1d.png)

Chrome run : http://www.webpagetest.org/result/150525_BR_ADN/1/details/

If I can support somehow or can provide more needed runs for debugging let me know. :)

Thanks

**Comment by timmfin** [comment]
I'm also seeing this issue. And I suspect it is related to this:

```js
// In Chrome version 40, you _can_ JSON.stringify window.performance "arrays"

performance.getEntriesByType('mark')  

// returns an array of PerformanceMarks ...
[PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark, PerformanceMark]

JSON.stringify(performance.getEntriesByType('mark'))  

// will return JSON of PerformanceMarks
"[{"duration":0,"startTime":912.4529999999709,"entryType":"mark","name":"start_early_requestor_script"},{"duration":0,"startTime":912.7500000000168,"entryType":"mark","name":"end_early_requestor_script"},{"duration":0,"startTime":913.6689999999703,"entryType":"mark","name":"mark_api_verify_request"},{"duration":0,"startTime":916.6189999999688,"entryType":"mark","name":"end_early_requestor_and_call_api_verify_script"},{"duration":0,"startTime":981.4089999999851,"entryType":"mark","name":"start_project_with_deps_script"},{"duration":0,"startTime":1175.8570000000077,"entryType":"mark","name":"mark_would_have_requested_api_verify"},{"duration":0,"startTime":1178.1819999999925,"entryType":"mark","name":"end_project_with_deps_script"},{"duration":0,"startTime":1367.8089999999656,"entryType":"mark","name":"mark_api_verify_success"},{"duration":0,"startTime":1388.0499999999643,"entryType":"mark","name":"mark_api_verify_success"},{"duration":0,"startTime":1568.9699999999789,"entryType":"mark","name":"mark_create-button_success"},{"duration":0,"startTime":1569.3610000000149,"entryType":"mark","name":"mark_table_success"},{"duration":0,"startTime":1579.7759999999812,"entryType":"mark","name":"mark_all_success"}]"
```

```js
// But in Chrome 43, window.performance "arrays" stringify to empty objects

JSON.stringify(performance.getEntriesByType('mark'))  

// will return an array of empty objects
"[{},{},{},{},{},{},{},{},{},{},{},{}]"
```

And references [like](https://github.com/WPO-Foundation/webpagetest/blob/50b26ac9a2a62d56eee3a78ef1fe7915fe89b77f/agent/browser/ie/pagetest/PagetestReporting.cpp#L3734) [these](https://github.com/WPO-Foundation/webpagetest/blob/3fa0afc8c1826792d794de180a25187d12f82f90/agent/browser/ie/wptbho/wpt.cc#L29) make it seem like WPT relies on `JSON.stringify`-ing the marks array.

**Comment by timmfin** [comment]
And digging further, this I bet [this change that makes](https://developers.google.com/web/updates/2015/04/DOM-attributes-now-on-the-prototype) "JSON.stringify will no longer serialize DOM Attributes" to be the cause of the issue ([issue link](https://code.google.com/p/chromium/issues/detail?id=467366)).

Sounds like WPT needs to manually serialize each performance mark instead of relying on `JSON.stringify`-ing them.

**Comment by pmeenan** [comment]
Good catch, thanks.  Just finished up the fix and it looks to be working correctly again: http://www.webpagetest.org/result/150601_WC_bb595418107b1b3895dc555b82a4de37/1/details/

**Comment by timmfin** [comment]
Very nice, thanks!

**Comment by stefanjudis** [comment]
Great. Thanks folks!
