### ISSUE TITLE
Agent/test not ended/finished with using script

### ISSUE THREAD

**Issue by Vandrix** [WPO-Foundation/webpagetest#447]
When I'm using a script with WPT to navigate URL and accepting cookie notice, test is running endless until it times out.
The script I use:

logData 1
navigate    http://www.website.tld
click	value=accept

So, click is working and accepting cookie notice, but after the complete website is finished loading, the test is not ended. It is finally receiving a time-out after 240 seconds.
I've tested on public and private instance.

I've also tried things like setActivityTimeout 1000 but without any luck. I've tested multiple websites with cookie notices, same behaviour. Test is not ended (except by time-out from agent).

Any thoughts on this?

**Comment by pmeenan** [comment]
What do you want the click to actually do?  If it is something you want to measure then you need to use clickAndWait instead.  Is it a HTML notice or a modal dialog (dialogs won't be clickable)?

Your best bet if you want to test the site without a cookie notice is to see what cookie they set to indicate that the notice was accepted and use a setCookie command (before the navigation) to set the cookie before loading the page.

**Comment by Vandrix** [comment]
It's a HTML notice. This works:

navigate	   www.domain.tld
clickAndWait	href=#

But I get strange testresults. Document complete finished after the click. I don't want to measure time before cookie notice, only results after accepting the cookie notice.

When I'm doing this:

logData	   0
navigate	   www.domain.tld
clickAndWait	href=#
logData	   1

It's accepting cookie notice and loading website, but test is not finished succesfully and running endless until time-out kicks in.

I've also tried to sent cookie, but without success:

navigate	   www.domain.tld
setCookie	   http://www.domain.tld	viewed_cookie_policy = yes

It is possible to e-mail you the URL in private so you can check?

Thnx!

**Comment by Vandrix** [comment]
Updated the last one. Sent cookie first then navigate command

**Comment by pmeenan** [comment]
Yes, email me the latest script you are trying at pmeenan@webpagetest.org
