### ISSUE TITLE
Occasional HTTP/2 waterfall failures in FF

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#455]
Occasionally e.g. 1 out of 9 runs (but sometimes more) seeing missing waterfalls when testing HTTP/2 with Firefox

e.g.

http://www.webpagetest.org/result/150706_W6_2ace0e4c241ecc1d94599278b7d45ec7/1/details/

**Comment by pmeenan** [comment]
Does your server support both SPDY and H2?  Just wondering if in some cases it falls back to SPDY for some reason and that's why it is missed.

**Comment by andydavies** [comment]
Oh, good point - I'm using h2o with SPDY enabled, I'll disable it (or use nghttp2) and recheck

**Comment by andydavies** [comment]
Doesn't appear to be SPDY related, several of these tests have no waterfall http://www.webpagetest.org/result/150709_CS_a447b21280a674d4614b47044fb82536/

and SPDY is no longer enabled

```
 ./nghttp -nv https://http2.andydavies.me/interio
[  0.037] Connected
[  0.040][NPN] server offers:
          * h2
          * h2-16
          * h2-14
The negotiated protocol: h2
```

**Comment by andydavies** [comment]
Also seeing it using nghttp as a server http://www.webpagetest.org/result/150709_CS_a447b21280a674d4614b47044fb82536/

SPDY isn't enabled here either

```
 ./nghttp -nv https://http2.andydavies.me/interio
[  0.029] Connected
[  0.031][NPN] server offers:
          * h2
          * h2-16
          * h2-14
          * http/1.1
The negotiated protocol: h2
```

**Comment by pmeenan** [comment]
Thanks.  Server going to be up for a while to test against?  Could be the H2 detection code I put in place that looks for the magic signature before decoding.  Should be easy enough to track down with a failcase.

**Comment by andydavies** [comment]
Yes, it'll be up for a while - I'm still experimenting - https://http2.andydavies.me/interio/

**Comment by pmeenan** [comment]
I just pushed an updated build that I didn't think fixed anything but may have inadvertently (maybe an off-by-one on my manual counting of the length of the HTTP/2 magic signature).  I've Re-run ~100 tests and haven't been able to reproduce the missing results since the update.

Can you re-open if you see the waterfalls missing again?

**Comment by andydavies** [comment]
I haven't seen it again since this fix, but will keep an eye out
