### ISSUE TITLE
WPT Private Amazon instance - unusual .crx extensions loaded

### ISSUE THREAD

**Issue by darraghgrace** [WPO-Foundation/webpagetest#457]
Hi, 
I have an Amazon EC2 instance deployed to Amazon. I am seeing some unusual .crx (chrome extensions) activity in my results, I am seeing this in my waterfall results more and more. We think it might be something to do with the Chrome agent trying to update the google wallet extension or something.

Host: redirector.gvt1.com

![crx_timeline](https://cloud.githubusercontent.com/assets/2386816/8590804/adf54ba2-261b-11e5-81d8-eefce9a3ad45.png)
![crx_requestdetailsr](https://cloud.githubusercontent.com/assets/2386816/8590805/adfcec04-261b-11e5-996e-d2c2ae6c28eb.png)

UPDATE : We have just observed this crx extension on the main webpagetest.org site, so it is not limited to private AMI instances.

**Comment by koriolis** [comment]
You can see this CRX injection issue popping up on the following tests in webpagetest.org:

http://www.webpagetest.org/result/150709_C0_GAG/
![image](https://cloud.githubusercontent.com/assets/581175/8592128/bc6ba268-2624-11e5-996a-6034c6146ccf.png)

http://www.webpagetest.org/result/150709_YQ_JDQ/
![image](https://cloud.githubusercontent.com/assets/581175/8592366/a676c044-2626-11e5-9e8c-03dd18f2dbc9.png)

http://www.webpagetest.org/result/150709_V5_JKH/
![image](https://cloud.githubusercontent.com/assets/581175/8593227/c34f617e-262d-11e5-94fa-2da90795ba37.png)

**Comment by pmeenan** [comment]
Thanks, those extension updates are like whack-a-mole with Chrome :(  I have a fix ready and I'll roll out an agent update in a few hours (just trying to get a few HTTP/2 fixes in as well)

**Comment by pmeenan** [comment]
ok, wptdriver 221 is now available (and on the public instance) and fixes the issue: http://www.webpagetest.org/result/150709_TQ_ZG0/
