### ISSUE TITLE
wptdriver Scripting issues with DOMElement and DOMRequest

### ISSUE THREAD

**Issue by elliottjass** [WPO-Foundation/webpagetest#459]
It looks like neither the DOMElement or the DOMRequest command are working properly with wptdriver.  When the DOMElement command is used, results are rendered, but DOM Element time does not show:
http://www.webpagetest.org/result/150710_X5_RZF/ - IE9 - No DOM Element Time
http://www.webpagetest.org/result/150710_49_RVZ/ - IE8 - DOM Element Time

When DOMRequest command is used, all tests return "Test Error: Data is missing"

http://www.webpagetest.org/result/150710_PH_11EV/ - IE8 - DOM Request Time
http://www.webpagetest.org/result/150710_G3_11EY/ - IE9 - "Test Error: Data is missing"

Could we get these commands so that they work with wptdriver?  Thanks

**Comment by EliSnow** [comment]
I'm encountering similar issues as well. I've tried adjusting timeouts, using `setDOMElement` and using `requiredRequest` but I can't get the test to wait for a piece of the page to load.

Any ideas, @pmeenan?
