### ISSUE TITLE
Use mozjpeg for encoding screenshots

### ISSUE THREAD

**Issue by pornel** [WPO-Foundation/webpagetest#460]
Mozjpeg has ability to [compress black-on-white text without ringing](http://calendar.perfplanet.com/2014/mozjpeg-3-0/), and such text is very common on screenshots of webpages. 
This would make webpagetests's screenshots much cleaner (and smaller).

**Comment by pmeenan** [comment]
The change has been made for the desktop agents (mobile shells out to imagemagick so it's a bit more complicated and depends on people deploying).  That said, right now it is just using the default settings and flags.  If custom options need to be specified to have it de-ring the text then there is still some work to do.

The change also uses mozjpeg for the image compression check when evaluating a site.

**Comment by pornel** [comment]
Great, thank you!

Deringing is enabled by default in mozjpeg and I've verified that it works.
