### ISSUE TITLE
Unable to build wpthook with nghttp2 due to lack of version headers

### ISSUE THREAD

**Issue by kart** [WPO-Foundation/webpagetest#463]
The latest webpagetest agent has issues when building with visual studio. The nghttp2 dependency is supposed to contain two generated files: **includes/nghttp2/nghttp2ver.h** and **libnghttp2.pc** but the process to build those on windows (MinGW or Cygwin) isn't obvious and most likely broken.

I tried to use the Makefile.msvc, but one of the first thing it does is to look for configure.ac in the parent folder which doesn't exist. I worked around by cloning the original nghttp2 repo and generating the necessary files on Mac (using autoconf and configure) and moving the generated files over to windows.

Should we just generate them once and check it in instead of gitignor'ing them? If not, what's the process to generate them on windows?

**Comment by pmeenan** [comment]
Sorry.  Apparently the nghttp2 project had a gitignore to ignore those files so my versions didn't get checked in.
