### ISSUE TITLE
Waterfall graph are not generated for some sites using SPDY testing with Firefox?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#474]
Hey Pat,
been testing Wikipedia today with Firefox (tested different locations) and all waterfall graphs are empty. It looks like this (the screenshots/filmstrips looks ok though):
<img width="954" alt="screen shot 2015-08-17 at 20 46 43" src="https://cloud.githubusercontent.com/assets/540757/9321896/1f42bb18-4521-11e5-96b1-35fe18ccd891.png">

More runs:
http://www.webpagetest.org/result/150818_PP_6BW/

It works fine in other browsers.

I tested other sites that is using SPDY and they seems to work. However testing Facebook gives almost the same: http://www.webpagetest.org/result/150818_R4_6D3/1/details/

Is there a known problem or do you know how I should debug it?

Best
Peter

**Comment by pmeenan** [comment]
SPDY decode for Firefox isn't implemented.  I recently added HTTP/2 decode but I'm on the fence about bothering with SPDY since it's being phased out by all of the browsers now that HTTP/2 is standardized.

**Comment by soulgalore** [comment]
aha cool, then I know, thanks!
