### ISSUE TITLE
Docs: setUserAgent out of date

### ISSUE THREAD

**Issue by mhansen** [WPO-Foundation/webpagetest#476]
At https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting, under

setUserAgent, it says:
"Browser Support: IE, Chrome (no SSL), Firefox, Safari"

but looks like in 2.17 it was fixed in chrome for SSL:
https://github.com/WPO-Foundation/webpagetest/releases/tag/WebPageTest-2.17

"Fixed support for setUserAgent for Chrome HTTPS requests"

**Comment by pmeenan** [comment]
Fixed
