### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by callumacrae** [WPO-Foundation/webpagetest#481]
I'm attempting to follow these instructions: https://sites.google.com/a/webpagetest.org/docs/private-instances/node-js-agent/setup

Running wptdriver.sh with or without arguments causes a Segmentation fault:

```
vagrant@precise32:~/wpt/agent/js$ ./wptdriver.sh -m debug --browser android:0cfe40ea1408275a --serverUrl example.com --location Nexus5 --processvideo yes
node --max-old-space-size=4096 --expose-gc src/agent_main --serverUrl example.com --location Nexus5 --browser browser_android_chrome.BrowserAndroidChrome --deviceSerial 0cfe40ea1408275a --chromedriver /home/vagrant/wpt/agent/js/lib/webdriver/chromedriver/Linux i686/chromedriver-* --captureDir /home/vagrant/wpt/agent/js/lib/capture --processvideo yes
Segmentation fault
vagrant@precise32:~/wpt/agent/js$ ./wptdriver.sh
node --max-old-space-size=4096 --expose-gc src/agent_main --serverUrl http://localhost:8888 --location Test --browser browser_local_chrome.BrowserLocalChrome --chromedriver /home/vagrant/wpt/agent/js/lib/webdriver/chromedriver/Linux i686/chromedriver-*
Segmentation fault
```

Maybe I'm misunderstanding something. Any ideas?

I'm running node 0.12 installed through nvm on Vagrant's precise32 VM.

**Comment by pmeenan** [comment]
You might need to modify wptdriver.sh to not add the --max-old-space-size.  It's trying to give it 4GB of RAM if needed but that won't work so well on a 32-bit VM.

**Comment by callumacrae** [comment]
That seems to have solved it, thanks!

Quick unrelated question: I'm not getting a speed index in my results. How do I get it to work?

Thank you for the speedy response :)

**Comment by pmeenan** [comment]
Speed index is tied to video capture.  Make sure you have video capture enabled.  If you're using the node agent with a desktop chrome it won't work since video capture isn't supported there yet.  Might be able to do something when Chrome 46 comes out since dev tools supports capturing a filmstrip directly now.

**Comment by callumacrae** [comment]
I think I have video capture enabled, but I'm not sure. I'm using an Android device. I'm getting the following error in my wptdriver.sh output:

```
I Sep_07_12:27:11.202 wd_server.js:1300 WebDriverServer.<anonymous> : Video processing error: python lib/video/visualmetrics.py -i runtmp/0cfe40ea1408275a/video.mp4 -d runtmp/0cfe40ea1408275a/video --orange --viewport --force --quality 75 --histogram runtmp/0cfe40ea1408275a/histograms.json --timeline runtmp/0cfe40ea1408275a/trace.json failed, code 1, stderr[210] CRITICAL:root:Error extracting the video frames from /home/vagrant/wpt/agent/js/runtmp/0cfe40ea1408275a/video.mp4
CRITICAL:root:No video frames found in /home/vagrant/wpt/agent/js/runtmp/0cfe40ea1408275a/video
```

Is there a better place to ask these questions instead of polluting a github issue?
