### ISSUE TITLE
Repeat View using Emulate Mobile Browser - No video capture, no SpeedIndex

### ISSUE THREAD

**Issue by darraghgrace** [WPO-Foundation/webpagetest#483]
The video for repeat view when running tests with the 'Emulate Mobile Browser' option is not being captured, hence no SpeedIndex is calculated. It is fine for first view. 
Please see here for run with the emulate mobile browser enabled - http://www.webpagetest.org/result/150909_AM_9b67bf229a31864f8196e29cdefb877c/
And here for emulate mobile browser disabled - http://www.webpagetest.org/result/150909_1Q_b1102bb223ae3e80cc2243d8292af97f/

btw. This also started to happen on my Amazon EC2 setup.

**Comment by darraghgrace** [comment]
This has started working again today - http://www.webpagetest.org/result/150916_FW_698a0c3ce51729f53facd6c671490d26/

**Comment by pmeenan** [comment]
Hmm, my favorite kind of issue though I'd have preferred to find out what was going on.  When it was failing even the screen shot taken at the end of the test was still blank which tells me that the measurement was probably accurate but something else might have been going on.  Maybe a Chrome update or a change to the site fixed things or changed the timing enough that it works now.

**Comment by pmeenan** [comment]
Did it also start working on your EC2 setup?

**Comment by koriolis** [comment]
Yes. It's working there now.
Together with Darragh, I've actually trace it a little further down.
Apparently it was not affecting all locations.

Test from Australia EC2 location at 9/9/2015, 4:25:33 PM showing the issue: http://www.webpagetest.org/result/150909_HK_VZD/

Same test from Sydney, Australia (Anchor) location at 9/9/2015, 5:27:22 PM not showing the issue:
http://www.webpagetest.org/result/150909_HK_VZD/
