### ISSUE TITLE
[question] Current status on the archive functionality using S3 and AWS? 

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#484]
Hello @pmeenan ,
I've been going through the docs and the forum and I'm not sure what's the best way/best practice of handling archiving runs on S3. I've setup my instance on AWS using the AMI and that works perfect. Also configured the archiving and setup S3 with *archive_days=0* and yes, the test are moved to S3. 

To actually remove test, do I need to setup a job that actually runs */cli/archive.php* or is there some functionality that removes the old test data automatically?

To be able to find/keep old tests, I've setup a an extra volume using the elastic block storage that keep the logs, so if I drop the WebPageTest server, I create a new one and mount that volume again to get the logs. Is that the standard way to do it or is there a better way?

Best
Peter

**Comment by pmeenan** [comment]
Yes, you need to also run cli/archive.php in cron (or otherwise) to have it clean up.  I've been meaning to add that to the built-in scheduling but apparently haven't yet.

Good question on the logs - I don't think there's a best practice on that yet and what you have is probably the best way to do it the way things are right now.  Eventually it would make sense to add archiving support to the logs as well (and to compress them).

**Comment by soulgalore** [comment]
ok cool thanks!

**Comment by thomasbaldwin** [comment]
@pmeenan does this functionality still work? I get this error when I try to run it
![Screen Shot 2022-08-20 at 1 12 22 PM](https://user-images.githubusercontent.com/5099084/185758755-e1c6dc15-40b4-48c2-b949-f89ff6eb9367.png)
:

**Comment by pmeenan** [comment]
@thomasbaldwin try running it from inside of the cli directory.  Looks like the include assumes cwd is the same directory as the script.

**Comment by pmeenan** [comment]
Ignore the warning, it continued to scan and archive independent of those warnings.

The log indicates that there is 1 test result (220820_ZX_49) in the results folder but that it was "kept" (which usually means it has been accessed recently enough to not be a candidate for archiving.

**Comment by thomasbaldwin** [comment]
sounds good thanks Patrick. Looks like it did archive!
