### ISSUE TITLE
PTST not in UA for https

### ISSUE THREAD

**Issue by stevesouders** [WPO-Foundation/webpagetest#488]
It's great having "PTST" appended to the UA string for tests coming from WebPageTest. I use this to detect "bot" traffic on my web server. But I just noticed that "PTST" is missing if the URL is https, as shown in this test result - notice how it's there for request 1 on http but disappears for the remaining requests that are done over https:
    http://www.webpagetest.org/result/150919_PY_SZ8/1/details/

Can we get "PTST" preserved for https?

**Comment by pmeenan** [comment]
Should be doable (though maybe a touch convoluted).  Right now we support custom UA strings for HTTPS but for the PTST we just append it to whatever the UA string is.  To do it for HTTPS we will need to know before-hand what the UA string is going to be so we can override the whole thing (chrome-specific issue, IE and Firefox should already work - though maybe not for HTTP/2).

Might also be able to do it in the extension where it filters the outbound requests.  If so then that would be a lot cleaner.

**Comment by stevesouders** [comment]
Pat fixed this (except for Safari).
