### ISSUE TITLE
export.php produces JSON with control characters in it

### ISSUE THREAD

**Issue by kart** [WPO-Foundation/webpagetest#490]
Seems like there has been a recent regression that causes the exported HAR to contain control characters in it. Take a look at this: http://www.webpagetest.org/result/150921_QB_13GY/1/details/. When I run a JSON validator on the downloaded HAR, I see this:

```
$ python -m json.tool ~/Downloads/yahoo.com.150921_QB_13GY.har 
Invalid control character at: line 1 column 182020 (char 182019)
```

and sure enough, there are weird control characters in some of the resources:

```
{"name":"_P","value":"3.29.1^E_pl^C1^DA_v^C3.29.1^Dtest^C901^D_bt^Crapid^D...
```

On an older webpagetest version, I see that these control characters are appropriately JSON encoded to \uXXXX values.

**Comment by pmeenan** [comment]
My guess would be this: https://github.com/WPO-Foundation/webpagetest/commit/cdb0ba9d4f568a977d2d48419dba9508013fac22

I'll see if reverting it helps

**Comment by pmeenan** [comment]
Though presumably since it was your fix that shouldn't be the issue - let me make sure I actually pushed it to the public server
