### ISSUE TITLE
[Question] SpeedIndex, TTFB, SPDY & Firefox

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#493]
Hey Pat, I have a question on how TTFB and SpeedIndex is calculated for Firefox. 

The background. We use WebPageTest to test our site (that uses SPDY). We test using Chrome, Firefox and IE11 (so Chrome & Firefox uses SPDY and IE HTTP1). For Firefox the TTFB is always 0, but I guess that is because we are using SPDY.

We have seen a increase in our TTFB, which also reflects in the SpeedIndex for IE & Chrome, but the SpeedIndex score for FF has actually improved.

The TTFB looks like this:
<img width="404" alt="tffb" src="https://cloud.githubusercontent.com/assets/540757/10159083/612b5ea4-6696-11e5-9d9f-d83b2b06057c.png">

And the SpeedIndex:
<img width="614" alt="speedindex" src="https://cloud.githubusercontent.com/assets/540757/10159086/6c4fbf5a-6696-11e5-9129-2b7ef8aee659.png">

The SpeedIndex graph isn't perfect but it still seems that we have an increase for all other browsers than FF. Could that be because that the TTFB is unusable since it's 0 meaning we should stop testing with Firefox until we start using HTTP/2? Or is the SpeedIndex calculated completely standalone from the video and the figures are right?

Best
Peter

**Comment by pmeenan** [comment]
The Speed Index should be entirely from the video and independent of the TTFB.  If you can confirm that the video is captured correctly then Speed Index will also be accurate.

Yes, TTFB for Firefox (or IE) won't work if you are using SPDY and should start working once you move to HTTP/2.  I never implemented a SPDY decoder and with the protocol deprecated there's not a lot of reason to invest the time into it.

**Comment by soulgalore** [comment]
Yep cool I'll go back and check the HARs to see if I can see why things has gone better for FF. 

Thanks :)
