### ISSUE TITLE
setViewportSize doesn't change the size

### ISSUE THREAD

**Issue by pskelin** [WPO-Foundation/webpagetest#507]
Running this script does not change the browser viewport size:

```
setViewportSize	1280 1024
navigate	http://whatsmy.browsersize.com/
```

Here is the test run:
http://www.webpagetest.org/result/151015_FC_NRD/

And the resulting image showing the resolution is not changed:
http://www.webpagetest.org/results/15/10/15/FC/NRD/1_screen.png

**Comment by bigethan** [comment]
Using an AMI it worked for me:
![1_screen](https://cloud.githubusercontent.com/assets/627/12093686/9d36f29a-b304-11e5-9b37-e3600681e2d9.png)

Make sure your script is tab separated?

**Comment by pskelin** [comment]
Thanks, I was definitely missing a tab between the two arguments

    setViewportSize	1280 1024
    setViewportSize	1280	1024

Works fine now.
