### ISSUE TITLE
[Question] How is total size calculated?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#511]
Hi Pat,
this is not important just want to check if you know. When we compare runs (we use the private amazon thing) a couple of times we got a big different in total size between runs but the size doesn't reflect in the rest of the assets, it's just the total that differs, in this case >200kb.

<img width="803" alt="screen shot 2015-10-21 at 12 31 39 pm" src="https://cloud.githubusercontent.com/assets/540757/10635108/a5442730-77f6-11e5-852c-f2135302b031.png">

Could it be that the "other" miss to pick something or could it be a layout thing?

Best
Peter

**Comment by pmeenan** [comment]
Is total from "Bytes In"?  If so, that is measured at the socket level and will include certificates, SSL overhead and even resources that may not have been captured (in particular, any HTTP/2 push resources but I don't believe you use those).

It's also possible that Chrome is doing something in the background that got caught but I've really tried to kill all that activity.  If you could happen to capture a tcpdump of a case when you see it happen it would really help.

**Comment by soulgalore** [comment]
Cool, will turn on tcpdump and see if it happens again. Lets close this for now and I'll create a new issue when I have more data,
