### ISSUE TITLE
extend PTST string

### ISSUE THREAD

**Issue by stevesouders** [WPO-Foundation/webpagetest#514]
Currently, tests from WebPageTest add "PTST" to the User-Agent string to indicate tests are from WebPageTest. This is helpful for website owners to filter, block, and count this traffic in a special way if desired.

With the number of WebPageTest private instances growing (SpeedCurve, NCC, etc.) it would be nice if there was a way to add more information to the User-Agent about WHICH WebPageTest instance was initiated the request. For example, a website might want to only allow tests from the NCC instance. 

It would be great if settings.ini had something like "instance_id" which was appended to "PTST". For example:
    instance_id="NCC"
which would result in a UA string that contained:
    PTST-NCC

**Comment by zeman** [comment]
Also when using a script to set the UA it overrides and removes the "PTST" string. Would be great if it was appended to both the default UA string or one set via scripting.
