### ISSUE TITLE
Show user timing *measures* (in addition to marks)

### ISSUE THREAD

**Issue by stevesouders** [WPO-Foundation/webpagetest#516]
WebPageTest is awesome! It automatically shows my User Timing marks. Yay!

But I also have "measure"s which do NOT show up. 

Could you add the ability to show measures (in addition to marks)?

Test case:
1. Go to https://speedcurve.com/speedcurve/speedcurve/site/1/3/chrome/1/30/suae70f7or0xyz0azse4st94xty07m/
2. Open console and enter performance.getEntriesByType("measure"). Notice that there's a measure called "hero".
3. This WPT result for that URL shows the mark "heromark" but does NOT show the measure "hero": http://www.webpagetest.org/result/151101_DE_BG3/1/details/

**Comment by andydavies** [comment]
As a mark has a start time and duration, do you envisage it being displayed as a coloured band like DOMContentLoaded and Load currently are?

Or were you thinking of something else?

**Comment by zeman** [comment]
I don't think the "measure" band needs to be visualized on the waterfall as we don't know when the start time for the measure is, so therefore can't position it on the waterfall. It's more the utility of being able to pull out all the marks and measures from the WPT json.

**Comment by stevesouders** [comment]
Mark: I was wrong - we DO know the start time (thanks for clarifying Andy). 

Pat says there's no reason we can't do this - it just hasn't gotten to the top of the list yet. 

Andy: At a minimum, we should do as Mark suggests and include them in the HAR and other results APIs. Ideally we'd also show them in the UI, but I'm not sure how to do that. Imagine a measure that goes from navigationStart to onload. If you color in that band, it's going to overlay almost everything in the waterfall. Perhaps there could be a bar at the top of the waterfall (kinda where the User Timing marks are shown right now).

**Comment by pmeenan** [comment]
First pass will be to expose them in the API.  The waterfall is getting a
bit crowded so I'm not sure how well they will fit there.

**Comment by pmeenan** [comment]
Just deployed wptdriver 255 with the feature to the public agents: http://www.webpagetest.org/xmlResult/151216_X1_RZC/
