### ISSUE TITLE
Mismatch in page size and assets size

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#518]
Hey Pat,
first: love webpagetest :) Can you say it too many times? We've been running it now for a while and have some problems with the size of content types:

When I check the total size it seems to be right (almost 1mb fully loaded):
http://www.webpagetest.org/result/151102_BJ_1300/

But for the content breakdown something is wrong (HTML 880 bytes, too small JS and CSS etc) :
http://www.webpagetest.org/breakdown.php?test=151102_BJ_1300&run=5&cached=0

We use that data in the API to keep track of the size of the pages.

Gilles in our team also saw that we WPT also record a couple of requests that we guess come from Chrome (don't think I've seen those before):

<img width="1022" alt="screen shot 2015-11-02 at 8 26 32 pm" src="https://cloud.githubusercontent.com/assets/540757/10891764/0bdcaa6e-81a0-11e5-9ca7-fdd5c9015437.png">

Best
Peter

**Comment by pmeenan** [comment]
Thanks for the report.  tl;dr: I'll take a look at it today, updated code for Chrome testing released on Friday may not be working as well as I hoped.

HTTPS data in Chrome is ..... complicated.  For all browsers, the overall bytes comes from intercepting the socket I/O and just counting as data is written/received.  That part is simple enough and works across all browsers.

For the request level details, WPT needs to get to the underlying requests.  For everything except for Chrome it can intercept the data before it is encrypted and operate on the raw HTTP requests.  In the case of Chrome it can't intercept the encryption so it relies on Chrome interfaces for getting the request details.  Historically it used the dev tools data but that wasn't always accurate and the timings could be off by quite a bit so I've been working on switching to use the netlog data from Chrome's networking stack instead.  On Friday I switched over to use the netlog data but it looks like it's not catching all cases so there's some work to do.

Hopefully it's just a matter of missing a class of events (like if your traffic is over SPDY which may be a case I missed).

**Comment by pmeenan** [comment]
Sadly, the main wikipedia page was one I was using when I was working on the code so clearly I didn't look close enough :(

**Comment by pmeenan** [comment]
Should be fixed now, sorry about that: http://www.webpagetest.org/breakdown.php?test=151103_BH_11D1&run=1&cached=0

The new requests are something from Chrome directly and look to be part of safe browsing.  Looking to see if any command-line options can be used to disable it.

**Comment by pmeenan** [comment]
OK, I think the new set of command-line flags I threw at Chrome managed to kill the background safe browsing activity.  Expect the top-level bytes-in to go down a bit (~70kb in the test I looked at) as a result.

http://www.webpagetest.org/result/151103_GY_12E0/

**Comment by soulgalore** [comment]
thanks Pat for the quick fix, looks good now on our side!
