### ISSUE TITLE
Repeat view for Chrome and SPDY shows wrong TTFB?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#523]
Hey Pat, sorry for filing one issue per day, I've missed this before. It seems like the repeat view using Chrome for a site using SPDY get wrong TTFB:

<img width="942" alt="screen shot 2015-11-06 at 11 03 42 am" src="https://cloud.githubusercontent.com/assets/540757/10994350/18aa0a56-8476-11e5-81a0-d21560b1bbdc.png">

http://www.webpagetest.org/result/151106_FQ_GE0/1/details/cached/

We collect that data today but we don't use it so it isn't super important for us.
Best
Peter

**Comment by pmeenan** [comment]
Keep them coming.  They're real issues and fixing them helps everybody.

**Comment by soulgalore** [comment]
Sorry that we use SPDY, we still reach more users with SPDY than HTTP/2 but I guess it change early 2016 :)

**Comment by pmeenan** [comment]
No worries, expect to be pinged by the Chrome team to see if there is anything we can do to help with the migration.  There are a couple of big sites that are still on SPDY which is why I sent out the FYI :-)

**Comment by soulgalore** [comment]
I can add one thing: we get the same behavior when we script tests. We do a login and measure the load time and asset size for logged in users, but the timings are wrong and the JS size is wrong because we miss getting some javascripts that load late. I can reproduce the HAR with wrong timings with a simplified version like this:
<pre>
logData 0
navigate https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page

logData 1
navigate https://en.wikipedia.org/wiki/Facebook
</pre>

And the result looks like this: 
http://www.webpagetest.org/result/151109_S3_BMD/

When we run on our Amazon instance we fail getting the async loaded JS:
<img width="941" alt="screen shot 2015-11-08 at 2 40 05 pm" src="https://cloud.githubusercontent.com/assets/540757/11028757/9f8e25c8-86c1-11e5-8251-909dd76c3430.png">

We'll change to use IE_11 and HTTP1 for the sizes, then it is ok, but it would be cool to have correct timings for SPDY, if it isn't too much work!

Best
Peter

**Comment by pmeenan** [comment]
Should be much better now (both cases).

Repeat view: http://www.webpagetest.org/result/151109_5A_131N/

Multi-step: http://www.webpagetest.org/result/151109_VS_131S/
