### ISSUE TITLE
HAR generated by WPT contains an empty "entries" list

### ISSUE THREAD

**Issue by ghost** [WPO-Foundation/webpagetest#526]
Hi Patrick,

I have attached a HAR file (renamed as txt) for https://www.facebook.com generated with the empty "entries" list. This was generated from one of our private instances

Also, are there any best practices around configuring WPT instances on AWS EC2 at various locations (9 locations)?

Do let me know

Arun

[www.facebook.com.151113_BD_SH.txt](https://github.com/WPO-Foundation/webpagetest/files/34039/www.facebook.com.151113_BD_SH.txt)

**Comment by pmeenan** [comment]
Can you reproduce it on the public instance?  Just wondering if it has been fixed already because in a quick test it looks to be working.  Could be either the agent code itself which has had a lot of recent fixes for HTTP/2 or the server HAR export code.

**Comment by arunvsarma** [comment]
Hi,

No, i am not able to reproduce the issue on the public instance. We are using v2.17 of wpt. After some rounds of testing,  we found that something is wrong with the agent that the test runs on. It throws about 45% error. Is there a way we can find what the error can be?

Arun

Sent from my Sony Xperia™ smartphone

---- Patrick Meenan wrote ----

Can you reproduce it on the public instance?  Just wondering if it has been fixed already because in a quick test it looks to be working.  Could be either the agent code itself which has had a lot of recent fixes for HTTP/2 or the server HAR export code.

---

**Comment by padibona** [comment]
We also are having the same issue on our private instance,   we run 2.18. Not reproduceable in public,  .har are created correctly. Here is Example URL: https://store.kaspersky.com/store/kasperus/en_US/buy/productID.275345500/quantity.1 

I think I read something about UTF-8 and some conflict with php or something a while back. Was that ever rolled out for the private instances?

Pete

**Comment by padibona** [comment]
We also are having the same issue on our private instance,   we run 2.18. Not reproduceable in public,  .har are created correctly. Here is Example URL: https://store.kaspersky.com/store/kasperus/en_US/buy/productID.275345500/quantity.1 

I think I read something about UTF-8 and some conflict with php or something a while back. Was that ever rolled out for the private instances?

Pete

**Comment by padibona** [comment]
Sorry for double post. Actually, our issue is different. We are getting what seems to be a valid .har (at least according to WPT) but our app that is fed by the resulting JSON is catching the results as invalid JSON. Do you happen to know exactly which encoding type is used? I think this might be our implementation of Python 2.7's JSON.load(). I'll play around with it and get back to you.

Pete

**Comment by pmeenan** [comment]
By-spec, HAR files are supposed to use UTF8.  Older versions of php didn't directly support UTF8 though so depending on what version of php you're running on the server might influence it (though the code is supposed to fall back to using a non-native JSON library in that case).
