### ISSUE TITLE
Show custom metrics plots when configured statically 

### ISSUE THREAD

**Issue by stydentsa** [WPO-Foundation/webpagetest#536]
Hello,

currently plots are shown for custom metrics in test mode. They are not when statically defined via js file under /settings/custom_metrics folder.

Thanks
~B

**Comment by pmeenan** [comment]
Something else must be going on.  Are you sure the static metrics are actually being collected?  Functionally, the statically defined ones just get added to the tests as if they were dynamic ones.

The HTTP Archive instance runs with several custom metrics defined statically and the metrics show in the plot page: http://httparchive.webpagetest.org/graph_page_data.php?tests=151115_0_54J&medianMetric=loadTime

**Comment by stydentsa** [comment]
Yes, I have some measured values, but still no plots. I'll try play a bit more. Maybe I miss something.

**Comment by stydentsa** [comment]
Hi Patrick,

It is ok, I didn't look at the graph_page_data at all. Thanks, I am closing it.
