### ISSUE TITLE
Crash loading https://www.lonelyplanet.com/asia?_v=split-12-destinations-next

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#543]
Chrome testing fails when trying to load https://www.lonelyplanet.com/asia?_v=split-12-destinations-next

http://www.webpagetest.org/result/151208_PY_2f20bc5c062b03b0ae42eb73d2d5eae6/

Firefox appears to work fine: http://www.webpagetest.org/result/151208_PZ_ed9c37e08f6d041a88b4c8e2b8cc1239/

**Comment by jcreamer898** [comment]
Still seeing this issue, any progress @pmeenan?

**Comment by pmeenan** [comment]
Looks like it is causing Chrome itself to crash when it collects the tracing data for reporting.  I'm checking to see if I can narrow it down to a reproducible test case and open a Chrome bug on the issue.

**Comment by pmeenan** [comment]
The crash is happening when blink.user_timing trace events are enabled (which I need to leave enabled for some of the timing data that is inserted in there).

If you happen to control the site code, I'm not 100% sure that it is the cause of the issue but the user timing marks look like they are not setting the name to what you maybe thought they should.

If you open the page, open the dev tools console and use:
```
performance.getEntriesByType('measure');
```

You will see 2 marks with names that look like they were supposed to be the code that was going to run:

```
name: "function (){(0,n.mark)(this.loadCritical)}"
```

and 

```
name: "function (){(0,n.mark)(this.loadBelow),(0,n.measure)("mark_critical_to_below",this.loadCritical,this.loadBelow),(0,n.measure)("mark_critical","domContentLoadedEventEnd",this.loadCritical)}"
```

Granted, whatever you do there should never crash the browser but my guess is that somewhere in the tracing code the mark names are causing the json converter to go badly.

**Comment by jcreamer898** [comment]
Ahh, interesting... I'll give it a go.

**Comment by jcreamer898** [comment]
So, this is what I see when I run it in the browser? 

![](http://d.pr/i/16Esd+)

**Comment by pmeenan** [comment]
Sorry, copy/pasted the wrong one from my debugging, the measures look ok, it's the marks:

```
performance.getEntriesByType('mark');
```

**Comment by jcreamer898** [comment]
Commenting out my perf marks fixed it. Thanks a bunch!
