### ISSUE TITLE
where do i describe instance size?

### ISSUE THREAD

**Issue by babatundebusari** [WPO-Foundation/webpagetest#544]
I have looked at the /var/www/webpagetest/www/settings/settings.ini file and see no where to describe the instance size to be used for the web page test agents.

I know it defaults to c3.medium but i want to change that default to t2.micro.

Can anyone please help?

Thanks

**Comment by pmeenan** [comment]
I need to add it to the sample but looks like it uses [ec2_instance_size](https://github.com/WPO-Foundation/webpagetest/blob/master/www/ec2/ec2.inc.php#L52)

**Comment by babatundebusari** [comment]
Ok will try that now...also where do i specify the following

#1. whether to only `stop` or `terminate` webpagetest agents?
#2. adjust the time to `stop` ot `terminate` webpagetest agents?

Thanks

**Comment by pmeenan** [comment]
You can't stop the agents (at least using the built-in functionality).  The built-in code only knows how to launch and terminate.

**Comment by babatundebusari** [comment]
ok added this to settings.ini file and thist even caused application NOT to spin up test agent instance

`ec2_instance_size=t2.micro`

I had to comment or remove that part and restart nginx before test agent instance was then created

So did not work

**Comment by babatundebusari** [comment]
does not work

**Comment by babatundebusari** [comment]
Ok found it; you were not clear enough

edited the file `/var/www/webpagetest/www/ec2/ec2.inc.php` and changed `$size = 'm3.medium';` to any instance type i wanted

Thanks

**Comment by babatundebusari** [comment]
Just found out if instance size is set to anything else except `m3.medium`, this will not work
Only m3.medium will make it work
Have no idea this software was built this way
