### ISSUE TITLE
archive.php removes tests while not archiving

### ISSUE THREAD

**Issue by artursudnik** [WPO-Foundation/webpagetest#546]
I am still verifying this but it is alarming.

After 475d3c3b4356ebd052b422108891f9ee90b39900 commit I lost many tests and archive directory does not contain them.

**Comment by artursudnik** [comment]
I confirm that on WPT instance created from AMI this also happens. Tests are removed by script without archiving them.

**Comment by artursudnik** [comment]
I am not sure but this is possible patch:

diff --git a/www/cli/archive.php b/www/cli/archive.php
index debad14..225cd39 100644
--- a/www/cli/archive.php
+++ b/www/cli/archive.php
@@ -225,8 +225,8 @@ function CheckTest($testPath, $id, $elapsedDays) {

   $delete = false;
   if (!is_file("$dir/$test/testinfo.ini") &&
-      !is_file("$dir/$test/testinfo.json.gz") &&
-      !is_file("$dir/$test/testinfo.json")) {
+      (!is_file("$dir/$test/testinfo.json.gz") ||
+      !is_file("$dir/$test/testinfo.json"))) {
       $delete = true;
   } else {
       $elapsed = TestLastAccessed($id);

**Comment by pmeenan** [comment]
Argh, I'm not sure how I didn't catch that when I ran it but thank you for catching and reporting it (and super sorry for any tests you may have lost)

**Comment by artursudnik** [comment]
no problem :-)
