### ISSUE TITLE
Include test info in UA

### ISSUE THREAD

**Issue by rviscomi** [WPO-Foundation/webpagetest#548]
See http://www.webpagetest.org/forums/showthread.php?tid=14152

The test ID, run number, and cache state should be included in the UA string. This would make it possible to reconstruct a link to the test results page from the web server's logs. One practical application of this is using existing RUM tools for synthetic monitoring.

**Comment by pmeenan** [comment]
Should be easy enough to pull off but I would want to make it an optional opt-in feature.  I already have problems from time to time where sites break even using the current UA string and I'm a bit concerned that adding more to it might break even more sites.

Current thought is to have a new field that lets you specify additional (arbitrary) information to be added to the UA string and have it support a few substitution strings for things like test ID, run and cache state.

Something like: WPT/%TESTID%.%RUN%.%CACHE%

the resulting UA could look like:

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 PTST/257 WPT/160107_QC_87f4a655744f286f1cb4f49c71b8dbe6.1.0

**Comment by pmeenan** [comment]
That also solves any issues of knowing which test system the tests came from in case you are running a private instance, testing from public (and maybe using SpeedCurve).  Otherwise you wouldn't know which system the test ID was good for.

**Comment by pmeenan** [comment]
Also live on the public instance now.  API-only though.

Here is a sample test: http://www.webpagetest.org/result/160107_HS_XQN/

Passed uastring=WPT/%TESTID%.%RUN%.%CACHED%
(appropriately URL encoded)
Resulting UA String: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 PTST/258 WPT/160107_HS_XQN.1.0

With the run and cached state changing for each of the runs.
