### ISSUE TITLE
onload with logData 0

### ISSUE THREAD

**Issue by azweb76** [WPO-Foundation/webpagetest#555]
We have an application where we need to login to an SSO page, then navigate to our app. We have a script where we logData 0 -> login -> logData 1 -> navigate to app. When onload is used, it stops after onload of the login step even though logData is 0. Any way we can check onload only if we are logging data?

**Comment by johnrussell9983** [comment]
+1

**Comment by Verkurkie** [comment]
+1
Let me just add that we're using Marcel Duran's webpagetest-API wrapper to submit these tests. It's the API wrapper that offers the "--onload" flag and as such, this may not be a WPT issue...
Marcel, if you're watching this, feel free to add any comments/ideas! :)

**Comment by pmeenan** [comment]
By "onload" do you mean the setting to stop at onload (web10 in the API)?  The naming is horrible but there is a script command [setAbm](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setABM) that can be used to toggle the end state mode.

I'm not 100% sure it is supported in wptdriver (IE10+, Chrome, Firefox) but if not adding it would be trivial.
