### ISSUE TITLE
Issues with EC2 AMI

### ISSUE THREAD

**Issue by leumas95** [WPO-Foundation/webpagetest#559]
Hi @pmeenan,

Is the EC2 AMI still up to date (Specifically the Server ami-eb3542d1)
Here it states "No configuration required" - https://sites.google.com/a/webpagetest.org/docs/private-instances
So I am not sure what I am doing wrong but it can start Agents fine but all my tests say "Waiting at the front of the queue..." no matter how long I wait.
I have attempted to mess around with the settings but nothing seems to help.
I am very comfortable with AWS and EC2 so I don't think I could be messing up but I am sure everyone thinks that about themselves.

**Comment by pmeenan** [comment]
Yes, it should automatically sync to master on github as soon as it starts (and hourly).  The "no configuration required" does require that ec2 keys be provided through user data that have permissions to launch and kill instances.  You can see if that is causing the problem by checking /var/www/webpagetest/www/ec2/log on the server

**Comment by leumas95** [comment]
Hi Thanks for the fast response.
As I said it starts the WebPagetest Agents fine. So the link to EC2 is functioning, and there are no errors in the EC2 log. Just lots of Launching, Started and Terminated log messages.
The issue is the tests wont run they just have the "Waiting at the front of the queue..." message no matter how long I wait.
I have checked the instance that is started, it has the same subset and has a fully open security group so I am not sure what the issue is.

**Comment by pmeenan** [comment]
Can you tell if the agents ever connect to the server?  Take a look at the user data from one of the launched instances and see what it thinks the server address is and make sure firewall rules, etc are letting it through?

**Comment by leumas95** [comment]
I have checked the nginx access.log and the Agent is making regular requests to getwork.php 
Here is an example:

10.3.0.197 - - [03/Feb/2016:06:55:07 +0000] "GET /work/getwork.php?shards=1&reboot=1&location=ap-southeast-2,ap-southeast-2_IE11&screenwidth=1280&screenheight=1024&winver=6.1&winserver=1&is64bit=1&key=<Key>&software=wpt&version=2.19.0.260&ver=260&pc=IP-0A0300C5&ec2=i-e2ccc03c&dns=10.3.0.2&freedisk=5.270&GPU=0 HTTP/1.1" 200 5 "-" "WebPagetest Driver" 

And the user data all appears to be correct for the agent.

**Comment by pmeenan** [comment]
Do you know if that is the test location that the job went to (/getlocations.php shows it in the queue)?  Sorry about the slow reply because you basically have me stumped.

**Comment by leumas95** [comment]
Yeah has me stumped as well.

Asia Pacific (Sydney) is listed in the queue and the agent is in ap_southeast_2 so I would assume that there matching up. It also only started that instance after I added that test to the queue.

I just started one in a different region, it started up in that region fine. And it seems to work well. Probably should have tried other regions Sydney is just optimal for my use case. Could there be an issue with the AMI used for the Agents in ap-southeast-2?

**Comment by marckubischta** [comment]
I'm seeing the same behavior for agents started up in us-west-2. I'll try us-east-1 instead, maybe that will resolve my issues.

**Comment by marckubischta** [comment]
I think this problem was the result of my not realizing the agents would start up in the `default` SG. I don't know what other SG I expected them to appear in, but once I modified the server's SGs to allow traffic from `TCP 80 default` I am now seeing "Waiting behind 1 other test" so this is clearly an improvement.

**Comment by joewilson81** [comment]
I am having a similar issue with the `us-east-1: ami-fcfd6194` AMI.

When I start a test, it hangs with the "Waiting at the front of the queue..." message.

From `/var/www/webpagetest/www/ec2/log/`:
```
16:57:27 - Launching m3.medium ami ami-4a84a220 in us-east-1 for us-east-1,us-east-1_IE11 with user data: wpt_server=ec2-54-224-248-255.compute-1.amazonaws.com wpt_loc=us-east-1,us-east-1_IE11 wpt_key=98adad2e5705aebecf193d50e39bef80fd87255b
16:57:27 - Error: Launching EC2 instance. Missing key or secret
```

I have a user set up via IAM with the `AmazonEC2FullAccess` policy. The user data for my EC2 instance is:
```
ec2_key=KEY_FOR_IAM_USER
ec2_secret=SECRET_FOR_IAM_USER
headless=0
```

These user data values are not showing up in the server log.

Any idea what I'm doing wrong?

**Comment by dominicmcginnis** [comment]
I'm having a similar issue.  I've got a WebPageTest agent launched, but everything is stuck.  I can see get locations shows:

Location ID	Description	Idle Testers	Total Tests	Being Tested	High Priority	P1	P2	P3	P4	P5	P6	P7	P8	P9
us-west-2:Chrome	US West (Oregon) - Chrome	0	3	0	3	0	0	0	0	0	0	0	0	0
us-west-2:Firefox	US West (Oregon) - Firefox	0	3	0	3	0	0	0	0	0	0	0	0	0
us-west-2:Safari	US West (Oregon) - Safari	0	3	0	3	0	0	0	0	0	0	0	0	0

If it helps, my Server has the following SG's:
Ports	Protocol	Source	FromPleasanton	default
80	tcp	209.220.148.0/24, 209.220.148.28/32	✔	 
22	tcp	209.220.148.28/32, 209.220.148.0/24	✔	 
443	tcp	209.220.148.0/24, 209.220.148.28/32	✔	 
All	All	sg-cd4c5daa	 	✔


My agent uses the default:
Ports	Protocol	Source	default
All	All	sg-52227f35	✔

**Comment by leotsem** [comment]
I'm having a similar issue. The agent is launched at `eu-west-1b` (ami-a3a81dd0), completed a few tests and then stucked. 
I can see the pending tasks at `getLocations.php`, the UI says `Waiting at the front of the queue...` and the server logs just mention the successful launch of the agent.

**Comment by leotsem** [comment]
Interestingly, the agent was terminated after ~1h and a new agent was immediately launched on the same region and managed to pick up the remaining tests. 
Here's the server log:
```
12:23:03 - Launching m3.medium ami ami-a3a81dd0 in eu-west-1 for eu-west-1,eu-west-1_IE11 with user data:...
12:23:04 - Instance ... started: m3.medium ami ami-a3a81dd0 in eu-west-1 for eu-west-1,eu-west-1_IE11 with user data:...  
13:15:08 - Terminated instance ... in eu-west-1
13:15:08 - Launching m3.medium ami ami-a3a81dd0 in eu-west-1 for eu-west-1,eu-west-1_IE11 with user data:...
13:15:09 - Instance ... started: m3.medium ami ami-a3a81dd0 in eu-west-1 for eu-west-1,eu-west-1_IE11 with user data:...
```
