### ISSUE TITLE
Possible to disable password bubble for Chrome?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#562]
Hello Pat,
we use WebPageTest to test pages as a logged in user. The scenario is simple:
```
logData 0
navigate https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page

setValue        name=wpName     XXXX
setValue        name=wpPassword YYYYY
submitForm      name=userlogin

exec document.body.innerHTML = "";
sleep	5

logData 1
navigate https://en.wikipedia.org/wiki/Facebook
```
And we try to measure the start render time for the user when she hits the next page, but I'm not able to get rid of the "remember the password" bubble from Chrome, so our start rendering happens when that goes away a couple of 100 ms after we start.

<img width="506" alt="screen shot 2016-02-07 at 4 03 56 pm" src="https://cloud.githubusercontent.com/assets/540757/12873057/795388c8-cdb4-11e5-9b4b-1cf75e75c27b.png">

I've seen that WPT has the --disable-save-password-bubble switch but could it be that [it only works for Mac OS X](http://peter.sh/experiments/chromium-command-line-switches/)? Do you know the best way to handle it?

Thanks
Peter

**Comment by pmeenan** [comment]
It should work for all versions.  I'll see if I can figure out why it isn't working or if there is another way to block the password manager.

**Comment by pmeenan** [comment]
Not sure why but when they enabled the Aura UI manager they switched it to always run which means that flag only works with Mac.

It looks like it is [configurable through policy settings](http://www.chromium.org/administrators/policy-list-3#PasswordManagerEnabled), I just need to figure out how to get the settings to apply to a machine that is not connected to AD.

**Comment by pmeenan** [comment]
ok, looks like that worked: http://www.webpagetest.org/video/compare.php?tests=160209_36_8244aa4e49b1d9bb8f95b62fab0ccd54-r:1-c:0

**Comment by soulgalore** [comment]
perfect thanks a lot @pmeenan !!!
