### ISSUE TITLE
Add support for testing "mini" Android browsers

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#565]
Specifically Opera Mini and UC Mini

Without remote debug interfaces it will be limited to data we can collect from video capture, tcpdump and logcat:
- Start Render
- SpeedIndex
- Visually Complete
- Bytes In
- Bytes Out
- Filmstrip
- First/Repeat view

Using a start page that flashes orange and then redirects to the page to be tested will allow for accurate video timings and can be launched with intent.

Things that will NOT be possible:
- Page timings (load time, DOMContentLoaded)
- Request timings/waterfall (in the case of the mini browsers they may not even exist in the tcpdump)
- Custom metrics
- Scripting of any kind
- Content blocking/SPOF (even with hosts file access, the mini browsers load pages remotely)

Beyond the agent support, there will be some server changes necessary to present results from video-only tests.

**Comment by cesarv76** [comment]
Hi,

I need to add Opera Mini to a WebPageTest private instance I'm setting up. Do you have any information on how to achieve this?

Thanks!

**Comment by pmeenan** [comment]
You should just need to Install the browser (and go through the initial setup) and then add it to the browsers list on the server.  Something like:

browser=Moto G4 - Chrome,Moto G4 - Chrome Canary,Moto G4 - Chrome Beta,Moto G4 - Chrome Dev,Moto G4 - UC Browser,Moto G4 - UC Mini,Moto G4 - Opera Mini,Moto G4 - Firefox
