### ISSUE TITLE
Issues with using S3 for storage

### ISSUE THREAD

**Issue by beenanner** [WPO-Foundation/webpagetest#570]
I'm running the private WPT 2.19 and it appears that results are immediately sent to S3 instead of waiting the pre-defined amount of time in the [settings.ini config](https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample#L160). Does local archiving need to be configured as well? I've uncommented the following replacing access key, secret, and bucket with my credentials.

archive_s3_server=s3.amazonaws.com
archive_s3_key=~my access key~
archive_s3_secret=~my secret~
archive_s3_bucket=~my bucket~
archive_days=7

 It also appears that the console.log that is captured and displayed on the screen_shot.php page from Chrome isn't available after the archiving.

**Comment by pmeenan** [comment]
Is the immediate uploading causing issues?  The logic uploads immediately when a test finishes and then deletes the local copy after the configured delay.

**Comment by beenanner** [comment]
I don't believe so. I'm misunderstood on the archiving no biggie if it uploads immediately I just didn't want it constantly reading from my S3 account for recent tests. ;-) So no bugs there. Would you know the best way to debug why the console.log isn't showing on the screen_shot.php page? I see the console_log.json.gz on the WPT server in the results directory.

-rw-rw-rw- 1 wpt-user wpt-user    28 Feb 24 20:15 2_console_log.json.gz

**Comment by beenanner** [comment]
Closing issue since it isn't really an issue just a misunderstanding of the archive functionality.
