### ISSUE TITLE
Windows 8.1 agent doesn't work correct after restart

### ISSUE THREAD

**Issue by Evgeni009** [WPO-Foundation/webpagetest#571]
Hi 
I have a problem with keeping agent live on Windows 8.1 after restart my computer. In “\Windows\Start Menu\Programs\Startup” folder I add wptdriver.exe shortcut but after restart nothing agent doesn’t start.
Do you have any ideas?

**Comment by pmeenan** [comment]
I've found task scheduler to be a lot more reliable than the startup folder on recent Windows releases.  You need to create a new task that runs at highest privliges that is triggered at the time of login for the user that auto-logins and also configure it to NOT automatically kill the task after 3 days.

**Comment by Evgeni009** [comment]
Thank you now work.
