### ISSUE TITLE
PHP7 support?

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#575]
Hi Pat,

Curious if you've done any testing with PHP7 and if that has much impact on throughput and lowering the resources needed by processes like workdone.php and resultimage.php?

Cheers,
Mark

**Comment by pmeenan** [comment]
Haven't looked yet. Are you seeing long times in those? Wonder if resultimage could be made faster by shelling out to imagemagick or pre-creating and caching thumbnails if you use the same size a lot. 



    _____________________________

**Comment by zeman** [comment]
<img width="903" alt="screen shot 2016-03-07 at 9 37 41 am" src="https://cloud.githubusercontent.com/assets/204268/13556843/570351fe-e448-11e5-9903-30f659753212.png">

Here's where we spend the most time according to New Relic with resultimage.php being number two with 26% of the time. We have the resultimage.php behind a cdn so images are cached after the initial request/generation.

<img width="893" alt="screen shot 2016-03-07 at 9 40 14 am" src="https://cloud.githubusercontent.com/assets/204268/13556871/cc6c7330-e448-11e5-9a21-aefecc63a101.png">

workdone.php is 46% of the time and within that it's DevToolsGetCPUSlices that consumes the most time.

**Comment by pmeenan** [comment]
Sorry, I wasn't thinking.

resultimage.php is where the agents upload individual files (screen shots for video, etc).  It should mostly be I/O bound but it probably does a little more heavy-lifting than it really needs to.  It does some validation on the upload to make sure it's really a valid test but the current check may be heavier than it needs to be.  Additionally it touches and chmod's the uploaded file which may not be necessary.  I'll add a little profiling and try a couple of tweaks to see if some of the overhead can be eliminated.  None of it is anything PHP 7 would help with though.  It's all I/O and not compute.

The cpu slices in workdone.php is something I'm looking at pushing down to the agents which will eliminate it entirely (it is what calculates the timeline data below the waterfall).  Pushing that work to the edge is the best way to scale it (and is one of my biggest cpu consumers as well).

**Comment by zeman** [comment]
Latest release now supports PHP7.
