### ISSUE TITLE
Add "block" query parameter to prefill input fields

### ISSUE THREAD

**Issue by stefanjudis** [WPO-Foundation/webpagetest#586]
Hey hey,

I'm about to build a Chrome Extension which can easily create WPT runs with blocked third parties. That for I followed the way Spof-o-matic is working and wanted to easily link to WPT.

Now I discovered that I can't "prefill" the `block` option via query param.

Would you be open for a PR for that? :)

I checked the code and it should be fairly easy to do.

**Comment by pmeenan** [comment]
Sure






On Wed, Mar 23, 2016 at 4:23 PM -0700, "Stefan Judis" <notifications@github.com> wrote:












Hey hey,



I'm about to build a Chrome Extension which can easily create WPT runs with blocked third parties. That for I followed the way Spof-o-matic is working and wanted to easily link to WPT.



Now I discovered that I can "prefill" the block option via query param.



Would you be open for a PR for that? :)
