### ISSUE TITLE
Pipeline the mobile agent tests

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#593]
The mobile agents only spend ~50% of their time actually running a test because everything is serialized:
- Check device
- Fetch work
- Prep device
- Run test
- Collect results
- Post-process results (particularly video but soon dev tools as well)
- Upload results

The post-processing and upload can be run as a background task while the next job is started which will significantly improve utilization.

**Comment by giovanisp** [comment]
Wouldn't post-processing (specially video) affect the CPU utilization graphic if a new test runs while the agent is working?

**Comment by pmeenan** [comment]
On mobile there is a host computer tethered to the phone.  The actual test is run on the phone (where the CPU matters) and the post-processing is done on the host computer.  Right now, even with 20 devices connected to a single i7 desktop the host computer rarely uses 50% CPU.
