### ISSUE TITLE
"PTST" missing when setting a UA string via a script or mobile=1

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#597]
Using agent 270

We're seeing that the "PTST" user agent string is missing when setting a user agent string via scripting and also putting Chrome into emulation mode using mobile=1.

Should we be expecting to see "PTST" when using mobile=1 or is it not possible?

Replicated on public WPT here, mobile emulation turned on: http://www.webpagetest.org/result/160401_0W_19Y0/1/details/#request1

Also "PTST" is often missing when setting the UA via a script:
http://www.webpagetest.org/result/160401_1H_1A2P/1/details/#request1

**Comment by pmeenan** [comment]
It's probably just a logic conflict because mobile emulation specifies user agent strings and I use them verbatum without adding the PTST string to the end.  Logic shouldn't be too hard to fix.
