### ISSUE TITLE
Feature request: easier to follow releases on auto updated server/agents

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#599]
Hi Pat,
we run one server and one agent that we have constantly up and running on Amazon. We have configured auto updates using http://cdn.webpagetest.org/. For me it's not perfectly clear when our agents are updated and with what code. Am I missing something or is there a way to see that except checking the actual code?

Things that would help me:
- A changelog. Yes I check Github and I follow the project but it would make it easier for me to browse through a changelog, for example to see when bugs are fixed or when browsers are updated to the latest version. Now I see that in the code on Github.
- Showing the version/commit/release in the HTML source on the WebPageTest server + API, so I can easy see which version we are using.

Best
Peter

**Comment by pmeenan** [comment]
I'll see about adding a record of when/what updates are done and expose it on the /install page. The updates happen hourly and are in the cron/* files.  The code that calls into that is triggered from getwork.php when the agents poll for work (so no agents would mean no updates).

I'll have to check but I may also have a cron job on the AMI that calls getwork.php with a bogus location just to make sure it still updates even when no agents are present.
