### ISSUE TITLE
Add Ability to Edit Label

### ISSUE THREAD

**Issue by jakejgordon** [WPO-Foundation/webpagetest#600]
As a user who is logged in
I can edit the Label of one of my test runs
Because I usually forget to set this and it's really hard to work with and compare historical test runs if you forget to add a label

I literally almost always forget to set a Label and if I could edit the labels on test runs that I made that would be amazing!

**Comment by andydavies** [comment]
You can edit it from the Test History page - hit the edit link in the label column

**Comment by sergeychernyshev** [comment]
Confirmed - it works.

You have to click "Save" button though as hitting enter in that field tries to submit the wrong form.

@jakejgordon, should we close this ticket?

**Comment by jakejgordon** [comment]
I must be missing something. I don't see an edit link in the label column:

![image](https://cloud.githubusercontent.com/assets/3045786/18552217/74dc066c-7b29-11e6-8c77-387b58af1d0e.png)

**Comment by sergeychernyshev** [comment]
Hmm, I see them there. I wonder if that's because I log in with forum account and not Google account. @pmeenan, any idea what's up here?
