### ISSUE TITLE
Disable prefetching of content using the flag: --prerender=false

### ISSUE THREAD

**Issue by UrmiB** [WPO-Foundation/webpagetest#604]
Hi,

Webpagetest allows the use of the prerender flag for Chrome to disable prefetching of content. This allows the user to capture the byte size metric without including the prefetched content.

Is it possible to use flags like this on SpeedCurve as well? It would be really helpful to have this.

Thanks,
Urmi Bhayani

**Comment by pmeenan** [comment]
Sorry, wrong place to ask.  You need to contact SpeedCurve and ask them if they can expose the Chrome command-line options (or this one specifically as an option).

**Comment by zeman** [comment]
Is it possible to pass Chrome command-line options via WPT scripts?

**Comment by pmeenan** [comment]
No but shouldn't be too hard to add if you need it. Runtest.php could pull it out. 






On Fri, Apr 22, 2016 at 8:18 AM -0700, "Mark Zeman" <notifications@github.com> wrote:












Is it possible to pass Chrome command-line options via WPT scripts?

**Comment by UrmiB** [comment]
Hi,

Can you tell me what the next steps here would be? Does this need to be
done via scripting in each individual URL or is there another way to do it
for all URLs simultaneously? It would be good to have a quick way to do
this, rather than add a script to every URL.

Thanks,
Urmi

**Comment by pmeenan** [comment]
@zeman filed an issue to allow the test options to be set by scripts which would be one way to get it to work through their existing interfaces.  FWIW, the scripts can do URL substitution so in theory you could just use a single script for all of the urls you'd want to apply it to.

setTestOption commandLine --whatever-to-disable-prefetch
navigate %URL%

If that doesn't or won't meet your needs (once actually implemented) you should take that up with SpeedCurve (this isn't a project page for SpeedCurve)
