### ISSUE TITLE
Trace & Timeline viewer pages broken in stable & nightly versions of Chrome, Firefox, and Safari

### ISSUE THREAD

**Issue by jfsiii** [WPO-Foundation/webpagetest#607]
The [timeline viewer][tlv] and [trace viewer][trv] pages show white screens and JS errors in both the stable & latest versions of the major browsers.

Chrome (& Canary) fail with: `inspector.js:10565 Uncaught TypeError: Object.observe is not a function`

Firefox (& Developer Edition) and Safari (& Technology Preview) fail with: `TypeError: document.registerElement is not a function`

The Chrome errors can likely be addressed by updating to the latest code. The URL seems to indicate the code is from November 4th, 2015. The code to [remove Object.observe landed November 17th, 2015][roo]. 

The errors for the other browsers might fixed by loading the [WebComponent polyfills][wcp].

[tlv]: http://static.webpagetest.org/chrome/inspector-20151104/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?test=160425_FF_15K6&run=1&cached=0
[trv]: http://www.webpagetest.org/chrome/trace.php?test=160425_FF_15K6&run=1&cached=0
[roo]: https://groups.google.com/a/chromium.org/forum/m/#!topic/chromium-checkins/d5x5mdu6KkY
[wcp]: http://webcomponents.org/polyfills/

**Comment by pmeenan** [comment]
Timeline is fixed now: https://github.com/WPO-Foundation/webpagetest/commit/8ab0fbd8f72dbe3d24713e87522be2b8e9da4236

Working on trace next.
