### ISSUE TITLE
downloadable version of your EC2 instances?

### ISSUE THREAD

**Issue by aafische** [WPO-Foundation/webpagetest#610]
Hi.  I wanted to download one your EC2 instances, so I can run it on a virtual machine inside a corporate network.

But per Amazon's policy, "you cannot export an instance unless it was previously imported into AWS [by you]".

Any chance you could make disk image available for download?

**Comment by pmeenan** [comment]
The agents are all Windows and the EC2 image wouldn't really make sense to run outside of EC2 (ignoring the Windows licensing issues).  The only real benefit for the EC2 instances is that they self-configure from the user data string but if you aren't running on EC2 that doesn't make sense.

Once you have a working Windows install/image, the additional agent setup steps are pretty small: https://sites.google.com/a/webpagetest.org/docs/private-instances#TOC-Test-Machine-s-1
