### ISSUE TITLE
Chrome CPU throttling

### ISSUE THREAD

**Issue by iLaurens** [WPO-Foundation/webpagetest#611]
As an experimental feature, Chrome has the ability to do CPU throttling. This is really useful for getting an even closer picture when emulating mobile devices. Could this be added to WPT in a way that it is possible to run Chrome tests with the various available throttle slowdown settings?

https://code.google.com/p/chromium/codesearch#chromium/src/out/Debug/gen/blink/platform/inspector_protocol/Dispatcher.cpp&sq=package:chromium&l=89&rcl=1461842418

**Comment by IDSFN** [comment]
i can't see CPU throttling anymore, I've heard that google decides to remove it ?

**Comment by pmeenan** [comment]
A better option since we control the whole OS would be to use the power management API's to set a lower max CPU power state.  That would also work across browsers.

**Comment by IDSFN** [comment]
@pmeenan yeah sure, but we need to mimic the memory too!

in linux you can use cpufreq which let you control your cpu clock speed
`sudo apt-get install indicator-cpufreq`
you can go down till 0.93GHZ

if you know a way to control Memory, please share

**Comment by pmeenan** [comment]
Memory isn't part of this issue and trying to mimic memory across platforms (Windows to Android) will not provide useful information.  Reducing memory is pretty easy, you can just allocate a chunk of non-pageable memory and be done with it.

For windows the power management controls can control the scheduling in 1% increments all the way down to 1% and should be good enough for making a faster desktop device look like it has a weaker CPU (what those actual targets are for any given device would be an exercise for the user).

**Comment by abarre** [comment]
I just would like to know if any attempt has been done on this feature.
From my external view, it seems easier to leverage on the Chrome CPU throlling.

<img width="676" alt="capture d ecran 2017-05-15 a 10 34 33" src="https://cloud.githubusercontent.com/assets/928701/26049105/1e168876-395a-11e7-82e2-8adf19760411.png">

**Comment by pmeenan** [comment]
wptagent (the new cross-platform agent) does CPU throttling on Linux but it is a fixed rate to match the mobile device being emulated (and transparent).

I'm still testing to make sure the Chrome throttling works well (found at [least one bug](https://bugs.chromium.org/p/chromium/issues/detail?id=720093) that is getting fixed for 59 or 60).

Once the Chrome throttling is verified to work reliably then it will be used for mobile emulation (transparently) and will be configurable through the API as a parameter.  I'm not sure that I want to expose the setting itself directly to the UI once it is enabled.

**Comment by pmeenan** [comment]
FYIW, the mobile device profiles in WPT now [include calibrated CPU throttling rates](https://github.com/WPO-Foundation/webpagetest/commit/0c16a5b719cf7defde98cb96260b993d74bd972f) for all of the devices.  Those are based on the cgroup throttling (Linux) though and will be refined once the Chrome throttling is ready.

**Comment by abarre** [comment]
Hi @pmeenan ,

I see that Chrome 61 ships the CPU throttling. Did you do any progress on this area ? Also, you mentioned the CPU throttling for Linux agent. Is there anything on Windows ?

**Comment by pmeenan** [comment]
wptagent (the new cross-platform agent) will CPU throttle on all platforms.  On Linux it will use cgroups and on Windows and Mac it will use the dev tools throttling.  For wptagent it is tuned to match the device being tested but can also be specified at runtime with "throttle_cpu=5.1" (or however much you want to throttle it).

I don't currently have plans to implement throttling in wptagent as I'm hoping to migrate all testing to the new agent but it can easily be added if needed.
