### ISSUE TITLE
Timeline (view) doesn't work - Object.observe JS error

### ISSUE THREAD

**Issue by stevesouders** [WPO-Foundation/webpagetest#617]
Can no longer open the timeline viewer. 

Example test: http://www.webpagetest.org/result/160509_JS_1a6661e6b202aa14c602be4d2614b1bf/

JS error: inspector.js:10565 Uncaught TypeError: Object.observe is not a function - inspector.js:10565

Chrome Version 50.0.2661.94 (64-bit) on MacOS

Happens on all results.

**Comment by pmeenan** [comment]
Think this is the same as #607 which I hadn't seen happening but it looks to be an issue with the latest Chrome update.  I'll update the embedded viewer in the morning which should fix it.
