### ISSUE TITLE
Loading bar fires off start render on Chrome (sometimes)

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#623]
Hi Pat,
we run tests on Chrome, connectivity 2G and emulating mobile. Sometimes the start render catches a small (I think) loading bar.

It only happens sometimes, check the drops in start render times:
<img width="1231" alt="screen_shot_2016-05-17_at_10 58 26_am" src="https://cloud.githubusercontent.com/assets/540757/15403639/4c0c642a-1dfa-11e6-883a-4a6ea1cbe1d7.png">

And when you look at one of those drop, the start rendering time correlates to the small grey bar:
<img width="456" alt="screen_shot_2016-05-17_at_10 59 51_am" src="https://cloud.githubusercontent.com/assets/540757/15403645/4fbc7a60-1dfa-11e6-80fb-4980b027274f.png">

Here's an example when it happens:
http://wpt.wmftest.org/result/160515_3T_4/

And screenshots:
http://wpt.wmftest.org/video/compare.php?tests=160515_3T_4-r:1-c:0

Best
Peter

**Comment by pmeenan** [comment]
Any chance you can share the viewport size you are emulating and the raw image for one of the screen shots?  The video processing code has logic to ignore a set number of pixels on each edge of the screen and it may need some tweaking.

It could also be the slight gray borders on the left and right of the image which may also be a result of the viewport emulation and the browser window not being sized exactly right.

**Comment by soulgalore** [comment]
Ah sorry. So we don't set anything extra, we just use set "emulateMobile" to true in the nodejs API, so I guess it will default for Iphone 6 with default viewport.

Not 100% sure how I get hold of the raw image the easiest way, would this one do? 
![frame_0040](https://cloud.githubusercontent.com/assets/540757/15407359/afc7465a-1e0a-11e6-9b77-b8d0bf64c1d6.jpg)

**Comment by zeman** [comment]
We're seeing this in mobile emulated tests as well. https://github.com/SpeedCurve-Metrics/SpeedCurve/issues/89

**Comment by pmeenan** [comment]
@zeman is it something you can reproduce 100% of the time?  A failcase would make debugging it infinitely easier.

**Comment by zeman** [comment]
@pmeenan trying to track some examples down. I suspect it's interment. :(

**Comment by pmeenan** [comment]
Any chance you can try with the 292 agent?  I tweaked things so it will be a little more generous with a border around the whole viewport (I think it may have been the gray edges that triggered it).

**Comment by soulgalore** [comment]
I'll try asap when I get back from my vacation :)

**Comment by soulgalore** [comment]
This looks much better now, thanks!
