### ISSUE TITLE
Reconfiguring ipfw queue with PLR=0 has significant measurement impacts

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#633]
As already reported [in a forum thread](http://www.webpagetest.org/forums/showthread.php?tid=14118), we found significant changes in measurements since version 2.15.
This problem was introduced with 022b5a86b2f3d8e8333ffbf21bd4132b9e8bcff5.

![PLR Issue](https://cloud.githubusercontent.com/assets/5701519/15815201/ca4ee0ea-2bcb-11e6-9aab-35208d8d3e09.png)
We are running two agents testing a website every 5 minutes, both with DSL 6000 throttling (6000/512 Kbps, 50ms Latency) and with PLR 0.
* The blue line is a 2.15 based agent
* The green line is a 2.18 based agent which was patched in between (see below).

We added logging for all "ipfw" commands executed by the two agents.
With the referenced commit, the PLR is set with `ipfw queue 1 config plr 0` and  `ipfw queue 2 config plr 0`, while before no extra command was executed for plr=0.

I modified the 2.18 based agent so the queue config commands for setting PLR are not executed anymore. I deployed this modified version  on 3rd June 2:00pm. As the graph shows, the measurements are much more stable, faster, and matching the 2.15 behavior.

So the queue config is clearly messing something up. From  the logging I can see that the queues are configured before with `ipfw.exe queue 1 config pipe 1 queue 100 noerror mask dst-port 0xffff`. Maybe this configuration is overwritten? I'm not really familiar with ipfw/dummynet.

**Comment by nilskuhn** [comment]
@pmeenan If that would be helpful we could measure with one of your actual agents, too. We could use it from OpenSpeedMonitor if you give us an api key.

**Comment by pmeenan** [comment]
Thanks.  I just made a change to not only drop the plr option when not used but to keep all of the other queue settings each time it is updated.  Ping me offline at pmeenan@webpagetest.org and I can get you a key for testing against the public instance.  I'll deploy the updated agents in a little bit (working on a few other fixes/changes) and let you know when it is live.

**Comment by sburnicki** [comment]
Thank you for the quick fix. We cherry-picked it in our 2.18 based branch and tested it. It runs smoothly as the 2.15 based branch.

We also ran tests with 5% and 10% PLR and were able to observe performance impacts, so PLR still works.
