### ISSUE TITLE
Server: Project directory structure?

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#636]
I would love to introduce new changes coming up with #618 as testable classes.
So it's likely we get a few more files with classes. So before I get into this, what would the preferred location for these class be?

In #634 i started off putting a class with name `<class>.inc` in the root directory.
However, I think putting them into `classes`, `src`, `wpt` or other directories would make sense, so the root directory doesn't get bloated.

Also, classes should maybe simply get a `.php` or `.class.php` extension, instead of `.inc`.

What do you think?

I would like to clarify this before my new pull request, since moving files makes the git log hard to use ;)

**Comment by pmeenan** [comment]
How about either a "support" or "include" directory?  I'm good with just ending it with .php once it is in a separate directory.

**Comment by sburnicki** [comment]
Great, I'm going for `include/<class>.php` then.
