### ISSUE TITLE
Server: Coding/Indention guidelines?

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#637]
Some files are indented with 4 spaces, some with 2 spaces. What is preferred?
(I personally perfer 4)

Same with coding style in general: Mostly I see the braces in the same line as the loop/if statements, but for some functions and classes they're also in the next line. What is preferred here?

**Comment by pmeenan** [comment]
2 spaces and braces on the same line is preferred.  I've been migrating the older code which uses the 4 spaces and separate lines over whenever I touch something.

**Comment by sburnicki** [comment]
Makes sense, thanks.
