### ISSUE TITLE
Firefox first byte time marked during cert verification

### ISSUE THREAD

**Issue by rviscomi** [WPO-Foundation/webpagetest#640]
See http://www.webpagetest.org/result/160612_XB_YR0/1/details/

First byte time is 0.44 seconds, which is in the middle of the OCSP requests.

Expected first byte time should be ~1.5 seconds, after request 5's TTFB.

**Comment by andydavies** [comment]
Think it's clearer without the redirects http://www.webpagetest.org/result/160614_MC_99ef31b151f7077ad2f3b66a8220ec33/1/details/

Though I'm in two minds about whether the redirects should be included (as they are a response from the server too!)

**Comment by pmeenan** [comment]
At the page level I look at "TTFB" as the first byte of the actual HTML which is why it skips over redirects (so it can penalize for long redirect chains).  That it is catching the OCSP responses is definitely a bug.
