### ISSUE TITLE
Timeout errors during video capture from iPad

### ISSUE THREAD

**Issue by anupdhml** [WPO-Foundation/webpagetest#641]
I am using the nodejs mobile agent to run URL tests on iPadPro and sometimes, testing halts with timeout errors of type:

```
I Jun_15_16:34:08.066 wd_server.js:437 WebDriverServer.<anonymous> : Test started
I Jun_15_16:34:20.260 wd_server.js:347 WebDriverServer.onDevToolsMessage_ : DevTools message: {"method":"Page.loadEventFired","params":{"timestamp":11.981091558467597}}
E Jun_15_16:34:29.009 process_utils.js:371 Socket.<anonymous> : /Users/adhamala/wpt/agent/js/lib/ios/video/xrecord STDERR: 2016-06-15 16:34:29.008 xrecord[8896:695672] Stopping recording...
E Jun_15_16:34:29.123 process_utils.js:371 Socket.<anonymous> : /Users/adhamala/wpt/agent/js/lib/ios/video/xrecord STDERR: 2016-06-15 16:34:29.123 xrecord[8896:695672] Done
I Jun_15_16:34:29.349 browser_ios.js:490 BrowserIos.<anonymous> : xrecord EXIT code null signal SIGSEGV
I Jun_15_16:34:29.429 browser_ios.js:529 BrowserIos.<anonymous> : Killed video capture
E Jun_15_16:34:34.500 wd_server.js:210 WebDriverServer.<anonymous> : Exception from "Process Video": Error: Command Timeout
I Jun_15_16:34:34.504 wd_server.js:1448 WebDriverServer.<anonymous> : Test passed
E Jun_15_16:34:34.513 wd_server.js:210 WebDriverServer.<anonymous> : Exception from "Done": Error: Command Timeout
E Jun_15_16:34:34.533 wd_server.js:1110 WebDriverServer.<anonymous> : App uncaught exception event: [{}]
C Jun_15_16:34:34.533 wd_server.js:1502 WebDriverServer.onUncaughtException_ : Uncaught exception: Error: Command Timeout
    at DevTools.<anonymous> (/Users/adhamala/wpt/agent/js/src/devtools.js:243:37)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
E Jun_15_16:34:34.549 wd_server.js:1110 WebDriverServer.<anonymous> : App uncaught exception event: [{"webdriver_promise_error_":true}]
C Jun_15_16:34:34.550 wd_server.js:1502 WebDriverServer.onUncaughtException_ : Uncaught exception: Error: Command Timeout
    at DevTools.<anonymous> (/Users/adhamala/wpt/agent/js/src/devtools.js:243:37)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

Full log for the test is attached: [timeout.txt](https://github.com/WPO-Foundation/webpagetest/files/317243/timeout.txt)

I have tried waiting for up to 15 mins but I have always had to kill the script (Ctrl-c or otherwise) and start it again, since this blocks other tests from running.

On the wpt server, I have `maxtime=600`, if that matters here. This is from Mac OSX 10.11.4 with wepagetest 2.19 on the server.

**Comment by pmeenan** [comment]
It's not a configuration problem, it's a bug that I haven't been able to track down yet and one of the main reasons I want to rewrite the code in something like python.  The exception from the timeout isn't being handled correctly and causes the execution flow to stop.  I had squashed most of the cases of that happening but it still happens every now and then (across my 24 android devices I see it happen once every few weeks but it's possible the iOS logic trips it more often).

I'll see if I can track this case down and add some protection around it.

One failcase I used to use when I ran Windows for the tethered hosts was to have a process that ran the agents and watched an "I'm alive" file that the agents would update every time they checked for a test.  If the file wasn't updated in an hour it would kill the process and re-spawn the agent (as a watchdog/safety valve).  The alive file logic is still available in the agents so it might also be worthwhile to create a python-based watchdog/wrapper that can keep it running for the edge cases like this.

**Comment by anupdhml** [comment]
Thanks @pmeenan! For the time being, I'll write a watchdog to kill and respawn the agent when this happens. Android has been pretty reliable for us and I haven't seen this there so far, but on iOS, it happened multiple times yesterday.

Note to others: Passing `--alive filename` to wptdriver.sh creates the alive file in the script directory. This should probably be documented in the script somewhere.
