### ISSUE TITLE
ErrorCode: 99999 but every response is a 200

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#645]
Hi Pat, 
I've been going through the backlog and there some errors that I've missed reporting. We have seen that sometimes (it doesn't happen often, I did not find super recent event when it happened, this is from May) we get the 99999 error code but all request/responses are 200. 
http://wpt.wmftest.org/result/160516_3B_8A/4/details/

Do you know what it can be? Or where I should look or how I can help? We signal a fail in our test suite if a test returns 99999. 

Best
Peter

**Comment by pmeenan** [comment]
Looking at the code I took a stab at the only case I could see this happening (a request was started but never completed so wasn't logged but still caused an error).  I'll have a new agent build shortly you can test with.

**Comment by pmeenan** [comment]
ok, 287 is out and should/might fix it.

**Comment by soulgalore** [comment]
thanks :)
