### ISSUE TITLE
Design of multistep result pages

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#653]
I want to start to implement multistep support (#618) in the different result pages.
Before getting started, I'd like to discuss the way the results hould be presented.

With multistep, the results per page increase. The way we chose in our fork before was to to just display all the results of all steps below each other (per run/view).

![image](https://cloud.githubusercontent.com/assets/5701519/16618431/98e82bbc-4389-11e6-93ef-c63af96582cf.png)

For some pages, we provided quicklinks on the top for better navigation on the page.

![image](https://cloud.githubusercontent.com/assets/5701519/16618462/ce07ebf2-4389-11e6-8818-87b3ad2ff753.png)

On the `details` page we also show all step results per run, but grouped (waterfalls, connection views, request details). This way it's for example possible to quickly compare waterfalls of different steps.
We introduced an "accordeon" to load the different results asynchronously and avoid long loading times.

![image](https://cloud.githubusercontent.com/assets/5701519/16618525/274d9432-438a-11e6-8bb8-c331f73bbdfe.png)

I'm also open for new ideas to make the results overseeable. If nobody has better ideas, I'd implement the pages similar to our fork.

**Comment by pmeenan** [comment]
Sounds good to me.  Only piece I'm not sure about are the grades.  I wouldn't want multiple rows of grades all in the header because it would push all of the other content out of view.  Maybe average all of the grades for the one at the top and then include the per-step gradings with the individual results (or only on the details page to avoid over-cluttering the main results page).

**Comment by pmeenan** [comment]
Not sure but it might be nice to auto-expand the first waterfall accordion.

Also, the quicklinks for the "customize waterfall" and "view all images" should probably just go to the actual destination pages since they are just links.

**Comment by sburnicki** [comment]
Average grades in the header make sense. The first screenshot is actually from the performance review page, where grades for all steps are presented.

Regarding the waterfalls: I also think it makes sense to auto-expand the first waterfall. With step-specific anchor links (which are also used in quicklinks), the target accordeon also gets automatically expanded.

And I agree that quicklinks for "customize waterfall" and "view all images" should be the "real" links.
