### ISSUE TITLE
Measuring a step without "onload" event

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#654]
Many pages load new content via AJAX, but do not fire an `onload` event, so it's currently not possible to measure this via WPT (to my knowledge). Especially with multistep, it would be a great benefit to not be restricted to page loads.

Nils and I discussed what we could do about this and we came up with the following idea:

```
setEventName    loadContent
setEventEnd childAdded  #mainContent    div.text.new-content
execAndWait document.querySelector('#ajaxInitiator').click()
```
1. We use a new WPT script command `setEventEnd` (name to be discussed) to set a user defined end for this step.
2. The browser extension, let's assume chrome for now, will execute this command by using a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver?redirectlocale=en-US&redirectslug=DOM/MutationObserver) to observe DOM changes specified by the arguments. In this case it would wait for a new child `div.text.new-content` of node `#mainContent`.
3. With `execAndWait` the actual measurement is started and an AJAX call is inititated.
4. The AJAX call will eventually insert new content in the page.
5. The `MutationObsever` notices the DOM changes and calls an event handler which disconnects the observer and sends a `wptLoad` request to the chrome extension.
6. The chrome extension will simply do the same as if an `onload` event has fired, so the step ends and results are saved by wptdriver.

Another idea for the arguments of `setEventEnd` would be to pass Javascript that calls a specific function/callback to signal the step's end.

This way, we only have minimal changes to the client and leverage the multistep capabilities to measure arbitrary events on a webpage.

What do you think about this idea? Do you think it would work, or are we missing something?

**Comment by pmeenan** [comment]
With a multi-step test, only the first step usually requires an onload event.  I believe further steps operate purely off of network activity (and if not that's a bug that was introduced at some point).

There is the setDomElement command that should do roughly what you describe which polls the DOM and will not stop the step until the DOM element becomes available (should probably be extended to allow for arbitrary JS to run for custom completion checks).  It adds overhead to poll though so it's not great.

At one pont there was also a DOM-exposed webpagetest object so you could have script call into "webpagetest.done" and attach your own timer or code to run which would eliminate the need to poll (use an observer or some such).  A cleaner implementation these days might be to allow control over the console log and have it wait for a specific console log message.  Something like:

```
setEventName	loadContent
setConsoleWait	wpt loaded
exec	<js that watches for the content to load and outputs console.log('wpt loaded') when it loads>
execAndWait	document.querySelector('#ajaxInitiator').click()
```

Only reason I recommend the console is that it is available on all of the mobile and desktop browsers wheer scripting would work and allows for low-overhead.

**Comment by nilskuhn** [comment]
I think you are right for multistep tests with _combineSteps_ where everything after first _navigate_ will be tracked and recorded into one big waterfall. But if you want to record different steps through the web application each with its own timings you would have to finish each step, explicitly (before you start the next one).

For that we used exactly two commands in the past: _navigate_ and _execAndWait_. Just these two led to multiple finished steps each ones waterfall starting with its initial request.

The problem:

Executing ajax initiating javascript via _exec_ command wouldn't create an own waterfall with timings for the ajax initiated, dom changing action. One can try to set the steps timeout to 10 secs or something and measure the ajax call as last step in the script. Sometimes you can take that steps fully loaded time as time for the ajax call but thats a bit hacky and wouldn't work if you have to measure other steps afterwards or there are some timer activities after loaded the ajax content.

Executing ajax initiating javascript via _execAndWait_ command would make the ajax step fail running into a timeout because no window.load event gets fired.

**Comment by pmeenan** [comment]
The ajax failing with execAndWait should be a bug.  If you can reproduce it please open an issue for it.  

combineSteps and discrete steps should both behave identically and an onload event should only be needed once during the lifetime of WPT running (arguably we may want to reset it for every navigate command at least but I don't think it does that).

**Comment by sburnicki** [comment]
Well, this is great. I just did some tests and were actually able to measure ajax steps.

About the setDomElement: I found [a blog article](https://davidwalsh.name/detect-node-insertion) about a method using trivial CSS animations and JS to detect a node insertion by listening for the animation start. Then we can inject CSS selectors to start the "animation" for a certain element we are waiting for.

The advantage of this method is that it requires no polling, thus shouldn't have a big overhead.

Here is a piece of Javascript I derived from the blog article that can be used to wait for an element to appear:
```javascript
function onElementExists(selector, callback) {
    var node = document.createElement('style');
    node.innerHTML = "@keyframes nodeInserted { from { opacity: 0.99; } to { opacity: 1.0; } } "+selector+" { animation-duration: 0.001s; animation-name: nodeInserted; }";
    document.body.appendChild(node);
    var event = function(event){ if (event.animationName == 'nodeInserted') callback(node); }
    document.addEventListener('animationstart', event, false);
    document.addEventListener('MSAnimationStart', event, false);
    document.addEventListener('webkitAnimationStart', event, false);
}
onElementExists("body div.page.ng-scope img.teaser_element_image", function() { console.log("teaser loaded!")})
```

Maybe we could derive a good implementation for `setDOMElement` from this approach.

**Comment by nilskuhn** [comment]
Looks like a good approach to measure ajax initiated dom insertions minimally invasive.

Great that we are actually able to measure ajax initiated loading with fully loaded time! 
Maybe timeouts with _execAndWait_ really were based on a bug in old multistep implementation.
