### ISSUE TITLE
AppVeyor builds of wptdriver

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#655]
[AppVeyor](https://www.appveyor.com/) is a cloud service for build/CI/CD which is free for open source projects.

I'd like to suggest to make an account for WebPagetest and integrate it with this github project, so there are builds available for quickly setting up or updating a desktop agent.
We can set up both continuous builds (good for testing) and release builds (for updating), that create and correctly label the driver for each release tag. I can even [push the artificats to the corresponding github release](https://www.appveyor.com/docs/deployment/github).

The AppVeyor setup to achieve this is pretty easy.

**Comment by sburnicki** [comment]
I created an AppVeyor project for our fork that successfully builds wptdriver with 32bit dummynet and 64bit dummynet. If desired, I can export the `appveyor.yml` configuration, so it can be put into the repo and AppVeyor can build from it without any additional configuration.
So for "official" builds, it would only be needed to create a WebPagetest AppVeyor account and connect it with this repo.

**Comment by pmeenan** [comment]
Sure, sounds good to me.  For the short term I still like doing the builds by hand so I can do some testing before releasing but it would be good to eventually move to a more robust CI pipeline

**Comment by sburnicki** [comment]
I agree with releases. But also having non-stable builds would allow people to easily use nightly builds, e.g. if they really rely on a fix.

**Comment by pmeenan** [comment]
Using "nightlies" might not work with the current update mechanism which uses the dll version number to update.  We can change the numbering scheme to include an auto-incremented build number as well and use that instead but out of the box if you use a nightly build it might prevent getting the next actual release.
