### ISSUE TITLE
Start render issues when using logdata=1

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#656]
I'm using a simple script to create a repeat view by loading the same URL twice and only logging data for the repeat view.

```
logData    0
navigate	http://www.telegraph.co.uk/fashion/london-fashion-week/40-years-ago-this-man-founded-london-fashion-week-with-only-1000/
logData    1
navigate	http://www.telegraph.co.uk/fashion/london-fashion-week/40-years-ago-this-man-founded-london-fashion-week-with-only-1000/
```

This can cause unpredictable results for visual metrics like start render because sometimes the screen changes before the request for second navigate command has returned. Here's an example where start render is only 202ms when it should have been around 2.5s.

http://www.webpagetest.org/video/compare.php?tests=160709_GA_9WT-r:1-c:0

Another run in the same test worked fine though.

http://www.webpagetest.org/video/compare.php?tests=160709_GA_9WT-r:3-c:0

Is this an agent issue or is there a better way to create a repeat through using just a script?

**Comment by andydavies** [comment]
Does this happen across all browsers or just Chrome?

I've been noticing some script failures that only happen in Chrome so I'm
debugging them ATM

**Comment by zeman** [comment]
Also see same issue in IE so not Chrome specific. But again really varies run to run, it's doesn't seem consistent at all.  

http://www.webpagetest.org/video/compare.php?tests=160709_QS_GWS-r:2-c:0

**Comment by soulgalore** [comment]
@zeman had these problems in the past and to understand whats causing the issue I removef the HTML between page loads, then it's easier to see in the video what's causing the start render (browser status line or whatever it is).
<pre>
logData    0
navigate    http://www.telegraph.co.uk/fashion/london-fashion-week/40-years-ago-this-man-founded-london-fashion-week-with-only-1000/
// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep   2
logData    1
navigate    http://www.telegraph.co.uk/fashion/london-fashion-week/40-years-ago-this-man-founded-london-fashion-week-with-only-1000/
</pre>

**Comment by zeman** [comment]
Thanks @soulgalore, that totally did the trick!  Hey @andydavies is there a good collection of example scripts anywhere we can contribute to? I can edit the WPT scripting page if we want to add more examples there for common scripts.
