### ISSUE TITLE
Parallel video processing fails on ios devices

### ISSUE THREAD

**Issue by anupdhml** [WPO-Foundation/webpagetest#657]
We have an iPad Pro and an iPhone 6 plus tethered to a mac host, with tests running continuously on each device. I noticed that speed index is reported as 0 about half the time for a device (and no video playback available from the web UI when that happens).

```
I Jul_12_15:07:50.304 wd_server.js:1373 WebDriverServer.<anonymous> : Video processing error: python lib/video/visualmetrics.py -i runtmp/d7f03c8bb535aac0d5817dc0831289918600ae87/160712_WV_6X9.1/video.mp4 -d runtmp/d7f03c8bb535aac0d5817dc0831289918600ae87/160712_WV_6X9.1/video --orange --viewport --force --quality 30 --maxframes 50 --histogram runtmp/d7f03c8bb535aac0d5817dc0831289918600ae87/160712_WV_6X9.1/histograms.json.gz failed, code 1, stderr[258] CRITICAL:root:Input video file runtmp/d7f03c8bb535aac0d5817dc0831289918600ae87/160712_WV_6X9.1/video.mp4 does not exist
CRITICAL:root:No video frames found in /Users/adhamala/wpt/agent/js/runtmp/d7f03c8bb535aac0d5817dc0831289918600ae87/160712_WV_6X9.1/video
```

I don't see any errors at the time of video capture but when it's time to process them, the file seems to be missing. Full log is attached here: [log_no_video.txt](https://github.com/WPO-Foundation/webpagetest/files/360110/log_no_video.txt)

I have been doing the same with an android tablet and a phone from a single windows host and there, things run fine. Is parallel video recording/processing not supported from mac systems?

**Comment by pmeenan** [comment]
That is correct.  The [iOS host docs](https://sites.google.com/a/webpagetest.org/docs/private-instances/node-js-agent/setup#TOC-iOS-specific-Host-Configuration-work-in-progress-) warn about it and it makes iOS testing an order of magnitude more expensive than Android testing (requiring a dedicated Mac for every device).
