### ISSUE TITLE
PTST is missing when requesting service workers

### ISSUE THREAD

**Issue by triblondon** [WPO-Foundation/webpagetest#658]
![wpt-403](https://cloud.githubusercontent.com/assets/1735391/16792890/b67271c8-4907-11e6-9c60-097c12c5be9e.png)

My server is denying all requests with a 403 response unless the UA includes 'PTST'.  In this test, all the requests succeed except those that are loading service workers.  The request inspector shows that the UA is missing the extra token.

**Comment by pmeenan** [comment]
Argh.  Thanks, this is going to take some gymnastics to fix cleanly so it may take a few days.  The header adding is done through dev tools and probably applies only to the tab being debugged so SW requests aren't seen.  I could probably override the full UA string through the command-line but it needs to know what the UA string should normally be first before appending the PTST so doing it without it being too fragile might be a bit convoluted.

**Comment by pmeenan** [comment]
The fixed agent hasn't been rolled out yet.  Doing that now and then I'll update and let you know when it is ready.

**Comment by pmeenan** [comment]
The updated agent just rolled out on the public instance (287).  There is a small window of 1-2 tests per agent whenever the browser updates where it may not include the string in the SW case but my guess is that hitting that small window per test machine with your tests is super-unlikely.

**Comment by sovanyio** [comment]
I think there has been a regression on this, noticing this same issue on the current iteration. Bypassing the service worker / user-agent issue in lighthouse testing by setting the bypass service worker flag on in that context, but not seeing an equivalent way to do that in WPT.
