### ISSUE TITLE
Links to rule descriptions on Performance Review page

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#660]
Recommendations on Performance Review page (e.g. http://www.webpagetest.org/result/160713_34_13WP/1/performance_optimization/) have titles like "Leverage browser caching of static assets" or "Compress Images", but that is often not enough for users to understand the concept or act on the recommendation.

Simple solution could be to add links to corresponding documentation - similar list already exists as part of ShowSlow project (but might require updating as pages now redirect to new locations and there are new or deprecated rules): https://github.com/sergeychernyshev/showslow/blob/d85e88128748a30e3b5aea911cad49fb9e785aeb/global.php#L315

**Comment by sergeychernyshev** [comment]
This file holds the rules: https://github.com/WPO-Foundation/webpagetest/blob/master/www/optimization.inc

Links should probably be on <h3> headers.

**Comment by erunyon** [comment]
Pull request to add links to most h3's on the page: https://github.com/WPO-Foundation/webpagetest/pull/1314

**Comment by sergeychernyshev** [comment]
Looks like PR #1314 was merged already and I've seen plenty of links without realizing it is related to one of my tickets. Closing.

**Comment by sergeychernyshev** [comment]
And thank you, @erunyon for making it happen!
