### ISSUE TITLE
Official Docker image for server

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#661]
We created a [Dockerfile](https://github.com/iteratec/webpagetest/blob/docker_server/Dockerfile) that can be used to create a docker image for quickly setting up a WPT server.

If desired, we can include this into the main project (maybe with another MAINTAINER in the Dockerfile), so [Dockerhub](https://hub.docker.com/) can get connected to this repo and build official WPT server images.

**Comment by pmeenan** [comment]
Sounds good to me.

**Comment by jangrewe** [comment]
@pmeenan Could you guys please sign up to Docker Hub and have it build the image automatically? It shouldn't take you longer than 3 minutes to do this, but will provide the community with an official image (not just the "build-the-image-yourself" Dockerfile in the repo), which allows us to source this Docker image then for our own deployments - e.g. just putting a custom locations.ini into it.

Thanks!

**Comment by sburnicki** [comment]
@jangrewe We currently auto build the image after every commit, see  https://hub.docker.com/r/iteratec/wptserver/
I'd also prefer an official image, though.

You can also simply mount the locations.ini into the container with
```
-v /path/to/locations.ini:/var/www/html/settings/locations.ini
```

**Comment by pmeenan** [comment]
Took a little more than 3 minutes to hook up and sort through the issues but should be good now: https://hub.docker.com/r/webpagetest/server/

**Comment by jangrewe** [comment]
Great, thank you @pmeenan!
