### ISSUE TITLE
API Key for private instance

### ISSUE THREAD

**Issue by KrisMuree** [WPO-Foundation/webpagetest#670]
Hi Guys,
  We are planning to run WTP as private instance. I would like to know few things before i go ahead create the private instance.

1. Should i need API Key to run the private instance? If yes, where to get it.

Thanks in advance
Kris

**Comment by soulgalore** [comment]
No you dont need it but you should configure your own key (check the docs) so that only you can use it.

Best
Peter

**Comment by pmeenan** [comment]
The keys are configured in settings/keys.ini on the server

**Comment by KrisMuree** [comment]
thank you. So we need to create a key and save it in settings/keys.ini?

Good Day.


Thanks,
Kishore Kumar Krishna Murthy

Ph:+91 9743223311

**Comment by pmeenan** [comment]
There is a keys.ini.sample in the settings directory that shows you what it should look like.
