### ISSUE TITLE
Using private instance outside

### ISSUE THREAD

**Issue by KrisMuree** [WPO-Foundation/webpagetest#671]
Hi Guys,
   I got private instance setup in one of VM located in US. Can I use the API key which is used in private instance to run the test from India using WTP webservices. Please find the sample URL

http://www.webpagetest.org/runtest.php?url=www.sears.com&runs=1&f=json&r=F5457ASDSDAS987

Thanks,
Kris

**Comment by pmeenan** [comment]
Using the public agents from a private instance is done by setting up a "relay" location in your private instance but it uses the API so you are limited to the locations that your API key (on the public instance) has access to and the testing limits there.
