### ISSUE TITLE
appendua not substituting test info

### ISSUE THREAD

**Issue by rviscomi** [WPO-Foundation/webpagetest#681]
For example, see the UA string in this request: https://www.webpagetest.org/result/160811_1E_142fa46fac7be41a8d9722bf2865ba1c/1/details/#step1_request1

> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 **WPT/%TESTID%.%RUN%/299**

Note that the %TESTID% and %RUN% placeholders are not filled.

To reproduce:

1. Go to https://www.webpagetest.org/?url=example.com&appendua=WPT/%TESTID%.%RUN%
2. Run test.
3. Inspect User-Agent request header.

Also tried encoding the % (as %25) but no change.

**Comment by rviscomi** [comment]
Thanks Pat!

**Comment by pmeenan** [comment]
Pushing the agent up now.

**Comment by pmeenan** [comment]
OK, fix has rolled out: https://www.webpagetest.org/result/160811_Q3_dbcaaad6fa3e598beeb1a3a54a22632c/1/details/#step1_request1

Private agents configured to auto-update should pick it up within the next hour.
