### ISSUE TITLE
Opera Mini with really fast first paint

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#682]
Hi Pat,
we've been trying out Opera Mini (which is great, I love it). It seems that we get a really fast first paint. The screenshots looks ok (the first paint is a valid metric) but 0.050s seems really fast (I don't remember it being so fast on my phone :)). Could it be a caching issue or do the test start to late?

https://www.webpagetest.org/result/160811_95_1CBP/

https://www.webpagetest.org/video/compare.php?tests=160811_95_1CBP-r%3A1-c%3A0&thumbSize=200&ival=16.67&end=visual 

Best
Peter

**Comment by pmeenan** [comment]
I'll have to take a closer look but it is possible the start of loading isn't being detected quite as early as it should be.  The timings rely 100% on processing the video.  The tests start by loading a blank page, starting video capture and then sending an intent to navigate the page.

In the case of Opera Mini it considers the start point to be when the fist bit of the throbbing progress icon shows in the viewport which at least when I was testing manually was the same point when the loading indicator in the UI changed.  It's also possible that there is a slight delay before they show the loading indicator but won't know for sure until I look closer.  It's also possible there was a browser update and they don't show the throbbing icon in the viewport anymore (in which case I can update the logic).

FYI, you can have webpagetest store and make available the original raw mp4 video capture from the device by starting out on http://www.webpagetest.org/?keepvideo=1 (or passing keepvideo=1 to the api).  The raw device video will be a link below the link to the filmstrip.  I usually take that and then feed it through the visualmetrics python script which is what does the trimming/extraction and metrics calculations.

I'm OOTO today so I may not be able to look closer until Monday.

**Comment by soulgalore** [comment]
Ah cool, I'll check the raw video tonight and see if I understand the root cause.
Thanks!

**Comment by soulgalore** [comment]
I checked the original video and only the indicator changed from a + to a rewind kind of thingy, so that seems to work. And it keeps going a couple of seconds before something happens on the screen but the first paint is still really early so it's something with visualmetrics.

<img width="405" alt="screen shot 2016-08-12 at 3 43 12 pm" src="https://cloud.githubusercontent.com/assets/540757/17624161/d29e9ef4-60a3-11e6-8693-13fd77be811e.png">

**Comment by pmeenan** [comment]
Thx. They changed the UI so I'll update visual metrics to handle both cases. 






On Fri, Aug 12, 2016 at 9:47 AM -0400, "Peter Hedenskog" <notifications@github.com> wrote:












I checked the original video and only the indicator changed from a + to a rewind kind of thingy, so that seems to work. And it keeps going a couple of seconds before something happens on the screen but the first paint is still really early so it's something with visualmetrics.

**Comment by pmeenan** [comment]
It will take around an hour for all of the agents to pick up the update.  I'll try re-running the test then to verify.

**Comment by pmeenan** [comment]
OK, looks a [lot better now](https://www.webpagetest.org/result/160813_Q0_NB8/) though I think there may be an issue with the tcpdump

**Comment by pmeenan** [comment]
The byte counts and timings are fixed now as well: https://www.webpagetest.org/result/160814_9Y_FV0/

**Comment by soulgalore** [comment]
Perfect thanks :)
