### ISSUE TITLE
Accordion pictures missing on webpagetest.org for multsitep pages

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#688]
As you can see for example [here](https://www.webpagetest.org/result/160816_NG_2a4a291233e0836d0941031c90b41dd6/1/breakdown/), the accordion pictures on webpagetest.org are missing.
These are namely:
* `images/accordion_closed.png`
* `images/accordion_opened.png`
* `images/activity_indicator.gif`

**Comment by pmeenan** [comment]
Thanks.  Forgot to copy that directory over.  Whenever I finally upgrade the server hardware next I'll be removing the manual step for pushing to prod :-)
