### ISSUE TITLE
Combining navigate + execAndWait steps is no longer working

### ISSUE THREAD

**Issue by marcelduran** [WPO-Foundation/webpagetest#689]
Combining navigate + execAndWait steps is no longer working. Last worked around 7/28.

The following scripted test completes but result is _"Test Data Missing"_. [sample](https://webpagetest.org/result/160817_SB_39RD/)
```
combineSteps
navigate	https://www.youtube.com
execAndWait	window.setInterval(scrollBy.bind(window, 0, 600), 1000)
```

This scripted test completes but not with desired behavior. Notice the filmstrip in this [sample](https://webpagetest.org/video/compare.php?tests=160817_JN_39S4-r%3A1-c%3A0&thumbSize=200&ival=500&end=full) stays at the top portion of the page and does not scroll to the bottom as tests prior to 7/28 used to.
```
navigate	https://www.youtube.com
execAndWait	window.setInterval(scrollBy.bind(window, 0, 600), 1000)
```

This seems similar to @sburnicki's issue #625

**Comment by pmeenan** [comment]
Thanks.  Looks like something is very wrong with combineSteps indeed.  A simple 2-page navigation is [also failing](https://www.webpagetest.org/result/160818_CM_5bada0c281bd9a6218bd24a77af85098/):

```
combineSteps
navigate	https://www.webpagetest.org/?bare=1
navigate	http://httparchive.org
```

It's easy enough to reproduce so hopefully it doesn't take long to fix.

**Comment by pmeenan** [comment]
Sorry about that, should be fixed and rolled out to the public instance now.  [Here](https://webpagetest.org/result/160819_R2_103S/) is the scroll test and [here](https://www.webpagetest.org/result/160819_9F_c147810d42b8b0ecd8a4cc0c92945801/) is the multiple navigation.

The multi-step support wasn't handling the combineSteps command correctly but it should be good now.
