### ISSUE TITLE
Problem with waterfall images & video for relayLocation

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#690]
Hey Pat,
I've been trying to setup webpagetest.org as an relayLocation. I can submit a job and get the result back, I can see that we have some data locally on our server and test start page works (or have some data) but images/video and some other pages doesn't work. This is an example: http://wpt.wmftest.org/result/160818_DT_5X/

Our server is on AWS and I added:
<pre>
[locations]
...
10=Dulles

[Dulles]
1=WPT-Dulles
label="Dulles"

....
[WPT-Dulles]
browser=Chrome,Firefox
label="WebPageTest.org Dulles"
relayServer="https://www.webpagetest.org/"
relayKey="OUR_SUPER_SECRET_KEY"
relayLocation="Dulles"
</pre>
in var/www/webpagetest/www/settings/ec2_locations.ini

I haven't found any errors in the logs but could be I'm looking in the wrong place, can you show me where to look?

Thanks Peter

**Comment by sburnicki** [comment]
I guess this is an issue with the `UrlGenerator` I introduced to generate links.
The URL of the waterfall thumbnail is generated as `http://wpt.wmftest.org/result/ae622160747643b8bc288dbfc35bfa83.160818_DT_5X/1_waterfall_thumb.png`, but should be `http://wpt.wmftest.org/result/160818_DT_5X/1_waterfall_thumb.png`.

Can somebody tell me at which part the `ae622160747643b8bc288dbfc35bfa83` gets important? So I can keep it in mind when fixing the issue :)

**Comment by soulgalore** [comment]
Sweet: waterfall and screenshots work now, thanks @sburnicki 

Filmstrip view and video do not work http://wpt.wmftest.org/result/160819_K8_3F/ (try clicking on the links).

**Comment by sburnicki** [comment]
Similar issue, will fix later it later this day :)

**Comment by pmeenan** [comment]
Looks like the test ID's were incorrectly getting changed on the relay server to include the relay key.  I just pushed the fix to the public server and did some quick testing and it appears to be working.  Can you let me know if it fixed the issues you were seeing.

Sorry if I'm a bit slow to respond, I'm out for the next week or so and working on a tiny laptop screen is....challenging ;-)

**Comment by soulgalore** [comment]
Yes filmstrip and video works now, thanks :)

>Sorry if I'm a bit slow to respond

Np at all. You get better support from you than any paid product.
