### ISSUE TITLE
relayLocation WPTAPIError: Internal Server Error

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#694]
Hey Pat,
I've setup WebPageTest.org as a relay server. For the devices I've setup it works fine, I get the data and the JSON result (I use the WebPageTest-API) works fine (except for https://github.com/WPO-Foundation/webpagetest/issues/690).

But for Firefox/Chrome on Dulles location I get errors (with the setup as #690). I get the data to my instance (the result look ok) but I get an error from the API:

<pre>
{ [WPTAPIError: Internal Server Error]
  name: 'WPTAPIError',
  code: 500,
  message: 'Internal Server Error' }
</pre>

Can you point me in the right direction where I can debug it?

Best
Peter

**Comment by pmeenan** [comment]
Can you try and see if the fix I just pushed for 690 also solves the issue you are seeing here?  It's possible that the incorrect test ID was getting embedded in URLs and confusing the API.

Is the API pointing to your local server which then relays to the public instance?  What happens if you hit the jsonResult.php?test=<testID> URL directly?

**Comment by soulgalore** [comment]
No it seems to still be there (or maybe our instance needs to be updated).

> Is the API pointing to your local server which then relays to the public instance? 

Yes.

>What happens if you hit the jsonResult.php?test= URL directly?

It works! http://wpt.wmftest.org/jsonResult.php?test=160819_J5_C0

This isn't super important for us, since it works for the devices. But if it would work, we could setup a relay for all our tests.

**Comment by pmeenan** [comment]
So, relay through the UI and by URL to the jsonResult.php is working ok but the API Wrapper is having issues and only for relayed tests to Dulles Firefox and Chrome?  To say that is bizarre would be an understatement.

I'll try to set up a configuration to see if I can reproduce it.  You shouldn't need to do anything to your setup as everything we were changing for multistep was supposed to be backward compatible.

We also have the HTTPS switchover on the public instance but that should be all-or-nothing on the failures.

Any chance you can watch the server access logs when the API wrapper makes the API calls and see what URL it is that it is requesting (or add logging to the wrapper to display the URL it is requesting)?  That may help track things down.

**Comment by soulgalore** [comment]
Yes it is strange, I don't understand why. I'll check the logs tomorrow and see what I can find out.

**Comment by soulgalore** [comment]
Ok it looks like this:
<pre>
IP - - [22/Aug/2016:08:02:12 +0000] "GET /work/postprocess.php?test=160822_EN_51 HTTP/1.1" 200 0 "-" "-"
IP - - [22/Aug/2016:08:02:13 +0000] "GET /jsonResult.php?test=160822_EN_51&medianMetric=SpeedIndex&medianRun=fastest HTTP/1.1" 500 5 "-" "-"
</pre>

But when I access <code>/jsonResult.php?test=160822_EN_51&medianMetric=SpeedIndex&medianRun=fastest</code> it works, I get the JSON back and a 200.

<pre>
IP - - [22/Aug/2016:08:05:49 +0000] "GET /jsonResult.php?test=160822_EN_51&medianMetric=SpeedIndex&medianRun=fastest HTTP/1.1" 200 40037 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
</pre>

**Comment by pmeenan** [comment]
Wonder if there is a race condition going on while the post-processing is being done.  Does anything show up in your web server error.log?

**Comment by soulgalore** [comment]
no, nothing. cannot find anything else in any of the other logs (if I'm not looking in the wrong place).

**Comment by soulgalore** [comment]
We got this for the all the tests we run as a relay server, I hadn't tested for a week and now we get the same behaviour for all runs. Which maybe is good in a way. The first access through the API gives an error and then when I access the individual test it works.

**Comment by Krinkle** [comment]
*bump*

**Comment by pmeenan** [comment]
FYI, there were a bunch of fixes recently where the tests were prematurely being called done and post-processing was running several times (fixes landed a few weeks ago).  Are you still seeing issues?

**Comment by soulgalore** [comment]
I haven't tested the last couple of weeks, let me test again.

**Comment by soulgalore** [comment]
Tested and I still got the same error. First access with the NodeJS API get 500 and after that I can access the result.

**Comment by soulgalore** [comment]
We still got the same problem, let me know if you have any ideas of other things I can try to make it work.
