### ISSUE TITLE
Main thread processing breakdown broken?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#698]
Hey Pat,
I think something has happened with "Main thread processing breakdown" all metrics are 0. The timeline view looks ok.

Here's two examples on when it doesn't work for me:
https://www.webpagetest.org/breakdownTimeline.php?test=160825_BX_3a60e73467dd6b0d20d70ddeee07dae3&run=1

https://www.webpagetest.org/breakdownTimeline.php?test=160825_79_9556a71071ac8effeb5bc254ce843df9&run=1

I run on Chrome and choose "Capture Dev Tools Timeline".

Best
Peter

**Comment by sburnicki** [comment]
I tracked the issue to `lib/trace/trace-parser.py`, which doesn't work. You can reproduce with:
```
python lib/trace/trace-parser.py -t /path/to/1_trace.json.gz -u /path/to/1_user_timing.json.gz -c out.json
```
`out.json` doesn't contain correct results.

I appended two traces from a test run. Maybe this makes debugging easier :)
[1_trace.json.gz](https://github.com/WPO-Foundation/webpagetest/files/437217/1_trace.json.gz)
[1_user_timing.json.gz](https://github.com/WPO-Foundation/webpagetest/files/437220/1_user_timing.json.gz)

**Comment by soulgalore** [comment]
thanks @sburnicki & @pmeenan !
