### ISSUE TITLE
Too fast TTFB time (and general download times)

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#699]
Hey Pat,
we've started to see unrealistic TTFB again and also general really fast download times. I'm not sure when it happened, I've seen it for Chrome and first I though it was when we turned on fetching devtools timeline but I've seen on other places too. The tests are simple and just access one URL.

TTFB:
<img width="948" alt="screen shot 2016-08-26 at 10 57 52 am" src="https://cloud.githubusercontent.com/assets/540757/18000398/2587612a-6b7e-11e6-8639-07d5bbb5b164.png">

Shooort download times (first view):
<img width="949" alt="screen shot 2016-08-26 at 10 58 06 am" src="https://cloud.githubusercontent.com/assets/540757/18000392/1ad7f7a8-6b7e-11e6-8b45-1c931c06b904.png">

Example of runs:
http://wpt.wmftest.org/result/160826_VJ_2K/
http://wpt.wmftest.org/result/160826_Y2_1R/

I can dig into it deeper later today to see if I can see when it first appeared (if it would help).

Best
Peter

**Comment by pmeenan** [comment]
Any chance you can change the "publish" to either point to https://www.webagetest.org or to api.webpagetest.org (it looks like it is broken right now)?

I'd like to look at the raw underlying testinfo.json and make sure it set the bandwidth and latency configuration correctly to see if it looks like it was a problem on the test agent with not traffic shaping or on the server with not setting the connectivity config correctly.

Up until recently, if you set an unknown connectivity type it would silently allow it but apply no traffic-shaping so if your server doesn't have 3GFast defined it could cause that (though generally it should always and not be intermittent).

**Comment by soulgalore** [comment]
Hmm,  could it be that it tries to publish to http://www.webagetest.org I don't remember that I changed any config, but I haven't tried it out since I setup the instance some while ago. I can check that + look for the testinfo.json that could be the case (but we run other tests with the same setup where it looks ok). I'll get back tomorrow.

**Comment by soulgalore** [comment]
Yep you are right, we are missing config for 3gFast, I've added that now.

About publishing, I've changed that to look like:
<pre>
publishTo=https://www.webpagetest.org
</pre>
but I still get an error. I don't see anything in the logs.

**Comment by soulgalore** [comment]
This works now, I'll create another issue about the publish to.
