### ISSUE TITLE
Publish to webpagetest.org from our Amazon instances doesn't work

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#702]
Is this a generic error or could it be something to our instances?

Our config looks like this:
<pre>
publishTo=https://www.webpagetest.org
</pre>
and we get an error. I don't see anything in the logs.

Example:
http://wpt.wmftest.org/publish.php?test=160829_5N_8Q

<img width="648" alt="screen shot 2016-08-29 at 8 19 01 pm" src="https://cloud.githubusercontent.com/assets/540757/18062145/e10f71d6-6e25-11e6-942a-43f9cf9ed628.png">

**Comment by andydavies** [comment]
As a short term fix change http to https in these two lines https://github.com/WPO-Foundation/webpagetest/blob/master/www/publish.php#L154 https://github.com/WPO-Foundation/webpagetest/blob/master/www/publish.php#L160

Once I've worked out the intent of https://github.com/WPO-Foundation/webpagetest/blob/master/www/publish.php#L6 I'll write a PR for it

Do we know of anyone who's publishing to something other then WPT?
