### ISSUE TITLE
Brotli not recognised as a valid compression type in recommendations

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#705]
WPT doesn't recognise Brotli compression, so gives an F due to lack of compression e.g.

https://www.webpagetest.org/result/160904_Z0_a446fc6c2e0efc41a1fa42c23b9561b7/1/performance_optimization/#compress_text

In this example HTML and CSS are compressed using Brotli but JS intentionally isn't compressed

**Comment by pmeenan** [comment]
Fix will be rolled out later today, I'll update when it is built.

**Comment by andydavies** [comment]
Thx, there's no rush must added the issues so they didn't get lost

**Comment by pmeenan** [comment]
Should be fixed now: https://www.webpagetest.org/result/160907_BS_868711508b26627e8b6504fa77d17e4d/1/performance_optimization/#compress_text
