### ISSUE TITLE
Response bodies for Brotli compressed resources aren't available

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#706]
From this test

https://www.webpagetest.org/result/160904_WW_3f397712d72565a92076764a22736b0a/1/details/#waterfall_view_step1

JS which isn't compressed has response bodies available but HTML and CSS which are Brotli compressed don't

**Comment by pmeenan** [comment]
Should be good now: https://www.webpagetest.org/result/160907_BS_868711508b26627e8b6504fa77d17e4d/1/details/#step1_request1
