### ISSUE TITLE
Report text compression savings using brotli

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#707]
Even for pages that use gzip, report on additional savings if brotli were used (if the browser requests it with accept-encoding).

**Comment by pmeenan** [comment]
Should be fixed now: https://www.webpagetest.org/result/160907_BS_868711508b26627e8b6504fa77d17e4d/1/performance_optimization/#compress_text

**Comment by Nickmob** [comment]
Great idea!

**Comment by staabm** [comment]
I would suggest to mention "Compress Transfer" with a "B" Grade when gzip is used and "A" when brotli/zopfli is available.
