### ISSUE TITLE
Get Opera Mini & UC Mini versions in the API?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#708]
Is it possible to add the the exact versions of UC & Opera, so you can get it from the API?

I have two concrete example where it could help us:
- When we pushed lazy loading images for our mobile version of the site, the amount of bytes increased for Opera Mini in extreme mode and to get better help from Opera what's happening in the blackbox getting the exact version would be great.
- With UC mini the screenshots in WebPageTest show elements that I cannot reproduce on my UC Mini, so it could either be different versions or if UC ship different versions to different locations. Would be great to exclude one of them.

Best
Peter

**Comment by pmeenan** [comment]
Should roll out to the public devices over the next hour.  [Here](https://www.webpagetest.org/jsonResult.php?test=160908_HV_3ed61a7f5cc2d5d9f1e8f148d2283d7e) is an example test.  There are now "osVersion" and "browserVersion" strings in the data with each page run (works for all of the browsers, including Chrome, UC and Opera).

**Comment by soulgalore** [comment]
It doesn't work perfectly for me?

For Chrome I get none of them:
https://www.webpagetest.org/jsonResult.php?test=160909_PA_MGW

For UC Mini I get the osVersion: 
https://www.webpagetest.org/jsonResult.php?test=160909_PR_MGX

And for Opera I get osVersion:
https://www.webpagetest.org/jsonResult.php?test=160909_AC_MGY

But for another Opera run (on another tester) I get get both osVersion and browserVersion:
https://www.webpagetest.org/jsonResult.php?test=160909_TK_M9F

Also if it would be possible to also squeeze in browserName, then we can fetch all info from the result to generate all info.

**Comment by pmeenan** [comment]
This has moved over to the new agent and it should be more consistent now.  I just rolled some fixes that should make it more reliable but there may still be times where it fails to get the package version over adb.

**Comment by soulgalore** [comment]
Ah great, I'll test it tomorrow!

**Comment by soulgalore** [comment]
It seems we get os version all the time now but miss browser version in most cases: 

For Opera Mini I got osVersion (but not browser version):
https://www.webpagetest.org/jsonResult.php?test=170502_RK_91P
https://www.webpagetest.org/jsonResult.php?test=170502_80_9DR

The same for UC mini (missing browser version): 
https://www.webpagetest.org/jsonResult.php?test=170502_GR_91N
https://www.webpagetest.org/jsonResult.php?test=170502_T4_9DQ

With Chrome I get both: 
https://www.webpagetest.org/jsonResult.php?test=170502_YG_9DS

**Comment by pmeenan** [comment]
OK, I finally tracked down the issue to some devices not having "head" available on the shell so the command to get the version was failing (my main dev devices all had it which made it a bit more painful to find).

[This update](https://github.com/WPO-Foundation/wptagent/commit/9f5e5c6cfffc158ecd2cdc040a7021191267ce1f) should hopefully fix the issue for good and should be live on all of the public agents in the next hour.

**Comment by soulgalore** [comment]
Ah great, I tested now. Seems like the version is there for all now!

One thing is that the fields are named differently on the old desktop agents and the new Linux version.

On desktop Windows we have:
browser_name
browser_version
https://www.webpagetest.org/jsonResult.php?test=170509_NP_C1K

On desktop Linux we have:
browserVersion
https://www.webpagetest.org/jsonResult.php?test=170509_8Q_BZJ

On mobile:
browserVersion
browserOs
https://www.webpagetest.org/jsonResult.php?test=170509_TS_8KC

We can pick the name of both that is ok, but it would be super if the agent also included the browserName, that makes it easier yo use use the result set to get the full agent info (as JSON without HTML).

Best
Peter

**Comment by pmeenan** [comment]
Agent has been updated (will be live in the next hour) so mobile and Linux will report os_version, browser_version and browser_name (keeps osVersion and browserVersion as well for backward compatibility).
