### ISSUE TITLE
Time Limit not taken into account

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#732]
I set `Time Limit=60` in wptdriver.ini file but wptdriver shows the line : 

```
Waiting up to 300 seconds for the test to complete
```

How can I set a limit inferior to 300 seconds ?

**Comment by pmeenan** [comment]
Try specifying [maxTime=](https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample#L46) in settings.ini on the server (I think it can also be specified on a per-location or per-connectivity basis).

We moved the timeout config to the server to make it more dynamic.

**Comment by abarre** [comment]
I set the value maxTime to 60.
Now, it's shown : 
```
Waiting up to 240 seconds for the test to complete
```
So, I'm not sure that this is working.

**Comment by pmeenan** [comment]
Yes, wptdriver waits a multiple of the test timeout (though that still seems a bit high) to allow some time for browser startup and calculating/recording the results after the test itself completes.

**Comment by sburnicki** [comment]
@pmeenan Is the `Time Limit` taken into account at all then? So is setting the time limit in the server config the "best practice"? I'm asking because we also had trouble with the agent's "Time Limit" (#696).

**Comment by pmeenan** [comment]
I haven't looked at the code recently but I am fairly certain that configuring the time limit on the server is the correct way to do it these days and it is passed through on a test-by-test basis.

**Comment by sburnicki** [comment]
Thanks, we will try this :)
