### ISSUE TITLE
ProcessResults =1 added to URL

### ISSUE THREAD

**Issue by nextprojectawesome** [WPO-Foundation/webpagetest#733]
I created several scripted tests using the API, but for some reason the URL was changed to add processresults=1 causing a 404, I have 10 other tests I tried on various sites, all with the same issue.

Example:
www.test.com shows at the url at the top
but REQUEST 1 shows as www.test.com/processResults=1

**Comment by pmeenan** [comment]
What is the exact URL (minus the API key) that you are using to submit tests?  The UI uses the API itself so odds are it is something with how you are encoding the test URLs.
