### ISSUE TITLE
Enable Firefox Gecko Profiler, similar to Chrome Traces

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#744]
_(Follow up from an ongoing conversation at Velocity with @pmeenan and discussions with Instartlogic on speedperception)_

I'll collect instructions here, after following up with @mstange, on how to best achieve this. We could either reach into Gecko from the WPT addon and start the SPS profiler and then pull the data, or enable profiler via command line.

**Comment by pmeenan** [comment]
Command-line would be preferred if it achieves what you'd want.  Far less plumbing to hook up.

**Comment by digitarald** [comment]
We have an API that could be used by the addon to get the profile json.

```js
const profiler = Components.classes["@mozilla.org/tools/profiler;1"]
  .getService(Components.interfaces.nsIProfiler);

const settings = {
  entries: 1000000,
  interval: 0.4,
  features: ["js", "stackwalk", "threads", "leaf"],
  threads: ["GeckoMain", "Compositor"]
}

profiler.StartProfiler(
  settings.entries,
  settings.interval,
  settings.features,
  settings.features.length,
  settings.threads,
  settings.threads.length
);

setTimeout(() => {
  profiler.getProfileDataAsync().then((profile) => {
    // Stopping the profiler will delete the data.
    profiler.StopProfiler();
    console.log(profile);
  });
}, 500);
```

More details on the output here: https://github.com/mstange/cleopatra/blob/cleopatra-react/docs/profile-data.md

**Comment by digitarald** [comment]
@pmeenan , I tried could you give me some clues where the code needs to be added so that the profile file can be transferred back to the WPT server and offered as download to the user?

**Comment by pmeenan** [comment]
This may be a bit harder now that we've switched to the new extension model.  Is it exposed to that interface in any way?

**Comment by mstange** [comment]
Not yet, we're working on that in [bug 1326572](https://bugzilla.mozilla.org/show_bug.cgi?id=1326572).

**Comment by pmeenan** [comment]
Thanks.  Following the bug so I can keep up with when it is ready.  I have a [new agent](https://github.com/WPO-Foundation/wptagent) that I'm bringing up Firefox support on right now that I'm planning to get as much out of "natively" as possible (marionette for automation, MOZ_LOG for as much as makes sense, WebExtensions for intercept/rewrite, etc).

**Comment by digitarald** [comment]
@squarewave @pmeenan now that [1326572](https://bugzilla.mozilla.org/show_bug.cgi?id=1326572) landed, it should be much easier. Can the FF extension get the timeline flag from the test run and return the profile to the same result field that Chrome returns traces to?

**Comment by squarewave** [comment]
@pmeenan, where exactly is it that the data needs to be dumped to? Or, what's the equivalent code in the Chrome extension? I'm having a bit of trouble figuring out what's being referred to here in order to understand what the FF WebExtension would need to do.
