### ISSUE TITLE
HTTP2 Incorrect Keep-Alive Red Flag

### ISSUE THREAD

**Issue by andreapernici** [WPO-Foundation/webpagetest#745]
Today I was testing this https://www.webpagetest.org/result/161015_VC_83fabf00494f7a4b47f58365fb8e720e/
and saw that keep-alive were flagged as F, but under HTTP/2 keep alives are the default and HTTP/2 doesn't use the connection header (see section 8.1.2.2 of the HTTP/2 spec here: http2.github.io/http2-spec/#HttpHeaders)

I also see a strange behaviour here https://www.webpagetest.org/result/161015_6S_dbd2408a93143539f45777f625e3ddaf/3/performance_optimization/#cache_static_content

**Comment by andydavies** [comment]
Looking at the requests / responses it looks like the client and server
made a HTTP/1.1 connection rather than a H2 one

I see the same problem here
https://www.webpagetest.org/result/161015_3N_HF5/1/details/#waterfall_view_step1

Perhaps it's a problem with the Paris agent?

**Comment by andreapernici** [comment]
Hi Andy. Yes I see some other strange things from Paris.

I'll try a new check from other locations.

**Comment by andreapernici** [comment]
This one from Amsterdam looks good https://www.webpagetest.org/result/161015_8X_888c89eba2df86021335bc652f2561a8/1/details/

I don't know if the Paris issues is related to the following strange URL they inject somewhere and not present on the page.

https://www.gtmasterclub.it/spinternalcall?method=SpSendLog&message=BROWSER_FINGERPRINT:{%22navigator%22:{%22javaEnabled%22:false,%22appCodeName%22:%22Mozilla%22,%22appName%22:%22Netscape%22,%22appVersion%22:%225.0%20(Windows%20NT%205.1)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/49.0.2623.112%20Safari/537.36%22,%22productSub%22:%2220030107%22,%22cookieEnabled%22:true,%22onLine%22:true,%22platform%22:%22Win32%22,%22userAgent%22:%22Mozilla/5.0%20(Windows%20NT%205.1)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/49.0.2623.112%20Safari/537.36%22,%22hardwareConcurrency%22:2,%22language%22:%22fr%22,%22languages%22:[%22fr-FR%22,%22fr%22,%22en-US%22,%22en%22],%22doNotTrack%22:null,%22plugins%22:[{%22mime%22:{%22desc%22:%22%22,%22type%22:%22application/pdf%22,%22extensions%22:[%22pdf%22]},%22name%22:%22Chrome%20PDF%20Viewer%22,%22desc%22:%22%22,%22filename%22:%22mhjfbmdgcfjbbpaeojofohoefgiehjai%22},{%22mime%22:{%22desc%22:%22Shockwave%20Flash%22,%22type%22:%22application/x-shockwave-flash%22,%22extensions%22:[%22swf%22]},%22name%22:%22Shockwave%20Flash%22,%22desc%22:%22Shockwave%20Flash%2021.0%20r0%22,%22filename%22:%22pepflashplayer.dll%22},{%22mime%22:{%22desc%22:%22FutureSplash%20Player%22,%22type%22:%22application/futuresplash%22,%22extensions%22:[%22spl%22]},%22name%22:%22Shockwave%20Flash%22,%22desc%22:%22Shockwave%20Flash%2021.0%20r0%22,%22filename%22:%22pepflashplayer.dll%22},{%22mime%22:{%22desc%22:%22Native%20Client%20Executable%22,%22type%22:%22application/x-nacl%22,%22extensions%22:[%22%22]},%22name%22:%22Native%20Client%22,%22desc%22:%22%22,%22filename%22:%22internal-nacl-plugin%22},{%22mime%22:{%22desc%22:%22Portable%20Native%20Client%20Executable%22,%22type%22:%22application/x-pnacl%22,%22extensions%22:[%22%22]},%22name%22:%22Native%20Client%22,%22desc%22:%22%22,%22filename%22:%22internal-nacl-plugin%22},{%22mime%22:{%22desc%22:%22Portable%20Document%20Format%22,%22type%22:%22application/x-google-chrome-pdf%22,%22extensions%22:[%22pdf%22]},%22name%22:%22Chrome%20PDF%20Viewer%22,%22desc%22:%22Portable%20Document%20Format%22,%22filename%22:%22internal-pdf-viewer%22}]},%22screen%22:{%22height%22:1080,%22width%22:1920,%22colorDepth%22:24,%22pixelDepth%22:24,%22availHeight%22:650,%22availWidth%22:1014},%22timezoneOffset%22:-120}
Loaded By: https://www.gtmasterclub.it/:655
Host: www.gtmasterclub.it
Error/Status Code: 200
Client Port: 0
Request Start: 2.624 s
DNS Lookup: 0 ms
Initial Connection: 1 ms
SSL Negotiation: 1 ms
Time to First Byte: 6 ms
Content Download: 1 ms
Bytes In (downloaded): 0.1 KB
Bytes Out (uploaded): 3.0 KB

**Comment by pmeenan** [comment]
Thanks.  I took the Paris location down and emailed the owner to have them take a look.  My guess would be some form of hacky anti-virus.
