### ISSUE TITLE
Chrome 54 and -2 response codes

### ISSUE THREAD

**Issue by jpenston** [WPO-Foundation/webpagetest#747]
Hi - I have been seeing a lot of -2 response codes in the object data, for example

https://www.webpagetest.org/result/161017_QY_1BN3/1/details/#waterfall_view_step1

There is also a strange 'Other Response' count in the summary data. 72 requests and 85 other responses.

These results started on or around 12th October 2016 and seem to be occurring with Chrome v54.0.2840.59

**Comment by pmeenan** [comment]
Looking into it now.  I can reproduce it and it looks to be HTTP/2 related so should be easy enough to fix.

**Comment by pmeenan** [comment]
Chrome 54 introduced support for larger HTTP/2 header dictionaries and the WPT agent wasn't dealing with it well so the response headers were not being decoded.

Should be [fixed now](https://www.webpagetest.org/result/161018_TQ_ZR8/1/details/#waterfall_view_step1).
