### ISSUE TITLE
bytes_in count is inaccurate for mobile browsers

### ISSUE THREAD

**Issue by rathnaprabhu** [WPO-Foundation/webpagetest#755]
bytes_in count for uc_mini is higher than expected.
For example for olx.co.id the expected bytes_in (per local tcpdump data) is 6K.
However when run through WPT the bytes_in count is around 28K. 
https://www.webpagetest.org/result/161027_QA_104de81f39a38cb1c937e2bdd93422e3/

One thing that could help (as Pat suggested) is to wait until data traffic settles down before navigation.
This issue might be applicable to other mobile browsers as well.

**Comment by pmeenan** [comment]
The agent already waits for traffic to settle before starting the test and also parses the tcpdump for the first browser-looking activity and starts then but it may be counting other activity as well.

If I get a chance I'll look through the tcpdump and see if there is any broadcast or other traffic in there that should clearly be filtered out and see what is going on.

**Comment by rathnaprabhu** [comment]
One thing I noticed in the code that waits for network to be idle is that it looks at 1 second intervals for any incoming traffic greater than 1000 bytes.
This might work for faster network speeds but for 2G speeds where RTT is 800ms checking every 1 second might be too aggressive and could lead to incorrectly deciding that the network is idle. I didn't get a chance to validate this theory, but something to consider.

**Comment by pmeenan** [comment]
Good call.  I think the correct fix is to move the traffic-shaping to after the browser has started and gone idle so any startup work can go unthrottled anyway.
