### ISSUE TITLE
Agent fails to run tests randomly on multi-processors architecture

### ISSUE THREAD

**Issue by guillaume-pasquet-ncc** [WPO-Foundation/webpagetest#762]
When running the WPT agent 333 on a Windows7 Enterprise KVM virtual machine with two processors (both with 2 processor sockets and two cores on the same socket), then tests on Chrome fail randomly. We have only seen this so far happening when running a bulk of urls of more than 100 (our real-life use-case is 775 urls).

When looking at the failures in action, the page loads fine but stays open until the agent times out, then the results show `The test completed but there were no successful results`.

I have attached a result folder from one such failure.

Edit: this also happens running on 2 cores on the same socket

- [Failed test work folder](https://github.com/WPO-Foundation/webpagetest/files/597681/failed-test-333.zip)
- [List of URLs that we run](https://github.com/WPO-Foundation/webpagetest/files/597713/URLs.txt)

**Comment by guillaume-pasquet-ncc** [comment]
We've dug out [an old forum post](https://www.webpagetest.org/forums/archive/index.php?thread-12074.html) that mentions running the wptdriver with an _Affinity_ setting. However this doesn't solve our problem either.

**Comment by ashvince** [comment]
Interestingly I have also now reproduced this issue under VirtualBox by selecting KVM as the Paravirtualzation Interface when configuring the windows guest settings (under Settings->System->Acceleration).

It is still intermittent but if you run the list of urls above you get at least one failure.

**Comment by guillaume-pasquet-ncc** [comment]
I've created a WPT instance on EC2 using the AMIs provided. While I don't see as many errors, there are still some suspicious timeouts that look a lot like what we were seeing on KVM.

You'll find [in the bulk test I ran](http://52.213.184.64/result/161121_E8_1/) the following pages have very long load time although they didn't take this long when eyeballing the agent. Also they're showing "(Error: Timed Out)".

- [office](http://52.213.184.64/result/161121_R4_A6/)
- [kiehls](http://52.213.184.64/result/161121_RM_80/)
- [riverisland](http://52.213.184.64/result/161121_C9_52/)
- [exantediet](http://52.213.184.64/result/161121_R7_20/)
- [lookfantastic](http://52.213.184.64/result/161121_G8_1Z/)

**Comment by pmeenan** [comment]
Sorry I didn't comment earlier - mostly don't have any good ideas.

The main thing that comes to mind is if the APIC/rdtsc clock that is exposed to the VM is not uniform across the cores then it could seriously throw off all of the timers and cause timeouts/random errors.  WPT uses QueryPerformanceCounter all over the place for it's high-resolution clocks and if that isn't uniform it can cause serious issues.

The [bcdedit command](https://sites.google.com/a/webpagetest.org/docs/private-instances#TOC-General-Machine-Configuration) to force Windows to use a stable clock is critical for KVM in particular.  Just a sanity check to make sure that was done on the test machines.

Looks like there is also a way to [force it in the KVM config](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Virtualization_Host_Configuration_and_Guest_Installation_Guide/KVM_guest_timing_management-Using_the_Real_Time_Clock_with_Windows_2008_and_later_guests.html) for newer Windows versions detect it automatically.

**Comment by pmeenan** [comment]
BTW, is it always Chrome or do you see issues with Firefox and IE as well?  I haven't tracked down whatever is going on but I have seen a fair number of cases where Chrome isn't reporting an onload event as having fired.  Not yet sure if it is because the extension didn't get the event or something else went wrong.  

335 [added a safety-net](https://github.com/WPO-Foundation/webpagetest/commit/ab154a9c1f987e98682f1198fb372ffc4aaeca49) to detect the page load event through the dev tools events in addition to the extension notifications but I don't know if it helped or not (hard to say without being able to reproduce it reliably).

**Comment by guillaume-pasquet-ncc** [comment]
@pmeenan Thanks for your feedback, I checked with our server people and we do apply this bcdedit command on our machines already.

The issue we're seeing exclusively happens on Chrome, Firefox and IE both behave fine. I'll give 335 or above a try and see if we can replicate the issue with it. It hadn't yet been released when we investigated our issues.

**Comment by pmeenan** [comment]
If you can also capture a dev tools timeline from the Chrome tests that would help so I can see if the load event is being recorded by Chrome itself internally to see if it is a Chrome issue or if there is something else I can do to the instrumentation side of things.

**Comment by ashvince** [comment]
I did try that, unfortunately it seemed that whenever we had a failure we would also encounter an issue where the timeline was not sent back either. 

I filed a different bug for that [here](https://github.com/WPO-Foundation/webpagetest/issues/763) as I was not 100% sure how related they were.

**Comment by pmeenan** [comment]
I don't have a Linux physical box handy but I can set one up over the next couple of days if it is reasonably easily reproduced in KVM.

@ashvince, what host OS were you using with VirtualBox + KVM?

**Comment by ashvince** [comment]
I was using Virtualbox running on a Linux (Fedora24) host. Thanks for your help btw.

**Comment by guillaume-pasquet-ncc** [comment]
@pmeenan I've tried running our URLs batch with  the agent 336, and I still experience the same timeout issue as with previous versions.

I tried opening the chrome devtools to have a timeline when the test runs, but I always have to click the "record" button, and so I usually miss the interesting loading parts of the site. Is there a chrome flag I could pass to assist in debugging this?

**Comment by pmeenan** [comment]
Capturing a timeline is a test option passed to the agents - https://github.com/WPO-Foundation/webpagetest/blob/master/www/runtest.php#L1952

timeline=1 in the test spec sent to the agents should enable it and you will get a trace json file with the results (if it is successful in capturing).  I wouldn't try to do anything manual.

**Comment by andydavies** [comment]
I've grabbed NetLog's from a test that failed and one that succeeded…

A couple of things jump out from the failure case:
- appear to be more failures on POSTs to http://127.0.0.1:8888/event/initiator
- there's no POSTs to http://127.0.0.1:8888/event/window_timing, http://127.0.0.1:8888/event/stats or http://127.0.0.1:8888/event/custom_metrics (so for what ever reason the   

[1_netlog-success.txt](https://github.com/WPO-Foundation/webpagetest/files/622156/1_netlog-success.txt)
[1_netlog-failed.txt](https://github.com/WPO-Foundation/webpagetest/files/622157/1_netlog-failed.txt)

I've pushed both tests to WPT

Failure - http://www.webpagetest.org/results.php?test=161130_4Q_1ff0aed0d52b60c50c4d4ee391519b27
Success - http://www.webpagetest.org/results.php?test=161130_71_6a6e908ce981a53b87e0f61d6470e055

**Comment by pmeenan** [comment]
I'm adding retries to the extension ajax code and (more importantly) updating mongoose to a newer build (taking a while because the API changed drastically in the 5 years since it was added).  The requests to localhost should NEVER fail but I think the old connection logic in mongoose could have gotten swamped.  Hoping to have it all plumbed through later today for some testing.

**Comment by pmeenan** [comment]
I just pushed out 337 which has the retry logic and the mongoose update.  Can you see if it helps in your failcases?

**Comment by guillaume-pasquet-ncc** [comment]
@pmeenan I've just run our batch of problematic URLs through the agent 337 on dual CPU VMs and I haven't spotted any issues with it. It looks like your changes have fixed our issue. Thanks!

**Comment by pmeenan** [comment]
Great.  Thanks for the detailed diagnosis - really helped isolate the issue.
