### ISSUE TITLE
Chrome timeline is sometimes missing from test result

### ISSUE THREAD

**Issue by ashvince** [WPO-Foundation/webpagetest#763]
In this test run on WPT public earlier I requested saving the chrome timeline. Out of 9 iterations only 8 have the timeline available for some reason.

https://www.webpagetest.org/result/161122_K7_028dcfba2f40f4b96ff0a1b160be28cd/

**Comment by andydavies** [comment]
@ashvince Is this still relevant or did the upgrade in the Moongoose version resolve it?

**Comment by ashvince** [comment]
My apologies for not closing this sooner!
