### ISSUE TITLE
Decode HTTP/2 timings and frames for mobile devices

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#764]
Use netlog for request timings and H2 information (priorities, streams, etc) instead of using the timings from the dev tools interface.

**Comment by DebugXYZ** [comment]
Curious on the background on this, are netlog request timings more accurate or provide some additional information that devtools doesn't provide that might be useful in the future?

**Comment by pmeenan** [comment]
Yes, they are much more accurate and come directly from the network stack as it issues requests on the wire.  It also provides low-level protocol details that aren't exposed to the higher level API's.

fwiw, this has already been implemented in the new agent ([wptagent](https://github.com/WPO-Foundation/wptagent)).
