### ISSUE TITLE
medianMetric should be SpeedIndex by default

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#767]
SpeedIndex should be used for the medianMetric by default. On our private instance, we systematically change the default value.

It seems to be a common practice http://calendar.perfplanet.com/2015/working-on-chrome-performance-with-webpagetest/. 

> Selecting the metric to use for picking a representative run: By default WebPageTest will pick the run with the median page load time (onload) as being the representative run for the given test. Given that we are usually optimizing for start render or Speed Index we override that by passing “medianMetric=SpeedIndex” as an option when getting the test results. You can provide any metric and that will be used for selecting the representative run instead of the page load time.

**Comment by abarre** [comment]
@pmeenan are you interesting in a PR that replace medianMetric='loadTime' by medianMetric='SpeedIndex' ?

**Comment by pmeenan** [comment]
I think I'd prefer to ease into it.  Start with a setting in settings.ini where the instance can have it's own default median metric but default to loadTime.  I switch the public instance over to SpeedIndex and make sure everything is smooth and then we switch the default.  That way people would still be able to specify loadTime as their default on an install-by-install basis if they don't want the change.

**Comment by pmeenan** [comment]
I'll happily accept a PR that does the setting path or if you'd rather I can just implement it later this afternoon

**Comment by abarre** [comment]
Last year, I did a quick search & replace in a commit https://github.com/
fasterize/webpagetest/commit/4eae868ffa6c405191b6300b8768cfca40bed2ae but
that was on a previous version.
I don't think that I will have the time before Christmas holiday. So, if
you can do it before, it would be better.

-- 
*Anthony BARRE*
Software Engineer
06 24 90 61 48

Fasterize - Accélérateur de site web

2017-12-14 15:14 GMT+01:00 Patrick Meenan <notifications@github.com>:

**Comment by pmeenan** [comment]
Should be [implemented now](https://github.com/WPO-Foundation/webpagetest/commit/a4f49a681ee7d9f37e889a1cd5b686fa36ab33c6).

Adding
```
medianMetric=SpeedIndex
```
to settings.ini should do it.

**Comment by pmeenan** [comment]
Hold off, may have broken something

**Comment by pmeenan** [comment]
nevermind, false alarm.  Looks to be working ok.
