### ISSUE TITLE
Too low TTFB for Firefox on second view?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#768]
Hi Pat,
for some runs we get a really low TTFB when first go to one page and then access another one. In this example we get 0.032s and the result looks like this (for Firefox): http://wpt.wmftest.org/result/161126_1F_3J/

We run on our own Amazon instance and run the test like this:

<pre>
logData 0
navigate https://en.wikipedia.org/wiki/Main_Page

// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep	2

logData 1
navigate https://en.wikipedia.org/wiki/Facebook
</pre>

Best
Peter

**Comment by soulgalore** [comment]
We still has that issue (updating the link since the old run is deleted): http://wpt.wmftest.org/result/170704_29_B3/1/details/#waterfall_view_step1

**Comment by cpeterso** [comment]
@soulgalore, what is the Time To First Byte for other browsers loading your test page?

@digitarald, have you seen any problems with WPT reporting a low Time To First Byte for Firefox?

**Comment by soulgalore** [comment]
@cpeterso it happens when we do a second view = accessing one page and then go to another URL:

```
logData 0
navigate https://en.wikipedia.org/wiki/Main_Page

// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep	30

logData 1
navigate https://en.wikipedia.org/wiki/Facebook
```
For Chrome at the moment it is between 100-120 ms, but we've seen the same thing happen there once in a while too. 

Maybe it is in our side that we should sleep longer between access and right now the connection is open and super fast?

**Comment by digitarald** [comment]
Interesting that this occasionally also affects Chrome. Might this be caused by slight difference in how browsers handle HTTP2, keeping the connection alive? I'll ping the networking team to hopefully add some expert opinion.
