### ISSUE TITLE
Multistep tests time out with 6th step in Chrome

### ISSUE THREAD

**Issue by nilskuhn** [WPO-Foundation/webpagetest#772]
*Chrome* multistep tests run into timeout with the 6th measured step. Here is an example with a simple (concededly not very sensible) script:

    setEventName	amazon_1
    navigate	https://www.amazon.de
    setEventName	amazon_2
    navigate	https://www.amazon.de
    setEventName	amazon_3
    navigate	https://www.amazon.de
    setEventName	amazon_4
    navigate	https://www.amazon.de
    setEventName	amazon_5
    navigate	https://www.amazon.de
    setEventName	amazon_6
    navigate	https://www.amazon.de
    setEventName	amazon_7
    navigate	https://www.amazon.de

[This wpt result](https://www.webpagetest.org/result/161205_ZQ_VFZ/) shows the effect. First five steps provide valid results, 6th step breaks the test and the whole test runs into a timeout. Following steps don't get measured no matter how many would follow. 

Up to five steps the test doesn't run into timeout:

    setEventName	amazon_1
    navigate	https://www.amazon.de
    setEventName	amazon_2
    navigate	https://www.amazon.de
    setEventName	amazon_3
    navigate	https://www.amazon.de
    setEventName	amazon_4
    navigate	https://www.amazon.de
    setEventName	amazon_5

[Here](https://www.webpagetest.org/result/161205_ZA_VR3/) is a successful result. The concrete steps in the script doesn't matter. We observed the same effect for different scripts.

This only occurs in Chrome browser.

**Comment by pmeenan** [comment]
Better: https://www.webpagetest.org/result/161209_6T_16YB/#run1_step7

The tests run but the in-page metrics for the later steps are still failing.  Pretty safe bet that it is because the xhr post's with the result data stop working.

**Comment by pmeenan** [comment]
Solution is probably going to be to just use one timer to do all communications with the server and any data that needs to get posted from the debugger side of things will just queue up a list of messages and the main task timer will send the messages if there are any and only poll for work when the message queue is empyt. :-/

**Comment by pmeenan** [comment]
Current theory is that Chrome is causing a new connection to be used for each navigation for the localhost connections and since we now keep the connections alive, it is running out of allowed concurrent connections after 6.  Looking into closing the idle connections on the mongoose side.

**Comment by pmeenan** [comment]
Really fixed this time: https://www.webpagetest.org/result/161210_9K_P6M/

wptdriver 345 is out and has the fix.

**Comment by sburnicki** [comment]
Thanks so much for fixing the issue!
