### ISSUE TITLE
Firefox popup about sending data affecting visual metrics

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#773]
Using agent 334 on EC2.

On some Firefox tests a popup along the bottom of the browser is shown with the message "Firefox automatically sends some data to Mozilla so that we can improve your experience". The popup can affect visual metrics like visually complete as the filmstrip is changing.

Example filmstrip image...

![frame_0083](https://cloud.githubusercontent.com/assets/204268/20902965/6264308a-bb9e-11e6-97d6-a4eb022ff3d2.jpg)

**Comment by pmeenan** [comment]
341 just rolled out with a blind stab at a fix (some prefs from Googling around).  Can you give it a shot and see if it fixes it for you?

**Comment by zeman** [comment]
Thanks Pat. Just grabbed latest agent, the code has changed but wptupdate.ini still has 340 for the version.

**Comment by pmeenan** [comment]
Sorry, I forgot to update the version initially and then forgot to update the ini inside of the zip.  Just updated it.

**Comment by zeman** [comment]
Hi Pat,

Got another one where Firefox is downloading safebrowsing files. Are we able to block those as well?

https://wpt.speedcurve.com/details.php?test=161210_KD_ef4ad169a9e9138116fd71f4759da4f7&run=4#waterfall_view_step1

**Comment by pmeenan** [comment]
Bizarre - it must be ignoring the browser.safebrowsing.enabled pref.  Adding a dns-level block now.

**Comment by pmeenan** [comment]
346 is up now with the DNS block
