### ISSUE TITLE
exec command log Data issue

### ISSUE THREAD

**Issue by mkrsinha5** [WPO-Foundation/webpagetest#778]
We are not getting page load result data when we use exec command in script but it works when we use execAndWait.Our test script needs to use **exec command to run JS code to go to next page** and capture page load time.
Do we know why **exec command does not log data**?
Note:We are setting logData 1 before exec

**Comment by pmeenan** [comment]
That is working exactly as intended.  The "andWait" means "wait for the navigation to happen" and marks the point where measurement needs to be done.  exec by itself just means "run this javascript and immediately do the next thing".  If you are filling out a form for example, you could have a bunch of exec commands to do each of the fields and then an execAndWait when it is time to submit and measure.
