### ISSUE TITLE
MS Edge - OCSP status checks missing from waterfall

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#779]
OCSP stapling isn't enabled on http2.andydavies.me but MS Edge doesn't show the OCSP status checks

Packet capture show's they're being made

http://www.webpagetest.org/result/161208_GY_9122ce2f00c38f92d4dea613191553f8/1/details/#waterfall_view_step1

**Comment by pmeenan** [comment]
Thx.  I'll be opening a bunch of issues with the Edge team to get more details out of the tracing.  Right now validation checks just show up as long HTTPS negotiations.  I'll see if there are any trace events currently exposed where I can see the information but it wasn't there the first time I looked.
