### ISSUE TITLE
MS Edge - smartscreen requests showing up in waterfalls

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#780]
Requests to Microsoft's smartscreen service show up in MS Edge waterfall

http://www.webpagetest.org/result/161208_GY_9122ce2f00c38f92d4dea613191553f8/1/details/#waterfall_view_step1

**Comment by pmeenan** [comment]
I'm a bit torn on that one.  It is enabled by default so I don't want to turn it off and I'm not sure hiding them  won't hide visibility into issues (though it's not great to count them against the request and bytes for the pages).
