### ISSUE TITLE
Possible to get more info from -2 errors in IE 11?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#783]
Hello Pat, 
we have a problem with one image that sometimes gives a -2 error when testing on IE 11. It only happens on that specific image. We cannot recreate the error outside WebPageTest, we checked that the image is ok on the instance that WebPageTest hits. But since it only happens on that image and only in IE 11, it would be interesting to know why.

The image is always:
https://upload.wikimedia.org/wikipedia/donate/thumb/2/22/Paypal-USD-color.svg/320px-Paypal-USD-color.svg.png

And here's an example or a run (request 74): 
http://wpt.wmftest.org/result/161218_EX_N2/3/details/#waterfall_view_step1

Is it possible to get more error info from IE 11 in WebPageTest?

Best
Peter

**Comment by Benno007** [comment]
Just a note on this, I get many -2 status codes appearing on my waterfalls, only in webpagetest for my website: https://www.webpagetest.org/result/170207_4H_77057f17f380bdc6d50e17e3ba668111/1/details/#waterfall_view_step1

For images, woffs, js and CSS. No idea whats causing them...

Our content is served from an AWS EC2 instance if it makes any difference.

**Comment by soulgalore** [comment]
Got a new fresh example here:
http://wpt.wmftest.org/result/170310_RC_4Z/3/details/#waterfall_view_step1
