### ISSUE TITLE
[FEATURES] Detect OVH's "private" CDN

### ISSUE THREAD

**Issue by vincent-guesnard** [WPO-Foundation/webpagetest#786]
Hello,

I'm currently using OVH's private CDN to manage my websites. I perfectly understand that you cannot deal with these "private" things. (i mean, register all known urls from private CDN).

But, maybe you should detect OVH CDN usage by watching headers from statics : 

https://cdn.touchweb.fr/media_pages_default_ovh-community-web.png

X-Cacheable:Matched cache
X-CDN-Any-IP:46.105.198.22
X-CDN-Pop:gsw
X-CDN-Pop-IP:46.105.197.0/26

In all case, thanks you for this website, you did a great job.

Best regards,

V

**Comment by pmeenan** [comment]
Should work now.  Just added X-CDN-Pop to the detection for OVH.
