### ISSUE TITLE
supported windows version for webpagetest 3.0

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#788]
@pmeenan,

Could you clarify if webpagetest 3.0 will work on windows server 2012 ?
The last release note only mentions windows 7 as a minimal : 
> Added Windows 10 support and now requires Windows 7 at a minimum.
New traffic-shaping driver (winshaper) is now used for Windows 8.1 or later.

I think that windows server 2012 is similar to windows 7.

**Comment by pmeenan** [comment]
Yes, Server 2012 is ~Windows 8.  It should also work fine with 2008 R2.  The main platform where support was terminated was Windows XP.  Vista may work but isn't really worth it at this point.
