### ISSUE TITLE
WPT sometimes leaks private communication urls (127.0.0.1:8888/viewport.js) in results

### ISSUE THREAD

**Issue by ashvince** [WPO-Foundation/webpagetest#790]
I have noticed that sometimes doing things like setting viewport sizes causes requests to 127.0.0.1:8888 to sometimes be shown the bottom of waterfalls.

Here is an example I just ran that shows the issue:
https://www.webpagetest.org/result/170113_VX_ZC1/1/details/#waterfall_view_step1

**Comment by ashvince** [comment]
I have confirmed that this also happens if I do the same thing bit via the GUI.

Here is a test where I did not use a script but just set the Iphone UA and viewport via the gui options then ran a straight test of the URL.

https://www.webpagetest.org/result/170113_W4_15DJ/

I dont think this happens for every URL though so this is probably Url Specific.

**Comment by ashvince** [comment]
I have managed to capture a debug log from Visual Studio of when it goes wrong here:

[football_pools_debug_log.txt](https://github.com/WPO-Foundation/webpagetest/files/711893/football_pools_debug_log.txt)

I have been trying to look for the section of code which should be filtering the list of requests (or prevents these internal requests from being added to the array) but have not been able to find it anywhere.

**Comment by pmeenan** [comment]
I think it was coming in from Dev tools where we don't include the connection-level filter to ignore traffic on localhost.  Looks like the additional filtering worked: https://www.webpagetest.org/result/170119_R2_KVD0/

Agent 354 includes the fix and is now available if you happen to be using a private instance.

Please re-open if you see them again.
