### ISSUE TITLE
Trying to detect Fastly CDN

### ISSUE THREAD

**Issue by hatzopoulos** [WPO-Foundation/webpagetest#801]
This resource is properly being detected as being loaded using Fastly CDN.
- https://redbot.org/?uri=http%3A%2F%2Fwww.markzproperties.com%2Fimg%2Frew-flogo.png
- https://www.webpagetest.org/result/170130_88_1B0Y/

This one on the other hand is not. Is there something in the headers or WPT code that would cause this to happen? The only difference is this one is using two google load balancers. I'm thinking it's the extra `via` headers but I'm not sure.
- https://redbot.org/?uri=http%3A%2F%2Fwww.manausa.com%2Fimg%2Frew-flogo.png
- https://www.webpagetest.org/result/170130_97_16RZ/

Thanks

**Comment by pmeenan** [comment]
Looks like the current Fastly detection is 100% from the cname on the DNS lookup which is why the Google Load Balancers would throw it off.  I'll see about adding header-based detection.

**Comment by hatzopoulos** [comment]
Thanks!
