### ISSUE TITLE
Implement  First Meaningful Paint metric

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#802]
I think that adding the (First Meaningful Paint)[https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint] metric would be a great addition (like ) to start render, speed index and now (Time to interactive)[https://github.com/WPO-Foundation/webpagetest/issues/781].

The current implementation on Lighthouse makes sense :

> First Meaningful Paint is essentially the paint after which the biggest above-the-fold layout change has happened, and web fonts have loaded.

See the spec to learn more: [First Meaningful Paint: A Layout-Based Aproach](https://docs.google.com/document/d/1BR94tJdZLsin5poeet0XoTW60M0SjvOJQttKT-JK8HI/view#heading=h.tdqghbi9ia5d).

**Comment by pmeenan** [comment]
FWIW, it is already available for Chrome if you enable timeline capture (though it isn't exposed in the main UI).  

You can see it in the filmstrip [timings graph](https://www.webpagetest.org/video/compare.php?tests=170131_NA_c467c87fcc59fe990e5ae472ded58fcb-r:3-c:0#compare-graph) and it is exposed as "chromeUserTiming.firstMeaningfulPaint" in the [API](https://www.webpagetest.org/jsonResult.php?test=170131_NA_c467c87fcc59fe990e5ae472ded58fcb&pretty=1).  The main issue with exposing it in the UI is just figuring out how to add another metric without over-complicating it more than it already is.

**Comment by abarre** [comment]
Thank you for the feedback.
I don't know how realistic this timing is.
In the linked example, the **first meaningful paint** timing (721ms) is inferior to the **start render** timing (1091ms).
It doesn't make sense for me.
In the api : 

```json
"chromeUserTiming.firstLayout": 718,
"chromeUserTiming.firstPaint": 721,
"chromeUserTiming.firstTextPaint": 721,
"chromeUserTiming.firstContentfulPaint": 721,
"chromeUserTiming.firstMeaningfulPaint": 721,
```

In the UI, we see that the start render is correct. 
<img width="995" alt="capture d ecran 2017-01-31 a 16 51 42" src="https://cloud.githubusercontent.com/assets/928701/22472330/957274b0-e7d5-11e6-96aa-ee80714b7f50.png">

In this example, it's hard to tell if the inconsistency between those metrics comes from the video capture that is too slow or if Chrome thinks that the first paint is 300ms before the real paint at the screen.

**Comment by pmeenan** [comment]
I'm confident enough in WPT's 100ms intervals to be sure that the bits were not on the screen at 721ms so I expect there's a little bit of slack in there.  If I had to guess it would be that the paint kicked off at 721ms but getting things from the raster thread through to the actual screen took ~300ms.

Looking at the [timeline](https://www.webpagetest.org/chrome/inspector-20160510/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?timeline=t:170131_NA_c467c87fcc59fe990e5ae472ded58fcb,r:3,c:0) it looks like 721ms is right around where the big layout finished but there is a block of time in raster and gpu right after that which is probably the actual getting of the bits to the screen.

Both Lighthouse and WPT just report what Chrome internally measures for FMP so it looks like there is still a bit of work on the algorithm to try and make it more accurate.

**Comment by pmeenan** [comment]
I sent a note with the details to the Chromium [Progressive Web Metrics](https://groups.google.com/a/chromium.org/forum/#!topic/progressive-web-metrics/fH0aslIKMrA) group.  It will probably turn into a Chrome issue/bug but I don't know how deep in the rendering pipeline they are committing to instrument.

**Comment by pmeenan** [comment]
I verified with the people implementing it that Chrome's current measurement does not include the raster and GPU time (though they are working on it).

**Comment by DivineTraube** [comment]
Quick question: is there any reason, the "chomeUserTiming" field containing the FMP is available in the public WPT instances but not on the private ones? We are using the latest version and the chromeTimeline is activated.

Any hint would be highly appreciated.

**Comment by pmeenan** [comment]
Are you running the latest public release from download or the tip of tree from Github?  The support was added after the last release was cut so unless you are running something more recent that is likely the cause.  I'll be cutting an updated official release this week and moving to a quarterly release schedule to keep them more in sync.

**Comment by KevT2017** [comment]
After the new version "WebPageTest 17.08" was released, our test agents automatically updated succesfully. We also merched our web server software with the master branch. Unfortunatly the "chromeUserTiming" field is still not available.

Do you have any idea what we're doing wrong?

**Comment by pmeenan** [comment]
Do you have timeline capture enabled for the tests?  If you have trace captured are you specifying explicit categories?  If so you may be missing the appropriate categories.

**Comment by KevT2017** [comment]
The "Capture Dev Tools Timeline" is activated and we do not capture chrome trace.
