### ISSUE TITLE
Firefox addon needs to be converted to WebExtension for 57

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#811]
I can reach out to the Firefox addon team. Is there anything that web extensions can not do that WPT needs?

**Comment by cpeterso** [comment]
Firefox 57 (November 2017) will drop support for legacy add-ons and only support [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions). Unfortunately, Firefox's WebExtension API does not yet include all of the Chrome extension APIs used by the wptdriver. Some missing APIs:

* chrome.management.getAll ([Firefox bug 1282981](https://bugzilla.mozilla.org/show_bug.cgi?id=1282981))
* chrome.management.launchApp
* contentSettings
* debugger
* some differences in tabs.create

**Comment by pmeenan** [comment]
FWIW, it doesn't need to be the way things are right now.  The main needed features are:
- Navigate a tab
- Get onload and error notifications for the navigation
- Run JS as if it was running from the dev console

As gravy, getting the request/response timings, headers and bodies and being able to do it all remotely would eliminate the need for an extension at all.

**Comment by luser** [comment]
Just curious--is there a reason webpagetest doesn't use WebDriver or something similar? Chrome and Firefox both have good built-in support for remote protocols based on that.

**Comment by pmeenan** [comment]
That works fine for driving the browser (to some extent) but not for extracting the timing of all of the resources, the headers, response bodies, etc.

Granted, for the current desktop implementation that uses API hooking to measure that stuff, webdriver may be a viable option to replace the Firefox extension.
