### ISSUE TITLE
measure behind proxy?

### ISSUE THREAD

**Issue by nilskuhn** [WPO-Foundation/webpagetest#817]
Hi,

is it possible to measure on an agent behind a proxy with actual wptdriver? I just found [this old thread](https://www.webpagetest.org/forums/showthread.php?tid=11041) about urlblast config. 

Regards, Nils

**Comment by wizzn** [comment]
The question actually is, whether the jobs and results can be sent to a wpt server from behind a proxy. The measurements itself are done within the bounds of the network and do not require a proxied connection.
