### ISSUE TITLE
Duplicate Authorization headers is breaking basic auth

### ISSUE THREAD

**Issue by rdejuana** [WPO-Foundation/webpagetest#818]
I ran a test with basic auth enable and it failed.  WPT is sending 2 Authorization headers.  This is causing 400 errors.

https://www.webpagetest.org/result/170221_7V_80f33a2ab66288c64435627ac96fab4d/1/details/

**Comment by rdejuana** [comment]
The issues started happening with these 2 commit were committed.

https://github.com/WPO-Foundation/webpagetest/commit/9e2ad5add9b00efa36cb19eb47df3401aef681dd

https://github.com/WPO-Foundation/webpagetest/commit/c7ec48b61d3481bdb82c13af6ad1426f9544bbca

**Comment by pmeenan** [comment]
Thanks - should be fixed now: https://www.webpagetest.org/result/170221_HA_a2f18184140912824a0c534fff7e93ff/
