### ISSUE TITLE
Best practice handling agentUpdate on AWS?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#819]
Hey Pat, 
I got question about how we can handle agent updates. Right now we have our server configured with `agentUpdate=http://cdn.webpagetest.org/` and it works great.

We want have better control when updates are pushed (new browser etc) so we know when updates happens. Then we can minimize the risks that the updates triggers an alert (or rather we know it's because of an update).

If we would just disable the autoupdate and then enable it at certain times a week, how long would it be until the agent is updated? 

Or is better way to make sure updates are handled at certain times?

Best
Peter

**Comment by pmeenan** [comment]
The browser, software and agent updates are all done separately.  For the agent updates, the server will check as part of the [hourly cron](https://github.com/WPO-Foundation/webpagetest/blob/master/www/cron/hourly.php#L25) which runs pretty close to the top of the hour.  If you want better control over it you would probably be better off just creating a stub php file that duplicates the AgentUpdate code and then trigger it whenever you want to apply an agent update.

The browsers (and python/support code) are configured on the agent in wptdriver.ini and the public AMI's are all configured to pull the installers from the public WPT config.  The images themselves don't have any Chrome or Firefox installed and they grab the currently published version at startup (and hourly) so the images can be static and never have to update.

If you want control over the browsers then you need to clone the ami's and modify wptdriver.ini to point to your server instead (or to not update the browsers and create new ami's each time a browser update comes out).  You'll also need to either manually update the .dat files and installers on your server or write some code to pull the files from the public wpt whenever you want to update.

**Comment by soulgalore** [comment]
Thanks for the answer!
