### ISSUE TITLE
Private instance without dependencies from outside?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#839]
Hi Pat,
today on a private instance if you look at a [result page](http://wpt.wmftest.org/result/170306_0P_71/) there are a couple of request that isn't loaded from the local domain:
<pre>
http://www.google.com/jsapi
https://www.google.com/jsapi  
https://www.google.com/uds/?file=visualization&v=1&packages=corechart
https://www.google.com/uds/api/visualization/1.0/84dc8f392c72d48b78b72f8a2e79c1a1/ui+en.css
https://www.google.com/uds/api/visualization/1.0/84dc8f392c72d48b78b72f8a2e79c1a1/format+en,default+en,ui+en,corechart+en.I.js
https://ajax.googleapis.com/ajax/static/modules/gviz/1.0/core/tooltip.css
</pre>
Is there a way to configure them to load them locally instead so it's possible to have a self hosted instance?

Best
Peter

**Comment by pmeenan** [comment]
I'm pretty sure that's all for the graphs in various places.  Eliminating them would require either disabling the graphs through a config setting or moving to a charting library that can be shipped with the code (I open to either/both).

On the result page it is for the pie charts with the resource breakdowns.  On the "plot all" chart it is all of the scatter plots, on the content/processing/domains breakdown pages it is the data tables and pie charts and on the filmstrip view it is all of the bar charts below the waterfall.

There may be a few other places but those are all of the ones that come to mind.

**Comment by soulgalore** [comment]
Moving the charting library would be cool since it would enable even more private access :) It's not  super prio for us, but it would be cool for WPT as product (in my opinion). 

I kind of like https://gionkunz.github.io/chartist-js/ and http://www.chartjs.org/ both Open Source and I think the match the graphs we have in WebPageTest today?

**Comment by soulgalore** [comment]
So I wonder: these requests will make all private instances non GDPR compliant right? At least not without adding a privacy policy on our side, saying we share that information.

**Comment by pmeenan** [comment]
That said, I'll happily accept a PR that switches to a locally-hosted charting library, it's just not something I'm actively working on myself.
