### ISSUE TITLE
S3 path-style vs virtual-hosted-style URLs

### ISSUE THREAD

**Issue by mverkerk-godaddy** [WPO-Foundation/webpagetest#840]
In the process of configuring our private WPT instance for S3 archiving, i came to learn that the S3-php client uses **"virtual-hosted-style"** URLs to connect to S3. Unfortunately, our solution (based on Ceph/S3) is configured to only support **"path-style"** URLs. Examples of both are:
```
virtual-hosted: http://<bucket>.<s3_server>/object
path-style: http://<s3_server>/<bucket>/object
```
I made some minor changes to `/www/lib/S3.php` to make it work for us and was curious if this is something you want to support through a new setting in `settings.ini`? Something like `archive_s3_url_type`?

changes to S3.php:

```
--- a/www/lib/S3.php
+++ b/www/lib/S3.php
@@ -1651,18 +1651,18 @@ final class S3Request
-               $this->uri = $uri !== '' ? '/'.str_replace('%2F', '/', rawurlencode($uri)) : '/';
-
-               if ($this->bucket !== '')
-               {
-                       $this->headers['Host'] = $this->bucket.'.'.$this->endpoint;
-                       $this->resource = '/'.$this->bucket.$this->uri;
+               $this->uri = "/";
+               if ($bucket != '') {
+                       $this->uri .= $bucket . "/";
                }
-               else
-               {
-                       $this->headers['Host'] = $this->endpoint;
-                       $this->resource = $this->uri;
+               if ($uri !== '') {
+                       $this->uri .= str_replace('%2F', '/', rawurlencode($uri));
                }
+               // $this->uri = $uri !== '' ? '/'.str_replace('%2F', '/', rawurlencode($uri)) : '/';
+
+               $this->headers['Host'] = $this->endpoint;
+               $this->resource = $this->uri;

```

**Comment by pmeenan** [comment]
I'd rather move to the official php sdk, the s3 lib is pretty ancient and doesn't work with some of the auth requirements if I remember correctly.  Only catch is that we need to keep the s3 lib for uploading to the Internet Archive's "s3-like" interface.

If the path-type works universally I'm good with the short-term fix as well.

**Comment by Verkurkie** [comment]
Gotcha! This page: http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html confirms that Amazon S3 supports both URL styles but there is a clear warning about region-specific endpoints when using path-style URLs. Virtual hosted URLs work best because DNS takes care of things so it should be the default. Path-style could just be an extra option, when needed ... wouldn't even have to make it part of settings.ini.sample, user can add it to their settings.ini when needed and archive.inc can pass it on to S3.php from $settings if it's there?

**Comment by pmeenan** [comment]
sgtm

**Comment by Verkurkie** [comment]
See PR: https://github.com/WPO-Foundation/webpagetest/pull/843.
Worked great on my end and should not impact local directory archiving. I did **not** test traditional 'vhost' style URLs on S3 ...
