### ISSUE TITLE
Edit Test Labels

### ISSUE THREAD

**Issue by tylergraf** [WPO-Foundation/webpagetest#842]
I LOVE webpagetest. Thank you so much for it.

I'd like to be able to edit labels for tests after I run them (mostly because I always forget to set it in the first place and I don't remember which tests are which). Even if you just add the api for it, I'd be happy with that. I can hit the api. 😄

**Comment by pmeenan** [comment]
Currently, if you are logged in you should be able to edit labels but it only shows up for you (and isn't reflected in the test history).

Longer-term it would be nice to allow for the test owner to update both.

**Comment by tylergraf** [comment]
@pmeenan, maybe you can send a screenshot or something, I can't figure out where to edit it in the ui.

**Comment by soulgalore** [comment]
@tylergraf Here:
![image](https://cloud.githubusercontent.com/assets/540757/23773913/88cb1c4e-0521-11e7-83c0-e9d3ec9994ed.png)

**Comment by Henning-Richters** [comment]
Could someone give me a recent screenshot, I can't find the link to edit the lable 🙈
