### ISSUE TITLE
Show which assets are returned from service worker, memory, etc.

### ISSUE THREAD

**Issue by grigs** [WPO-Foundation/webpagetest#845]
I've been doing a decent amount of testing of service workers to try to determine how they impact the performance of pages. Using WebPageTest, I never know whether or not service workers are working or not.

I finally constructed a test page just to confirm that service workers are actually working:
https://cloudfour.com/test-service-worker-on-wpt/

If a service worker is installed, the will be a gray box placeholder image. I confirmed this works on WPT with a repeat view here:
http://www.webpagetest.org/result/170314_6B_15GZ/

However, when I look at the WPT timeline, I can see no indication that the service worker was responsible for delivering some of the assets:
<img width="941" alt="screen shot 2017-03-14 at 11 33 15 am" src="https://cloud.githubusercontent.com/assets/804237/23916647/1f8e32ca-08aa-11e7-9513-e3d79655492c.png">

Compare that to the Chrome DevTools for that page where it is clear what is coming from the ServiceWorker versus disk cache or memory cache:
<img width="737" alt="screen shot 2017-03-14 at 11 34 27 am" src="https://cloud.githubusercontent.com/assets/804237/23916695/4f0e89be-08aa-11e7-8cbc-02a861e9d62a.png">

I'm not sure what the best way is to display this information especially when part of what the repeat view shows is the decrease in requests. 

But as more sites start implementing service workers, it seems like it will be important to report not just that a request didn't go out over the network, but what fulfilled the asset request.

**Comment by addyosmani** [comment]
I love the idea of expressing what resources were served from Service Worker / Cache API vs disk cache here. Heavily rely on how DevTools does this in the Network panel.
