### ISSUE TITLE
Allow using POST with JSON body as params while using WPT API

### ISSUE THREAD

**Issue by greng** [WPO-Foundation/webpagetest#847]
It would be nice to use POST with JSON body to call API, i.e.
POST http://wepagetest.org/runtest.php
body:
`{
"k": "apikey",
"url": "www.aol.com",
"f": "json"
}`
instead of passing query string to the URL
GET http://wepagetest.org/runtest.php?k=apikey&url=www.aol.com&f=json

The issue is that sometimes it is necessary to pass the whole URL encoded script with GET that is not very convenient.

**Comment by pmeenan** [comment]
FWIW, not quite as convenient but you can POST with a multipart-encoded body with all of the fields (that's what the UI does).  I'll see if there is an easy way on the server to detect multipart vs plain (json) post bodies.

**Comment by greng** [comment]
@pmeenan, thanks for informing, POST works for me with application/x-www-form-urlencoded content-type. Despite it's no so convenient as JSON, it's definitely better than just GET with that long URL.

P.S. Thank you for all your work around WPT, I like this tool.
