### ISSUE TITLE
Firefox agent not taking any "setheader" value for H2 enabled domains

### ISSUE THREAD

**Issue by nehaprabhu78** [WPO-Foundation/webpagetest#848]
Hi. I was running a couple of tests last evening and I noticed that the FF agents weren't taking the explicit headers i was trying to send using the "setHeader" command for H2 enabled sites. 

The script I used for both tests:
setHeader test:test
navigate https://http2.akamai.com/

FF WPT result: https://www.webpagetest.org/result/17031...view_step1
Chrome WPT result:
https://www.webpagetest.org/result/17031...view_step1

I have tried addHeader too it doesn't work. I have raised the issue on the webpage test forum too : http://www.webpagetest.org/forums/showthread.php?tid=14802. 

Would you let me know what could be going on here or if you need any additional information?

**Comment by nehaprabhu78** [comment]
Hi team.. checking to see if someone was able to take a look..

**Comment by realmsoft** [comment]
Been around a while.  I've been struggling with the issue since early 2016 and finally logged it here:
https://github.com/WPO-Foundation/webpagetest/issues/728

**Comment by pmeenan** [comment]
Now that the firefox agent is using the new extension model it should be a lot easier to implement (if it doesn't already work).  It may be a few days before I can take a look though.
