### ISSUE TITLE
setViewportSize is not working

### ISSUE THREAD

**Issue by sumanadh** [WPO-Foundation/webpagetest#853]
setViewportSize does not set the browser size to defined dimensions. It starts the test in the default browser window size no matter what the setViewportSize is set. Updating the agents to latest does not work either.  setViewportSize seem to be broken in public instance of webpagetest as well. 

Here are couple of test I have tried in public instance with setViewportSize 300 600. Both the result show the browser size as 929x1047.

https://www.webpagetest.org/result/170322_TV_1E94/
https://www.webpagetest.org/result/170322_T3_1E8X/

Expected: setViewportSize should set the viewportsize to defined dimensions
Actual: setViewportSize dimensions are ignored and test starts in default browser size

**Comment by okor** [comment]
I have noticed the same problem, `setViewportSize` appears to be completely broken.

**Comment by pmeenan** [comment]
Sorry about the delay.  Finally tracked down the issue and it should be working again:

https://www.webpagetest.org/result/170330_AV_1BYA/

**Comment by okor** [comment]
@pmeenan Hey no problem. Thanks for all of your awesome hard work and the fix. I only just noticed myself.
