### ISSUE TITLE
Set DNS for mobile devices

### ISSUE THREAD

**Issue by pedro93** [WPO-Foundation/webpagetest#854]
Hello,

I am not sure if this is bug, missing feature or simply not possible but I am unable to run a webpage test for mobile devices on pages with a custom ```setDns``` script.

The run in question is: https://www.webpagetest.org/result/170330_25_P74/

If I run the test for the chrome desktop browser it works just fine.

Thank you taking the time to read this.

**Comment by pmeenan** [comment]
There were some extra spaces in the script before the IP and url and the mobile agents weren't stripping the spaces out.  I just pushed a fix but it will take ~ an hour to roll out.

In the meantime, if you remove the spaces so it is only tabs in the script it works correctly: https://www.webpagetest.org/result/170330_GA_0bad89b4bb29d50172ddf1475d84dd1c/

**Comment by pedro93** [comment]
Thank you so much!
