### ISSUE TITLE
Problems with "exec" on Firefox since new extension (371)

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#857]
Since using the new extension (#855), quite some scripts stopped working with Firefox.
For example:
```
navigate https://login.audi.com/login/#/de/DE/login
sleep 3
execAndWait document.querySelector(".login_loginform_registernow").click()
```
This script usually results in two steps, the second after clicking on a link.
This works with [Chrome](http://www.webpagetest.org/result/170407_T0_KKS/) and also worked with Firefox before. Now, Firefox [doesn't execute](http://www.webpagetest.org/result/170407_M4_KJP/) the JavaScript anymore.

I also tried different JavaScript commands (like removing DOM nodes, setting input, etc), they all do not work. Interestingly only specific websites are affected, like the one refrenced. On others I don't have this problem.

When I watched Firefox on an gent running the code I saw for example
```
InPageCommandRunner got a command:  Object { command: "evalInPage", target: "document.querySelector(".lo…" }
```
in the console, but nothing happened. When I pasted the same "target" into the console, it was correctly executed.

Any hints on why this behavior might happen or how I can track this down?

**Comment by pmeenan** [comment]
@squarewave fyi, this may be the kind of sandbox issue I was worried about here: https://github.com/WPO-Foundation/webpagetest/pull/855#issuecomment-291198202

Without the debugger* support for running script through the same path as the console uses I'm afraid a lot of scripts may not work.  Unfortunately the old way also breaks electrolysis and won't work going forward.

Do you happen to know if executing script through marionette goes in through a more privileged path?  If so I can see about adding some level of marionette support.

**Comment by pmeenan** [comment]
@sburnicki could you PTAL at wptdriver 372 which I just rolled out to see if it solves all of the cases you have?  The audi case appears to be [working ok now](https://www.webpagetest.org/result/170407_RT_e6d963ad8c48ba53e5cbc8ea0346fc3a/).

Thx @squarewave for the fix.

**Comment by sburnicki** [comment]
AFAICS everything is working fine again. @pmeenan, @squarewave Thank you both so much for your quick help!
