### ISSUE TITLE
Disable password bubble for Chrome emulating mobile?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#859]
Hi Pat,
we get the password bubble for our emulated mobile test on Chrome and desktop tests when we log in a user. Can you check if it is possible to disable it again? [Last time](
https://github.com/WPO-Foundation/webpagetest/issues/562) we got it for our desktop tests but that time it was fixed. I haven't got back in time to check when it was introduced, let me know if that would help and I can check.

![3_screen](https://cloud.githubusercontent.com/assets/540757/25131487/3b45766a-2446-11e7-959c-8c63887186d6.png)

![1_screen](https://cloud.githubusercontent.com/assets/540757/25131677/e6c9669a-2446-11e7-8202-c8979ca29aab.png)

Thanks
Peter

**Comment by pmeenan** [comment]
I just pushed 373 to the public servers.  Can you see if the added command-line option gets rid of it?

**Comment by pmeenan** [comment]
Nevermind - re-ran the old test and it is still failing.  :-/  Wonder if they changed the policies that are used to disable it or how policies are applied.  Digging in deeper now

**Comment by pmeenan** [comment]
Argh, still not working...

**Comment by soulgalore** [comment]
thanks for keeping me updated :)

**Comment by pmeenan** [comment]
OK, Finally got it working in 375 by moving the settings change into the extension.

**Comment by soulgalore** [comment]
thanks, looks good on our side too now!

**Comment by soulgalore** [comment]
Just one quick thing: In our test the password bubble was the first frame so it wasn't picked up as first visual change. However the "waiting" text in the bottom was, so it was the first visual change. But when the password bubble was removed, the waiting text also was removed, so it was a double win :) 

![pickup](https://cloud.githubusercontent.com/assets/540757/25166583/5d49015a-24dc-11e7-8a50-158484b6d5a2.png)
