### ISSUE TITLE
Number of DOM Elements is always 0 for Firefox

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#860]
Looks like it was introduced with #855

**Comment by cpeterso** [comment]
CC @squarewave, who wrote the new Firefox WebExtension.

**Comment by squarewave** [comment]
@pmeenan I'm having a bit of difficulty figuring out where this number comes from. Do you know where I should look?

**Comment by digitarald** [comment]
`Critical blocking resources` also has stopped reporting, visible further down the page in https://speedcurve.com/demo/site/?b=firefox&d=-1&de=1494313199&ds=1492412400&r=us-west-1&s=299&u=908

**Comment by pmeenan** [comment]
Sorry about the delay.  The DOM element count (as well as user and navigation timing data) come from the [collectStats command](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/browser/chrome/extension/wpt/background.js#L491). which looks like it is [wired-up](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/browser/firefox/webextension/extension/wpt/background.js#L509) in the Firefox extension and looks like it [should be collecting it](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/browser/firefox/webextension/extension/wpt/script.js#L534).

Maybe it is related to the security issues we had earlier with permissions or there could be a race condition.  The Chrome agent stops polling for tasks until all of the metrics have been reported and custom scripts have been run.  Depending on how async the messaging is for the stats collection I guess it's possible that it is continuing on before the stats are available.

**Comment by fooksupachai** [comment]
I think that number of DOM elements  should be "0" , So like the previous comment .we should follow up.
