### ISSUE TITLE
Firefox Nightly shows footer slidein with unsent crash reports

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#862]
Landed in https://bugzilla.mozilla.org/show_bug.cgi?id=1269998 This feature has not made it to Beta/Release yet.

Tested on Windows 7/Firefox Nightly.

**Comment by digitarald** [comment]
Looks like the pref to disable is `browser.crashReports.unsubmittedCheck.enabled`

**Comment by pmeenan** [comment]
Rolling an update now with this and the polling interval change.  I'll let you know when it is rolled out so you can validate it is working.

Boy, it would be awesome if all browsers supported a command-line flag "running-test" or something so we didn't have to keep turning features off with every release (Chrome is probably even worse about it).

**Comment by pmeenan** [comment]
376 Just rolled out with the pref set to false.  Feel free to re-open if that didn't take care of it.
