### ISSUE TITLE
Firefox idles a lot of localhost:8000, stretching out test runs

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#863]
Not sure if this happened before the #855 , but Firefox waits a long time on the initial local page before loading the actual test page. In Chrome as comparison the local page is barely visible and immediately triggers the next page load.

**Comment by digitarald** [comment]
@squarewave did you see any differences in how the new/old extensions handled connecting to the local WPT agent server and trigger page load?

**Comment by squarewave** [comment]
Hmm, both the Chrome extension and the new WebExtension start off with this bit:

```js
  browser.tabs.query(queryForFocusedTab, focusedTabs => {
    ...
  };
```

But I noticed that in FF, focusedTabs can be an empty array on startup. So I added a setTimeout to retry every half second. If I had to guess I'd say this is where the delay is coming from. I'll dig into it a bit though.

**Comment by squarewave** [comment]
Scratch that, I think a 0 just snuck into the TASK_INTERVAL constant (5000 instead of 500).

**Comment by digitarald** [comment]
Looks that way. Interesting that it causes more than 5sec delay

**Comment by digitarald** [comment]
@pmeenan I still see Nightly spending a 10sec+ on 127.0.0.1:8888/blank2.html. Chrome shows it only for less than 1s.

**Comment by digitarald** [comment]
A new setup on Windows 10 works much faster. Maybe the agent somehow didn't update?
