### ISSUE TITLE
Chrome 58 emulated mode changes background color?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#867]
Hi Pat,
this not an WebPageTest issue I think it comes from Chrome. When 58 was updated we suddenly got a drop in first visual change with about a second for all our mobile tests that runs Chrome mobile emulated (we set emulateMobile to true, nothing else).

It looks like this and the grey color is picked up as first visual change.
<img width="1016" alt="screen shot 2017-04-28 at 12 21 27 pm" src="https://cloud.githubusercontent.com/assets/540757/25527252/3e5a1f20-2c18-11e7-8cef-9ed9c37aec81.png">

http://wpt.wmftest.org/video/compare.php?tests=170428_81_9X-r:2-c:0

It could of course be our code, but then somehow occurred when we switched to 58.

Best
Peter

**Comment by pmeenan** [comment]
That looks suspiciously like the background color that Chrome uses for the window that surrounds the actual emulated viewport.  My guess is that it is a similar GPU problem that has happened before where it doesn't clear out the buffer when painting the blank screen when the page commits.

Doesn't appear to be an issue on real devices: https://www.webpagetest.org/result/170428_GR_3d4815459f7b3822f8323787ea56d3e8/

I'll add logic to detect the solid gray and delete those frames from the beginning.

**Comment by pmeenan** [comment]
You can see the same gray around the border here:

![image](https://cloud.githubusercontent.com/assets/444165/25529790/92e094ba-2bf1-11e7-84dd-f9b3fb5c87b1.png)

That was from mobile emulation on the Linux agent (which looks like Dev tools screen shots have more issues with the "fit" emulation option that I need to sort out)

**Comment by pmeenan** [comment]
I just pushed 377 which should fix it:

![image](https://cloud.githubusercontent.com/assets/444165/25532617/f23dcac2-2bfb-11e7-9163-43658f861552.png)

**Comment by soulgalore** [comment]
Yep you are right. I see the same on my other tests (on Linux), the same behaviour there, after a second or two the full screen becomes grey. No luck it can be fixed in Chrome for future releases? 

We updated to 58 the 23rd on another machine, but I missed that because we only have negative alerts firing when metrics increases:
<img width="1407" alt="screen shot 2017-04-28 at 16 15 25" src="https://cloud.githubusercontent.com/assets/540757/25532524/eefdad96-2c2d-11e7-957b-24366706374d.png">

**Comment by pmeenan** [comment]
Are your Linux test with the WPT agent or the sitespeed.io agent?  The WPT agent uses the dev tools frames which shouldn't have the same issue (at least that I could see).

It's been a problem in Chrome for a while though it used to show up on the mobile devices as the "orange" screen flashing back before the real page content paints.

I'll see if I can find a clean repro case under normal user usage and file a crbug.

**Comment by pmeenan** [comment]
btw, if it will help, I can add the same logic to visualmetrics.py as an option to ignore solid-color frames when looking for start render (if that will help with your linux agent).

**Comment by soulgalore** [comment]
Great, thanks for the quick fix! 

> btw, if it will help, I can add the same logic to visualmetrics.py as an option to ignore

Would be super, thanks!

**Comment by pmeenan** [comment]
any chance you can send over a raw video with the gray frames?  That would help when testing the visualmetrics change locally.

**Comment by soulgalore** [comment]
Yes of course will fix one now.

**Comment by soulgalore** [comment]
Argh I have a bug in our code that always generates the timer, I need to fix that first to be able to generate the video without any text. Will fix that tonight, need to cook food for the kids, it's that time here now :)

**Comment by pmeenan** [comment]
no rush.  If at all possible, the original video that you pass into visualmetrics when running the test would be best rather than one that has been processed and re-encoded.

**Comment by soulgalore** [comment]
we don't have that today, I need to add a conf to keep the old ones. Only thing with the processed one is that we remove the orange frame, have a version here if it van help: https://www.peterhedenskog.com/video-grey.mp4

**Comment by soulgalore** [comment]
Ok, here's the original, uncut version: https://www.peterhedenskog.com/original-video.mp4

I got a change in VisualMetrics that I haven't pushed, I'll create an issue and discuss it later this weekend. We use the full video screen when we decide when the orange go to white (I think the original version cut X pixels), but we got cases in Chrome where the screen could be just a couple of pixels orange (I guess that is the same GPU thing).

**Comment by pmeenan** [comment]
I just updated visualmetrics to take a --gray command-line option which will remove any gray frames at render start.

If you have example videos of other problems I'm happy to debug them and make the code more robust.

**Comment by pmeenan** [comment]
And I apologize in advance for not also supporting --grey.  Couldn't decide which spelling to use so just picked one randomly.

**Comment by soulgalore** [comment]
hehe ok, thanks :)
