### ISSUE TITLE
Content Breakdown - Chrome - Uncompressed Size is 0

### ISSUE THREAD

**Issue by czb182** [WPO-Foundation/webpagetest#868]
I'm running wpt using chrome and I'm not getting back uncompressed sizes anymore.  This is since has been happening since April 27th some time.

example: https://www.webpagetest.org/result/170501_ZJ_R8F/6/breakdown/

**Comment by pmeenan** [comment]
Should be fixed as of a couple of hours ago: https://www.webpagetest.org/result/170501_1C_YSS/1/breakdown/

Chrome 58 broke the TLS API hooking so WPT didn't have access to the raw responses.
