### ISSUE TITLE
Iphone/IpadMini Timeouts

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#871]
Hi Pat,
we have had problems get any Iphone 6/  iPadMini2 test through the last weekend (week) on the public instance but I guess it has been overloaded with work. When I check them now most of them have run through. We have a default timeout for 10 minutes but that is probably too optimistic. I've increased the timeout time.

https://www.webpagetest.org/result/170508_9G_FTN/ (stuck)
https://www.webpagetest.org/result/170508_TK_FTQ/
https://www.webpagetest.org/result/170507_SG_QVN/

I guess you can just close this, and I can keep track if the increase of timeout helps.

Best
Peter

**Comment by pmeenan** [comment]
Oh, 10 minutes is WAY optimistic for the iPhone 6 in particular.  It seems to be crazy-busy on a regular basis with over 40 high-priority tasks in it's queue.

If I can get time to build out the new agent and eliminate the need for a Mac to drive each phone I'll be able to deploy a few more which should help.

**Comment by soulgalore** [comment]
Nothing to do here, lets close it.
