### ISSUE TITLE
Add UserTiming measures to events/marks table

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#875]
Waterfall drawing for UserTiming marks and measures is complicated and that's why measures were only added to API at this point (#516).

But it might be less problematic to add them to events table at the top of the page that already shows all collected UserTiming marks.

Measures have start, end and duration as informative components with duration probably being the most important of the three.

**Comment by mattgen88** [comment]
I'd also like to see this, additionally I'd like to see it done in such a way where a lot of user marks doesn't stretch the page width out forever. Currently with many marks it'll just keep growing the table out infinitely. It'd be nice if there was some better UI for marks along side measures.

**Comment by sergeychernyshev** [comment]
Checked this today only to realize that measures are still not in the table (or were removed from the table again).

Keeping this ticket open then.
