### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID error in EC2

### ISSUE THREAD

**Issue by paha77** [WPO-Foundation/webpagetest#876]
Hi,

I'm running my own WebPageTest instance on Amazon EC2 (created from the AMI 22cefd3f in Europe-Central-1).  Since 1.5 weeks I'm not able to test my HTTPS sites because on the client, which the instance brings up on demand (from the AMI 87f2ebeb) all of the certificates are invalid:

![1_screen](https://cloud.githubusercontent.com/assets/5096366/26061799/3d954eba-3989-11e7-9af4-f00374b67681.png)

Of course they are valid and even if I create an instance from the same AMI manually, change the Windows Password, login with remote desktop and open the same website with Chrome's mobile view they are working.

Does anyone had similar issues or ideas?

Thank you.

**Comment by paha77** [comment]
Answer to myself, ignoring SSL certificate errors solves the problem:

![image](https://cloud.githubusercontent.com/assets/5096366/26062552/70b7ad22-398b-11e7-9017-8c34727e3a2e.png)

But I'm still wondering what's the reason.  Thx.

**Comment by pmeenan** [comment]
Possibly the root certs on the OS need updating and they aren't getting updated.  There was an [update](https://github.com/WPO-Foundation/webpagetest/commit/4b53dfac62aee4b82cf756460174d456c9b66527) back on 5/5 to prevent cert updates from happening during the test itself (which would throw the perf measurements off).

 It's probably a good time to release updated AMI's that have all of the OS updates (including root certs) installed.
