### ISSUE TITLE
Emulated mobile in Chrome gets different viewport Windows vs Linux

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#878]
Hi Pat,
been testing out the AMI for Linux and it works fine for us except that it seems that the default viewport when you run a test for Chrome as emulated mobile is different.

On our Windows instance the screenshot looks like this:
![1_screen_thumb](https://cloud.githubusercontent.com/assets/540757/26201660/64825e76-3bd4-11e7-9718-c06e84e27d6f.jpg)

And on the Linux instance (using the exact same configuration):
![1_screen_thumb-1](https://cloud.githubusercontent.com/assets/540757/26201714/970761f2-3bd4-11e7-9055-1769038d83a3.jpg)

Best
Peter

**Comment by pmeenan** [comment]
I don't think the agent got the test settings correctly.  It is possible that there were updates to the server side (work/getwork.php) where the test options are json-encoded or something else went wrong.

Can you run the agent with -vvvv and post the debug entry where it gets the test job from the server which should have the mobile emulation settings?

The "Dulles - Linux" location is running the linux agent and the "Mumbai" location is running the EC2 Linux AMI and both look to be working fine which makes me think it's a server-side issue (or possibly the agent expecting some fields and not being as backward-compatible with earlier servers).

[Test from Dulles](https://www.webpagetest.org/result/170518_7Y_f68108fda7235ef4e3562670a9ef3009/):
![image](https://cloud.githubusercontent.com/assets/444165/26204734/a0cb047c-3bad-11e7-9c34-af186504f33b.png)

[Test from Mumbai (AMI)](https://www.webpagetest.org/result/170518_GV_ad0e39bcb7c2d9b1e044b48a20af7fd7/):
![image](https://cloud.githubusercontent.com/assets/444165/26204911/42be3966-3bae-11e7-9bd1-fd71b0b3e2a1.png)

**Comment by soulgalore** [comment]
Finally got around to test again with an updated work/getwork.php on the server, but I got the same thing there (http://wpt.wmftest.org/result/170621_F6_E4/), but maybe there's something else that I should update. 

I'll test to see if I can login to the agent, it auto spins up by the server and it complains about the public key/username/password. I'll try some more.

Btw do you know when you will have time to make Firefox to work in the Linux instance (I would like to switch so we save money).

**Comment by soulgalore** [comment]
Also we didn't have the latest version of the code running for our server but according to https://sites.google.com/a/webpagetest.org/docs/private-instances it should auto update, is that right?

**Comment by pmeenan** [comment]
Auto-updating the server should happen from the automated cron job and the setting to auto-update git but I have seen it have issues (not sure exactly why yet).

The linux agent should support sending a debug log if you run a test with debug=1 option (assuming the server code is updated to pass it through).  Done through the UI you can add ?debug=1 as a query param to the test UI and it will pass it through as a hidden parameter.  The debug log for each test will be to the left of the waterfall with the dev tools timeline.  That will help for figuring out what is going on.

Firefox support in the Linux agent is close.  It should be able to run a test and get a waterfall right now.  I just need to add the video capture and it should be basically done.  Response bodies and optimization checks won't be available for a few Firefox releases though until they ship the web extension API for getting response bodies (it is being worked on right now).

**Comment by soulgalore** [comment]
Thanks! I turned on the gui and added the debug parameter but wasn't able to get the log, so I guess we don't have the latest (or even months old) version of the server, I'll try to run the update manually.

I tried out the Firefox version a month ago and then you got an error immediately but I can try again when I got the latest version of the server. Thanks again for all the help!

**Comment by soulgalore** [comment]
Updated the code with "git pull origin master" and now it works! The problem on our side was that I've manually updated settings/ec2_locations.ini to include webpagetest.org as a relay server, and then when that file also was updated on Github, I got the error "Your local changes to the following files would be overwritten by merge ..." and I think the php hourly cron script just swallows the error (I could see it when I run the update manually). We got a lot of new functionality now :)

**Comment by soulgalore** [comment]
Just FYI just tried latest Firefox on Linux and get "First View: Test Error: Invalid browser - Firefox".

**Comment by pmeenan** [comment]
Just pushed the Linux path detection (and did some quick testing).  Should work with both Stable (or beta) as well as Nightly.  Nightly runs in parallel, stable and beta both install to the same location so it is one or the other.

Only requirement is you need to install the marionette_driver pip package (sudo pip install marionette_driver).

Working on getting the video capture hooked up right now (it already starts with an auto-hiding orange splash screen so should just be a matter of using ffmpeg to record the xvfb buffer or screen).
