### ISSUE TITLE
Custom user-data for auto started EC2 Agents

### ISSUE THREAD

**Issue by kszarlej** [WPO-Foundation/webpagetest#879]
Documentation states that setting wpt_username and wpt_password for agent is possible in user-data. However function that auto starts EC2 agents(https://github.com/WPO-Foundation/webpagetest/blob/master/www/ec2/ec2.inc.php#L53) sets only three values (wpt_loc, wpt_server, wpt_key). Is there any other way to instruct webpagetest to set additional settings in user-data? I tried to set `user-data=myuserdata` in ec2_locations.ini with ec2_location setting enabled but it looks like it doesnt work.

**Comment by pmeenan** [comment]
No (at least with how the code is currently).  The user data is generated dynamically and doesn't have support for custom fields.

Shouldn't be hard to add, the code is [here](https://github.com/WPO-Foundation/webpagetest/blob/master/www/ec2/ec2.inc.php#L53)

**Comment by kszarlej** [comment]
Thanks @krzysztof-pyrzyk-ah  and @pmeenan the issue is resolved.
