### ISSUE TITLE
exec command doesn't seem to work

### ISSUE THREAD

**Issue by abarre** [WPO-Foundation/webpagetest#880]
Hi,

I tried to use the command `exec` to execute custom script in the page but it seems to break the test. The agent fails in timeout after 9min.

```
navigate http://www.clarins.ru/
exec window.performance.mark('mark_fully_loaded');
````
Ref : http://www.webpagetest.org/result/170522_FY_163V/

The same test without exec is executed in 20sec.
```
navigate http://www.clarins.ru/
```
Ref : http://www.webpagetest.org/result/170522_W9_1650/

PS : I'm testing a way to add a script that stops some animations (eg: sliders) to improve reliability of visual metrics (Speed Index, Visually Complete).

**Comment by pmeenan** [comment]
exec runs after the previous step (i.e. after the navigation of the page has been done and fully measured).  There's no way to inject code into the page while it is loading which is what it sounds like you need.

**Comment by abarre** [comment]
Thank you for your quick reply.

At Fasterize, it's a pain to deal with this slider when measuring metrics. I think that a lot of users share this problem.
It would be interesting to add an option directly in WPT that stop setTimeout, setInterval, and CSS animations after the window.onload event.

I will prototype a Chrome extension that stops animations and see if it works with WPT.

**Comment by simonhearne** [comment]
@abarre [setActivityTimeout](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setActivityTimeout) could be your friend here. I blogged about using to help improve the reliability of visual metrics with sliders & spinners: <https://webperf.ninja/2016/getting-reliable-visual-metrics/>

**Comment by abarre** [comment]
Thanks @simonhearne, yes, it seems to work in my test : 
http://wpt.fasterize.com/video/compare.php?tests=170526_33_Q,170526_TZ_N,170526_XN_K,170526_TZ_N,170526_HT_H,170526_TH_G,170526_7T_P,170526_G3_M,170526_ND_J

The tests with the `setActivityTimeout` have the label "fix".
