### ISSUE TITLE
Issues with EC2 instance creation/termination, possibly due to WebPageTest thinking the instance are not longer up (not sure why)

### ISSUE THREAD

**Issue by padibona** [WPO-Foundation/webpagetest#883]
Hello,

I have several issues with the EC2 AMIs currently.

Issue #1:

The getTesters.php seems to stop seeing a working EC2 instance (according to the EC2 Dashboard)

As seen from the getTesters page:
![image](https://cloud.githubusercontent.com/assets/2515197/26565063/72b5488c-44ad-11e7-8105-ed8ed6aab9fd.png)

As seen from the AWS Console:

![image](https://cloud.githubusercontent.com/assets/2515197/26565087/ab418260-44ad-11e7-8c49-a02e200a5408.png)

Issue #2:
A known working (according to AWS) instance gets terminated hourly, no matter what.
This issue may be related #1. I've added ec2.log below showing the up and down nature of all the instance thrashing.

Issue #3:
Looking at the below log you can see that an instance according to WebPageTest failed at coming up. When in fact that instance ID shows up here:
![image](https://cloud.githubusercontent.com/assets/2515197/26565299/82d33754-44af-11e7-9861-9da3ea70b569.png)
I've noticed that the label for WebPageTest Agent did not show up. Does this mean that the instance got spun up but there was no proper tag associated with 'WebPageTest' so WPT thinks it is a failed instance. 

Comments:

I'm not sure what parts of code is doing what, but there seems to be some sort of communication issue between what WebPageTest thinks are active EC2 agents, and actually what are the active agents according to EC2.

One thing I have noticed is that the EC2 Instances.dat file seems to have the correct number of Instances that are actually in EC2 and which ones. Here is an example of this:

Accoriding to ec2instanced.dat:

{"ami-2f221c41":{"count":1},"ami-87f2ebeb":{"count":1},"ami-4a84a220":{"count":2}}

According to AWS:

![image](https://cloud.githubusercontent.com/assets/2515197/26565461/13e7c6fa-44b1-11e7-95af-c8a75f718e76.png)

Here is that log I was talking about:

ec2.log:

00:05:09 - Launching c4.large ami ami-4a84a220 in us-east-1 for us-east-1 with user data: wpt_server=myserver wpt_loc=us-east-1 wpt_key=mykey
00:05:11 - Instance i-084210c2ff253ef08 started: c4.large ami ami-4a84a220 in us-east-1 for us-east-1 with user data: wpt_server=myserver wpt_loc=us-east-1 wpt_key=mykey
00:05:11 - Error: Launching EC2 instance. Region: us-east-1, AMI: ami-4a84a220, error: The instance ID 'i-084210c2ff253ef08' does not exist
00:10:10 - Terminated instance i-0d731039184f9332e in us-east-1
00:20:10 - Terminated instance i-0f298574f47aea309 in us-east-1
00:25:08 - Terminated instance i-0f298574f47aea309 in us-east-1
00:30:10 - Terminated instance i-037e825e1f9fcdeff in ap-northeast-1
00:30:11 - Terminated instance i-0d9d9e0c4fc198cbf in us-east-1
00:30:11 - Terminated instance i-06f18ba18103a429a in us-east-1
00:30:11 - Launching c4.large ami ami-4a84a220 in us-east-1 for us-east-1 with user data: wpt_server=myserver wpt_loc=us-east-1 wpt_key=mykey
00:30:12 - Instance i-0561bc8a21f92f545 started: c4.large ami ami-4a84a220 in us-east-1 for us-east-1 with user data: wpt_server=myserver wpt_loc=us-east-1 wpt_key=mykey
00:35:10 - Terminated instance i-037e825e1f9fcdeff in ap-northeast-1
00:35:11 - Terminated instance i-0d9d9e0c4fc198cbf in us-east-1
00:35:11 - Terminated instance i-06f18ba18103a429a in us-east-1
00:45:11 - Terminated instance i-0fdfbc8dabd44e553 in eu-central-1
00:45:11 - Terminated instance i-07e0e85cfe916f7e9 in us-east-1
00:45:11 - Launching c4.large ami ami-4a84a220 in us-east-1 for us-east-1 with user data: wpt_server=myserver wpt_loc=us-east-1 wpt_key=mykey
00:45:12 - Instance i-06e530129cf57f8d9 started: c4.large ami ami-4a84a220 in us-east-1 for us-east-1 with user data: wpt_server=myserver wpt_loc=us-east-1 wpt_key=mykey
00:50:11 - Terminated instance i-0612240f2b5dc339e in ap-northeast-1
00:50:11 - Terminated instance i-0aa5c76fa78ea6f31 in eu-central-1
00:50:12 - Terminated instance i-0fdfbc8dabd44e553 in eu-central-1
00:50:12 - Terminated instance i-07e0e85cfe916f7e9 in us-east-1
00:50:12 - Launching c4.large ami ami-87f2ebeb in eu-central-1 for eu-central-1 with user data: wpt_server=myserver wpt_loc=eu-central-1 wpt_key=mykey
00:50:13 - Instance i-050d7f09fa4ba2edd started: c4.large ami ami-87f2ebeb in eu-central-1 for eu-central-1 with user data: wpt_server=myserver wpt_loc=eu-central-1 wpt_key=mykey
00:50:13 - Launching c4.large ami ami-2f221c41 in ap-northeast-1 for ap-northeast-1 with user data: wpt_server=myserver wpt_loc=ap-northeast-1 wpt_key=mykey
00:50:15 - Instance i-0e6db1b8a92599cab started: c4.large ami ami-2f221c41 in ap-northeast-1 for ap-northeast-1 with user data: wpt_server=myserver wpt_loc=ap-northeast-1 wpt_key=mykey
00:55:10 - Terminated instance i-0612240f2b5dc339e in ap-northeast-1
00:55:11 - Terminated instance i-0aa5c76fa78ea6f31 in eu-central-1
01:00:09 - Terminated instance i-084210c2ff253ef08 in us-east-1
01:05:10 - Terminated instance i-084210c2ff253ef08 in us-east-1
01:25:10 - Terminated instance i-0561bc8a21f92f545 in us-east-1
01:25:10 - Launching c4.large ami ami-4a84a220 in us-east-1 for us-east-1 with user data: wpt_server=myserver wpt_loc=us-east-1 wpt_key=mykey
01:25:11 - Instance i-0b59bcfb8bd4560fb started: c4.large ami ami-4a84a220 in us-east-1 for us-east-1 with user data: wpt_server=myserver wpt_loc=us-east-1 wpt_key=mykey
01:30:09 - Terminated instance i-0561bc8a21f92f545 in us-east-1

I hope this will help diagnose what is going on.

If you need any other information I would be happy to give you whatever you need. I will be actively working on this project until further notice.

Thanks,

Pete

**Comment by padibona** [comment]
Update:

We have another instance of WebPageTest using a manual install into Azure with the 3.0 code and 348 agents which works like a charm! 

![image](https://cloud.githubusercontent.com/assets/2515197/26566452/f4ebc528-44b8-11e7-8a0a-d43eb4f52245.png)

Agents are rock solid, all the time.

Thought this might help troubleshoot some things.

Thanks,

Pete

**Comment by padibona** [comment]
Hello,

Another Update:

It seems that all agents are communicating fine with the server and actually running tests, which is super good news.

Here are some things that are still happening:

1. The /getTesters.php?f=html is still not showing all of the available testers.
2. We still are having instances being shut down about every 55 minutes, is this AWS instance management based on what the getTesters is seeing? If so, that could totally explain why we are seeing this behavior. The http://server/install/ is also showing the incorrect number of agents.

When I get a chance, I will try spinning up a fresh server and manually install based on the 3.0 code release with all linux updates done beforehand.

I'll keep you posted with more info as it comes in.

Thanks,

Pete

**Comment by pmeenan** [comment]
getTesters should reflect what WPT knows about the agents and yes, if there are instances running that it doesn't know about it very well may kill them (to avoid zombies which unfortunately happens with EC2 every now and then).  

It shouldn't be possible for instances to get work but not show up in the UI unless both the PC name and the IP address it is connecting from is the same (the name + the IP are the unique key they are indexed under).  If it is coming in through a load balancer then that might mess up the IP address.

**Comment by pmeenan** [comment]
FWIW, the scaling up/down logic hasn't really had a lot of exercise so if you see anything else weird then feedback is appreciated (particularly if you try out fixes on a running system).  

The scaling up logic is [here](https://github.com/WPO-Foundation/webpagetest/blob/master/www/ec2/ec2.inc.php#L272) and scaling down is [here](https://github.com/WPO-Foundation/webpagetest/blob/master/www/ec2/ec2.inc.php#L131)

**Comment by padibona** [comment]
Some updates to things I am seeing:

1. It looks like there are some testers that are up in AWS, not showing in getTesters.php but still running tests. Pictures will be below labeled #1.

2. We had things settle down (no Instance spinning up or terminating) for a few days, but I lowered the EC2 Scale Factor setting and it seems once the Autoscale kicked in it threw something out of whack.

3. At one point we had 1 agent showing up in getTesters.php but 2 in AWS. I then terminated the missing EC2 manually then piled up some API tests. Here is what happened:
     a. Autoscale correctly spun up a new Instance to meet our 2 minimum.
     b. Both testers showed up in getTesters.php for the duration of the remaining API tests.
     c. Almost immediately (maybe a cron job timed at the same time) the New EC2 Instance disappeared 
          from the list of available testers in the getTesters.php. This seemed weird to me as I was under the 
          impression that it was supposed to not remove testers unless they have been idle for 15 minutes 
          or more.
     d. I then kicked off another pile of API tests and the 'marked offline' (I think) new EC2 instance did not 
         show up in the getTesters.php, nor actually run any tests.
Here are the pictures showing how the getTesters.php is not actually showing a seemingly working tester based on the number of tests and timestamps:

11:23AM:

![image](https://user-images.githubusercontent.com/2515197/26940371-04884932-4c40-11e7-9c14-c053240f56ff.png)

![image](https://user-images.githubusercontent.com/2515197/26940384-0d8a677c-4c40-11e7-800c-8c3c6bb318af.png)


11:24AM:

![image](https://user-images.githubusercontent.com/2515197/26940399-1b8ec43a-4c40-11e7-8328-8ba8780740ca.png)

![image](https://user-images.githubusercontent.com/2515197/26940423-2db56920-4c40-11e7-8d58-ce99e47bd565.png)

Based on what I show above, can you think of any particular areas that might be causing the behavior I am seeing?? 

When I get a chance (might be a few days) I will put in some strategic logging and/or commenting out of things to see what is actually happening. 

Thanks,

Pete

**Comment by quentin389** [comment]
Hi,
I think this may be related to `EC2_SendInstancesOffline()` function marking instances as offline whenever more than one instance is running, and not looking at `EC2.*.min` setting.

I'm currently testing the following patch:

```Index: www/ec2/ec2.inc.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- www/ec2/ec2.inc.php	(revision e3adb3f6d1b4a77dd2f565edfa070dc0269c442d)
+++ www/ec2/ec2.inc.php	(revision )
@@ -228,19 +228,27 @@
   // Figure out how many tests are pending for the given AMI across all of the locations it supports
   foreach ($locations as $ami => $info) {
     $tests = 0;
+    $min = 0;
     foreach($info['locations'] as $location) {
       $queues = GetQueueLengths($location);
       if (isset($queues) && is_array($queues)) {
         foreach($queues as $priority => $count)
           $tests += $count;
       }
+      $locMin = GetSetting("EC2.min");
+      if ($locMin !== false)
+        $min = max(0, intval($locMin));
+      $locMin = GetSetting("EC2.$location.min");
+      if ($locMin !== false)
+        $min = max(0, intval($locMin));
     }
     $locations[$ami]['tests'] = $tests;
+    $locations[$ami]['min'] = $min;
   }
   
   foreach ($locations as $ami => $info) {
-    // See if we have any offline testers that we need to bring online
-    $online_target = max(1, intval($locations[$ami]['tests'] / ($scaleFactor / 2)));
+    // See if we have any online testers that we need to make offline
+    $online_target = max($info['min'], intval($locations[$ami]['tests'] / ($scaleFactor / 2)));
     foreach ($info['locations'] as $location) {
       $testers = GetTesters($location);
       if (isset($testers) && is_array($testers) && isset($testers['testers']) && count($testers['testers'])) {
```

I'm not completely positive if that fixes the whole issue though, as I'm not sure yet why those instances are being terminated at some point nor I have tested it with any other settings than my own.

**Comment by padibona** [comment]
@quentin389 This does indeed seem to have fixed all of the issues I was seeing. We now spin up and properly spin down machines and we still have our Minimum Testers always up and ready for ad-hoc users.

Thanks again!

Closing this.
