### ISSUE TITLE
Remove Connected Test Agents

### ISSUE THREAD

**Issue by dtrikannad** [WPO-Foundation/webpagetest#884]
Hi, is there anyway to reset the test locations back to empty? I want to reset a location test agent and want to reuse a wpt_location, but I've noticed that even though the test agent is no longer up, the server keeps thinking a previously connected agent is always connected. Is there anyway to force it to update itself?

Thank you.

Deep

**Comment by pmeenan** [comment]
You can wipe out the {docroot}/tmp directory but the agents should automatically disappear after an hour.

**Comment by dtrikannad** [comment]
Great, thank you! Just got worried about them piling up.

Deep
