### ISSUE TITLE
Resources blocking doesnt work anymore

### ISSUE THREAD

**Issue by MW-support-MW** [WPO-Foundation/webpagetest#890]
When i try to block resources they are still being loaded. This wasn't the case two weeks ago.

**Comment by pmeenan** [comment]
Looks like Chrome changed the API for blocking requests.  Should be [fixed](https://github.com/WPO-Foundation/webpagetest/commit/9f9f3567fd758ad53f9493dac5a999436c31d784) now (re-open if it isn't).
