### ISSUE TITLE
SetCookie is not work

### ISSUE THREAD

**Issue by gulipingTju** [WPO-Foundation/webpagetest#893]
I have build webpagetest as  private instances. when I use android phone as the agent , the setCookie command is not work. I got the log of agent ,that says "Unexpected script command:setcookie". My agent code is the latest version. I don't know how to fix that. Please help me. Thanks!

**Comment by DarkSoulCool** [comment]
I think for  Android apps can use cookies.  That is, the apps can use a website and rely on cookies, but those cookies are only known to the app.  I do not think there is a way around that.

**Comment by pmeenan** [comment]
Which agent are you running?  [wptagent](https://github.com/WPO-Foundation/wptagent) is the current mobile agent and should support setting cookies.
