### ISSUE TITLE
Possible to show cached requests in waterfall?

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#894]
Seeing Javascript execution in the waterfall is extremely helpful.

However, for cached views or multi step measurements, there might be lots of JS execution from cached resources, so we can't figure out which resources cause CPU utilization from the waterfall.
To expose this, it would be very helpful to be able to also show cached resources in the waterfall, e.g. in the custom waterfall view.

Do we have enough data from the tests to enable this?

**Comment by jamesshannon** [comment]
+1 I mostly wanted to see cached requests as a sanity check, but CPU utilization is important, too. See, e.g., [this test](https://www.webpagetest.org/video/compare.php?tests=171124_33_388d64eacc59083277f71c3f78ebb10b-r:1-c:0-s:2).

I built a "warmer" page that loads the AMP runtime (the assumption being that most browsers will have this cached). Clearly the runtime is getting loaded and parsed, but it's not showing up in the waterfall.
