### ISSUE TITLE
Should Custom Metrics have a separate namespace to avoid clashes with other results fields?

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#903]
Noticed I can create a custom metric that has the same name as one of the other results fields, but in the results I'll get back the value from the result:

In this example https://webpagetest.org/custom_metrics.php?test=170706_QR_PW2&run=1&cached=0 I created a custom metric called visually complete

```
[visualComplete]

return "Maybe";
```

In the results the visualComplete custom metric contains the value from visualComplete in the test rather than the value I returned from the custom metric

Wonder if they should live under the custom field in the results e.g. data.median.firstView.custom._customMetricName_

Although this is of course a breaking change for those using the API

**Comment by pmeenan** [comment]
I actually put them in the same namespace on purpose but it could be a bit of a foot-gun.  The main use case I was thinking about was to be able to override the "result" with a custom metric as a way to do in-page validation that the correct page loaded.

**Comment by andydavies** [comment]
I only came across it because I was looking at the JSON so I'm going to close
