### ISSUE TITLE
Some probes need a restart

### ISSUE THREAD

**Issue by borisschapira** [WPO-Foundation/webpagetest#906]
![capture d ecran 2017-07-17 a 10 03 37](https://user-images.githubusercontent.com/284742/28259579-3f183796-6ad7-11e7-8f95-72f0bd389094.png)

From this test https://www.webpagetest.org/result/170717_VZ_470ba4855543e93a8236dc557463536b/1/screen_shot/#step_1

**Comment by pmeenan** [comment]
Should be fixed now.
