### ISSUE TITLE
TimeToInteractive on private instance

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#907]
Hi,
I am currently trying measure the TTI of a website with a private WPT instance, but I had no luck so far.
I activated `Capture Video` and `Capture Dev Tools Timeline`, set a minimum test duration to 15s and even increased the activity timeout to 7s, but I still can't see the TTI.

Taking a look at the code I found that the agent needs to send the `interactive.json.gz` file, but it's not present in the result directory.
Do you have any idea why the file could be missing?
Both agent and server are running the latest version.

Thanks!

**Comment by pmeenan** [comment]
Only thing that comes to mind is if python isn't installed on the agent.  It [runs the python trace parser](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/wptdriver/webpagetest.cc#L1245) to extract the interactive times.

**Comment by sburnicki** [comment]
Python is installed, and I can manually parse the trace on the agent, but somehow the agent doesn't seem to be able to do this. Is there any way to capture and access the logs written via `OutputDebugStringA`?

Also, is there a reason why interactive parsing is not part of the trace post-processing in the server? Would love to integrate that.

**Comment by soulgalore** [comment]
We have the same problem on our AWS instance. But it works if I for example run https://www.webpagetest.org/result/170914_16_f952a555710ff45e81cf1084d3629d22/1/details/#waterfall_view_step1

I wonder maybe we somehow don't run the latest version.

**Comment by soulgalore** [comment]
It works when I deployed a Linux agent, so I'm trying to redeploy our Windows agent.

**Comment by soulgalore** [comment]
No that doesn't work (it should auto-update before the first run right?).

**Comment by pmeenan** [comment]
To get the OutputDebugString logs you can run DebugView on the agent (though a lot of the logging is disabled in release builds).

If you go to /getTesters.php it should tell you the version of software the agents are running (391 is the current build).  The agents will auto-update from the server and the server will not give them any tasks if they aren't running the same version as what the server has (which may or may not be the latest depending on if you have it pulling agent updates).

One thing that it may require is a server-side setting "[enable_agent_processing=1](https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample#L73)".  That shouldn't be optional anymore and I can change the agent to always do processing like the Linux agent does.

**Comment by soulgalore** [comment]
Adding "enable_agent_processing=1" made it work for me, thanks!!!!!

**Comment by soulgalore** [comment]
One last thing, do you feel it is too early to add it in the result JSON? We wanna start to keep track of it and see if there's a metrics we should follow.

**Comment by soulgalore** [comment]
Ah see now that it is called "LastInteractive" in the JSON, works fine!

**Comment by pmeenan** [comment]
There are a few different Interactive ones in the JSON.  The actual code is [here](https://github.com/WPO-Foundation/webpagetest/blob/master/www/page_data.inc#L271).

Not all of them will always be there because some of them require a 5 second window of time after the last activity and in some tests stop before there is 5 seconds of calm.

The full set is:
* FirstInteractive - First period after render where the page was interactive for 5 seconds
* TimeToInteractive - Also known as consistently interactive in Lighthouse speak and waits for the js to finish loading and then 5 seconds of interactivity (can fire WAY late in some cases)
* LastInteractive - Measured from the end of the test, whatever the last point where it was interactive was
* TTIMeasurementEnd - The end time of the timeline data

**Comment by pmeenan** [comment]
btw, I just pushed a 392 build which makes the agents always do edge processing regardless of the pref.

**Comment by sburnicki** [comment]
Build 392 fixed the issue also for me. So I guess we were also just missing the  `enable_agent_processing=1` option.
