### ISSUE TITLE
Lighthouse blocked urls ignored by WPT

### ISSUE THREAD

**Issue by wardpeet** [WPO-Foundation/webpagetest#913]
when running wpt with a blocked url `blocked: https://www.googletagservices.com/tag/js/gpt.js` lighthouse is not blocking the url.

Lighthouse has the flag `--blocked-url-patterns=` to block urls.
**Reference**: [lighthouse-core/gather/gather-runner.js](https://github.com/GoogleChrome/lighthouse/blob/07817f90e538dbbd2e8e430e12a1deab569d718c/lighthouse-core/gather/gather-runner.js#L179)
**wpt**: [test run](http://www.webpagetest.org/result/170804_Q1_4a1422dbe40ede076c78d2430f454fb3)

**Comment by patrickhulce** [comment]
Slight miscommunication here @wardpeet sorry 'bout that :)

Two items here:

1. Lighthouse needs to have better support for setting blocked urls from the command line (currently intended for use through the node API only and isn't very smooth, setting just one blocked URL breaks things for example)
2. Have [wptagent](https://github.com/WPO-Foundation/wptagent/blob/2d6172d01c18b7db5710b7b2ab37c5d52c468586/internal/devtools_browser.py#L355) send over any blocked URLs so we can add them to our list when we call setBlockedUrls

**Comment by pmeenan** [comment]
Should be [fixed now](https://github.com/WPO-Foundation/wptagent/commit/e1caf64a8f4ca0f1aa8f1beeb5d60fc61cc11e98). (rolling out over the next hour).
