### ISSUE TITLE
EC2 Linux locations with Firefox?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#930]
Hi Pat,
we wanna start testing replacing our Windows agent with Linux and wanna check if it would be ok to start add Firefox to the *ec2_locations.ini* Linux or is it something more you wanna do before that?

Best
Peter

**Comment by pmeenan** [comment]
Oh, thanks.  Forgot I already had the Linux AMI's in the ini.  I think they are pointing to the older pre-Firefox AMI.  Updating them now.
