### ISSUE TITLE
elastic ip for aws test agents?

### ISSUE THREAD

**Issue by nilskuhn** [WPO-Foundation/webpagetest#932]
Hi,

is it possible to configure public/elastic IP's for autoscaled test agent machines? Respective do they need one? I used this AMI to setup the server in eu-central-1: 
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-fcfd6194

The server launches an agent instance and I can connect via RDP but the agent needed a public IP to connect to wptserver and the internet. And even after doing that manually the agent didn't get work from server. In wptdriver.ini on agent is no server url or wpt location configured. locations.ini is also empty on wptserver. Do these files get managed with launching new agents normally?

Regards, Nils

**Comment by pmeenan** [comment]
The agent gets it's config data through userdata and isn't stored on disk.  If you specify a ["host" in settings.ini](https://github.com/WPO-Foundation/webpagetest/blob/master/www/ec2/ec2.inc.php#L89) it will use that IP address or name as the server for the agents to connect to.

**Comment by nilskuhn** [comment]
OK, thanks for the info.
I could fix it by just set `auto-assign public-IP=true` for the subnet of the agents/wptserver.
I didn't need to configure a host in `settings.ini`. Maybe your server AMI does that automatically.
