### ISSUE TITLE
Firefox shows unsent crash report bar

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#934]
![2017-09-15 13 21 58](https://user-images.githubusercontent.com/8599/30501914-0db0673e-9a19-11e7-910c-fa6e3509a923.jpg)

This causes the captured viewport to be smaller compared to Chrome.

`browser.crashReports.unsubmittedCheck.enabled` is already disabled in prefs, so I will follow up on Firefox's side on how to fully suppress the prompt bar.

**Comment by digitarald** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1400388

**Comment by pmeenan** [comment]
Do you know if the crash reports are stored somewhere I can just nuke on disk?

**Comment by digitarald** [comment]
Should be all in `%APPDATA%\Mozilla\Firefox\Crash Reports\`

**Comment by digitarald** [comment]
Looks like it should be fixed in 56, expected to ship Sep 28th.

https://bugzilla.mozilla.org/show_bug.cgi?id=1399796

**Comment by pmeenan** [comment]
393 had a bug where it would only delete the crash reports when clearing IE's caches - ugh.  Rolling out 394 right now with the fix.
