### ISSUE TITLE
Performance Review page is overflowing

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#935]
When performance review page has long URLs, it becomes very wide.

Might be worth using "overflow:hidden" or "overflow:wrap" on .test_results-content

![2017-09-16_13-20-04-compressor](https://user-images.githubusercontent.com/38076/30514405-2ef29146-9ae2-11e7-892a-ad84b3339203.png)

**Comment by adioe3** [comment]
I'd like to take this

**Comment by pmeenan** [comment]
Sure.  Pull requests happily accepted.

**Comment by YernYee** [comment]
Hello, this issue can be close since it's already fixed through merge pull request right?

**Comment by michaeladams01** [comment]
Yes

**Comment by sergeychernyshev** [comment]
Confirmed on WebPageTest.org! Thank you!
