### ISSUE TITLE
Unable to interact with text fields in Angular 2

### ISSUE THREAD

**Issue by locmai** [WPO-Foundation/webpagetest#936]
In an Angular 2 site,I'm still able to set the value for the field follow the API in the doc. 
But it seems like the field didn't trigger the binding event and no value is submitted.
Is there a workaround by using JavaScript?

**Comment by sburnicki** [comment]
You can manually dispatch a change event on the required field. Example
```
exec	document.getElementById("user").value = "testuser";
exec	document.getElementById("user").dispatchEvent(new Event("change"));
```

**Comment by locmai** [comment]
Hi I have tried your example in Chrome console, am I wrong with the event name? I have the same issue with WebPageTest
![interactwithangular2](https://user-images.githubusercontent.com/27542393/30549290-97ee56c0-9cbe-11e7-8fa2-fc955315d5b3.png)

**Comment by locmai** [comment]
Hi again, I found the solution. Thanks for your help.

**Comment by sburnicki** [comment]
@locmai : Great that you found the solution. What was the problem? Please share your solution for other people running into the same issue.

**Comment by Verkurkie** [comment]
@locmai i have the same problem with a React based page - how did you solve it?

**Comment by locmai** [comment]
Hi @Verkurkie , with Angular 2/4, I tried to access the app scope through ng.probe then I get it props model and call the method setValue from it.

Something like this
```
const formElement = document.getElementsByName("form")[0]
const formAngular = ng.probe(formElement);
formAngular.injector._view._NgModel_17_7.context._control.setValue("test")
```

Sorry if I was not clear about the solution. Don't really know how to explain them well.

For React, one of my teammate suggested to try the "dispatchEvent Keyboard event" or something. Hope it help.
