### ISSUE TITLE
statusCode 200 but one run fails?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#937]
Hi Pat, 
we run a test instance where we also do runs every hour on WebPageTest. One of our most common problems is that one of three runs fails on large sites (here we test NYTimes but we seen the same on cnet):
https://www.webpagetest.org/results.php?test=170918_9N_c51a338f94533f5d560c43995a0a1581

The problem is that the JSON returns: **"statusCode":200,"statusText":"Test Complete"** but one run fails. Is it like that by design? 

Right now we check SpeedIndex, if that is 0, we know the run failed. But is there a better way?

Best
Peter

**Comment by pmeenan** [comment]
There is a successfulFVRuns that tells you how many of the runs were successful and each run should have a "result" code associated with it (only 0 and 99999 are successful).

**Comment by soulgalore** [comment]
Ah thanks I missed that.
