### ISSUE TITLE
No Service Worker Request with Chrome 63

### ISSUE THREAD

**Issue by ErikWitt** [WPO-Foundation/webpagetest#938]
Hey there,

short background: we are running our own cluster of WPT instances on AWS with customized agents. We just started to run WPT agents on Google Chrome Dev 63, because of better Service Worker performance.

Now, with the current Chrome version 61, WPT shows all request that are made by a Service Worker in the waterfall. With Chrome Dev 63 no requests to or from the Service Worker are shown (same thing as with browser cache hits).

I am aware that Chrome Dev 63 isn't stable and all yet. But I guess the problem will persist, since Service Worker requests are now decoupled from the main threat (see https://bugs.chromium.org/p/chromium/issues/detail?id=443374).

Just wanted to let you know before WPT is updating to Chrome 62 or 63.

**Comment by pmeenan** [comment]
The ssl hooking is a bit fragile but it should be fixed now.  The main WPT server finds the necessary offsets in the dll for the various ssl functions that need intercepting and I just updated it to handle the newer symbol files.

That said, there are a few local caches you may need to clear to see it work (or when the next dev build rolls out it should re-update):

1. On the server in work/chrome, delete all of the zero length files (or delete all the files and it will just re-fetch what it needs from the public WPT server).  If there are no files (or directory), it is fine, then the agents are getting the offsets directly from the public server.
2. On the agent in the chrome/Application directory for the latest version (or all of the directories), delete wpt.sym which is the locally cached version of the file.

I tested against the current Canary but let me know if it still isn't working and I can take a look at Dev to see if it is using different symbols.

It may not be quite as robust on Windows for running continuously, but the [new cross-platform agent (wptagent)](https://github.com/WPO-Foundation/wptagent) doesn't rely on API hooking and is somewhat less fragile.

**Comment by ErikWitt** [comment]
Hey, thanks for the quick answer. Unfortunately your instractions did not work for us. 

This is our test (published to WPT.org): https://www.webpagetest.org/results.php?test=170921_61_b3669e11118fa4327b91c2c9e60c007f

This is the script that we ran

```
logData	0
blockDomainsExcept	testpage.app.baqend.com
navigate	https://testpage.app.baqend.com/
blockDomainsExcept
navigate	about:blank
logData	1
navigate	https://testpage.app.baqend.com/
```

The first 4 lines just install the service worker without loading external resources. The other lines start the actual test. For this run we cannot see a single request as they are all handled by the service worker.

**Comment by ErikWitt** [comment]
We have done further testing now. For Chrome Dev, Chrome Beta and Chrome Canary we do not see requests from Service Worker. Only Chrome Stable (version 61) shows them.

Versions are:
Version 62.0.3202.29 (Official Build) beta (32-bit)
Version 63.0.3218.0 (Official Build) dev (32-bit)
Version 63.0.3222.0 (Official Build) canary (32-bit)

We have also tried 64 bit, with the same result.

We have redone the whole setup and used newly installed Chromes, still we see no requests from Service Worker. Any suggestions?

**Comment by pmeenan** [comment]
Taking a look now.  At a minimum I may add the devtools-level request data from service workers when SSL hooking fails (that's how non-sw requests show up correctly for pages in the same browser).

**Comment by pmeenan** [comment]
Any chance you are running on a 64-bit OS and can install a 64-bit version?  Still trying to track down exactly why it is failing but it looks like it is working for the 64-bit build.

The 32-bit hooks are working for the outbound data but the read hooks aren't firing so something screwy is going on.

**Comment by ErikWitt** [comment]
we tried all the mentioned chrome versions in 32 as well as 64 bit. None has worked for us so far.

**Comment by pmeenan** [comment]
May have it, looks like one of the parameters changed from an int to a bool.  Testing out the fix now

**Comment by pmeenan** [comment]
I just rolled out 395 which should fix it.  I'm seeing the sw requests in airhorner where I wasn't seeing them before (or any requests for that matter): https://www.webpagetest.org/result/170922_70_159ce7680eb5df331cf14527d1897681/

Also, just a sanity check, WPT will only display requests that actually go over the network.  If the sw actually completes the requests from it's local cache you won't see it.
