### ISSUE TITLE
Firefox visual scoring includes network indicator overlay

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#939]
Testing Firefox on a Windows 10 machine I got a 30s+ test due to the network overlay being included in the scoring:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/8599/30569799-c4de3fba-9c91-11e7-8b6c-17e5f256a40b.png">

**Comment by pmeenan** [comment]
:-/  I'll take a look today.  The video processing [excludes 25 pixels](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/wpthook/results.cc#L60) along the bottom of the screen when looking for changes to avoid the status indicator triggering but it's possible that the indicator got bigger than when it was first implemented.

**Comment by digitarald** [comment]
Video just doesn't any other visual changes: https://www.dropbox.com/s/py5o4he4zpmi61f/video%281%29.mp4?dl=0

The only workaround that we might have here is something like `statuspanel { display: none }` in `userChrome.css`

**Comment by digitarald** [comment]
In this case the loadtime (fully loaded) being 36sec seems to be the issue for the long video time. So maybe not an issue with the overlay

**Comment by pmeenan** [comment]
If the video is around actual size, it looks like the status bar is ~32 pixels.  I'm building an update now that applies the userChrome.css to make sure it isn't a problem regardless of the size (also adding it to wptagent).

**Comment by pmeenan** [comment]
393 just rolled out which hides the status bar for Firefox (wptagent also picked up the fix).
