### ISSUE TITLE
NodeJS Agent was not able to export appropriate data for the result view

### ISSUE THREAD

**Issue by locmai** [WPO-Foundation/webpagetest#940]
Hi, I was trying to run the nodejs agent on Window Server followed this [link](https://sites.google.com/a/webpagetest.org/docs/private-instances/node-js-agent/setup) and then I got the Test Data is missing issue:
The result showed that the test data was missing even it already followed my script, so I check the log,It still produced the result folder and files (as you can see on the third window on bottom right).
![agentsbug](https://user-images.githubusercontent.com/27542393/30682871-6b2a5a26-9ed5-11e7-8e38-da590e848510.png)
Does anyone has the solution for this problem that could help or is it a well-known bug? 

Thanks in advance!

**Comment by pmeenan** [comment]
The NodeJS agent isn't actively developed anymore and was barely ever functional for desktop browsers (it was mainly for Android/iOS testing).  There is a new cross-platform agent ([wptagent](https://github.com/WPO-Foundation/wptagent)) that supports Desktop testing on Linux, Mac and Windows as well as Android and iOS testing.

**Comment by locmai** [comment]
Yeah gotta try that agent. Thanks for your support!
