### ISSUE TITLE
UAModifier does not affect Chrome

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#943]
Hey,

I set the `UAModifier` in `settings.ini` to `monitor/webpagetest PTST`. For tests with IE and Firefox I can see the modified UA in the request headers of the resulting waterfall.
With Chrome, the User Agent seems to only contain `PTST` but not the `monitor/webpagetest` part.

Is there any way I can debug why the setting is ignored with Chrome?

**Comment by fooksupachai** [comment]
I have tried to find out about this issue.

I want you to visit this link  : <a href="(https://github.com/jugglinmike/chrome-user-agent)">https://github.com/jugglinmike/chrome-user-agent</a>

If this is beneficial to you, I will be very glad but this is not useful to you, I apologize.

**Comment by pmeenan** [comment]
Sorry, this was fixed earlier this week in both wptdriver and wptagent.
