### ISSUE TITLE
Multistep doesn't work on new iOS agent

### ISSUE THREAD

**Issue by nilskuhn** [WPO-Foundation/webpagetest#944]
Hi,

it seems like the new iOS agent is just recording the last step of a multistep script. In [this test](https://www.webpagetest.org/result/170925_A7_e07183fb67a334f7b2f9ae00f663c4ae/1/details/) I used the following script on agent `Dulles, VA - iPhone 8 iOS 11 - FIOS`:
```
setEventName	HP_entry
navigate	https://www.amazon.com
setEventName	meetAlexa
navigate	https://www.amazon.com/b/ref=unrec_bubbler_3_v2?_encoding=UTF8&node=16067214011&ref=unrec_bubbler_3_v2&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=&pf_rd_r=R238YQWX9E4K245CSPWT&pf_rd_t=36701&pf_rd_p=56864b5e-bb8e-4327-9c4a-ab8bbca08822&pf_rd_i=desktop
```
But in the result the amzon homepage is missing.

Regards, Nils

**Comment by pmeenan** [comment]
Thanks.  Should be [fixed now](https://www.webpagetest.org/result/171003_T5_ddb3bc18ddbf9b0a77b925425e6079fd/) as of [this commit](https://github.com/WPO-Foundation/wptagent/commit/267d995fca13c0513ae787ce7d5b0bd8d813a78c).

**Comment by nilskuhn** [comment]
Great, thanks!
