### ISSUE TITLE
Cannot set timeout probably

### ISSUE THREAD

**Issue by locmai** [WPO-Foundation/webpagetest#945]
Hi I'm trying to set the timeout higher than 5 minutes with low traffic network (2G mobile).

I tried to set it in the settings.ini, wptdriver.ini and even in the script( setTimeoutActivity command) for around 1800s (30 minutes). The tests were always ended around 5 minutes and return the 99997 result code.

![buganhpeemanoi](https://user-images.githubusercontent.com/27542393/31007975-9b1c566e-a52c-11e7-8ca1-2721b88c8f60.png)
![bugnuane](https://user-images.githubusercontent.com/27542393/31007976-9b1d1946-a52c-11e7-8e1d-7682d13b5212.png)
![bugnuaneanhoi](https://user-images.githubusercontent.com/27542393/31007977-9b2374b2-a52c-11e7-99ce-8c9fdd4dada4.png)

Is there any workaround or something wrong in my setting?

ps: here is the script I used:
logData    1
setEventName    Load Login Page
setTimeout    1800
setActivityTimeout    10000
navigate    our_website

**Comment by paulcalvano** [comment]
It looks like the wptagent code is setting the max allowed timeout to 1200, which may explain why it's not taking your 1800s timout..   Check out https://github.com/WPO-Foundation/wptagent/blob/master/internal/webpagetest.py#L507

```
if time_limit > 0 and time_limit < 1200:
     job['timeout'] = time_limit
```

**Comment by locmai** [comment]
well I used the old wptdriver. And even with the 1200 seconds limit, it is still around 20 minutes which in my case only ran for around 5 minutes and it's already timeout.

**Comment by paulcalvano** [comment]
Hi @locmai .   Can you try 1199 seconds?

Based on the code snippet I shared above from wptagent, it looks like the timeout script setting will not be applied at all if it is not >0 and < 1200.   If I'm reading it correctly, then setting it to 1200 will cause it to default to 5m.   I wonder if you will get your desired result by setting it to 1199 in your script.

**Comment by minhhoangvn** [comment]
Hi @paulcalvano , i got similar issue, i used agent is written in C/C++(https://github.com/WPO-Foundation/webpagetest/tree/master/agent/wptdriver). I also tried to set timeout 1199 but unfortunately my test still running only 5 minutes
