### ISSUE TITLE
Performance Testing locally hosted pages

### ISSUE THREAD

**Issue by Jesna12** [WPO-Foundation/webpagetest#949]
Hi team,

Is it possible to performance test a webpage hosted locally? I have set up the private version of WPT hoping that I will be able to test locally hosted pages. But when I give the URL of locally hosted page, it is showing some error messages. Can anyone suggest me whether we can test locally hosted pages or not?

**Comment by pmeenan** [comment]
Yes, it can.  What error message?  There is a setting in settings.ini on the server to enable testing of private IP ranges.

**Comment by Jesna12** [comment]
Thank you so much @pmeenan :)  . it worked. I missed to enable that private testing option in settings.ini.
