### ISSUE TITLE
WPT private instance not working in chrome

### ISSUE THREAD

**Issue by Jesna12** [WPO-Foundation/webpagetest#950]
I have configured WPT private instance .It is working fine in IE11 but not in Chrome.When I give Chrome as browser ,the test page is not loading in chrome.It is showing the below errro(attached screenshot ).Do we need to do any setting in the configuration file to enable testing in chrome?I am using the chrome version 61.0.3163.79
![wpt](https://user-images.githubusercontent.com/20107859/31426728-2d3f1f28-ae82-11e7-9728-ae362c3dbaa9.png)

**Comment by jirawat050** [comment]
Delete google chrom and new dowload(Sorry if answer not help you)

**Comment by pmeenan** [comment]
What version of wptdriver is running? https://sites.google.com/a/webpagetest.org/docs/private-instances#TOC-Updating-Test-Agents

I assume Chrome works fine when manually loading pages on the machine and it is just when testing that it has issues.  If so then it is either the command-line parameters being passed, something with the hooking or how the network is configured.

Does the machine need to go through a proxy to reach the Internet?  One thing the agent passes is a flag to turn off all proxy settings.
