### ISSUE TITLE
Broken viewport for some runs on emulated mobile Chrome

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#951]
Hi Pat,
we have a problem where the viewport becomes wrong for some runs when we test emulated mobile (we use the Windows agent):

We do five runs and the first looks ok:
![1_screen_thumb-2](https://user-images.githubusercontent.com/540757/31543514-b0b84466-b016-11e7-92b4-9c22b630a015.jpg)

Then there are a couple of ones that looks like this:
![2_screen_thumb](https://user-images.githubusercontent.com/540757/31543524-c21aa88e-b016-11e7-8b2e-f04f3e78bacb.jpg)

Here's the full result:
http://wpt.wmftest.org/result/171012_TZ_50/

Best
Peter

**Comment by pmeenan** [comment]
I've seen a few cases where the browser window is resized even smaller than that when doing the mobile emulation but haven't tracked it down (not helped by the fact that I can't reproduce it).  The one time I had a machine that could reproduce it, I rebooted and it went away :(

I'll poke through the code to see if I can find anything that might cause it but it is going to be a fair bit of trial and error without a way to reproduce.

**Comment by pmeenan** [comment]
There's a good chance it's not the same issue but the Amsterdam GoDaddy location on the public WPT has similar mobile emulation issues: https://www.webpagetest.org/result/171013_CA_95a306935d97db6c222f730d757c2743/

![image](https://user-images.githubusercontent.com/444165/31550053-08195c22-affe-11e7-8d50-9801fa10cd33.png)

At least that gives me something to try fixes against to see if it also fixes the issues you are seeing.

**Comment by pmeenan** [comment]
Not sure if it fixes your case but I just rolled out wptdriver 396 which has a fix for cases where it incorrectly was setting the viewport to 0 if some other code paths failed (which [fixed the issue in Amsterdam](https://www.webpagetest.org/result/171013_KC_0a45faa3225d612691d7b86b0a67675a/))

**Comment by soulgalore** [comment]
Went through a couple of runs and I cannot see the problem anymore, I think you solved the issue, thanks!
