### ISSUE TITLE
Runs fail with error 99997 when enabling Chrome trace option

### ISSUE THREAD

**Issue by webmonarch** [WPO-Foundation/webpagetest#954]
On our private WPT server we started noticing our automated tests failing with error 99997 about 4 days ago. Jobs were also failing (using our same infrastructure) when submitted (via REST) to the public `webpagetest.org` server. Jobs submitted via the UI were completing successfully.

I eventually started diffing some job files in `/var/www/webpagetest/www/work/jobs` and noticed the difference between successful and failing tests as the `trace` option.

I notice the `trace` option is not mentioned in the REST submit API docs (but I still see it in the web submit UI, under the chrome tab).

Perhaps related, I also now see a `lighthouseTrace` option showing up in the job data.

Is this expected?

**Comment by pmeenan** [comment]
99997 should be a timeout (no page load event fired before the test timeout).  The timing is around when Chrome 62 rolled out which would be more suspicious than the test options though depending on the trace options you could be crashing the browser by collecting too much data.  Did the failing tests have the trace option enabled?  If so, were categories set or not?

**Comment by webmonarch** [comment]
Yeah, for me, all tests failed with the `trace` option enabled. Both via REST and the UI, both locally and on the public `webpagetest.org`.  When I submitted via REST, no trace categories were set. When I submitted via the UI, the default trace categories were set.
