### ISSUE TITLE
API calls wrongly classified under uncached static assets leading to F grade 

### ISSUE THREAD

**Issue by ashrith-kulai** [WPO-Foundation/webpagetest#958]
1. API calls wrongly classified under uncached static assets leading to F grade. 
2. The files service-worker.js getting flagged for no max-age header although it is present. 

Website url: https://book.olacabs.com

WPT result: 
https://www.webpagetest.org/performance_optimization.php?test=171025_CX_09f6d2ce653273f142594d4c7423d479&run=1#cache_static_content

**Comment by pmeenan** [comment]
Any reason you are using max-age=0 instead of no-cache for the API calls?  I can update WPT to treat max-age=0 the same as no-cache but I'm pretty sure the max-age=0 is throwing it off (in both cases).

**Comment by ashrithkulai** [comment]
I am using cache-control:public, max-age=0 for service-worker.js 
For API: cache-control: max-age=0, private, must-revalidate
The api headers are not in my control. Since max-age=0 is similar/same to no-cache it would be great if you could update it to treat them the same.
