### ISSUE TITLE
WPT doesn't consistently capture lightspeed test

### ISSUE THREAD

**Issue by jamesshannon** [WPO-Foundation/webpagetest#961]
When checking "Capture Lighthouse Report" I find that lighthouse is only done / captured / presented about 30% of the time. I define this by the "Lighthouse PWA Score" box at the top right.

I haven't noticed any consistency in when it works or doesn't. Sometimes it's even worked on some tests within a bulk test and not others. In all cases I'm testing with Nexus 5 / Nexus 5 Chrome.

Though now that I go back through some random tests which I recall did NOT work, I see a lighthouse score. So maybe there's just an additional delay and not notification that "Test is done but lighthouse is still going..." In which case this is a FR for a greyed out lighthouse square. OTOH, the delay seems pretty variable, sometime between 30 seconds and >5 minutes, so I'm not so sure about this.

Though I did find [one recent test](https://www.webpagetest.org/result/171025_8A_e88525f901a9e7b38ca2542ecb54cbe9/) with no lighthouse score, but since it's more of an anomaly than I remember it's possible that I forgot to check the checkbox.

FWIW: It's also not clear to me which test those square scores are taken from.

**Comment by addyosmani** [comment]
Lately (last 3-4 weeks), I've noticed a few instances where /easy (with Lighthouse checked) for the 3G/EM presents hasn't been consistently including a Lighthouse report when processing is done. 

This has been quite variable (e.g if one run doesn't include it, re-do and the next one might). For the time being I've switched back to using the advanced view with manually checking the Lighthouse report option. For some reason (may just be blind luck) those seem to have a higher success rate.. :)
