### ISSUE TITLE
Public Instance: Queue Jumping of UI-submitted tests

### ISSUE THREAD

**Issue by jamesshannon** [WPO-Foundation/webpagetest#974]
Both yesterday and today I've seen my tests' place in the queue go up and down. For example, right now it's been jumping around between 100 and 115, moving down a few spots, then up almost as much. My test has only moved 10 absolute places in the last 2.5 hours.

I'm using a Nexus 5 from Dulles. UI-submitted with a batch of 2 URLs. AFAICT, there is a priority concept (I see that in the getLocations API) but the default for UI-based tests should be above that for any other (API) submitted test.

I understand that sometimes the queue might slow down or even stop (especially if I've specified particular hardware), but I don't see why new tests are getting prioritized ahead of mine on the public instance.

**Comment by pmeenan** [comment]
Batch and API tests get lower priority than one-off UI tests so this is expected.  There is only one Nexus 5 online right now (2 of the devices are offline).  Generally, unless you need the Nexus 5 specifically the recommended device to use is the Moto G4 which is around the same CPU speed, more modern and there are 24 of them in the pool.

**Comment by jamesshannon** [comment]
Oh. Good to know about the # of nexus' / # of G4s. I knew that specifying the model (any model) would be limiting, but didn't realize that.

Suggestion: Make "device groups", like "last generation mobile" or "last generation android". That's all I really cared about, and figured the nexus and g4 were similarly available.
