### ISSUE TITLE
URL parsing failure when delivering job via API

### ISSUE THREAD

**Issue by DominiqueFuchs** [WPO-Foundation/webpagetest#975]
When triggering a job from OpenSpeedMonitor to latest WPT release 17.08, the URL from the script seems to get sliced down to the first occurance of an ampersand. For example one can take this snippet:

navigate http://www.example.com/search?=12345&id=67&string=89

in an OSM script and trigger it as a job. But the job will (probably) fail with 404 or whatever because WPT only visits the following URL:

http://www.example.com/search?=12345

I think this is an WPT issue because I looked at the nginx logs and verified that the URL arrives at WPT complete and indeed:

`"POST /runtest.php?url=&label=Test&location=Testagent-WPTdriver:Firefox.custom&runs=1&fvonly=0&video=1&web10=0&noscript=0&clearcerts=0&ignoreSSL=0&standards=0&tcpdump=0&continuousVideo=0&private=0&mobile=0&timeline=0&timelineStack=0&lighthouse=0&trace=0&traceCategories=blink,v8,cc,gpu,blink.net,netlog,disabled-by-default-v8.runtime_stats&bodies=1&bwDown=5000&bwUp=1000&latency=28&plr=0&script=setEventName%20TestEvent%0D%0Anavigate%09http://www.example.com/search?=12345&id=67&string=89&f=xml HTTP/1.1" 200 598 "-" "Java/1.8.0_91"`

the URL is complete and correctly parsed at this point. Any hints on this, am I missing something?

**Comment by pmeenan** [comment]
The URL encoding for the script is incorrect.  Somehow you managed to urlencode the tabs and newlines but not the URL within the script.  All of those ampersands and the question mark should be encoded.

**Comment by DominiqueFuchs** [comment]
I actually tried that (even though it worked in earlier setup with this script, but that was WPT before 3.0 and ancient OSM version - and I always thought it 'should' work because you're supposed to let OSM handle the enconding when writing scripts). However, when setting up the script like this (e.g. replacing ? by %3F and & by %26:

`navigate http://www.example.com/search%3F=12345%26id=67%26string=89`

this results in an POST that looks like:

`"POST /runtest.php?url=&label=Test&location=Testagent-WPTdriver:Firefox.custom&runs=1&fvonly=0&video=1&web10=0&noscript=0&clearcerts=0&ignoreSSL=0&standards=0&tcpdump=0&continuousVideo=0&private=0&mobile=0&timeline=0&timelineStack=0&lighthouse=0&trace=0&traceCategories=blink,v8,cc,gpu,blink.net,netlog,disabled-by-default-v8.runtime_stats&bodies=1&bwDown=5000&bwUp=1000&latency=28&plr=0&script=setEventName%20TestEvent%0D%0Anavigate%09http://www.example.com/search%253F=12345%2526id=67%2526string=89&f=xml HTTP/1.1" 200 598 "-" "Java/1.8.0_91"`

The resulting URL in WPT Queue looks like expected

`http://www.example.com/search%3F=12345%26id=67%26string=89`

but again this get's 404ed and indeed when I try to visit this URL the page cannot be found (when I replace the percent-encoding back to non-encoded version I get the result page). Now where I think about it: The page I'm trying to test is a real-world website with a shop search engine and this osm-job should trigger a search via the provided URL and retreive the result page. Is it possible that the search engine can't handle the encoded URL and in earlier version this worked because it was possible to use nun-encoded chars without getting the URL cut?

**Comment by pmeenan** [comment]
If you are encoding by hand doing string substitution you are doing it wrong.  Most languages have built-in support for urlencoding a string.

The encoded version of your script should be:

```
setEventName%09TestEvent%0Anavigate%09http%3A%2F%2Fwww.example.com%2Fsearch%3F%3D12345%26id%3D67%26string%3D89
```

**Comment by DominiqueFuchs** [comment]
Yes, I guess I still didn't make my point clear enough. Substitution war just a try to see what the output in the resulting POST looks like.

Do you know OpenSpeedMonitor mentioned in my initial post? This is an frontend similar to sitespeed or (in the past) wptmonitor. The script editor in OSM doesn't even allow you to write full encoded scripts. It is designed to encode them itself (maybe except for some special chars in URL, docs arent clear), so if you full encode the script it won't save because it doesn't recognize the syntax.

That said, the resulting POST from above (the one you noticed as 'partial encoded') comes from OSM, that runs the script written without userside encoding. This worked in (a lot) earlier versions. But right now (using WPT 17.08 and OSM 4.3.3 or 4.4.0) it doesn't and I do not see a potential workaround.

Your posts make me think that I may have been wrong in thinking this would belong to WPT. I guess I have to dig a little deeper (when I find the time for it, actually heavily possible) to examine what exactly changed or is breaking the correct way of encoding the request for WPT OSM-internally.

Thanks for your comments on this!

**Comment by pmeenan** [comment]
My money is on a bug in OSM.  WPT gets used for complicated scripts quite regularly both through the UI and API and there haven't been any issues reported with it.

**Comment by DominiqueFuchs** [comment]
FTR if anyone stumbles upon this here first: I opened an issue in the OSM project (see above) where it has been reproduced and confirmed. A fix for this is on its way.
