### ISSUE TITLE
Ability to disable agent rebooting functionality

### ISSUE THREAD

**Issue by tehmonolith** [WPO-Foundation/webpagetest#979]
Due to limited resources, our WPT agent is on a machine that serves other purposes as well (less than ideal, we know). As such, we'd like the ability to disable the agent rebooting functionality so that we can safely run WPT without worry that it might reboot the shared machine, interrupting any other tasks taking place on the machine at the same time. Thanks.

**Comment by pmeenan** [comment]
FWIW, wptdriver is deprecated and will stop working with Chrom in June or July.  If you switch to [wptagent](https://github.com/WPO-Foundation/wptagent) then there is no reboot logic (though it may close any open windows which would still be bad).

Depending on the browsers you need to test you can also run Linux inside of a VM on the same machine and run the agent inside of the VM.  That way there would be no chance of interference.

**Comment by tehmonolith** [comment]
Thank you very much. We'll migrate to the new agent.
