### ISSUE TITLE
Modify wd_server onPageLoad to match desktop logic

### ISSUE THREAD

**Issue by zwri** [WPO-Foundation/webpagetest#98]
Modify the NodeJS agent's page completion logic to match the desktop code.

The current agent does:
   1. send Page.navigate
   2. wait for first Page.loadEventFired
   3. wait another 10s for the page to "coalesce"

Instead, it should (roughly) match the desktop "IsDone" logic:
  https://github.com/WPO-Foundation/webpagetest/blob/master/agent/wpthook/test_state.cc#L304

except that
  - it should watch the DevTools events instead of the extension's raw network events
  - it shouldn't poll every 100ms
  - ignore the "OnAllDOMElementsLoaded" check 

Pseudocode:
<pre>
  def start:
    is_active = true     // ie not done or timeout
    is_loading = false   // aka navigating
    is_loaded = false    // aka navigated
    min_time = now + min_duration
    max_time = now + timeout_duration
    timer.set(max_time)

  def onDevToolsMessage(m):
    if not is_active:
      return
    elif m == "Page.frameNavigated" and not is_loading:
      is_loading = true
      return
    elif m == "Page.loadEventFired" and is_loading:
      is_loading = false
      is_loaded = true
    elif is_web10 or not (m =~ "Network.*" and is_loaded):
      return
    t = now + (is_web10 ? 0 : activity_duration)
    t = min(max_time, max(min_time, t))
    timer.reset(t)

  def onTimer:
    is_active = false
    Done() if now &lt; max_time else Timeout()
</pre>

**Comment by pmeenan** [comment]
Done.
