### ISSUE TITLE
Do different runs of a test run in different devices?

### ISSUE THREAD

**Issue by inian** [WPO-Foundation/webpagetest#987]
I have configured it to run in Nexus 5. The screenshot of the device result seem to be different across runs. Just wanted to confirm if they are all running on Nexus 5 and just the look of the screenshot is different across these runs. 

https://www.webpagetest.org/result/171115_G1_55cf252e5ccbdd1a0bd4b0a2c2bf91c8/

**Comment by pmeenan** [comment]
There are 2 nexus 5 devices in rotation right now (24 Moto G4's) and the test runs are sharded across all of them.  If you click on an individual waterfall it will give you the name of the machine (which device) that specific run was on.

**Comment by inian** [comment]
cool, just confirming cos the home button and the back buttons looked different for the 2 Nexus 5s. I had expected the same device frame across all screenshots.
