### ISSUE TITLE
Windows agents make requests that should be blocked

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/webpagetest#992]
I've noticed that the Windows WPT agents don't block all requests that match the `block`, `blockDomains`, and `blockDomainsExcept` script directives.

Here's a test on a Dulles Windows agent which makes a request to www.google.com when it shouldn't: https://www.webpagetest.org/result/171118_A1_3e6dfa8f0f89dc3d65984a67a44e9180/1/details/

And here's the same test on a EC2 Linux agent which correctly blocks the request: https://www.webpagetest.org/result/171118_T8_e462e2d458725768219d93bd282b4e71/1/details/

I've tried various combinations of the `block` directives but the Windows agents always seem to make the request.

**Comment by pmeenan** [comment]
All of the agents have been migrated to the new codebase (wptagent) and the blocking is now consistently supported across Windows and Linux (and across browsers except for iOS).
