### ISSUE TITLE
pingback api not called

### ISSUE THREAD

**Issue by kitsaravana** [WPO-Foundation/webpagetest#994]
using webpagetest server docker & webpagetest client docker, got results from jsonurl, but couldn't get the pingback id as callback from docker.

code snippet:
curl -X POST \
  http://localhost:4000/runtest.php \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F url=https://webpagetest.org/ \
  -F f=json \
  -F pingback=http://localhost:37854/ \
  -F fvonly=1

**Comment by soulcorrosion** [comment]
I'm also using docker. I send the pingback url however I'm never notified. I have to create a polling mechanism to check on the test results. It would be great to have the pingback so we can get the results as quickly as possible.

**Comment by Yiivgeny** [comment]
Uncomment `local_server=http://127.0.0.1` in `settings/settings.ini`
