### ISSUE TITLE
Lighthouse FMP numbers are not captured by WPT

### ISSUE THREAD

**Issue by bhattdeepak90** [WPO-Foundation/webpagetest#995]
@pmeenan -- while running the tests with lighthouse option, WPT is not giving the lighthouse FMP numbers. Can you please help.

**Comment by pmeenan** [comment]
Do you have an example test?

[This one](https://www.webpagetest.org/jsonResult.php?test=171121_7T_267ba68e6f9f959877ff459af64c3c9b&run=1) captured it:

```
lighthouse.Performance.first-meaningful-paint: 365.9,
```

It is also in the html version of the lighthouse report:

![image](https://user-images.githubusercontent.com/444165/33083235-d0a64c3c-ceac-11e7-9e25-c8cb29f519fa.png)
